### ISSUE TITLE
Contract name collisions cause silent failure

### ISSUE THREAD

**Issue by beether** [trufflesuite/truffle#443] opened 2017-06-12 01:56 UTC
- [ x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

There are two .sol files:  One.sol, UsesOne.sol.  If One.sol defines `contract One` and UsesOne.sol defines `contract One` (for example, to be used only as an interface), then after compiling the resultant /build/contracts/One.json will contain only the interface ABI as defined in UsesOne.sol -- no bytecode and missing whatever functions weren't declared.

## Steps to Reproduce

Create two files in /contracts:

One.sol

```
contract One {
  function myFunc1(uint _num) returns (uint){}
  function myFunc2(uint _num) returns (uint){}
}
```

UsesOne.sol
```
// define interface to One
contract One {
   function myFunc1(uint _num) returns (uint)
}
contract UsesOne {
  // doesnt matter what goes in here
}
```
## Expected Behavior

After `truffle compile --all` build/contracts/One.json should contain an ABI with both myFunc1 and myFunc2, and also have an unlinked_binary.  OR, an error will be thrown specifying that `contract One{}` is defined in two places.

## Actual Results

build/contracts/One.json will contain an ABI of the interface One.json as defined in UsesOne.sol.  No unlinked_binary, and missing myFunc2.

## Environment

* Operating System: 
* Truffle version: 3.2
* Ethereum client:
* node version:
* npm version:

**Comment by beether** [comment] 2017-06-12 01:56
@tcoulter confirmed it

**Comment by beether** [comment] 2017-06-12 02:05
It should be noted that even if a collision occurs with --compile-all, it may could still also occur from a normal `compile`.  Eg, if you edit `UsesOne.sol` and do compile, it will clobber `builds/contracts/One.json`.  The ideal result is that it would still warn you or error out, even if the only thing being recompiled is `UsesOne.sol`

Ideally, the fix to this would ensure that even if you first create `One.sol` compile, then create `UsesOne.sol`, and compile, the collision will be detected.

**Comment by tcoulter** [comment] 2017-07-13 18:39
Hi there. I'm marking this as a dupe of #387. Please track progress there. Thanks!

**Closed by tcoulter** 2017-07-13 18:39 UTC
