### ISSUE TITLE
Problem with Keccak when installing truffle

### ISSUE THREAD

**Issue by adriendulong** [trufflesuite/truffle#1950] opened 2019-04-25 07:44 UTC
I keep have the same issue as described in the #1584 with Keccack when trying to install Truffle.

I have tried with different versions, I also tried to compltely unbinstall glo--bally and install globally again, but I always get the same error when installing:

```
npm install -g truffle
/Users/adriendulong/.nvm/versions/node/v12.0.0/bin/truffle -> /Users/adriendulong/.nvm/versions/node/v12.0.0/lib/node_modules/truffle/build/cli.bundled.js

> keccak@1.4.0 install /Users/adriendulong/.nvm/versions/node/v12.0.0/lib/node_modules/truffle/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild /Users/adriendulong/.nvm/versions/node/v12.0.0/lib/node_modules/truffle/node_modules/keccak
> node-gyp rebuild

  CXX(target) Release/obj.target/keccak/src/addon.o
../src/addon.cc:37:47: error: too few arguments to function call, single
      argument 'context' was not specified
    unsigned int rate = info[0]->IntegerValue();`
```

Is anyone getting the same issue? 
Could it be related to the configuration of my node installation?

Thank you

**Comment by eggplantzzz** [comment] 2019-04-26 13:09
Yes, I can reproduce the issue. It is likely due to using Node 12. We'll have to look into it. In the meantime if you downgrade to something between version 8.9.4 and the latest version of 11 it should be perfectly fine. Thanks for the heads up on this!

**Comment by wbt** [comment] 2019-05-06 17:44
This may be a duplicate of issue #1584, in which node 9.3.0 was used.  Therefore, switching to that version of Node seems unlikely to be a successful solution.

**Comment by eggplantzzz** [comment] 2019-05-15 17:43
@adriendulong Can you give some information about versioning? For example, are you on Windows or Mac? Can you paste the output from `truffle version` here as well?

**Comment by fainashalts** [comment] 2019-11-13 19:09
Hi @adriendulong thanks for opening this issue! Can you get back to us about @eggplantzzz's question? We'll close this for issue maintenance next week unless it's still an issue.

**Comment by gnidan** [comment] 2019-11-27 18:56
Closing now for issue maintenance. Feel free to get back to us an we'll re-open! Thanks!

**Comment by triple-vee** [comment] 2020-03-29 17:16
I had this problem when trying to install everything globally. Once I removed all the packages globally and created a local instance of node, the packages installed without error in my local instance.

**Comment by mikec** [comment] 2020-05-04 12:43
Also had this problem installing with node `v12.16.1`. Rolled back to node `v11.14.0` and install worked.

**Comment by asimjb1200** [comment] 2021-03-27 11:52
This is still an issue with node v13.9.0. Is anyone planning on fixing this or will we always be forced to roll back our node version?

**Comment by Iwitrag** [comment] 2021-12-31 17:04
Same issue with node `v14.16.0`

**Comment by cds-amal** [comment] 2021-12-31 20:19
Hi @Iwitrag ,

We've been on the lookout for this one for a while. Can you share reproduction steps as well as environment details so we  can investigate/reproduce? Thanks in advance!

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by cds-amal** [comment] 2022-02-02 19:36
Closing for issue maintenance. Please let us know if this is still an issue.

**Closed by cds-amal** 2022-02-02 19:36 UTC
Labels: needs reproduced
