### ISSUE TITLE
run plugin "help" features..

### ISSUE THREAD

**Issue by rocky** [trufflesuite/truffle#1473] opened 2018-11-27 21:16 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle)

It would be nice to be able to get a list of plugins that are installed other than looking at the truffle configuration file. 

Is there a preferred way for a plugin to provide help for it? In the example of https://github.com/trufflesuite/truffle/issues/1472 I used `console.log` after looking at `config.help`, but is that recommended? For the core commands, their help is formatted in a uniform way, right?

**Comment by CruzMolina** [comment] 2018-12-12 05:31
jotting down for posterity (if I'm unable to get to this before going on leave), I think this should be handled in the "runHandler" in `truffle-core/lib/run.js`. completely agree that we should provide a standard/recommended way for plugin writers to specify in some manner what they would like to display (perhaps using our `displayCommandHelp` func from our end) when a `--help` flag is passed. Ideally in the `truffle-plugin.json` something like...

```
{
  "commands": {
    "hello": "hello.js"
  },
  "help": {
    usage: "truffle run hello [name]",
    description: "Greets a given user",
    options: [
      {
        option: "name",
        description: "Name of user to greet."
      }
    ]
  }
}
```

or also potentially allowing a file to specified (which we would parse with certain expected parameters in mind).

Also agree it would be nice to get a list of properly configured/installed plugins, perhaps a `--list` flag to call with truffle run (`truffle run --list`)

(Btw, thanks for making all these truffle run issues! 🎉 )

**Comment by rocky** [comment] 2018-12-12 22:46
You are very welcome. Thanks for considering this and working on this. 

Please keep us (me, and more generally the Mythrili team) apprised of run plugin work. We can and do want to help here. We can help test things. 

I am (now) watching release tags, but that can be a little to late to get the most benefit before a release.

**Comment by eggplantzzz** [comment] 2019-02-21 15:27
I think we wanna keep this open

**Comment by gnidan** [comment] 2019-12-04 18:57
Looks like this is a duplicate of #1551. Closing for issue maintenance. Thanks!

**Closed by gnidan** 2019-12-04 18:57 UTC
Labels: enhancement, needs labels
