### ISSUE TITLE
`apollo-server` in Truffle DB should be upgraded to v3

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4634] opened 2022-01-19 22:09 UTC
## Issue

So, it looks like our use of `apollo-server` v2 in Truffle DB is responsible for multiple of the warnings that people are seeing when they install Truffle.  I think if we upgraded to v3, we could cut down on those warnings a little.  Of course, v3 has breaking changes from v2, but it sounds like they shouldn't be too bad?  FWIW, here's [the migration guide](https://www.apollographql.com/docs/apollo-server/migration/) and the [list of breaking changes from the 3.0.0 release notes](https://github.com/apollographql/apollo-server/blob/main/CHANGELOG.md#breaking-changes).

## Environment

* Truffle version (`truffle version`): 5.4.29

**Comment by dongmingh** [comment] 2022-05-26 18:35
Close this since the issue is fixed in #4801.

**Closed by dongmingh** 2022-05-26 18:35 UTC
Labels: db, dependencies, priority2 ⚠️
