### ISSUE TITLE
could not deploy the contract in Quorum network

### ISSUE THREAD

**Issue by vishnutm** [trufflesuite/truffle#2779] opened 2020-01-23 06:31 UTC
**Issue**
I'm trying to use truffle on Quorum, i build a 3 node setup from the using raft consensus. But i can not depoly a contract in that network

**3Node setup:**
./startnode1.sh
./startnode2.sh
./startnode3.sh

My smart contract in truffle is 
```solidity
pragma solidity ^0.5.0;

contract SimpleStorage {
  uint public storedData;

  constructor(uint initVal) public {
    storedData = initVal;
  }

  function set(uint x) public {
    storedData = x;
  }

  function get() view public returns (uint retVal) {
    return storedData;
  }
}
```

after compiling the smart contract . i copy the abi and byte code public-contract.js 
```javascript
a = eth.accounts[0];
web3.eth.defaultAccount = a;

// abi and bytecode generated from simplestorage.sol:
// > solcjs --bin --abi simplestorage.sol
"abi" = [
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor"
  },
  {
    constant: true,
    inputs: [],
    name: "last_completed_migration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "uint256",
        name: "completed",
        type: "uint256"
      }
    ],
    name: "setCompleted",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "new_address",
        type: "address"
      }
    ],
    name: "upgrade",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];

var bytecode =
  "0x608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506102b7806100606000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630900f01014610051578063445df0ac146100955780638da5cb5b146100b3578063fdacd576146100fd575b600080fd5b6100936004803603602081101561006757600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919050505061012b565b005b61009d6101f7565b6040518082815260200191505060405180910390f35b6100bb6101fd565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b6101296004803603602081101561011357600080fd5b8101908080359060200190929190505050610222565b005b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614156101f45760008190508073ffffffffffffffffffffffffffffffffffffffff1663fdacd5766001546040518263ffffffff1660e01b815260040180828152602001915050600060405180830381600087803b1580156101da57600080fd5b505af11580156101ee573d6000803e3d6000fd5b50505050505b50565b60015481565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141561027f57806001819055505b5056fea265627a7a7231582009f44aafb2cd64c2bed2f4eeee0f2550b0b7f731d231fd1354f52fcba565eeb064736f6c634300050c0032";

var simpleContract = web3.eth.contract(abi);
var simple = simpleContract.new(
  42,
  { from: web3.eth.accounts[0], data: bytecode, gas: 0x47b760 },
  function(e, contract) {
    if (e) {
      console.log("err creating contract", e);
    } else {
      if (!contract.address) {
        console.log(
          "Contract transaction send: TransactionHash: " +
            contract.transactionHash +
            " waiting to be mined..."
        );
      } else {
        console.log("Contract mined! Address: " + contract.address);
        console.log(contract);
      }
    }
  }
);
```

when truffle migrate it . it generate the error like this

**truffle migrate --reset**
```
Compiling your contracts...
===========================
> Compiling ./contracts/SimpleStorage.sol
> Artifacts written to /home/vishnu/NetObjex/quorum/fromscratch/qutruffle/build/contracts
> Compiled successfully using:
   - solc: 0.5.0+commit.1d4f565a.Emscripten.clang

Running migration: 1_initial_migration.js
Deploying Migrations...
Migrations: 0x76527e53747a15589c156a4F15574bdEBf3858d0
Saving successful migration to network...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Transaction: 0x38bdc1220bc3821832505c50cd491e52f5d1729d1680d98859b717884ea271ec exited with an error (status 0) after consuming all gas.
     Please check that the transaction:
     - satisfies all conditions set by Solidity `assert` statements.
     - has enough gas to execute the full transaction.
     - does not trigger an invalid opcode by other means (ex: accessing an array out of bounds).
Truffle v5.0.14 (core: 5.0.14)
Node v12.14.0
```
**Enviornment**:

 Operating System: Ubuntu 18.04.3 LTS
Quorum geth version : Geth/v1.8.18-stable-51e1f635(quorum-v2.4.0),
Truffle version ; Truffle v5.0.14 (core: 5.0.14),
Solidity v0.5.0 (solc-js)
Node v12.14.0
Web3.js v1.0.0-beta.37

**Comment by EmanHerawy** [comment] 2020-01-28 21:05
Hi, How does your truffle.js / truffle-config.js look like ?
To use Quorum, you must modify your network in truffle-config.js to include a parameter type set to "quorum"
`      type: 'quorum' // needed for Truffle to support Quorum`
please check this https://www.trufflesuite.com/docs/truffle/distributed-ledger-support/working-with-quorum

**Comment by gnidan** [comment] 2020-01-29 18:37
@eggplantzzz suggests that there might be a problem with the tutorial. Can anyway verify whether this tutorial is up-to-date or not?

**Comment by gnidan** [comment] 2020-01-29 18:37
@vishnutm also, you might have more luck with Node v10 instead of Node v12

**Comment by gnidan** [comment] 2020-03-04 18:54
Closing this for issue maintenance and since no one knows what's going on. 😄 

Thanks! Let us know if you know what's going on, and I'll happily re-open!

**Closed by gnidan** 2020-03-04 18:54 UTC

**Comment by CruzMolina** [comment] 2020-03-04 18:55
Hey @vishnutm!

If you can share a repo with reproduction steps, would be happy to re-open and look into this. 

Thanks!
