### ISSUE TITLE
[BUG] Cannot destructure property `context` of 'undefined' or 'null'. @ truffle debug

### ISSUE THREAD

**Issue by mesqueeb** [trufflesuite/truffle#1365] opened 2018-10-23 05:55 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Right after `truffle debug txid` I get:

```
// compiling all contracts
Gathering transaction data...

redux-saga error: uncaught at session.saga
at session.saga
 at recordInstance
 TypeError: Cannot destructure property `context` of 'undefined' or 'null'.
    at Object.addInstance (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:100224:23)
```

## Expected Behavior

Start the debug process.

## Actual Results

See "issue" above.

## Environment

* Operating System: `macOS mojave latest`
* Ethereum client: `ganache-cli@6.1.8`
* Truffle version: `Truffle v4.1.14 (core: 4.1.14)`
  and `Solidity v0.4.24 (solc-js)`
* node version: `v10.10.0`
* npm version: `v6.4.1`

## Steps to Reproduce

Currently only happening in a private repository. Was not able to reproduce yet.

## Details 

This is the function in cli.bundled.js that's failing:
```js
/**
 * Adds known deployed instance of binary at address
 *
 * @return {string} ID (0x-prefixed keccak of binary)
 */
function* addInstance(address, binary) {
  let search = yield (0, _effects.select)(_selectors2.default.info.binaries.search);
  if (binary != "0x0") {
    let { context } = search(binary);

    yield (0, _effects.put)(actions.addInstance(address, context, binary));

    return context;
  }
}
```

**Comment by roschler** [comment] 2018-11-14 15:03
I encountered this error too today.  I am using Ganache v 1.2.2, Node.JS 8.1, and NPM 5.6.0.

**Comment by flockonus** [comment] 2018-11-19 21:47
Having the same error when debugging some transactions on Truffle 4.1.14

I'm under the impression that it happens more often on larger functions, but i could be wrong.

**Comment by ldub** [comment] 2018-11-22 02:34
+1 Same issue here, also this appears to be related to https://github.com/trufflesuite/truffle/issues/1051

Folks in that thread were seeing the same issue towards the end.

**Comment by gnidan** [comment] 2019-02-13 18:36
Can someone who can reproduce this please try it again on Truffle v5.0.4? @haltman-at has been making lots of debugger stability improvements and I'm hoping it solves issues like this one.

**Comment by julien51** [comment] 2019-04-18 13:55
Still happening for us with truffle 5.0.13...

**Comment by haltman-at** [comment] 2019-04-18 23:16
Hi, would you mind posting the precise error message?  It doesn't seem possible that this exact *same* error would still be occurring, because `evm.addInstance` no longer attempts to destructure the `context` property of anything, but perhaps it could be a similar and related one.  I'd need to see the error message to have any idea.

Additionally, if you have more detailed reproduction steps, that would be very helpful.

Thank you!

**Comment by eggplantzzz** [comment] 2019-07-10 17:54
Closing this for now. If anyone can provide reliable reproduction steps then it would be super helpful in troubleshooting this!

**Closed by eggplantzzz** 2019-07-10 17:54 UTC
Labels: Debugger
