### ISSUE TITLE
Update web3-provider-engine to match web3-provider-engine v15.0.12

### ISSUE THREAD

**Issue by paulbarclay** [trufflesuite/truffle#3129] opened 2020-06-28 08:59 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The following error trace is caused by Infura returning an invalid block (and not returning an error). Metamask has fixed this issue in v15.0.12 (https://github.com/MetaMask/web3-provider-engine/issues/313).

## Steps to Reproduce

Wait for Infura to screw up (I guess you could make a dummy endpoint that returned a null block)

## Expected Behavior

There should be no exception; we should just wait for a successful block

## Actual Results

Throws because the block is null, which crashes the entire app.

[web   ] [2020-06-27T14:43:34.534Z] /var/app/current/node_modules/@trufflesuite/web3-provider-engine/index.js:219
[web   ]     number:           ethUtil.toBuffer(jsonBlock.number),
[web   ]                                                  ^
[web   ] [2020-06-27T14:43:34.534Z] TypeError: Cannot read property 'number' of null
[web   ]     at toBufferBlock (/var/app/current/node_modules/@trufflesuite/web3-provider-engine/index.js:219:50)
[web   ]     at self._getBlockByNumber (/var/app/current/node_modules/@trufflesuite/web3-provider-engine/index.js:60:27)
[web   ]     at _handleAsync (/var/app/current/node_modules/@trufflesuite/web3-provider-engine/index.js:136:12)
[web   ]     at /var/app/current/node_modules/@trufflesuite/web3-provider-engine/index.js:199:9
[web   ]     at /var/app/current/node_modules/async/internal/once.js:12:16
[web   ]     at replenish (/var/app/current/node_modules/async/internal/eachOfLimit.js:61:25)
[web   ]     at /var/app/current/node_modules/async/internal/eachOfLimit.js:71:9
[web   ]     at eachLimit (/var/app/current/node_modules/async/eachLimit.js:43:36)
[web   ]     at /var/app/current/node_modules/async/internal/doLimit.js:9:16
[web   ]     at end (/var/app/current/node_modules/@trufflesuite/web3-provider-engine/index.js:176:5)
[web   ]     at /var/app/current/node_modules/@trufflesuite/web3-provider-engine/subproviders/provider.js:19:5
[web   ]     at XMLHttpRequest.request.onreadystatechange (/var/app/current/node_modules/web3-providers-http/src/index.js:96:13)
[web   ]     at XMLHttpRequestEventTarget.dispatchEvent (/var/app/current/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
[web   ]     at XMLHttpRequest._setReadyState (/var/app/current/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
[web   ]     at XMLHttpRequest._onHttpResponseEnd (/var/app/current/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
[web   ]     at IncomingMessage.<anonymous> (/var/app/current/node_modules/xhr2-cookies/xml-http-request.ts:311:39)

## Environment

* Operating System: Docker (linux)
* Ethereum client: hd-wallet-provider
* Truffle version (`truffle version`): 1.0.36

**Comment by CruzMolina** [comment] 2020-06-29 17:04
Thanks for the heads up @paulbarclay ! @ltfschoen has a fix for this in https://github.com/trufflesuite/provider-engine/pull/6. Closing as a duplicate of #3130 .

**Closed by CruzMolina** 2020-06-29 17:04 UTC

**Comment by CruzMolina** [comment] 2020-06-29 23:13
Until this goes out in our official weekly release, the fix for this is out at `@truffle/hdwallet-provider@next`.

Please give it a shot and let us know if this particular error has been resolved! 🙏
