### ISSUE TITLE
FATAL ERROR: NewNativeModule Allocation failed - process out of memory

### ISSUE THREAD

**Issue by Doughp** [trufflesuite/truffle#4592] opened 2022-01-05 21:23 UTC
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
I am getting this error when trying to run "truffle migrate --reset" to Ganache and the port is correct and address.
I am trying to connect my Smart Contract and my DApp. I have ran the node --max-old-space-size=8192 and tried with underscores instead.

## Steps to Reproduce

I have installed truffle and ganache and I have my contracts inside my dapp and then i ran ganache-cli to open ganache and then i opened a new terminal and ran truffle migrate --reset
## Expected Behavior

What you expected to happen.
I wanted to connect to Ganache

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

===========================

<--- Last few GCs --->
 p[6376:0C773D28]     7391 ms: Mark-sweep (reduce) 177.6 (186.1) -> 172.4 (179.5) MB, 178.3 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, bigges172.4 (179.5) -> 172.2 (177.2) MB, 184.2 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 185 
ms) (average mu = 0.448, current mu = 0.061) memory p

<--- JS stacktrace --->

FATAL ERROR: NewNativeModule Allocation failed - process out of memory

![Screenshot 2022-01-05 152250](https://user-images.githubusercontent.com/94391490/148291385-b9560c9d-f6a7-4a03-8c74-69f28c054b47.jpg)

## Environment

* Operating System: Windows 10 I have updated to latest
* Ethereum client:
* Truffle version (`truffle version`): 5.4.26
* node version (`node --version`): 16.13.1
* npm version (`npm --version`):  8.3.0

**Comment by cds-amal** [comment] 2022-01-05 21:48
Hi @Doughp,

Is it possible to share your repo with the contracts so we can investigate this issue? Also, can you share the specific [windows 10 version](https://docs.microsoft.com/en-us/windows/release-health/release-information) you used? 

Thanks!

**Comment by Doughp** [comment] 2022-01-05 22:03
> Hi @Doughp,
> 
> Is it possible to share your repo with the contracts so we can investigate this issue? Also, can you share the specific [windows 10 version](https://docs.microsoft.com/en-us/windows/release-health/release-information) you used?
> 
> Thanks!

Yes
https://github.com/Doughp/FATALERROR.git

**Comment by lsqproduction** [comment] 2022-01-07 17:19
Hello @Doughp 
I tried to reproduce the error using windows 10 21H2 32GB RAM with the provided repo above and wasn't successful. 
May I know how much free memory do you have before running` truffle migrate --reset`?
Are there other applications you're running at the same time?

**Comment by Doughp** [comment] 2022-01-07 20:36
I am not having issues with truffle anymore.
I have no clue why it was giving me those errors I think I had too much
running at the same time.
I have 85GB free on my computer.  Now however, I am getting this error when
running the Dapp I have made no changes to any of the node modules folders.
I wasn't having this issue before I had the "FATAL ERROR" and I also
downloaded a copy that I was using before I ran into that error.

As you can see the button Mints and it sends the metadata to pinata but it
does not pop up to actually Mint the token.

**Comment by cds-amal** [comment] 2022-01-11 17:14
Hey @Doughp , glad you're not having issues with Truffle anymore! To tie things up, could you confirm the amount of RAM (not disk space) on your device? We're working on making Truffle a better experience on Windows and every bit of data helps. Thanks in advance!

**Comment by Doughp** [comment] 2022-01-12 20:40
8.00GB with 7.53GB Available

**Comment by gnidan** [comment] 2022-01-26 19:45
Thanks for the info! Looks like we can close this now for issue maintenance. Feel free to reach out again in a new issue if anything else comes up! Cheers!

**Closed by gnidan** 2022-01-26 19:45 UTC
