### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by vidhyaramani** [trufflesuite/truffle#876] opened 2018-03-29 08:01 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by vidhyaramani** [comment] 2018-03-29 08:04
Hi, I have an issue in truffle connection with visual studio code. I have installed everything followed by the link https://davidburela.wordpress.com/2016/11/18/how-to-install-truffle-testrpc-on-windows-for-blockchain-development/ everything was succesfully installed. . I have created my project and run the command truffle init but not opening the default project structure in visual studio code. Solidity is also there,  Please help me out! Thanks!

**Comment by cgewecke** [comment] 2018-03-29 14:52
@vidhyaramani Closing as duplicate of #874. Please see the response there.

**Closed by cgewecke** 2018-03-29 14:52 UTC
