### ISSUE TITLE
ES6 update?

### ISSUE THREAD

**Issue by vincentserpoul** [trufflesuite/truffle#228] opened 2016-08-08 02:34 UTC
For example, instead of 

```
  it("should call a function that depends on a linked library  ", function(){
    var meta = MetaCoin.deployed();
    var metaCoinBalance;
    var metaCoinEthBalance;

    return meta.getBalance.call(accounts[0]).then(function(outCoinBalance){
      metaCoinBalance = outCoinBalance.toNumber();
      return meta.getBalanceInEth.call(accounts[0]);
    }).then(function(outCoinBalanceEth){
      metaCoinEthBalance = outCoinBalanceEth.toNumber();

    }).then(function(){
      assert.equal(metaCoinEthBalance,2*metaCoinBalance,"Library function returned unexpeced function, linkage may be broken");

    });
  });
```

we would have:

```
  it("should call a function that depends on a linked library  ", () => {
    const meta = MetaCoin.deployed();
    let metaCoinBalance;

    return meta.getBalance.call(accounts[0])
    .then(outCoinBalance => {
      metaCoinBalance = outCoinBalance.toNumber();
      return meta.getBalanceInEth.call(accounts[0]);
    })
    .then(outCoinBalanceEth => outCoinBalanceEth.toNumber())
    .then(metaCoinEthBalance => assert.equal(
        metaCoinEthBalance, 2*metaCoinBalance,
        "Library function returned unexpeced function, linkage may be broken"
      );
    );
  });
```

Do you all consider it an improvement?

**Comment by tcoulter** [comment] 2017-07-13 17:01
Hi there. Thanks for posting this. I'm going to mark this as a duplicate of #314. Even though async/await is fully supported in Node 8, I want to wait a bit to ensure we're not prohibitively excluding users who cannot install Node 8 for some reason (either because of their organization's rules, or something else). Will reconsider this in a month or two. Keep watch of #314 for more info.

**Closed by tcoulter** 2017-07-13 17:01 UTC
