### ISSUE TITLE
Error installing truffle-contract@4.0.28

### ISSUE THREAD

**Issue by sebastiantf** [trufflesuite/truffle#2286] opened 2019-08-09 10:15 UTC
## Issue

`npm install truffle-contract --save-dev` fails with the following error:
```
> sha3@1.2.3 install E:\project-folder\node_modules\sha3
> node-gyp rebuild


E:\project-folder\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\user\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\project-folder\node_modules\sha3
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN project-folder@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-08-09T09_46_09_741Z-debug.log
```

But the following steps work:
1. `npm install truffle-contract@4.0.21 --save-dev`
    * this would produce the same error as above
2. After 1, `npm install truffle-contract --save-dev` works fine. 
    * truffle@4.0.28 is installed correctly
## Steps to Reproduce

1. `npm install truffle-contract --save-dev` => error
2. `npm install truffle-contract@4.0.21 --save-dev` => error
3. `npm install truffle-contract --save-dev` => success

## Expected Behavior

Step 1 should work fine

## Environment

* Operating System: Windows 10
* Truffle version (`v5.0.29`):
* node version (`v10.15.3`):
* npm version (`6.4.1`):

**Comment by gnidan** [comment] 2019-08-12 02:09
Will have to look into this. Thanks for raising the issue!

**Comment by haltman-at** [comment] 2020-05-13 18:00
Hi, is this still a problem on the most recent version of Truffle Contract?  Thank you!

**Comment by sebastiantf** [comment] 2020-05-13 18:05
I'm not sure. I haven't been using truffle for some time now.

**Comment by eggplantzzz** [comment] 2020-05-20 18:06
Closing for issue maintenance. If you want us to pursue this further then please do get back to us and we'll try to help you out! Thanks!

**Comment by PatrickAlphaC** [comment] 2020-08-01 20:53
Yes it's still an issue. I have yet to find a work around.

**Comment by CruzMolina** [comment] 2020-08-01 21:09
Ah, yeah this still would be an issue when installing `@truffle/contract` as a devDep. https://github.com/trufflesuite/truffle/blob/develop/packages/contract/package.json#L44

See the PlantUML diagram in https://github.com/trufflesuite/truffle/issues/3175.

**Comment by fainashalts** [comment] 2020-08-05 18:01
Hi @PatrickAlphaC thanks for getting back to us! Can you try this again with the latest version of `@truffle/contract`? If that doesn't work, can you provide reproduction steps (if they are different in any way from those in the original issue)? Thanks!

**Comment by CruzMolina** [comment] 2020-08-05 18:25
Scratch what I said earlier. `@truffle/contract` isn't pulling down `ganache-core` when installed a devDep. 

Looks like this was an old issue with `web3` having `node-gyp` as a deeply nested dependency in `beta.37`.
This issue should be resolved on latest `truffle-contract`, along with `@truffle/contract`.

**Comment by PatrickAlphaC** [comment] 2020-08-05 23:42
Works for me now :)

**Comment by eggplantzzz** [comment] 2020-08-06 16:00
Very cool, closing this.

**Closed by eggplantzzz** 2020-08-06 16:00 UTC
Labels: bug, help wanted, needs reproduced
