### ISSUE TITLE
Error: unknown transaction

### ISSUE THREAD

**Issue by hqxluoyang** [trufflesuite/truffle#747] opened 2018-01-12 03:02 UTC
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: unknown transaction

**Comment by cgewecke** [comment] 2018-01-12 17:47
Hi @hqxluoyang, thanks for opening. Which Ethereum client are you using? Your issue might the same as #721.

**Comment by cgewecke** [comment] 2018-01-16 02:11
Closing as duplicate of #749

**Closed by cgewecke** 2018-01-16 02:11 UTC
