### ISSUE TITLE
Can't use the debugger to step in to `address.call` method (using `-x` and the address is verified on Etherscan)

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/truffle#4584] opened 2022-01-04 01:55 UTC
This is related to https://github.com/trufflesuite/truffle/issues/4582. The same exact reproduction steps apply here. After setting the breakpoint continue (`c`) to the breakpoint :sparkles: _twice_ :sparkles:  and then try to step in to the `target.call` call. I couldn't get it to step in; it would just continue to the `return _verifyCallResult(success, returndata, errorMessage);` line.

IMPORTANT NOTE: `ganache@7.0.0-beta.2` does not return the correct value for `returndata` here (which is why i'm messing with this contract in the first place).

This is the line at which we set the breakpoint:

```
119:         (bool success, bytes memory returndata) = target.call{ value: value }(data);
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Here is a printout of the `Local variables` at this moment:

```
target: 0x2150b45626199CFa5089368BDcA30cd0bfB152D6
data: hex'36df7ea50000000000000000000000007900c70a377f89df29d1d1939469ae3b74c5b740'
value: 0
errorMessage: 'SR: call reverted'
```

The full function:
```
    /**
     * @dev Same as {xref-Address-functionCallWithValue-address-bytes-uint256-}[`functionCallWithValue`], but
     * with `errorMessage` as a fallback revert reason when `target` reverts.
     *
     * _Available since v3.1._
     */
    function functionCallWithValue(address target, bytes memory data, uint256 value, string memory errorMessage) internal returns (bytes memory) {
        require(address(this).balance >= value, "Address: insufficient balance for call");
        require(isContract(target), "Address: call to non-contract");

        // solhint-disable-next-line avoid-low-level-calls
        (bool success, bytes memory returndata) = target.call{ value: value }(data);
        return _verifyCallResult(success, returndata, errorMessage);
    }
```

My debugger output when attempting to step in:
```
debug(development:0x1d3bc7a1...)> i


Address.sol:

117: 
118:         // solhint-disable-next-line avoid-low-level-calls
119:         (bool success, bytes memory returndata) = target.call{ value: value }(data);
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

debug(development:0x1d3bc7a1...)> i

Address.sol:

118:         // solhint-disable-next-line avoid-low-level-calls
119:         (bool success, bytes memory returndata) = target.call{ value: value }(data);
120:         return _verifyCallResult(success, returndata, errorMessage);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

debug(development:0x1d3bc7a1...)>
```

**Comment by davidmurdoch** [comment] 2022-01-04 01:56
I just realized I'm not using my etherscan API key... so don't look into this yet! I'll add it and try again.

**Comment by davidmurdoch** [comment] 2022-01-04 02:09
Update: it still doesn't step in with an etherscan API key.

**Comment by davidmurdoch** [comment] 2022-01-04 02:11
Additional information:

The address in question (`0x2150b45626199CFa5089368BDcA30cd0bfB152D6 - HarvestV2Keep3rStealthJob`) is the debugger's list of affected addresses:

```
⚠ Errors occurred while compiling sources for addresses 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48, 0x39AA39c021dfbaE8faC545936693aC917d5E7563, 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B, 0xcb12Ac8649eA06Cbb15e29032163938D5F86D8ad.
✔ Gathering information about your project and the transaction...

Addresses affected:
 0xC454F4E1DDB39c8De9663287D52b0E4Feb4cA45E - StealthVault
 0x2150b45626199CFa5089368BDcA30cd0bfB152D6 - HarvestV2Keep3rStealthJob
 0x0a61c2146A7800bdC278833F21EBf56Cd660EE2a - StealthRelayer
 0x1cEB5cB57C4D4E2b2433641b95Dd330A33185A44 - Keep3rV1
 0x169E633A2D1E6c10dD91238Ba11c4A708dfEF37C - EACAggregatorProxy
 0x785433d8b06D77D68dF6be63944742130A4530d1 - AccessControlledOffchainAggregator
 0x7900c70a377f89DF29D1D1939469ae3B74c5B740 - Strategy
 0x5f18C75AbDAe578b483E5F43f12a39cF75b973a9(UNKNOWN)
 0xe11ba472F74869176652C35D30dB89854b5ae84D(UNKNOWN)
 0x736D7e3c5a6CB2CE3B764300140ABF476F6CFCCF - V2Keeper
 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48(UNKNOWN)
 0xa2327a938Febf5FEC13baCFb16Ae10EcBc4cbDCF - FiatTokenV2_1
 0x39AA39c021dfbaE8faC545936693aC917d5E7563(UNKNOWN)
 0xD8EC56013EA119E7181d231E5048f90fBbe753c0 - LegacyJumpRateModelV2
 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B(UNKNOWN)
 0xBafE01ff935C7305907c33BF824352eE5979B526 - Comptroller
 0xc00e94Cb662C3520282E6f5717214004A7f26888 - Comp
 0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F - UniswapV2Router02
 0x31503dcb60119A812feE820bb7042752019F2355 - UniswapV2Pair
 0x397FF1542f962076d0BFE58eA045FfA2d347ACa0 - UniswapV2Pair
 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 - WETH9
 0x0eeA166dC8e01f3CA5AFFa03aa316B3BDB8e6E16 - FlashMintLib
 0x1EB4CF3A948E7D72A198fe073cCb8C7a948cD853 - DssFlash
 0x6D2299C48a8dD07a872FDd0F8233924872Ad1071 - UniswapAnchoredView
 0x6B175474E89094C44Da98b954EedeAC495271d0F - Dai
 0x35D1b3F3D7966A1DFe207aa4514C12a259A0492B - Vat
 0x9759A6Ac90977b93B58547b4A71c78317f391A28 - DaiJoin
 0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643 - CErc20Delegator
 0xa035b9e130F2B1AedC733eEFb1C67Ba4c503491F - CErc20Delegate
 0xFB564da37B41b2F6B6EDcc3e56FbF523bD9F2012 - JumpRateModelV2
 0xDDCea799fF1699e98EDF118e0629A974Df7DF012 - CommonHealthCheck
 0xcb12Ac8649eA06Cbb15e29032163938D5F86D8ad(UNKNOWN)
 0x11B7a6bc0259ed6Cf9DB8F499988F9eCc7167bf5(UNKNOWN)

Warning: The source code for one or more contracts could not be found.
```

**Comment by haltman-at** [comment] 2022-01-04 02:15
Note that if it were in fact just due to repeated timeouts from Etherscan, the address ought to appear in the list of addresses there were problems fetching.  Since you haven't included such a list I'm assuming there were none, so it really is something else, not just some timeout problem.  It doesn't appear in the list of addresses there were problems compiling either.  I wonder what's going on...?

**Comment by davidmurdoch** [comment] 2022-01-04 16:10
in case you missed it, I did include the list of addresses.

**Comment by haltman-at** [comment] 2022-01-04 17:56
No I mean, there's the list of addresses affected; there's the list of addresses that wouldn't compile; there's no list of addresses where a problem was encountered fetching.  I'm assuming that's because there was, in fact, no such list (it's not going to print anything if there's nothing to print).  I was just accounting for the possibility that you might have missed a line while copying and pasting.  But presumably you didn't, and so the problem isn't a timeout.

**Comment by haltman-at** [comment] 2022-01-04 22:59
Further note from @davidmurdoch: Apparently the first occurrence is fine, it's the second where the problem occurs.

**Comment by davidmurdoch** [comment] 2022-01-04 23:02
Yes, sorry. That's what I meant when I said:

> ...after setting the breakpoint continue (c) to the breakpoint :sparkles:  *twice* :sparkles: ...

**Comment by haltman-at** [comment] 2022-01-04 23:10
Ah, sorry, I missed that.

**Comment by haltman-at** [comment] 2022-01-04 23:12
OK, so having reproduced this, the reason it doesn't step in the second time is because there's nothing to step into!  The second time it hits that breakpoint, it's *returning* from that function, so of course it then proceeds to the next line.

So there is an issue here, but it's an issue of the debugger acting counterintuitively when pressing `c` (you don't expect that it'll take you to the function's return, but rather to the next invocation -- do we have an issue open for that?), rather than one of it failing to step into anything.

**Comment by kevinweaver** [comment] 2022-01-05 19:21
Closing this out in favor of a new issue @haltman-at will create.

**Closed by kevinweaver** 2022-01-05 19:21 UTC
Labels: Debugger
