### ISSUE TITLE
Deployment artifacts do not store smart contract records for multiple networks with the same network ID

### ISSUE THREAD

**Issue by busypeter** [trufflesuite/truffle#1832] opened 2019-03-19 11:53 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The deployment artifacts in ``build/contracts/`` store the migration state, i.e. addresses of deployed contracts. These addresses are stored per network ID, so if in truffle-config.js we define more than one network with the same ID, ``truffle migrate`` will only store state for one network (probably for the last deployment, I haven't tested this).

There are multiple scenarios where this feature is required. One would be where we have multiple test environments, e.g. TEST and STAGE, and we want them on the same testnet. In this case, in truffle-config.js we'll have two networks with different names, but with the same network ID.

## Steps to Reproduce
1. Add the following networks to truffle-config.js:
```
    stage: {
      provider: () => {
        return new HDWalletProvider(STAGE_MNEMONIC, "https://rinkeby.infura.io/v3/" + INFURA_STAGE_TOKEN)
      },
      network_id: 4
    },
    dev: {
      provider: () => {
        return new HDWalletProvider(DEV_MNEMONIC, "https://rinkeby.infura.io/v3/" + INFURA_DEV_TOKEN)
      },
      network_id: 4
    },
```
2. Run ``truffle migrate``.

## Expected Behavior

Deployment artifact stores contract addresses for both 'stage' and 'dev' networks.

## Actual Results

Deployment artifact stores contract addresses for one network only.

## Environment

* Operating System: Any
* Ethereum client: Any
* Truffle version (`truffle version`): 5.0.2
* node version (`node --version`): 8.10.0
* npm version (`npm --version`): 6.5.0

**Comment by gnidan** [comment] 2019-04-17 17:51
Yep. This is a known limitation. Frustrating as heck, I know! I'll group this into #1718, since there's ongoing work there to address these problems. Thanks for bringing this up!

**Comment by gnidan** [comment] 2019-07-09 02:55
Issue maintenance: closing this as duplicate of #1087

**Closed by gnidan** 2019-07-09 02:55 UTC
Labels: Migrations, enhancement, help wanted
