### ISSUE TITLE
Error: Returned error: Cannot get state root with uncommitted checkpoints

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [trufflesuite/truffle#2811] opened 2020-02-04 15:56 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
```

{
 Error: Returned error: Cannot get state root with uncommitted checkpoints    at PromiEvent (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
    at TruffleContract.getETH (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
    at Context.<anonymous> (/home/test/IdeaProjects/carbon-token/test/DECA.js:293:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  hijackedStack: 'Error: Returned error: Cannot get state root with uncommitted checkpoints\n    at Object.ErrorResponse (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/src/errors.js:29:1)\n    at /home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-requestmanager/src/index.js:140:1\n    at /home/test/.npm-global/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:112:1\n    at XMLHttpRequest.request.onreadystatechange (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-providers-http/src/index.js:96:1)\n    at XMLHttpRequestEventTarget.dispatchEvent (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)\n    at XMLHttpRequest._setReadyState (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)\n    at XMLHttpRequest._onHttpResponseEnd (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)\n    at IncomingMessage.<anonymous> (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)' }

```

## Steps to Reproduce
Take this contract : 
```

pragma solidity 0.5.16;

contract DECA {
    address payable private _owner;

    constructor () public {
        _owner = msg.sender;
    }

    function() external payable {

    }

    function getETH() public {     
        _owner.transfer(address(this).balance);
    }

}

```

And execute this test : 
```
async function getHighBalance() {
    var accounts = await web3.eth.getAccounts();
    var acc = accounts[0];
    console.dir(acc)
    var b = await web3.eth.getBalance(acc);

    console.dir(b)
    let high = {
        "address": acc,
        "balance": b
    }

    return high;
}
 describe('reproducer', async function () {
        it('check getETH', async function () {
            this.creator = await getHighBalance();

            this.deca = await DECA.new({
                from: this.creator.address,
                gas: 6712390
            })

            let decaBalance = await web3.eth.getBalance(this.deca.address);
            assert.equal(decaBalance.toString(10), '0', " wrong contract balance")
            var sender = await getHighBalance();
            await web3.eth.sendTransaction({
                from: sender.address,
                to: this.deca.address,
                value: 1000,
                gas: 6712390
            });
            decaBalance = await web3.eth.getBalance(this.deca.address);
            assert.equal(decaBalance.toString(10), '1000', " wrong contract balance")
            let wasErr = false;
            try {
                await this.deca.getETH({from: this.creator.address, gas: 6712390})
            } catch (err) {
                console.dir(err)
                wasErr = true;
            }
            assert.equal(false, wasErr, "getETH not possible to test because of bug in truffle")
            decaBalance = await web3.eth.getBalance(this.deca.address);
            assert.equal(decaBalance.toString(10), '0', " balance of the DECA expected to be empty")
        })
    })
```

## Expected Behavior

pass test

## Actual Results

failed because of exception

## Environment

* Operating System:  arch linux
Truffle v5.1.11 (core: 5.1.11)
Solidity v0.5.16 (solc-js)
Node v8.16.2
Web3.js v1.2.1

**Comment by kostysh** [comment] 2020-02-07 00:36
faced the same issue

**Comment by gnidan** [comment] 2020-02-19 18:38
Nice, Arch Linux :)

I think we'll need to investigate this. @davidmurdoch is this a Ganache error?

**Comment by davidmurdoch** [comment] 2020-02-19 21:28
Hey @vitaliy-kuzmich, i'm unable to reproduce the issue given the code supplied here. If you configure this test to run on its own via `it.only` does the test still fail for you? example: 

```
 describe('reproducer', async function () {
        it.only('check getETH', async function () {
            // {the rest of the test here}
        });
});
```

unrelated question: is there a specific reason you are using Node 8?

**Comment by vitaliy-kuzmich** [comment] 2020-02-23 17:20
@davidmurdoch it still does not work with it.only, shows same error. I do not remember why I did not upgrade for the newer Node version, maybe because in past testrpc did not want to work with newer version.

**Comment by davidmurdoch** [comment] 2020-02-24 19:11
@@vitaliy-kuzmich can you try updating truffle to v5.1.14 and try again?

**Comment by vitaliy-kuzmich** [comment] 2020-02-26 14:17
@davidmurdoch 
Truffle v5.1.14 (core: 5.1.14)
Solidity v0.5.16 (solc-js)
Node v13.9.0
Web3.js v1.2.1

That error message still remains. 

```
Error: Returned error: Cannot get state root with uncommitted checkpoints    at PromiEvent (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
at TruffleContract.getETH (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
at Context.<anonymous> (/home/test/IdeaProjects/carbon-token/test/DECA.js:252:37)
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
hijackedStack: 'Error: Returned error: Cannot get state root with uncommitted checkpoints\n' +
'    at Object.ErrorResponse (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/src/errors.js:29:1)\n' +
'    at /home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-requestmanager/src/index.js:140:1\n' +
'    at /home/test/.npm-global/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:112:1\n' +
'    at XMLHttpRequest.request.onreadystatechange (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/web3-providers-http/src/index.js:96:1)\n' +
'    at XMLHttpRequestEventTarget.dispatchEvent (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)\n' +
'    at XMLHttpRequest._setReadyState (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)\n' +
'    at XMLHttpRequest._onHttpResponseEnd (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)\n' +
'    at IncomingMessage.<anonymous> (/home/test/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)\n' +
'    at IncomingMessage.emit (events.js:333:22)\n' +
'    at endReadableNT (_stream_readable.js:1201:12)\n' +
'    at processTicksAndRejections (internal/process/task_queues.js:84:21)'

```

**Comment by davidmurdoch** [comment] 2020-02-28 16:02
@vitaliy-kuzmich Hmmm, I'm still unable to reproduce the issue. Are you able to create a minimal reproduction repository (or upload a zip/archive and share a link) so I can debug the same exact configuration and code that is exhibiting this behavior?

**Comment by vitaliy-kuzmich** [comment] 2020-02-28 18:46
@davidmurdoch was you able to reproduce it before truffle  v5.1.14 ?

**Comment by vitaliy-kuzmich** [comment] 2020-02-28 18:49
@kostysh what is your system environment ?

**Comment by davidmurdoch** [comment] 2020-02-28 18:49
I was not able to reproduce this issue with truffle 5.1.14 or 5.1.11.

You don't need to include any `node_modules` folders, but do be sure to include the project's lock file (`yarn.lock`, `package-lock.json` or `npm-shrinkwrap.json`) if present.

**Comment by vitaliy-kuzmich** [comment] 2020-02-28 19:07
@davidmurdoch  Can you explain how are you going to debug it ? Maybe share some links ? Because I did not know how to put breakpoints in truffle.

[reproducer.tar.gz](https://github.com/trufflesuite/truffle/files/4268601/reproducer.tar.gz)

**Comment by davidmurdoch** [comment] 2020-02-28 19:35
@vitaliy-kuzmich What version of `ganache-cli` did you use for these tests? I noticed in `run-rpc.sh` you have `/full path here/ganache-cli` but `ganache-cli` isn't defined in your `package.json`.

If you have `ganache-cli` installed globally (which is normal), run `ganache-cli --version` in your terminal to output that version.

**Comment by vitaliy-kuzmich** [comment] 2020-02-28 19:56
@davidmurdoch Ganache CLI v6.9.1 (ganache-core: 2.10.2)

**Comment by davidmurdoch** [comment] 2020-02-28 20:20
I'm able to reproduce this now. The reason I couldn't reproduce before is because the bug only happens when the account involved in the transfer is holding VERY large amount of ether, `999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999` qualifies. :-D

At first glance this appears to be caused by an `ethereumjs-vm` bug (probably two bugs). The first bug is that `ethereumjs-vm` can't properly compute very large numbers. The other is that when an opcode throws an exception the vm's internal checkpoint stack isn't reverted enough times.

Or... it's a ganache-core bug. An easy fix for you right now is to reduce your  account's ether amount.

As for how to debug this... It's a bit convoluted:

 * I cloned `ganache-cli`
 * modified `lib.js` to reference my locally cloned `ganache-core` instead of the `node_modules` version.
 * I start up `ganache-cli` via `node --inspect /path/to/ganache-cli/cli.js`.
 * I then opened `ganache-core` in Visual Studio Code and set relevant breakpoints there.
 * I then attached to the modified `ganache-cli` (via Visual Studio Code) node debugger (Ctrl+Shift+P, select `>Debug:Attach to Node Process`)

Now when I run `truffle test` the debugger will pause on my breakpoints and I can inspect variables and step through as needed.

**Comment by davidmurdoch** [comment] 2020-02-28 21:12
Related issue: https://github.com/ethereumjs/ethereumjs-vm/issues/672

**Comment by vitaliy-kuzmich** [comment] 2020-02-29 08:38
@davidmurdoch thanks for debug tips!

**Comment by vitaliy-kuzmich** [comment] 2020-03-02 08:03
@davidmurdoch but wait, my script worked since testrpc times, is it mean that new changes chat came with eth-js related things, broke bignumber in js ? Or bignumber is not part of this ecosystem already?

**Comment by davidmurdoch** [comment] 2020-03-02 13:30
I believe they added an upper limit recently (in the past 6 months) because some operations require the data fit in a specific byte length.

**Comment by gnidan** [comment] 2020-07-15 17:56
@vitaliy-kuzmich is this issue still causing trouble for you?

**Comment by gnidan** [comment] 2020-08-26 18:20
Closing this for issue maintenance.

Let us know if there's more that's actionable for Truffle here and we can reopen. Thanks again!

**Closed by gnidan** 2020-08-26 18:20 UTC
Labels: needs investigated
