### ISSUE TITLE
Error: Failed to fetch the Solidity compiler

### ISSUE THREAD

**Issue by N-dcool** [trufflesuite/truffle#5878] opened 2023-02-09 11:26 UTC
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
<img width="711" alt="Screenshot 2023-02-09 at 4 43 04 PM" src="https://user-images.githubusercontent.com/107427909/217797671-0dda3b3c-93f2-4cb7-89d1-140e67f54983.png">

## Steps to Reproduce

1. I created new directory Truffle:
2.  `cd truffle`
3.   `truffle init`
4.    created a sampleContract.sol
5.  `npm init -y`
6.   for my contact i required npm package @openzeppelin/contracts : `npm install --save @openzeppelin/contracts`
7.   `truffle compile`

## Expected Behavior

it should compile normally but not compiled.!!

## Actual Results

Not compiled

## Environment
* Operating System:  MacOS
* Ethereum client: 
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`): 
<img width="249" alt="Screenshot 2023-02-09 at 4 53 31 PM" src="https://user-images.githubusercontent.com/107427909/217799700-73177014-3f8a-4c0f-b4bd-91f767d5132e.png">
<img width="645" alt="Screenshot 2023-02-09 at 4 53 55 PM" src="https://user-images.githubusercontent.com/107427909/217799727-96ced886-2e4a-44f4-8a75-e4e957217bcc.png">
<img width="569" alt="Screenshot 2023-02-09 at 4 54 18 PM" src="https://user-images.githubusercontent.com/107427909/217799761-f500e6b5-0012-4c27-b12a-ec932697e90a.png">

**Comment by cliffoo** [comment] 2023-02-09 19:05
Hey @n-dcool are you behind some special network (GFW or something else)?

Can you also try `node -e "fetch('https://relay.trufflesuite.com/solc/emscripten-wasm32/list.json').then(r => r.text()).then(console.log)"` and share with us the result? Thanks!

**Comment by N-dcool** [comment] 2023-02-10 08:35
<img width="917" alt="Screenshot 2023-02-10 at 2 01 03 PM" src="https://user-images.githubusercontent.com/107427909/218042656-1b0fc806-eb2f-48e4-80be-e16d9bd06b14.png">


> Hey @N-dcool are you behind some special network (GFW or something else)?
> 
> Can you also try `node -e "fetch('https://relay.trufflesuite.com/solc/emscripten-wasm32/list.json').then(r => r.text()).then(console.log)"` and share with us the result? Thanks!

no I am not using any special network.

**Comment by eggplantzzz** [comment] 2023-02-10 17:46
Do you get a bunch of JavaScript if you pop the following URL into a browser? https://binaries.soliditylang.org/emscripten-wasm32/solc-emscripten-wasm32-v0.8.17+commit.8df45f5f.js

**Comment by eggplantzzz** [comment] 2023-02-10 17:46
Do you get JavaScript when you click on the following URL? https://relay.trufflesuite.com/solc/emscripten-wasm32/solc-emscripten-wasm32-v0.8.17+commit.8df45f5f.js

**Comment by N-dcool** [comment] 2023-02-10 18:43
> Do you get JavaScript when you click on the following URL? https://relay.trufflesuite.com/solc/emscripten-wasm32/solc-emscripten-wasm32-v0.8.17+commit.8df45f5f.js
> 
> It seems like you should be able to access it.

Yes I am getting javascript file :
<img width="979" alt="Screenshot 2023-02-11 at 12 11 32 AM" src="https://user-images.githubusercontent.com/107427909/218172364-c47f859e-d4f1-490a-8832-8d3cd95a59f2.png">

**Comment by sixpep-vamshi** [comment] 2023-02-11 12:32
Same issue here

**Comment by sixpep-vamshi** [comment] 2023-02-13 10:04
I tested this on windows and it's working fine. Not working on Mac OS Ventura 13.2, Is this related to any network issue?

**Comment by N-dcool** [comment] 2023-02-13 10:48
> I tested this on windows and it's working fine. Not working on Mac OS Ventura 13.2, Is this related to any network issue?
I think so its related to network issue in MacOS, it could be due to compatibility issues. :(

**Comment by sixpep-vamshi** [comment] 2023-02-13 10:50
Any solution you can think of other than moving to windows :(

**Comment by N-dcool** [comment] 2023-02-13 10:52
I have searched on StackOverflow and other community forums, but I haven't been able to find a proper solution to my problem.

**Comment by sixpep-vamshi** [comment] 2023-02-14 05:42
It's working now

**Comment by N-dcool** [comment] 2023-02-14 07:20
Thnaks now its working fine and compiling!!

**Comment by eggplantzzz** [comment] 2023-02-14 16:07
Ah, so maybe this is a problem with how you installed Truffle. Perhaps you installed Truffle using `sudo`. I would really recommend against doing this. If you do this, there can be permissions issues that can cause problems later.

Instead I would recommend re-installing Node and npm with a Node version manager like nvm, and this is actually what npm recommends. See [this article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#reinstall-npm-with-a-node-version-manager) for more information on this. Then you should run Truffle without `sudo`.

**Comment by N-dcool** [comment] 2023-02-14 17:48
no I have not used `sudo` to install truffle instead used `npm install -g truffle`

**Comment by N-dcool** [comment] 2023-02-14 17:51
> Ah, so maybe this is a problem with how you installed Truffle. Perhaps you installed Truffle using `sudo`. I would really recommend against doing this. If you do this, there can be permissions issues that can cause problems later.
> 
> Instead I would recommend re-installing Node and npm with a Node version manager like nvm, and this is actually what npm recommends. See [this article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#reinstall-npm-with-a-node-version-manager) for more information on this. Then you should run Truffle without `sudo`.

I suggest you to try `truffle compile` once in Mac machine, or there any wrong configuration in my system I will get to know!

**Comment by eggplantzzz** [comment] 2023-02-14 18:13
I am on a mac (as well as a lot of people on my team) and I cannot reproduce your issue. I can run `truffle compile` without any problem. I suggest you try re-installing Node, npm, and Truffle (use the npm article I linked above) and see if you can compile after that. If you try it, let me know how it goes! I'll try and help you get it working on your machine.

**Comment by sixpep-vamshi** [comment] 2023-02-15 05:55
I actually installed using nvm as docs suggest, other options all worked fine except the compile, where it's trying to download the compiler. When I run compile a second time without using sudo, it works.

**Comment by sixpep-vamshi** [comment] 2023-02-15 05:56
> I am on a mac (as well as a lot of people on my team) and I cannot reproduce your issue. I can run `truffle compile` without any problem. I suggest you try re-installing Node, npm, and Truffle (use the npm article I linked above) and see if you can compile after that. If you try it, let me know how it goes! I'll try and help you get it working on your machine.

Also, what mac os are you running?

**Comment by N-dcool** [comment] 2023-02-15 17:24
> > I am on a mac (as well as a lot of people on my team) and I cannot reproduce your issue. I can run `truffle compile` without any problem. I suggest you try re-installing Node, npm, and Truffle (use the npm article I linked above) and see if you can compile after that. If you try it, let me know how it goes! I'll try and help you get it working on your machine.
> 
> Also, what mac os are you running?

Ventura 13.1

**Comment by N-dcool** [comment] 2023-02-15 17:30
> I am on a mac (as well as a lot of people on my team) and I cannot reproduce your issue. I can run `truffle compile` without any problem. I suggest you try re-installing Node, npm, and Truffle (use the npm article I linked above) and see if you can compile after that. If you try it, let me know how it goes! I'll try and help you get it working on your machine.

I re-install all packages again and at first I faced some issue while compiling 1st time but after that its working fine 😄

**Comment by eggplantzzz** [comment] 2023-02-16 19:09
@sixpep-vamshi did you end up re-installing with a Node version manager? Did you get this issue resolved?

**Comment by mjdacs** [comment] 2023-02-17 14:36
I am having the same issue as OP, reinstalled using the provided link in thread and still having problems

**Comment by eggplantzzz** [comment] 2023-02-17 17:47
@mjdacs how is your internet connection? This problem can also be caused by a bad connection. Could you try on a different one to see if you have the same issue? Also, are you able to get a valid response when trying to access the material at this url https://relay.trufflesuite.com/solc/emscripten-wasm32/solc-emscripten-wasm32-v0.8.17+commit.8df45f5f.js? You should see a bunch of JavaScript.

**Comment by mjdacs** [comment] 2023-02-17 22:03
Connection is good. I can probably try another connection this weekend. Yes, I am able to see the JavaScript in the link.

I actually have this problem on both personal (mbair os v11.2.1) and work (mbpro os v13.2.1) machines.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/16667331/219801949-33a087ce-b0d6-4529-89dc-473081914958.png">

**Comment by eggplantzzz** [comment] 2023-02-21 17:58
So the fact that you can see that JavaScript means you can access the compiler but something must be going wrong somewhere else. Just to verify that you are using nvm, can you give me the output for when you enter `which truffle` in the terminal? It will give you the path to the truffle binary. You may, of course, remove anything that you might find to be "sensitive information" from the path it outputs. Thanks!

**Comment by mjdacs** [comment] 2023-02-22 16:03
@eggplantzzz yes captain

<img width="386" alt="image" src="https://user-images.githubusercontent.com/16667331/220682723-4582e6ef-bbdf-4819-ad86-7f8d75b34948.png">

**Comment by eggplantzzz** [comment] 2023-02-22 21:24
Thanks! Hmm, I'll have to go look at the code a little bit more, figure out what else could be going on, and find another way to try and figure out what's going on here.

**Comment by mjdacs** [comment] 2023-02-23 15:12
Yes I get the same error when I run `truffle compile` or `truffle test` (which runs the compiler). 

`Compiling your contracts...`
`==========`
`Error: Failed to fetch the Solidity compiler from the following locations: https://relay.trufflesuite.com/solc/emscripten-wasm32/,https://binaries.soliditylang.org/emscripten-wasm32/,https://relay.trufflesuite.com/solc/emscripten-asmjs/,https://binaries.soliditylang.org/emscripten-asmjs/,https://solc-bin.ethereum.org/bin/,https://ethereum.github.io/solc-bin/bin/. Are you connected to the internet?`


 `at VersionRange.<anonymous> (/Users/michael/.nvm/versions/node/v18.14.1/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:189:1)
    at Generator.next (<anonymous>)
    at /Users/michael/.nvm/versions/node/v18.14.1/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:8:1
    at new Promise (<anonymous>)
    at exports.modules.780.__awaiter (/Users/michael/.nvm/versions/node/v18.14.1/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:4:1)
    at VersionRange.getSolcFromCacheOrUrl (/Users/michael/.nvm/versions/node/v18.14.1/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:180:1)
    at VersionRange.<anonymous> (/Users/michael/.nvm/versions/node/v18.14.1/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:212:1)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/michael/.nvm/versions/node/v18.14.1/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/VersionRange.js:5:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Truffle v5.7.7 (core: 5.7.7)
Node v18.14.1`

**Comment by eggplantzzz** [comment] 2023-02-23 15:26
Thanks for confirming. Currently Truffle errors like this when something goes wrong while trying to fetch the compiler but our error messaging is a little bit imprecise unfortunately. Maybe I can go in a update the code so that the messaging reveals a little more precisely what is going on when it crashes. Give me a little bit of time but I'll try to continue helping troubleshoot.

**Comment by mjdacs** [comment] 2023-02-23 15:29
Thank you, I will keep digging in the meantime on my end. Really appreciate the help.

**Comment by mjdacs** [comment] 2023-02-23 22:16
Holy cow -- `sudo` fixed it. However I do not want to call `sudo` with truffle. What do i have to do there?

**Comment by eggplantzzz** [comment] 2023-02-24 16:49
Yeah I would recommend against using `sudo` with Truffle. So that means it is actually a permissions error like I suggested was a possibility. It is likely an error when attempting to save the compiler to disk after downloading it. Usually that happens when people use `sudo` to install Truffle or when they aren't using Node and npm with nvm...but you are which is strange. In the past these types of errors have generally gone away when they install Node and npm using nvm so I'm not sure what to suggest now. I can tell you that Truffle uses a folder to store compilers and some configuration settings that it needs write access to. On mac that location is `~/Library/Preferences/truffle-nodejs/`, you can check to see what permissions your current user has to that folder. And more specifically, Truffle saves compilers in `~/Library/Preferences/truffle-nodejs/compilers/node_modules/`. I think Truffle is throwing when it is trying to save a filer in that folder. Go ahead and check what kind of permissions your current user has for that folder.

**Comment by eggplantzzz** [comment] 2023-02-24 17:04
I went ahead and create https://github.com/trufflesuite/truffle/pull/5930 which will cause Truffle to give a better error message to the user when there are permissions errors while saving the compiler. Hopefully this will save us all more time troubleshooting in the future :)

**Comment by Rachmaninoffff** [comment] 2023-02-26 14:59
> Yeah I would recommend against using `sudo` with Truffle. So that means it is actually a permissions error like I suggested was a possibility. It is likely an error when attempting to save the compiler to disk after downloading it. Usually that happens when people use `sudo` to install Truffle or when they aren't using Node and npm with nvm...but you are which is strange. In the past these types of errors have generally gone away when they install Node and npm using nvm so I'm not sure what to suggest now. I can tell you that Truffle uses a folder to store compilers and some configuration settings that it needs write access to. On mac that location is `~/Library/Preferences/truffle-nodejs/`, you can check to see what permissions your current user has to that folder. And more specifically, Truffle saves compilers in `~/Library/Preferences/truffle-nodejs/compilers/node_modules/`. I think Truffle is throwing when it is trying to save a filer in that folder. Go ahead and check what kind of permissions your current user has for that folder.

I met the same problem, I can definitely tell you that the issue you mentioned earlier is indeed a permission problem, which is caused by the folder "~/Library/Preferences/truffle-nodejs/". After I changed the ownership to the user using "chown -R xxxx ~/Library/Preferences/truffle-nodejs/", it ran successfully again. The error message is too misleading, so I suggest that you modify the error reporting code.

**Comment by eggplantzzz** [comment] 2023-02-27 15:37
That PR mentioned above will hopefully make troubleshooting this in the future easier. It should give a better message in v5.7.8 and newer.

**Comment by mjdacs** [comment] 2023-02-27 15:43
Thanks again for the better conceptual understanding of what was going on. Got it working on both machines I had issues with

**Comment by eggplantzzz** [comment] 2023-02-27 15:47
Thanks for inspiring the PR!

**Comment by cliffoo** [comment] 2023-03-09 16:20
`v5.7.8` is out and now Truffle should point to permission errors when trying to cache compilers, in which case check yo installation! Closing, thanks all.

**Closed by cliffoo** 2023-03-09 16:20 UTC

**Comment by ghost** [comment] 2024-02-13 14:04
Hi guys, I have the same probleme on a virtual machine using Linux Redhat 8 with :
Truffle v5.11.5
Solidity - 0.8.0
Node v16.20.2
npm 8.19.4

I'm stuck on this for now 1 month this is horrible..
