### ISSUE TITLE
Cannot inspect mappings with addresses as keys

### ISSUE THREAD

**Issue by fvictorio** [trufflesuite/truffle#2889] opened 2020-03-17 00:14 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue. ([Link](https://gitter.im/ConsenSys/truffle?at=5e6ad246d8cd7e214f03ddf2))

---------------------------

## Issue

Mappings that have addresses as keys can't be inspected in debugger.

## Steps to Reproduce

1. Run `truffle unbox metacoin` in some directory
2. Start `ganache-cli` in another terminal
3. Configure the development network to use 8545 as port (probably not necessary if you start ganache-cli in 7545, but that's how I did it)
4. Run `truffle test`
5. Run `truffle compile` (`truffle debug` doesn't seem to compile the contracts if they weren't compiled yet, maybe another issue?)
6. Run `truffle debug` with the last transaction, that calls the `sendCoin` method
7. Step over until you reach the first line of the method
8. Run `:balances` or `:balances[msg.sender]`

## Expected Behavior

`:balances` should show the map with the proper contents, and `:balances[msg.sender]` should show 10000

## Actual Results

I got `Map {}` and `undefined`, respectively.

## Environment

* Operating System: Ubuntu 19.10
* Ethereum client: Not relevant?
* Truffle version (`truffle version`): 5.1.17
* node version (`node --version`): 10.18.1
* npm version (`npm --version`): 6.13.4

**Comment by haltman-at** [comment] 2020-03-17 05:07
Ah, I see the problem.  I'm afraid I'm going to have to close this as a won't-fix for now.  The problem has nothing to do with using addresses as mapping keys.

The problem is that you're asking to see `msg.sender` appear in the list of keys for `balances` at the start of the function, before `balances[msg.sender]` is accessed in the transaction.  Step a bit further, to after this is accessed, and you'll see both `balances` and `balances[msg.sender]` appear correctly.

OK, but why should you have to step that far to see the correct value?  Shouldn't it be correct as soon as `balances` comes in scope?  Well, that would certainly be nice, ideally that's how it would work, but unfortunately this touches on several fundamental limitations of the debugger:
1. First and most obviously, even if we got `balances[msg.sender]` right, there's simply no way that `balances` can appear with `msg.sender` as a key before `balances[msg.sender]` has been accessed, because before that there simply isn't any way for the debugger to know that `msg.sender` even is a key.  This one isn't so much a limitation of the debugger as a limitation of Solidity -- mappings don't track their keys, so there's no way for the debugger to know a given mapping's keys before those keys are accessed.  Now you might ask, OK, maybe I could manually enter keys for it to watch?  Unfortunately that runs up against the other problems, as you'll see...
2. So on seeing the above, you might say, OK, sure, the debugger can't get `balances` right due to Solidity's limitations, but maybe it could at least get `balances[msg.sender]` right, given that determining that doesn't require knowing what the keys are?  And, yes, notionally such a thing would be possible.  But right now that's not how watch expressions work; watch expressions (as opposed to watch individual variables) are kind of a crude hack where we take the decoded Solidity variables and then interpret the expression as JavaScript.  It's awful, yes.  But in order to do better, we'd need, basically, a Solidity interpreter, and we don't have that at the moment, unless we're going to write our own, which would be a substantial undertaking.  So that's out.  But OK -- maybe we could at least add a way that you could manually add `msg.sender` as a key to watch, as I suggested above?  And then things would be OK?  And this is where we run into the biggest problem...
3. The problem that all of the above suggestions run into is that the debugger can only see storage that has been accessed during the transaction.  Even if you could inspect `balances[msg.sender]` before that key was accessed, you wouldn't get the right value for it; you'd just get 0.  (You can try this yourself with other sorts of state variables -- you'll notice the debugger always shows them as 0 until accessed, or until something sharing a slot with them is accessed.)  See, the debugger works by analyzing a trace it gets from the ethereum client, and these traces only show the storage that was accessed, not all the storage.  So, if a storage slot hasn't been accessed, we simply have no way to know its value, under the current architecture.  In order to provide correct values for storage variables before they're accessed, we'd have to do a bunch of additional work to determine their starting values at the beginning of the transaction.  And, let me tell you, that is not as easy as it might sound.

Now, in the long run, I'm planning to write a "reconstruct mode" for the debugger, that will *do* that additional work, remove limitation (3) (well, mostly, anyway), and allow manual watching of mapping keys, at the cost of a longer startup time.  However, that's a long way off, and there's simply no way to fix the problem you describe without that.  In the meantime, I'm closing this issue.  For now I'm afraid you're just going to have to content yourself with only being able to see mapping values after the corresponding keys have been accessed.  Sorry...

(Meanwhile, trying this example has made me realize that we don't handle tabs properly when it comes to positioning the carets that show where in the code you are, yikes!  I'll have to fix that...)

**Closed by haltman-at** 2020-03-17 05:07 UTC

**Comment by haltman-at** [comment] 2020-03-17 20:51
All that said, I should really open an issue for this reconstruct mode I've been talking about, even if it's not high-priority at the moment and so won't be gotten to for a while.  I'll go do that and it'll be linked here! :)

**Comment by fvictorio** [comment] 2020-03-18 17:24
Thank you for the detailed explanation! It totally makes sense for this to be a won't fix. Keep up the amazing work :smiley:

**Comment by haltman-at** [comment] 2020-03-18 17:35
Thanks!  We will get to making reconstruct mode eventually, it's just pretty low-priority at the moment. :)  Unfortunately making it work for mappings runs into additional complications and will probably never really be convenient, but I'm hopeful that I can at least make it workable...
