### ISSUE TITLE
Can't install truffle

### ISSUE THREAD

**Issue by swadhinbiswas000** [trufflesuite/truffle#5015] opened 2022-04-10 18:19 UTC
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I have tried to install truffle in my windows 10 operating system but always getting this error. I have tried almost everything I found online, Nothing works.
![image](https://user-images.githubusercontent.com/52545489/162633719-b377bdd3-1fca-40fd-99b4-21809c21886d.png)

## Environment

* Operating System:  Windows 10
* Ethereum client:
* Truffle version (`truffle version`):
* node version (16.14.2):
* npm version (6.0.1):

**Comment by eggplantzzz** [comment] 2022-04-12 15:27
If not you probably need to install the extra build tools that the Node installer prompts you for. There will be a checkbox while installing that you will need to check. Let me know if this helps you make any progress. Or you may just need to install Visual Studio?

**Comment by swadhinbiswas000** [comment] 2022-04-12 16:17
I tried to install it with the check mark. Now I got this error on powershell.
![Screenshot_1](https://user-images.githubusercontent.com/52545489/163008036-84a41ebd-11b6-4d2c-94d4-447cab2801a7.png)

**Comment by eggplantzzz** [comment] 2022-04-12 16:26
It looks like you are missing some things in your environment, can you try to address the warnings/errors you see above?

**Comment by cds-amal** [comment] 2022-04-13 18:02
Closing as it's a duplicate of https://github.com/trufflesuite/truffle/issues/4951

**Closed by cds-amal** 2022-04-13 18:02 UTC
