### ISSUE TITLE
Solidity test works fine, js test doesn't.

### ISSUE THREAD

**Issue by colus001** [trufflesuite/truffle#1076] opened 2018-06-29 16:30 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I created almost same test code in javascript and solidity. Solidity version works fine but js version doesn't work.

## Steps to Reproduce

TheContract.sol
```
pragma solidity ^0.4.23;

contract TheContract {
  struct Object {
    address createdBy;
    uint balance;
  }

  Object[] public objects;

  mapping (address => uint) countByOwner;

  function createNewObject(address _owner, uint _balance) public {
    objects.push(Object(_owner, _balance));
    countByOwner[_owner]++;
  }

  function getObjectsCountByOwner(address _owner) external view returns (uint) {
    return countByOwner[_owner];
  }

  function getObjectsByOwner(address _owner) external view returns (uint[]) {
    uint[] memory result = new uint[](countByOwner[_owner]);

    uint counter = 0;
    for (uint i = 0; i < objects.length; i++) {
      if (objects[i].createdBy == _owner) {
        result[counter] = i;
        counter++;
      }
    }
    return result;
  }
}

```

theContract.js
```
var TheContract = artifacts.require('./TheContract.sol');

contract('TheContract', function (accounts) {
  const tester = accounts[0];

  it('should create new objects by tester', function() {
    let theContract;

    return TheContract.deployed()
      .then((instance) => {
        theContract = instance;

        return theContract.createNewObject.call(tester, 1)
      })
      .then(() => {
        return theContract.createNewObject.call(tester, 2)
      })
      .then(() => {
        return theContract.getObjectsCountByOwner.call(tester)
      })
      .then((count) => {
        assert.equal(count.toNumber(), 2, 'Object count hasn\'t set properly')
      })
  })
})
```

TestTheContract.sol
```
pragma solidity ^0.4.23;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/TheContract.sol";

contract TestTheContract {
  function testCreateNewObject() public {
    TheContract theContract = TheContract(DeployedAddresses.TheContract());

    address tester = 0x24226C148f9ac4F0B46a9eeD8a426a6D9B9794c3;

    theContract.createNewObject(tester, 1);
    theContract.createNewObject(tester, 2);
    Assert.equal(theContract.getObjectsCountByOwner(tester), 2, "Object count hasn't set properly");
  }
}
```

and then

```
$ truffle test
```

## Expected Behavior

```
  TestTheContract
    ✓ testCreateNewObject (109ms)

  Contract: TheContract
    ✓ should create new objects by tester (---ms)

  2 passing (2s)
```

## Actual Results

```
  TestTheContract
    ✓ testCreateNewObject (109ms)

  Contract: TheContract
    2) should create new objects by tester
    > No events were emitted

  1 passing (2s)
  1 failing

  1) Contract: TheContract
       should create new objects by tester:

      Object count hasn't set properly
      + expected - actual

      -0
      +2

      at TheContract.deployed.then.then.then (test/theContract.js:19:16)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Environment

* Operating System: MacOSX
* Ethereum client: Ganeche
* Truffle version (`truffle version`): Truffle v4.1.13 (core: 4.1.13) Solidity v0.4.24 (solc-js)
* node version (`node --version`): v8.11.1
* npm version (`npm --version`): 6.1.0

**Comment by cgewecke** [comment] 2018-06-29 23:28
@colus001 Thank's for such a clear description and reproduction case :)

It looks like the test failure here is caused by post-fixing `.call` on methods you actually want to 'send' as transactions to the network, rewriting the state of the chain. `.call` runs the transaction locally without persisting state and is useful for retrieving data from a local client, or for testing out a transaction before broadcasting it. 

More info about this difference  [here](https://ethereum.stackexchange.com/questions/765/what-is-the-difference-between-a-transaction-and-a-call).

`truffle-contract` actually automatically figures out whether to call or send your function based on it's  ABI. So you can just write:
```javascript
theContract.createNewObject(tester, 1); // send fn
theContract.getObjectsCountByOwner(tester);  // call fn
```
and they should both work as expected.

**Comment by colus001** [comment] 2018-07-02 07:42
@cgewecke Thanks for your answer. 

```
  Contract: TheContract
{ [Function]
  call: [Function],
  sendTransaction: [Function],
  request: [Function: bound ],
  estimateGas: [Function] }
    2) should create new objects by tester
    > No events were emitted```

Should i use sendTransaction? It seems there's no `send` function. It's a bit confusing to me.

1. Does this contract requires `msg.sender` to send gas to run the function?

or

2. Does this contract requires modifier `payable`to run the function?

**Comment by colus001** [comment] 2018-07-02 14:54
I added comment but removed since I figured out somehow. But here's another question.

1)  "Why do we have two test environment. `.js` and `.sol`?" 

2) "Where can I find `Assert.sol`'s full documentation?"

Let me understand better with truffle environment, please.

**Comment by cgewecke** [comment] 2018-07-02 15:06
@colus001 Good questions

+ `.sol` allows you to test using the Solidity language itself, running on the `evm`. This useful if you are developing Solidity libraries that will be consumed by contracts and want to validate them in the context they will execute in. Solidity is a strongly typed language vs. JS so testing in that language ensures the tests lose nothing 'in translation'. The drawback is that the evm has many limitations around contract size, gas cost etc that make writing tests in Solidity quirky and difficult. Most engineers prefer js testing which is more flexible and has much better tool support. 

+  I believe `Assert.sol` is only documented within the file, as natspec comments.

**Comment by colus001** [comment] 2018-07-03 10:17
Thanks for the answer. Everything works fine finally @cgewecke except I don't know how to handle accounts in `.sol` and unlike `.js` test it seems I can't set the `{ from: owner }` while send transaction.

**Comment by cgewecke** [comment] 2018-07-03 19:20
@colus001 Yes, that's an example of how the JS interface is much more flexible. Testing solidity *with* solidity mostly makes sense for Solidity library development. In other words, for code that will only be consumed by contracts. Even then a parallel JS suite may be necessary to cover cases that are to difficult to model in Solidity itself. 

I'm going to close this because it like your original issue is more or less resolve. Thanks @colus001 :)

**Closed by cgewecke** 2018-07-03 19:20 UTC

**Comment by colus001** [comment] 2018-07-04 04:51
Thanks for great answers @cgewecke 👍
