### ISSUE TITLE
get error header not found

### ISSUE THREAD

**Issue by macchain** [trufflesuite/truffle#4479] opened 2021-12-01 08:45 UTC
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ code: -32000, message: 'header not found' })
## Environment

* Operating System:  macos
Truffle v5.4.22 (core: 5.4.22)
Solidity - 0.6.12 (solc-js)
Node v14.17.3
Web3.js v1.5.3

**Comment by fainashalts** [comment] 2021-12-01 19:33
Hi @macchain can you tell us some more about how this error comes about? We would love to help but need some reproduction steps and/or a stacktrace. Thanks so much!

**Comment by macchain** [comment] 2021-12-02 01:49
I execute `truffle migrate --network mainnet -f 2 --to 2` to deploy a contract or run a scripy 
```
gk@gkdeMacBook-Pro contract-huoying % truffle migrate --network main -f 12 --to 12

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.


Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ code: -32000, message: 'header not found' })
    at Web3ProviderEngine.emit (events.js:364:17)
    at /Users/gk/freelancer/huoying/contract-huoying/node_modules/@trufflesuite/web3-provider-engine/index.js:57:14
    at afterRequest (/Users/gk/freelancer/huoying/contract-huoying/node_modules/@trufflesuite/web3-provider-engine/index.js:151:21)
    at /Users/gk/freelancer/huoying/contract-huoying/node_modules/@trufflesuite/web3-provider-engine/index.js:176:21
    at /Users/gk/freelancer/huoying/contract-huoying/node_modules/@trufflesuite/web3-provider-engine/index.js:238:9
    at /Users/gk/freelancer/huoying/contract-huoying/node_modules/async/internal/once.js:12:16
    at replenish (/Users/gk/freelancer/huoying/contract-huoying/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/gk/freelancer/huoying/contract-huoying/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/gk/freelancer/huoying/contract-huoying/node_modules/async/eachLimit.js:43:36)
    at /Users/gk/freelancer/huoying/contract-huoying/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/gk/freelancer/huoying/contract-huoying/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at Request._callback (/Users/gk/freelancer/huoying/contract-huoying/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:70:28)
    at Request.self.callback (/Users/gk/freelancer/huoying/contract-huoying/node_modules/request/request.js:185:22)
    at Request.emit (events.js:375:28)
    at Request.<anonymous> (/Users/gk/freelancer/huoying/contract-huoying/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:375:28)
    at IncomingMessage.<anonymous> (/Users/gk/freelancer/huoying/contract-huoying/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:481:28)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
@fainashalts Thank you for your help

**Comment by andrewpros** [comment] 2021-12-04 15:36
I have the same issue only with mainnet, any solution, bsc testnet works.

**Comment by eggplantzzz** [comment] 2021-12-06 17:50
@macchain Can you share your project with us? I am particularly interested in your `truffle-config.js`.

**Comment by lachlan-nicholson** [comment] 2021-12-07 02:35
I'm having the same problem. Others have suggested increasing pollingInterval / deploymentPollingInterval, or swapping to another network and back. I've also tried updating web3/truffle/hdwallet-provider. Nothing has worked so far.

**Comment by wainguo** [comment] 2021-12-20 11:07
have the same problem on bsc mainnet：

compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'bscmainnet'
> Network id:      56
> Block gas limit: 80000000 (0x4c4b400)


1_initial_migration.js
======================
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ code: -32000, message: 'header not found' })
    at Web3ProviderEngine.emit (events.js:304:17)
    at /Users/guochengxing/topgoal/topgoal-contract/node_modules/@trufflesuite/web3-provider-engine/index.js:57:14
    at afterRequest (/Users/guochengxing/topgoal/topgoal-contract/node_modules/@trufflesuite/web3-provider-engine/index.js:151:21)
    at /Users/guochengxing/topgoal/topgoal-contract/node_modules/@trufflesuite/web3-provider-engine/index.js:176:21
    at /Users/guochengxing/topgoal/topgoal-contract/node_modules/@trufflesuite/web3-provider-engine/index.js:238:9
    at /Users/guochengxing/topgoal/topgoal-contract/node_modules/async/internal/once.js:12:16
    at replenish (/Users/guochengxing/topgoal/topgoal-contract/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/guochengxing/topgoal/topgoal-contract/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/guochengxing/topgoal/topgoal-contract/node_modules/async/eachLimit.js:43:36)
    at /Users/guochengxing/topgoal/topgoal-contract/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/guochengxing/topgoal/topgoal-contract/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at Request._callback (/Users/guochengxing/topgoal/topgoal-contract/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:70:28)
    at Request.self.callback (/Users/guochengxing/topgoal/topgoal-contract/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/Users/guochengxing/topgoal/topgoal-contract/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/Users/guochengxing/topgoal/topgoal-contract/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by haltman-at** [comment] 2022-02-09 19:50
Does anyone have detailed reproduction steps, or a reproduction project we could check out?  Thanks!

**Comment by Morinohtar** [comment] 2022-02-22 11:53
Same problem of #4498 

Any news about fixing this issue?

**Comment by haltman-at** [comment] 2022-02-22 17:51
We're going to need reproduction steps if we're going to get anywhere on this issue.

(Meanwhile this should possibly be closed as duplicate?)

**Comment by eggplantzzz** [comment] 2022-03-22 15:20
Closing for issue maintenance due to lack of repro steps and it possibly being a duplicate issue.

**Closed by eggplantzzz** 2022-03-22 15:20 UTC
