### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:175527:50

### ISSUE THREAD

**Issue by JackPickering** [trufflesuite/truffle#849] opened 2018-03-15 16:21 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Whenever I try to deploy a set of migrations with a pre-existing build folder, I get the error:
```
TypeError: Cannot read property 'call' of undefined
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:175527:50
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
This prevents me from deploying my contracts to a test chain whilst hosting them on my local machine. 

The error is called from this function:
```
`  lastCompletedMigration: function(options, callback) {
    var Migrations;

    try {
      Migrations = options.resolver.require("Migrations");
    } catch (e) {
      return callback(new Error("Could not find built Migrations contract: " + e.message));
    }

    if (Migrations.isDeployed() == false) {
      return callback(null, 0);
    }

    var migrations = Migrations.deployed();

    Migrations.deployed().then(function(migrations) {
      return migrations.last_completed_migration.call();
    }).then(function(completed_migration) {
      callback(null, completed_migration.toNumber());
    }).catch(callback);
  },`
```

At this specific line:
` return migrations.last_completed_migration.call();`

Interesting that the contract has a function lastCompletedMigration, but uses last_completed_migration in the bundled.js file and is not found?

Trying:
1. Deleting the build folder
2. `truffle migrate --reset`

Are unacceptable fixes for this issue, I need to deploy a large set of contracts which should link together, this requires me to run various migrations after each other in order to keep under the block gas limit. Therefore, I NEED THE BUILD FOLDER and the migrated contracts when migrating.

## Steps to Reproduce

Set up a truffle project
Migrate your contracts to a network
Attempt to migrate with an existing build folder

## Expected Behavior

The contracts are either overwritten (if same chain) or simply added to the other chain (if different)

## Actual Results

```
TypeError: Cannot read property 'call' of undefined
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:175527:50
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

## Environment

* Operating System: macOS High Sierra 10.13.3
* Ethereum client: Geth
* Truffle version (`truffle version`): v4.0.1
* node version (`node --version`): v8.9.0
* npm version (`npm --version`): v5.6.0

**Comment by cgewecke** [comment] 2018-03-22 04:24
@JackPickering I'm going to close this as a duplicate of your other report [here](https://github.com/trufflesuite/truffle/issues/326#issuecomment-374979284). Happy to continue in that thread. Thanks!

**Closed by cgewecke** 2018-03-22 04:24 UTC
