### ISSUE TITLE
Original Stack Trace is Not Defined (promievent.js)

### ISSUE THREAD

**Issue by karthedew** [trufflesuite/truffle#3186] opened 2020-07-20 17:58 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Original Trace Stack error when trying to call the getBalanceInEth() contract function.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

### Step 1
Create a simple Angular project.

### Step 2
Require "web3", MetaCoin.json compiled ABI, and @truffle/contract.

Set provider to http://127.0.0.1:7545 (working in Windows 10)

```

declare let require: any;
declare let window: any;
const Web3 = require('web3');
const tokenABI = require('../../../../../../Blockchain/build/contracts/MetaCoin.json');
const contract = require('@truffle/contract');
const provider = new Web3.providers.HttpProvider("http://127.0.0.1:7545");

```

### Step 3
Create a "getEtherBalance()" function that returns the ether balance an account by creating an instance of the Token Contract with the ABI and provider.

```
getEtherBalance(account: string) {    

    return new Promise( function ethBalance (resolve, reject) {
      let deployed;

      const MetaContract = contract(tokenABI);

      MetaContract.setProvider(provider);

      MetaContract.deployed().then(function resolver(instance) {
        deployed = instance;
        return instance.getBalanceInEth.call(account)                          // BREAKS HERE
      }).then((result) => {
        console.log(result)
        return resolve(result)
      }).catch(err => {
        reject(err);
      })
    })
  }

```

## Expected Behavior

Expected to get the Ethereum balance of the current MetaMask account. (Imported the Ganache seed phrase and connected to the Ganache network.)

## Actual Results
![ErrorMessage](https://user-images.githubusercontent.com/35015336/87969750-9486c280-ca77-11ea-9341-f34f8a796bbf.PNG)

When I launch the Frontend which makes the call to the getEtherBalance() function, returns a "ReferenceError: originalStackTrace is not defined."

## Environment

* Operating System: Windows 10
* Ethereum client: Ganache
* Truffle version: v5.1.34 
* node version: v10.13.0
* npm version :  6.14.5
* Web3.js version: V1.2.1

## Full Contract Service Code
```

import { Injectable } from '@angular/core';

declare let require: any;
declare let window: any;
const Web3 = require('web3');
const tokenABI = require('../../../../../../Blockchain/build/contracts/MetaCoin.json');
const contract = require('@truffle/contract');

const provider = new Web3.providers.HttpProvider("http://127.0.0.1:7545");


@Injectable({
  providedIn: 'root'
})
export class Web3serviceService {

  // === LOCAL VARIABLES ===
  private web3Provider: any;
  accounts: any;
  web3: any;
  // MetaContract: any;

  constructor() {

    if (typeof window.web3 === 'undefined' || (typeof window.ethereum !== 'undefined')) {
      console.log('MetaMask is installed!!')
      // this.web3Provider = window.ethereum || window.web3;
      this.web3Provider = new Web3(new Web3.providers.HttpProvider('http://127.0.0.1:7545'));
      window.web3 = new Web3(this.web3Provider);
      console.log('=====================================')
      console.log(this.web3Provider)
    } else {
      this.web3Provider = new Web3(new Web3.providers.HttpProvider('http://127.0.0.1:7545'));
      // if you are using linux or ganche cli maybe the port is  http://localhost:8545
      //   Web3.providers.HttpProvider.prototype.sendAsync = Web3.providers.HttpProvider.prototype.send;
      //   this.web3Provider = new Web3(new Web3.providers.HttpProvider('https://rinkeby.infura.io/v3/Private_key'));
      // Change with your credentials as the test network and private key in infura.io
    }

    this.web3 = this.web3Provider;

  }

  async getAccounts() {
    return new Promise((resolve, reject) => {
      // this.web3.request({ method: 'eth_requestAccounts' }).then((acc) => {
      this.web3Provider.eth.getAccounts().then((acc) => {
        return resolve(acc)
      }).catch((err) => {
        return reject(err)
      })
    });
  }

  getEtherBalance(account: string) {    

    return new Promise( function ethBalance (resolve, reject) {
      let deployed;

      const MetaContract = contract(tokenABI);

      MetaContract.setProvider(provider);

      MetaContract.deployed().then(function resolver(instance) {
        deployed = instance;
        return instance.getBalanceInEth.call(account)
      }).then((result) => {
        console.log(result)
        return resolve(result)
      }).catch(err => {
        reject(err);
      })
    })
  }

}

```

**Comment by gnidan** [comment] 2020-07-20 22:23
This line strikes me as problematic:

```javascript
        return instance.getBalanceInEth.call(account)                          // BREAKS HERE
```

Trouble is: `instance.getBalanceInEth` is a function, so when you do `instance.getBalanceInEth.call`, you're invoking [Function.prototype.call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call). The error you're seeing is because `account` is passed as the first argument, thus binding `this` to `account` instead `instance.getBalanceInEth`.

Try doing `instance.getBalanceInEth(account)` instead.

**Comment by haltman-at** [comment] 2020-07-21 00:12
@gnidan That's not what should happen?  If `getBalanceInEth` is a method of the contract instance, then `instance.getBalanceInEth.call(account)` should do it as a call; Truffle Contract provides that.  Of course, if `getBalanceInEth` is a `view` or `pure` function, then it will call by default, but Truffle Contract provides `call` for all contract methods; `Function.prototype.call` should not get invoked.

**Comment by haltman-at** [comment] 2020-07-21 00:14
@karthedew Could you clarify what the Solidity code you were using is?  You make it sound like you were using a box; could you clarify which one?

**Comment by haltman-at** [comment] 2020-07-21 00:25
OK, I think I've identified the problem, and have put up a PR to fix it.  We'll see if this does indeed resolve it.

**Comment by karthedew** [comment] 2020-07-21 00:49
@gnidan Thanks for your response. I did try it both ways with the same result.

@hltman-at Thank you for looking into this! Just to answer your question, I has using "truffle unbox metacoin" (GitHub repo here: https://github.com/truffle-box/metacoin-box). I'm compiling with Solidity 0.5.16+commit.9c3226ce.Emscripten.clan.

I created an open GitHub repository with my code for reference (https://github.com/karthedew/AngularTruffleExample).

Also, I apologize if pasting directly is not appropriate. This is my first GitHub Issue Submission.

**Comment by karthedew** [comment] 2020-07-21 14:55
@haltman-at , I implemented your changes directly in my local @truffle/contract package. Changes fixed the current issue.

Unfortunately this has exposed another challenge...

![image](https://user-images.githubusercontent.com/35015336/88068798-8a230200-cb25-11ea-8ab7-92952a1f5f04.png)


It appears as though the txHash is not getting set when you use the call() method ( in this case, [ ``` return instance.getBalanceInEth.call() ```]). 

The transaction hash looks like it should be set in "Execute.js" on line 544. The method above does not actually make it to this part of the code, so ```this.txHash``` never gets set in the promievent object.

![image](https://user-images.githubusercontent.com/35015336/88069101-e554f480-cb25-11ea-8f73-aec34490a2ff.png)


I plan to investigate further, but I am not sure if this should be written up in a new Issue? 

Hopefully there is an easy solution to this.

**Comment by haltman-at** [comment] 2020-07-21 18:19
Indeed, `txHash` will not be set if you used call.  But that does not seem to be the problem here, nor do I see any reason it would cause a problem.  Rather, from your error message, it seems to be complaining that `this` is undefined!

I'm not sure what to do about that.  That said, since you seem to be willing to twiddle the code yourself, here's something you could try (and if this works then we can merge it).  On line 74, does anything change if you replace
```
  this.reject = rejectHijacker;
```
with
```
  this.reject = rejectHijacker.bind(this);
```

That's the best thing I can think of at the moment.  But I'll try a more detailed reproduction myself later and try to see what's going on.

Thanks for the report!

**Comment by karthedew** [comment] 2020-07-22 14:24
It looks like that was the issue. binding ```this``` to ```rejectHijacker;``` worked. 

Just got a chain of problems here though. 

I don't think this is necessarily a problem with the code? It could be how I have Ganache setup? Though I am able to pull the Ganache accounts with MetaMask and web3.

I feel like ```rpcReturn``` should be known when the Ganache provider (localhost:7545 on my machine) is set to the ContractABI?

![image](https://user-images.githubusercontent.com/35015336/88123143-1e6d8300-cb7f-11ea-8cc6-e0a9bcd95e6e.png)

Anyways, maybe this issue can be closed as the fixes seem to have fixed my original problem....

**Comment by karthedew** [comment] 2020-07-22 14:45
I think I solved this problem with how I inject and interact with my web3. Thanks!

**Comment by haltman-at** [comment] 2020-07-22 22:52
OK, thanks for checking that!  I've put up a PR to fix the second problem.

But that does leave us with the third one.  That one I'm confused about; `rpcReturn` shouldn't be undefined.  I'm going to have to try reproducing your problem myself and see what might be causing that.

(To be clear -- what these problems all have in common is that they're all problems in our code used for producing stacktraces in Truffle Test.  Just to be clear, that is the context this is all occurring in, right?  You're not getting these problems outside of Truffle Test, and not if you don't explicitly ask for stacktraces, right?  If you're getting these problems outside of Truffle Test, or even when you don't ask for stacktraces, then something is very wrong...)

I am confused about this statement, though:

>  the Ganache provider (localhost:7545 on my machine) is set to the ContractABI

Could you explain what you mean by that?  I'm afraid I don't understand.

Anyway I'll try reproducing this and see if I can get that third problem to pop up.  Thanks for the report!

**Comment by karthedew** [comment] 2020-07-24 05:20
After I inject my Angular project with web3 (ex, ```this.web3 = new Web3.providers.HttpProvider('http://localhost:7545');```), I call a function that tries to interact with my Truffle Smart Contract. Sorry my statement was a bit confusing. I guess I assumed that ```rpcReturn``` was part of the communication between the @truffle/contract package and Ganache?

I'm not sure what "getting stacktraces" is (apologies, not familiar with this). Where I'm seeing issues, is within this specific function:

```
async getEtherBalance(account: string) {    
    
    const that = this;

    return new Promise( function ethBalance (resolve, reject) {

      const contract = require('@truffle/contract');
      const MetaContract = contract(tokenABI);

      let deployed;

      MetaContract.setProvider(that.web3);

      MetaContract.deployed().then(function resolver(instance) {
        deployed = instance;
        return instance.getBalanceInEth.call(account)
      }).then((result) => {
        console.log(result)
        return resolve(result)
      }).catch(err => {
        reject(err);
      });
    });
  }
```

To answer your question about my previous statement. After injecting my application with the Ganache server, I use truffles "contract()" method with the contract ABI (or contract JSON file) that gets built with ```truffle migrate```. Once that "ContractABI" is set, I give it the provider. 

My code breaks when I call the line ```return instance.getBalanceInEth.call(account)```. I was thinking / assuming that this line wasn't the real issue and instead may be happening when I set the provider (```MetaContract.setProvider(that.web3);```).

**Comment by eggplantzzz** [comment] 2020-07-24 21:52
I think this issue may be resolved in Truffle 5.1.36. If you upgrade, does your problem persist?

**Comment by haltman-at** [comment] 2020-07-25 01:52
Well, the initial two issues should be fixed in 5.1.36; I didn't yet get to this third issue being discussed.

**Comment by haltman-at** [comment] 2020-07-25 02:01
@karthedew I see, weird!  So, to explain a bit more -- I wrote some functionality that allows contracts to generate stacktraces for reverted transactions when the contract's methods are invoked from Truffle Test.  The line about `rpcReturn` is part of that functionality.  I'm confused as to why it's being hit here, as from what you're saying, this is not occurring inside Truffle Test.

So, yeah, going to have to sit down and try to reproduce this.  Not very familiar with front-end stuff but I'll see first if I can reproduce it outside of that context; otherwise I guess I'll have to try to figure out how Angular works...

**Comment by karthedew** [comment] 2020-07-27 19:30
Thanks for your help @haltman-at! Didn't get a chance to look further into it last weekend. Will have some time this week though.

**Comment by haltman-at** [comment] 2020-07-28 05:48
OK, just tried to reproduce this without Angular and was not able to hit the problem you described.  Here's what I did:

1. Made a new directory and ran `truffle unbox metacoin`, as well as `npm add @truffle/contract`
2. Set up a Ganache instance on port 7545, uncommented the `development` network in `truffle-config.js`, and ran `truffle complile` and `truffle migrate`
3. Created a new file, `index.js`, which the following contents, based on what you described above:
```
const Web3 = require('web3');
const tokenABI = require('./build/contracts/MetaCoin.json');
const contract = require('@truffle/contract');
const provider = new Web3.providers.HttpProvider("http://127.0.0.1:7545");

function getEtherBalance(account) {    

    return new Promise( function ethBalance (resolve, reject) {
      let deployed;

      const MetaContract = contract(tokenABI);

      MetaContract.setProvider(provider);

      MetaContract.deployed().then(function resolver(instance) {
        deployed = instance;
        return instance.getBalanceInEth.call(account)                          // BREAKS HERE
      }).then((result) => {
        console.log(result)
        return resolve(result)
      }).catch(err => {
        reject(err);
      })
    })
}

const web3 = new Web3(provider);
web3.eth.getAccounts().then(accounts => getEtherBalance(accounts[0]));
```
4. Ran `node index.js`.

I did not encounter the undefined `rpcReturn` problem, but rather got the following printout:
```
<BN: 4e20>
(node:29945) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

And of course `0x4e20` is equal to 20000, the correct amount.

So, hm, could it be that the problem only occurs in browser, or even only in Angular?  Never used Angular before, but I guess I'll have to try that out...

(Also @karthedew let me know if I've misunderstood the setup here.  Of course, I tested using node rather than browser + Angular, but like I said that's because I wanted to first do a quick test in an environment I'm more familiar with; will have to try Angular later.)

**Comment by haltman-at** [comment] 2020-07-28 06:14
Alternatively, @karthedew, could you provide more detailed instructions regarding the setup here?  As someone who doesn't know Angular, it's a bit underspecified.  (Alternatively, do you have a reproduction repo I could just check out?)

Like, create an Angular project, OK; unbox Metacoin, compile and deploy, OK; but I don't understand where to put the rest of the code that you list (what file does it go in?) in order to make it part of the Angular project, nor how to then invoke it.  Could you fill in the gaps?  Thank you!

**Comment by karthedew** [comment] 2020-07-28 16:34
@haltman-at Great! Thanks for checking that. 

The link to a simplified model of this Angular project is here:
> 
> I created an open GitHub repository with my code for reference (https://github.com/karthedew/AngularTruffleExample).
> 

I'll need to update the package.json file to use the latest version of ```@truffle/contract``` that has the previous 2 error fixes.

### Angular Folder Structure
Essentially what you need to know is that all of your Typescript, HTML, and CSS files go into ```/src/app```.

```app.component.ts``` is your main Typscript file.
```app.component.html``` is your main HTML file.
```app.component.css``` is your main CSS file. 

I would recommend that you do all of your checking in these files.

### About Component Files

Everything in Angular is based on components (usually files are named like ```<filename>.component.ts```). If you start with a basic exported typescript class, to make it an Angular component, you utilize the ```@Component``` decorator:

 1] "selector" - this is how you can call the component in an HTML tag. In this case your HTML tag would be<app-root>.
 2] "templteUrl" - your reference location to the component HTML file.
 3] "styleUrls" - your reference to the CSS file.

Alternatively, Angular automatically creates components in the command line with "ng generate component <component name>", so you really never manually create a component class.

```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent { ... }```
```

### Services
In the project I linked above, I created a service component that should hold all the methods that will interact with the Truffle Smart Contract. In Angular, service components are decorated with ```@Injectable```. 

When you want to use your Angular service, you must "inject" it into your component (as aforementioned) class. This looks like:

```
import { Component } from '@angular/core';
// STEP 1: Import your Angular Service
import { Web3serviceService } from "./services/web3/web3service.service";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  
  // STEP 2: "Inject" your service in the constructor.
  constructor(private web3Service: Web3serviceService) {

    // STEP 3: Now your service class is instantiated and you can call its methods
    let value = web3Service.getEtherBalance(this.account);

  }
```

## Start the Angular Project

In the root directory, just use ```npm start``` to run the project. Will be at ```http://localhost:4200```

**Comment by karthedew** [comment] 2020-07-28 16:44
After your verification that the Truffle contract code is working correctly with no rpcRetrun issues, I'm wondering of there is a communication restriction between Angular and Ganache server through RPC requests. 

I thought maybe it was related to setting up CORS when you are running both a Frontend server and Backend server on the same machine, but in different ports. Usually this is setup on the backend side of things. Alternatively, you can also setup a Proxy configuration file (see, [article]( https://www.positronx.io/handle-cors-in-angular-with-proxy-configuration/#:~:text=Enable%20CORS%20with%20Proxy%20Configuration%20Settings%20in%20Angular.&text=To%20enable%20CORS%20via%20proxy,the%20deliberate%20use%20of%20SSL.)).

I tried this out, but unfortunately with no progress. 

Did a little more research and then came across [this issue](https://github.com/trufflesuite/ganache/issues/359). So it seems that RPC capabilities were already added to Ganache.

**Comment by haltman-at** [comment] 2020-07-31 22:53
@karthedew Thanks!  I missed where you posted that repo originally.  Unfortunately I can't seem to get it working?  I downloaded it like you suggested, went into `Frontend/web3front`, upgraded the `@truffle/contract` version and ran `npm install`; and then tried just running `npm start` like you suggested.  However, when I pointed my browser to `http://localhost:4200/`, what I got was an error page (titled `Error`) with just the message `Cannot GET /`.

Looking at the terminal window where I ran `npm start`, I see a lot of "Can't resolve module" errors, which is strange, because I ran `npm install`.  Following that, I see a large number of `ENOENT` errors coming from something trying to find certain directories in my home directory -- namely, `~/external`, `~/externhome`, `~/externwinhome`, `~/tbhome`/, and `~/winhome`.  Of course I don't have any of these directories.

So, something seems to be missing here.  Are there additional steps I should take here to get this project running?  Thank you!

(As for the rest... again, to my mind, the real question is why the function where this error occurs is being called at all.  If it's not in the context of `truffle test`, that function shouldn't even be called...)

**Comment by haltman-at** [comment] 2020-07-31 23:10
Also tried this again after actually installing the peer dependencies this time (sort of).  (I say sort of because there was actually no way for me to satisfy all the peer dependencies?  Because some things required `@angular/compiler` v9, and some things required `@angular/compiler` v10; I ended up going with v10 as only `@angular/compiler-cli` required that, whereas various things required v9?)

This led to the same result in the browser, but a rather different error in the terminal:

```
ERROR in TypeError: Cannot read property 'start' of undefined
    at Object.addParseSpanInfo (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/diagnostics.js:56:32)
    at AstTranslator.visitPropertyRead (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:203:27)
    at PropertyRead.visit (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler/bundles/compiler.umd.js:7462:28)
    at AstTranslator.translate (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:74:24)
    at /home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:118:124
    at Array.reduce (<anonymous>)
    at AstTranslator.visitInterpolation (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:118:36)
    at Interpolation.visit (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler/bundles/compiler.umd.js:7590:28)
    at AstTranslator.translate (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:74:24)
    at Object.astToTypescript (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:51:27)
    at TcbExpressionTranslator.translate (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1213:33)
    at tcbExpression (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1201:27)
    at TcbTextInterpolationOp.execute (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:317:24)
    at Scope.executeOp (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:976:26)
    at Scope.render (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:889:22)
    at Object.generateTypeCheckBlock (/home/sniffnoy/truffle/AngularTruffleExample/Frontend/web3front/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:57:37)
```

So, uh, I still haven't managed to get this working well enough to replicate the issue.

**Comment by haltman-at** [comment] 2020-08-03 20:08
Hm, no, that gets me back to the same problem I had before, more or less.  So, uh, @karthedew, I can't figure out how to get this project working?

**Comment by karthedew** [comment] 2020-08-04 03:32
@haltman-at hmm, that's interesting. I removed all global packages in npm so I'd have a clean slate. Pulled down the project from GitHub and did "npm install" then ran "npm start". This worked for me, so I'm not sure what's going on here. 

I did see that I had the ```pacakge-lock.json``` file still in the repo. Maybe try deleting that file and the ```node_modules``` and try the ```npm install``` again. 

One thing to note is that Angular does not mix versions. So whatever packages you have for Angular need to all be the exact same versions. I'm not sure why you were seeing dependencies for version 10? The ```package.json``` file was all v9.0.7.

I'm wondering if trying a different version of Angular would fix this problem. I'll try that and see what happens.

**Comment by karthedew** [comment] 2020-08-04 15:38
@haltman-at Just thought you could also try running ```ng update --all``` to get the latest version of all packages. This might also help fix the issue.

**Comment by haltman-at** [comment] 2020-08-04 22:49
Aha, indeed, `ng update --all` seems to have finally gotten it working, thanks! :)  Now let's see about reproducing this error...

**Comment by haltman-at** [comment] 2020-08-04 23:31
Hm, so I'm running into a different problem trying to test this: As best I can tell, my browser is blocking all the requests made to the Ganache instance due to them not passing same-origin policy / CORS.  So basically nothing's working.  Will have to see if I can find a way around this.

**Comment by haltman-at** [comment] 2020-08-05 00:26
OK, finally got the OK, finally go tup and running with Angular, and I'm afraid I still can't reproduce this problem.  I'm getting the account balance just fine.

**Comment by karthedew** [comment] 2020-08-05 00:59
So I ended up running the same ```ng update --all```, and this did the trick. There must've been some Angular packages that weren't coordinating together, is my bet? Angular requires everything to be the same version, though it's sometimes easy to install different versions between different Angular packages. 

Thanks so much for all your help! I think we can close this issue.

**Comment by haltman-at** [comment] 2020-08-05 18:10
Hm, weird.  No idea.  Guess I'll close this!  Thanks for all the help with reproducing this.

**Closed by haltman-at** 2020-08-05 18:10 UTC
