### ISSUE TITLE
Contract transaction not found after 50 blocks on Kovan

### ISSUE THREAD

**Issue by quantumproducer** [trufflesuite/truffle#818] opened 2018-02-25 18:32 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

I checked the block explorer and my local parity, mine was synced. Just a few minutes before I was making deployments. Then I tried again and got this:

Contract transaction not found after 50 blocks on Kovan network.

```
[truffle migrate --network=kovan
Using network 'kovan'.

Running migration: 2_deploy_contracts.js
  Deploying Story...
  ... 0xd88cc3655cae77efbabc804733051d62424e1338a315b7dfbf52690aa4fe76e0
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract transaction couldn't be found after 50 blocks
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:327560:30
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:64332:21
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:64331:32
    at Array.forEach (<anonymous>)
    at Object.onMessage [as callback] (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:64329:22)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:329703:20
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:329702:12
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:176186:11](url)
```

**Comment by cgewecke** [comment] 2018-02-25 19:18
@quantumproducer Could you see if this issue is a duplicate of #677? There's some discussion of workarounds in that thread [here](https://github.com/trufflesuite/truffle/issues/677#issuecomment-361679479).

**Closed** 2018-02-25 19:21 UTC
