### ISSUE TITLE
 Having access to a real account in the MainNet with a pregenerated account

### ISSUE THREAD

**Issue by atelomycterus** [trufflesuite/truffle#686] opened 2017-11-17 16:11 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm able to have access to a real account in the MainNet with a pregenerated account (0x627306090abab3a6e1400e9345bc60c78a8bef57). 

## Steps to Reproduce
Video: https://youtu.be/7JV6DsFz_5A

The short description: Run "truffle develop". 10 accounts are generated  with the menemonic phrase 
"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat".
Open MetaMask and enter mnemonic phrase to have access to an account.

## Expected Behavior

No access to real account in the MainNet.

## Actual Results

I have access to a real account in the Main Net using a pregenerated account with the mnemonic.

## Environment
* Operating System: MacOs 
* Truffle version: 4.01
* Ethereum client: Metamask 3.12
* node version: 8.9.1
* npm version: 5.5.1

**Comment by tcoulter** [comment] 2017-11-28 18:07
Hi there,

Thanks for the ticket. Accounts are no unique across blockchains. In fact, as long as you have the private key to an account, you can use that account on any Ethereum-based blockchain (Mainnet, Classic, Ropsten, Rinkeby) so long as someone sends you Ether to that account on that chain. When you have a mnemonic, you essentially hold information to derive the private key; so you can use that mnemonic on any chain. 

As you can see, people have (likely accidentally) used the Truffle mnemonic on the main chain: https://etherscan.io/address/0x627306090abaB3A6e1400e9345bC60c78a8BEf57

I'm going to close this as it's not a bug, but a property of private/public key encryption. Cheers!

**Closed by tcoulter** 2017-11-28 18:07 UTC

**Comment by deviant32** [comment] 2018-01-02 15:56
I have the private key for that exact same account.  I just sent 1 eth to the account and it automatically sent .2 to another wallet with a .78 transaction fee!

**Comment by nocow4bob** [comment] 2018-02-16 01:56
I just experienced this exact same thing.

**Comment by benjamincburns** [comment] 2018-02-27 05:37
@deviant32, @nocow4bob, and if @atelomycterus also lost funds to this problem, you as well...

By any chance would each of you be willing to sit down and chat with me about how you lost your ETH? I want to make sure that we understand in depth what happened. There are certainly some obvious things we can be doing to improve, and we're working on those now, but I want to make sure that we're not missing the forest for the trees.

If you're willing, you can quickly/easily self-schedule a time to meet on [my calendly page](https://calendly.com/ben-burns/feedback-session). It'll block off 60 minutes from my calendar, but we can keep it brief if you have less time than that. Thanks in advance!
