### ISSUE TITLE
Failure when passing an array to a function from the truffle console

### ISSUE THREAD

**Issue by ESRogs** [trufflesuite/truffle#526] opened 2017-08-04 01:25 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Passing an array to a function from the truffle console (or using truffle exec) results in `Error: Invalid number of arguments to Solidity function`

## Steps to Reproduce

C.sol
```
pragma solidity ^0.4.4;
contract C {
    function foo(uint[] bar) {
    }
}
```
2_deploy_contracts.js
```
var C = artifacts.require("./C.sol");
module.exports = function(deployer) {
    deployer.deploy(C);
};
```
at the truffle console:
```
var c
C.deployed().then((_c) => {c=_c;})
c.foo([0]) // Error: Invalid number of arguments to Solidity function
c.foo(web3.eth.accounts.constructor([0])) // fine
```

## Expected Behavior

`c.foo([0]) // no error`

## Actual Results

`c.foo([0]) // Error: Invalid number of arguments to Solidity function`

## Environment

* Operating System: macOS Sierra 10.12.6
* Truffle version: 3.4.6 (also repro's on 3.4.7)
* Ethereum client: TestRPC v4.0.1
* node version: 6.10.2
* npm version: 3.10.10

**Comment by ESRogs** [comment] 2017-08-04 01:26
See my additional comments here: https://gitter.im/ConsenSys/truffle?at=5983c7ca210ac2692050c372

**Comment by skmgoldin** [comment] 2017-08-07 01:49
I can reproduce this. I think it was introduced in 3.4.7.

```
git clone git@github.com:skmgoldin/simple-token-launch.git
nohup testrpc -a 100 > /dev/null &
truffle test
```
The migration will fail with the `Invalid number of arguments to Solidity function` [here](https://github.com/skmgoldin/simple-token-launch/blob/master/migrations/2_deploy_adtoken.js#L65-L68) (those are arrays).

**Comment by skmgoldin** [comment] 2017-08-15 22:39
Still not fixed in 3.4.8

**Comment by tcoulter** [comment] 2017-08-15 23:14
This is a [web3](https://github.com/ethereum/web3.js) issue. We should take this up with the web3. 

Specifically, this is *not* the right way to test for an Array, especially in the browser:

```
if (item instanceof Array) { ... }
```

As @ESRogs mentioned, this (bad) method of testing for arrays occurs in web3's code [here](https://github.com/ethereum/web3.js/blob/develop/lib/utils/utils.js#L547). 

The right way, instead, is below: 

```
if (Array.isArray(item)) { ... }
```

See the [Mozilla developer docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray), and the `instanceof vs isArray` heading. `Array.isArray()` is the preferred method in Node as well.

**Comment by tcoulter** [comment] 2017-08-15 23:16
In case you're worried about `isArray` in browser usages: http://caniuse.com/#search=isArray

**Comment by tcoulter** [comment] 2017-08-15 23:16
I'm going to close this issue here. I don't think this is something we can fix from Truffle's end.

**Closed by tcoulter** 2017-08-15 23:16 UTC

**Comment by skmgoldin** [comment] 2017-08-15 23:32
Thanks Tim. It's been so long since I've used web3 directly I thought it was just called Truffle now.

**Comment by makoto** [comment] 2017-08-22 20:25
Any idea why this started as a problem? The PR on web3.js is referring to the code which hasn't been changed for almost 3 years. Started having the same problem when I upgrade truffle v3.4.7. Interestingly the problem only happens when I am in `truffle console` or `truffle exec`, does not occur in the `truffle test` context.

**Comment by ESRogs** [comment] 2017-08-29 00:48
> The PR on web3.js is referring to the code which hasn't been changed for almost 3 years.

@makoto The utils.isArray function may have been written years ago, but it started being called as part of parameter validation just two months ago. See: https://github.com/ethereum/web3.js/blame/530c4a3b1d7bc787c90e9b0e35fd3c9ae560d76e/lib/web3/function.js#L69
