### ISSUE TITLE
`truffle networks` produces errors

### ISSUE THREAD

**Issue by stoplion** [trufflesuite/truffle#3863] opened 2021-02-22 04:58 UTC
- [ x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

[![Image from Gyazo](https://i.gyazo.com/e161ce2b74a107473960bb77d275f578.gif)](https://gyazo.com/e161ce2b74a107473960bb77d275f578)

`$ truffle networks` produces error:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.display (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/networks.js:58:41)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/networks.js:31:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
Truffle v5.1.67 (core: 5.1.67)
```

## Steps to Reproduce

`$ truffle networks`

## Expected Behavior
Shows deployed addresses

## Actual Results
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.display (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/networks.js:58:41)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/networks.js:31:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
Truffle v5.1.67 (core: 5.1.67)
```

## Environment

* Operating System:  OS X 10.15.7
* Ethereum client: 
* Truffle version: v5.1.67
* node version: v15.4.0
* npm version: 7.5.0

**Comment by eshaben** [comment] 2021-03-03 19:22
Thanks for filing the issue @stoplion. We were unable to reproduce the issue. Do you have the repository we could use to reproduce this issue with?

**Comment by davidmurdoch** [comment] 2021-04-28 18:44
Closing for issue maintenance. If you still need to resolve this issue let us know and we can reopen this issue. Thanks!

**Closed by davidmurdoch** 2021-04-28 18:44 UTC
