### ISSUE TITLE
Client connection failure/timeout after initially being successful while running tests

### ISSUE THREAD

**Issue by rynobey** [trufflesuite/truffle#3471] opened 2020-10-26 10:12 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

After some tests pass successfully, the rest start failing with connection timeouts/failures.

## Steps to Reproduce

Really hard to reproduce, but seems to happen after the tests have been running for some time, and especially when trying to deploy some rather big contracts (consuming ~50 million gas).

## Expected Behavior

Tests should pass (no connection timeout).

## Actual Results

After the first couple of tests pass successfully, the rest start failing with either
```
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 8555
    - network_id > *
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
```
or
```
Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

After looking at the output on ganache-cli, it looks like it is being bombarded by thousands of `eth_getBlockByNumber` calls after sending a transaction, especially if the transaction consumes a lot of gas. I'm not sure, but this could possibly be related to https://github.com/trufflesuite/truffle/issues/3464 and/or https://github.com/trufflesuite/truffle/issues/3468.

Note: Downgrading to truffle 5.1.49 seems to resolve the problem.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): 5.1.50
* node version (`node --version`): 10.16.3
* npm version (`npm --version`): 6.10.2

**Comment by gnidan** [comment] 2020-10-28 17:57
Hm, well #3464 just got fixed and will get released tomorrow, so if that's the cause, then you should be good.

But I suspect it's not so easy. We'll have to look into this.

Thanks for reporting!

**Comment by gnidan** [comment] 2020-10-28 17:59
Oh by the way - it'd be super helpful if you could provide a repo for reproduction steps!

**Comment by rynobey** [comment] 2020-10-30 07:03
Thanks @gnidan ! I will give the new release a try and report back. Unfortunately, I cannot provide the code I used to produce this problem, but if it is still happening on the latest release, I will look at making a dedicated example in a public repo for reproducing it.

**Comment by rynobey** [comment] 2020-11-03 16:40
@gnidan Sadly, after trying truffle 5.1.51 the problem persists. I have created this repo that reproduces the problem for me locally: https://github.com/rynobey/test-failure-example - please let me know if it does not successfully reproduce.

**Comment by gnidan** [comment] 2020-11-04 18:57
Thanks for the reproduction repo @rynobey! We'll look into this and hopefully get you a resolution soon.

**Comment by Kerfred** [comment] 2020-11-06 09:59
Same problem (the first error message).
It works well with Truffle 5.1.49, but not with Truffle versions 5.1.50,.5.1.51 and 5.1.52.

For information, I use Ganache CLI v6.12.1 (ganache-core: 2.13.1)

The problem happens when I run a full: truffle test
But it doesn't happen if I test only the file where the error occurs.
Hope this will help.

**Comment by idmontie** [comment] 2021-11-09 20:20
I'm seeing a similar issue, but only on Windows. We have around 100 tests that all pass successfully using two different reporters (the default and eth-gas-reporter). The run and pass fine on Mac OS X (10.15.7) and on Ubuntu 20.04.3, but they will randomly fail near test 90+ on Windows 10.

Running the tests individually, they pass. Running the full test suite, we see 1 to 5 different tests randomly fail. This failure happens all the time when using the default test reporter, and we rarely see it with eth-gas-reporter.

We have `ganache-cli` running and it continues to run without errors when these tests fail.

**Comment by rynobey** [comment] 2022-01-11 10:20
@gnidan is there any update regarding this issue? I have tried again using truffle@5.4.28 (with solidity-coverage@0.7.11, which uses ganache-cli@6.12.1 and ganache-core@2.13.1) but still run into the same problem (using the example here https://github.com/rynobey/test-failure-example), now with a new error
```
  1) Contract: TestContract
       This test is exactly the same as the first test. It fails with truffle ^5.1.50 but passes on v5.1.49:
     Uncaught TypeError: Cannot read property 'pop' of undefined
      at CheckpointTrie._updateNode (node_modules/truffle/build/735.bundled.js:100592:28)
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/735.bundled.js:100312:21
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/735.bundled.js:100702:18
      at processNode (node_modules/truffle/build/735.bundled.js:100713:18)
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/735.bundled.js:100697:9
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/735.bundled.js:100394:11
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/735.bundled.js:116232:7
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/735.bundled.js:101754:16
      at replenish (node_modules/truffle/build/735.bundled.js:102287:25)
      at iterateeCallback (node_modules/truffle/build/735.bundled.js:102276:17)
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/735.bundled.js:102250:16
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/735.bundled.js:116228:7
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/735.bundled.js:100369:13
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/735.bundled.js:3081:16
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/263.bundled.js:2519:15
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/263.bundled.js:2146:19
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/276.bundled.js:11246:21
      at /home/ryno/projects/rynobey/test-failure-example/node_modules/truffle/build/276.bundled.js:7716:21
```

**Comment by eggplantzzz** [comment] 2023-02-16 19:18
Hey @rynobey, does this still occur using the latest version of `ganache`(7.7.5)? Do note that the package name changed from `ganache-cli` to `ganache`.

**Comment by rynobey** [comment] 2023-02-17 09:08
Hi @eggplantzzz ! I haven't checked this recently since we switched to hardhat a while back. I'm not sure when I will get a chance to try it with the latest versions, but will report back here if/when I do.

**Comment by eggplantzzz** [comment] 2023-02-17 17:47
Ok thanks @rynobey!

**Comment by cds-amal** [comment] 2023-03-23 16:46
Hi @rynobey , closing this for issue maintenance, however, if you do get back with a report, we'd be happy to reopen and investigate. Thanks!

**Closed by cds-amal** 2023-03-23 16:46 UTC
Labels: bug, needs reproduced, needs investigated, priority3 🔧
