### ISSUE TITLE
Unstructured Storage Proxy Pattern with Quorum 

### ISSUE THREAD

**Issue by FITStaff** [trufflesuite/truffle#2178] opened 2019-07-11 17:08 UTC
I implemented an unstructured storage proxy pattern that I’ve successfully tested in Remix. However, when I call the logic contract via the proxy in Truffle I get an error. There’s one function modifier and it just checks to make sure the caller is an Owner, which in this case the calling address is the owner/deployer of the contract. Any ideas? The first image below is the error message and the second image below is proof that I’m connected to the correct contract instance and have already set the proxy target to the most updated contract address and am calling from the contract owner.
 
![image](https://user-images.githubusercontent.com/34380717/61070481-d436bb00-a3dc-11e9-9485-8dffafdd9d2b.png)

Proof that proxy is pointed to most updated address and that my calling address is registered as the owner, which is the function modifier controlling the ‘registerOrganization’ method:
![image](https://user-images.githubusercontent.com/34380717/61070512-e7498b00-a3dc-11e9-8463-f742365fd41e.png)

Stack:
Truffle v4.1.15: For some reason, this was the only version I could get my quorum private contracts to deploy without any errors
Blockchain: QuorumMaker (local)
Node: v10.16.0
npm: 6.9.0
Proxy Pattern: https://github.com/zeppelinos/labs/tree/master/upgradeability_using_unstructured_storage

**Comment by CruzMolina** [comment] 2019-07-11 17:38
Hmm, this probably won't fix it, but can you try passing your owner address as a string (i.e. `('FL', 1, 'test', "0x...")`?

You mention that your contract is a private contract, if so you might need to interact with it using a `privateFor` param passed in your tx call. `privateFor` params were officially supported as of truffle `v5.0.14`.

**Comment by parm23** [comment] 2019-07-11 17:57
@CruzMolina I moved from 4.1.15 (post deployment) to v5.0.14. After running the transaction again, it returned a more insightful error

truffle(quorumMaker1)> Directory.at(OwnedUpgradeabilityProxyDirectory.address).registerOrganization("FL", "1", "test", "0x7090462b2c5e3416fb6bb505814261772e49b194")
Thrown:
evalmachine.<anonymous>:0
Directory.at(OwnedUpgradeabilityProxyDirectory.address).registerOrganization("FL", "1", "test", "0x7090462b2c5e3416fb6bb505814261772e49b194")
                                                        ^

TypeError: Directory.at(...).registerOrganization is not a function
    at evalmachine.<anonymous>:0:57
    at Script.runInContext (vm.js:133:20)
    at runScript (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:352961:14)
    at Console.interpret (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:352975:19)
    at ReplManager.interpret (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:353960:18)
    at bound (domain.js:402:14)
    at REPLServer.runBound [as eval] (domain.js:415:12)
    at REPLServer.onLine (repl.js:642:10)
    at REPLServer.emit (events.js:198:13)
    at REPLServer.EventEmitter.emit (domain.js:448:20)
truffle(quorumMaker1)> 


It seems as if it's not finding the 'registerOrganization' function in the proxy, but the proxy is supposed to forward that to the Directory contract as part of the proxy's fallback function. The contract is calling "Directory" at the Proxy's address, per the instructions of the unstructured proxy pattern. Seems to be able to resolve this fine in Remix. Any experience with this?

**Comment by CruzMolina** [comment] 2019-07-11 18:11
If you're using the VM on Remix, it isn't going to provide accurate quorum RPC responses, since I believe it uses `ethereumjs-vm` under the hood.

It might help to provide a repo for reproduction and/or reproduction steps since I'm not sure how you're migrating to QuorumMaker. Depending on how you deployed your various contracts, you might need to pass a `privateFor` param.

**Comment by parm23** [comment] 2019-07-11 18:53
@CruzMolina this specific contract is actually public. I have some others that were made private, i removed those for now but you can check out my deploy script 

https://github.com/parm23/privateQuorumProxy/tree/master/truffle-init-default

**Comment by parm23** [comment] 2019-07-11 19:32
@CruzMolina after updating the truffle syntax, it just looks like it won't allow you to attach a Proxy contract address to a logic contract's instance, such as Directory.at()

![image](https://user-images.githubusercontent.com/42729062/61079551-1964e800-a3f1-11e9-980c-87dee7cec8d5.png)

**Comment by parm23** [comment] 2019-07-11 19:36
![image](https://user-images.githubusercontent.com/42729062/61079774-8f694f00-a3f1-11e9-9a46-9cd6d196355f.png)

prev. image came out a bit blurry

**Comment by parm23** [comment] 2019-07-11 19:48
@CruzMolina  Seems that truffle just won't let you attach a proxy contract address into a logic contract instance. The 0x89 below is the proxy contract address: 

![image](https://user-images.githubusercontent.com/42729062/61080469-21be2280-a3f3-11e9-9e27-3af7264da0a1.png)

**Comment by CruzMolina** [comment] 2019-07-12 15:52
Closing since I believe this has been resolved over Gitter.

**Closed by CruzMolina** 2019-07-12 15:52 UTC
Labels: Enterprise, Quorum
