### ISSUE TITLE
Failing tests cause "after each" hook to fail too

### ISSUE THREAD

**Issue by PeterBorah** [trufflesuite/truffle#294] opened 2016-11-01 17:16 UTC
## Issue

All failing tests are followed by an error that looks like this:

    2) TestApproveAndCall "after each" hook: after test:                                                               
       Uncaught ReferenceError: SolidityCoder is not defined                                                      
        at /usr/local/lib/node_modules/truffle/lib/testing/testrunner.js:241:20
        at Array.forEach (native)
        at /usr/local/lib/node_modules/truffle/lib/testing/testrunner.js:229:10
        at intermediary (/usr/local/lib/node_modules/truffle/lib/testing/testrunner.js:298:5)
        at request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:114:13)
        at dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
        at setState (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
        at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
        at endReadableNT (_stream_readable.js:975:12)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickDomainCallback (internal/process/next_tick.js:122:9)

## Steps to Reproduce

Write a Truffle test that fails in any way. 

## Expected Behavior

The test should fail, but the after each hook should not.

## Actual Results

The after each hook fails with a "SolidityCoder is not defined" error.

## Environment

Truffle v3.0.0-2
EthereumJS TestRPC v3.0.0
MacOSX

**Comment by rmerom** [comment] 2016-12-20 06:12
I'm getting the same issue
Truffle v3.0.0-4
EthereumJS TestRPC v3.0.3
Ubuntu

**Comment by tcoulter** [comment] 2016-12-20 16:28
Good catch, thanks!

**Comment by tcoulter** [comment] 2017-03-20 22:52
I can't reproduce this. My guess this was fixed on the 3.x branch. Here's my output when I make a default test fail (by changing an expected value to `559`).

```

  Contract: MetaCoin
    ✓ should put 10000 MetaCoin in the first account
    ✓ should call a function that depends on a linked library (58ms)
    1) should send coin correctly

    Events emitted during test:
    ---------------------------

    Transfer(_from: <indexed>, _to: <indexed>, _value: 10)

    ---------------------------


  2 passing (258ms)
  1 failing

  1) Contract: MetaCoin should send coin correctly:
     AssertionError: Amount wasn't correctly taken from the sender: expected 559 to equal 9990
      at test/metacoin.js:59:14
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

Going to close this. If you run into it again please reopen.

**Closed by tcoulter** 2017-03-20 22:52 UTC

**Comment by PeterBorah** [comment] 2017-03-21 02:57
Yes, I think this works as expected on the latest version.
