### ISSUE TITLE
Truffle Migration fails on 5.1.50 with type error param.substring

### ISSUE THREAD

**Issue by lsqproduction** [trufflesuite/truffle#3977] opened 2021-04-16 02:55 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Migration deployment failed with TypeError: param.substring is not a function 

## Steps to Reproduce
```console
git clone https://github.com/sirenmarkets/core.git
cd core && npm install

truffle migrate
```

## Expected Behavior

mirgate successfully

## Actual Results

`TypeError: param.substring is not a function
`

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`5.1.50`):
* node version (`15.8.0"):
* npm version (`7.6.0`):

**Comment by eggplantzzz** [comment] 2021-04-19 20:08
Hey @lsqproduction, does it still fail on the latest Truffle?

**Comment by lsqproduction** [comment] 2021-04-20 00:11
Same error on latest 5.3.2

**Comment by leeftk** [comment] 2022-10-06 18:15
We went through the git history on `https://github.com/sirenmarkets/core.git` and could not reproduce the issue so we are closing it.

**Closed by leeftk** 2022-10-06 18:15 UTC
Labels: bug, needs investigated, priority2 ⚠️
