### ISSUE TITLE
Use ganache core as provider

### ISSUE THREAD

**Issue by lughino** [trufflesuite/truffle#4471] opened 2021-11-27 14:19 UTC
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I'm trying to use ganache-core as a provider for the development network.
The reason for this is to have a clean environment to run my tests and avoid spinning up the ganache-cli or gui.
It seems to work well if I run the migrate command, but it fails during testing, especially when I try to access to a value inside the contract.

## Steps to Reproduce

This is my contract:
```sol
pragma solidity >=0.8.10;

import './Campaign.sol';

/**
 * @title CampaignFactory
 * @dev
 */
contract CampaignFactory {
    address[] public campaigns;

    function createCampaign(uint256 minimumContribution) public {
        Campaign newCampaign = new Campaign(minimumContribution, msg.sender);
        address newCampaignAddress = address(newCampaign);
        campaigns.push(newCampaignAddress);
    }

    function getDeployedCampaigns() public view returns (address[] memory) {
        return campaigns;
    }
}
```

This is my truffle configuration:
```js
const ganache = require('ganache-cli');

module.exports = {
  networks: {
    development: {
      host: '127.0.0.1',
      port: 8545,
      network_id: '*',
      provider: function() {
        return ganache.provider({
          network_id: '1638017666257',
          gasPrice: '0x77359400',
          gasLimit: '0x6691b7',
          callGasLimit: '0x1fffffffffffff',
          accounts: [
            {
              balance: '0x56bc75e2d63100000',
              secretKey:
                '0xb1630540f208e55d3837d33186940c69a4a7f8befd277f9371e86475cab74f05',
            },
            {
              balance: '0x56bc75e2d63100000',
              secretKey:
                '0x63200de6db357083e94d36fa61af687099963001fcf7d0b41a5f2d226d8d7fb1',
            },
            {
              balance: '0x56bc75e2d63100000',
              secretKey:
                '0x3c933b0cb73160953df050e21c28bbdd703c3578d275ff024a2989141816b355',
            },
            {
              balance: '0x56bc75e2d63100000',
              secretKey:
                '0x2bd7e16e9afbf7c75c212287c7a5f462f0fb9d95eae24aed3aa47d8485d2fa09',
            },
            {
              balance: '0x56bc75e2d63100000',
              secretKey:
                '0x0b3e3836d95c5054473d1f07e45816d683d4ee8534e5dc8d1f70e3a794694205',
            },
            {
              balance: '0x56bc75e2d63100000',
              secretKey:
                '0x6bace9f5dedc020c6d9394caa6d8e9ad78355f70010ec34fca9ff4c0f2c632b8',
            },
            {
              balance: '0x56bc75e2d63100000',
              secretKey:
                '0x25288af18c33f7c5aa472203256cca9c65bb7f0f630f90fa5d7faaea18e6e596',
            },
            {
              balance: '0x56bc75e2d63100000',
              secretKey:
                '0xee520411581c6fdc355c32297b9dcf65f0862f14a4c1e41c114412a14683be80',
            },
            {
              balance: '0x56bc75e2d63100000',
              secretKey:
                '0x3d44fe3aa7fa08db700238b1608ef3205ee721a2468796f29e0660f9568ac51d',
            },
            {
              balance: '0x56bc75e2d63100000',
              secretKey:
                '0xd1eded9528e73c6699f6520801e7b4d08a1442a4c68f9cb64d335d0067df153e',
            },
          ],
        });
      },
    },
  },
  compilers: {
    solc: {
      version: '>=0.8.0',
      settings: {
        optimizer: {
          enabled: true,
          runs: 200,
        },
      },
    },
  },
};
```
The reason for setting those options in the provider is because of several errors I received.

This is the test:
```js
import {CampaignInstance} from '../types/truffle-contracts/Campaign.d';
import {CampaignFactoryInstance} from '../types/truffle-contracts/CampaignFactory.d';

const CampaignFactory = artifacts.require('CampaignFactory');
const Campaign = artifacts.require('Campaign');

contract('CampaignFactory', async (accounts) => {
  let campaignFactory: CampaignFactoryInstance;
  let campaign: CampaignInstance;
  let campaignAddress: string;

  beforeEach(async () => {
    campaignFactory = await CampaignFactory.deployed();
    await campaignFactory.createCampaign('100');
    [campaignAddress] = await campaignFactory.getDeployedCampaigns(); // the error happen here
    campaign = await Campaign.at(campaignAddress);
  });

  it('should deploys a factory contract and a campaign', () => {
    expect(campaignFactory.address).to.exist;
    expect(campaign.address).to.exist;
  });
});

```

## Expected Behavior

To work properly in the same way as with ganache cli.
If I run the same test pointing to ganache-cli, everything works properly.

## Actual Results

I receive this error:
```
Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
```

## Environment

* Operating System: 
* Ethereum client: ganache-cli 6.12.2
* Truffle version (`truffle version`): 5.4.22
* node version (`node --version`): 16.13.0
* npm version (`npm --version`): yarn 1.22.17

**Comment by fainashalts** [comment] 2021-12-01 19:18
HI @lughino, can you try removing the `host` and `port` in your network setting and see if that helps? It is our hunch that the issue is that these settings are competing with `provider`. 

We think Truffle could definitely provide a better error here if this is the problem, so please let us know so we can make the needed changes. Thanks!

**Comment by MicaiahReid** [comment] 2022-02-16 18:14
Closing for issue maintenance. Please reopen or create another issue if this is still happening.

**Closed by MicaiahReid** 2022-02-16 18:14 UTC
Labels: error better
