### ISSUE TITLE
Truffle migration - Intrinsic gas too low. How to fix this?

### ISSUE THREAD

**Issue by ProphetDaniel** [trufflesuite/truffle#857] opened 2018-03-21 05:51 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

[Ethereum Stack Exchange link](https://ethereum.stackexchange.com/questions/42268/truffle-migration-intrinsic-gas-too-low-how-to-fix-this)

## Steps to Reproduce

```bash
truffle migrate --reset --network live
```

## Expected Behavior

```bash
Using network 'live'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xe1b191ce722bc3ec922071c396a627365f16ca69c0b2a7d2ce5830d4f1e6881a
  Migrations: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Replacing ClassicDelta...
  ... 0x66988f39a95507976ee6362a55d66c11dd7513e2818af0bd127f79aa17979f66
  ClassicDelta: 0xf12b5dd4ead5f743c6baa640b0216200e89b60da
Saving artifacts...

```

## Actual Results

```bash
Using network 'live'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
intrinsic gas too low
```

## Environment

* Operating System: Windows 10 Pro
 -> Version 1709
 -> OS Build 16299.309 
* Ethereum client:
* Truffle version (`truffle version`): 
 -> Truffle v4.1.3 (core: 4.1.3)
 -> Solidity v0.4.19 (solc-js)
* node version (`node --version`):
 -> v9.8.0
* npm version (`npm --version`): 
 -> 5.7.1

**Comment by cgewecke** [comment] 2018-03-21 14:46
@ProphetDaniel Which Ethereum client are you using? If possible, could you look at Truffle's [advanced configuration](http://truffleframework.com/docs/advanced/configuration#networks) docs and make sure you have configured your project correctly? Then post your `truffle.js` here. 

The error message comes from the client and means that the client estimated the cost of executing the transaction and discovered it had no possibility of success given the amount of gas the user specified.

**Comment by ProphetDaniel** [comment] 2018-03-22 14:40
@cgewecke, here Is the [code](https://github.com/ClassicDelta/Smart-Contracts) which is also available at the Stack Exchange [thread](https://ethereum.stackexchange.com/questions/42268/truffle-migration-intrinsic-gas-too-low-how-to-fix-this). So I will paste here from GitHub repository.

There is no particular client involved other than Infura. This code follows instructions from [here](http://truffleframework.com/tutorials/using-infura-custom-provider).

```javascript
require('dotenv').config();
require('babel-register');
require('babel-polyfill');

const HDWalletProvider = require('truffle-safe-hdwallet-provider');

const providerWithMnemonic = (mnemonic, rpcEndpoint) =>
  new HDWalletProvider(mnemonic, rpcEndpoint, 0, 1, process.env.PASSWORD);

const infuraProvider = network => providerWithMnemonic(
  process.env.MNEMONIC || '',
  `https://${network}.infura.io/${process.env.INFURA_API_KEY}`
);

const provider = apiToUse => providerWithMnemonic(
  process.env.MNEMONIC || '',
  process.env.MAINNET_ENDPOINT+`${apiToUse}`
);

const ropstenProvider = process.env.SOLIDITY_COVERAGE
  ? undefined
  : infuraProvider('ropsten');

module.exports = {
  networks: {
    development: {
      host: 'localhost',
      port: 9545,
      network_id: '*', // eslint-disable-line camelcase
    },
    live: {
      provider: provider('eth-api'),
      network_id: 1,
    },
    ropsten: {
      provider: ropstenProvider,
      network_id: 3, // eslint-disable-line camelcase
    },
    coverage: {
      host: 'localhost',
      network_id: '*', // eslint-disable-line camelcase
      port: 8555,
      gas: 0xfffffffffff,
      gasPrice: 0x01,
    },
    testrpc: {
      host: 'localhost',
      port: 8545,
      network_id: '*', // eslint-disable-line camelcase
    },
    ganache: {
      host: 'localhost',
      port: 7545,
      network_id: '*', // eslint-disable-line camelcase
    },
  },
  solc: {
    optimizer: {
      enabled: true,
      runs: 200
    }
  },
};
```

**Comment by cgewecke** [comment] 2018-03-22 14:49
@ProphetDaniel Could you try specifying `gas` and `gasPrice` fields in your live network? You'll need to figure out where these limits are. I suggest writing a set of tests that simulates the deployment and calling `.estimateGas` in order to check the range of the values. Another option is this truffle utility: [eth-gas-reporter](https://github.com/cgewecke/eth-gas-reporter) which will produce a gas usage report by watching the execution of the tests.

In the stack-exchange post it says you are running against ganache, not infura. Are you actually seeing this error on Ganache?

**Comment by ProphetDaniel** [comment] 2018-03-22 15:39
@cgewecke, Regardless if ran against Ganache or Truffle development, the problem still happens.

**Comment by cgewecke** [comment] 2018-03-22 16:53
@ProphetDaniel Gas.

**Comment by ProphetDaniel** [comment] 2018-03-22 19:12
@cgewecke , after updating truffle config live section to:
```javascript
    live: {
      provider: provider('eth-api'),
      network_id: 1,
      gasPrice: 2000000000,
      gas: 6000000,
    },
```
The problem still persists.

**Comment by cgewecke** [comment] 2018-03-22 20:23
@ProphetDaniel I'm going to close this because you really need to do what is suggested in the [comment](https://github.com/trufflesuite/truffle/issues/857#issuecomment-375333447) above to isolate where the problem is. In other words, write tests, get them passing on Ganache. Test your migrations on Ganache. Discover the answers to the following questions by doing that work:

+ Are your contracts too big?
+ Is there an issue with the mainnet client you're using?
+ Is there an issue with your wallet?
+ Is there an issue with the way the provider is being instantiated: e.g `eth-api`?

It's not possible to debug this as presented, and it's likely not a bug in truffle. I'd also encourage you to seek help at Zeppelin's slack if you are using their code. Our gitter is another resource. The github issues here for reporting problems specific to the codebase or proposing features. 

Thanks.

**Closed by cgewecke** 2018-03-22 20:23 UTC
