### ISSUE TITLE
Etimedout 49.44.79.236:443  error while unboxing a metacoin project

### ISSUE THREAD

**Issue by Ashokanandhu** [trufflesuite/truffle#5809] opened 2022-12-26 12:31 UTC
![Screenshot (6)](https://user-images.githubusercontent.com/119148713/209549385-a5beed88-84d3-487a-b085-ddb777e0a03c.png)
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by dongmingh** [comment] 2023-01-05 18:37
Closing as duplicate of #5799

**Closed by dongmingh** 2023-01-05 18:37 UTC
