### ISSUE TITLE
Deployment issue in Polygon Network

### ISSUE THREAD

**Issue by racetrack0616** [trufflesuite/truffle#4240] opened 2021-08-09 05:14 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I am not able to deploy my smartcontracts in Matic testnet.
## Steps to Reproduce

My truffle config for matic testnet
```
matic: {
      provider: () => new HDWalletProvider(MNEMONIC, `https://polygon-mumbai.g.alchemy.com/v2/<my_key>`),
      network_id: 80001,
      confirmations: 2,
      timeoutBlocks: 200,
      networkCheckTimeout: 90000,
      skipDryRun: true
    }
```

## Expected Behavior

With the matic config it is suppose to deploy in the matic testnet without any issue because that is what the official documentation of polygon also supports.
## Actual Results

I am constantly getting an error as 
![image](https://user-images.githubusercontent.com/68948218/128662800-b00a9507-2613-4e9a-b223-2abe0cc1417b.png)

## Environment

* Operating System: Ubuntu 18
* Ethereum client:
* Truffle version (`truffle version`): v5.1.65 - a development framework for Ethereum
* node version (`node --version`):v12.18.3
* npm version (`npm --version`): 6.14.6

**Comment by racetrack0616** [comment] 2021-08-09 05:21
Before everything I also wanted to know if my config is correct or not with the rpc URL that I am using.
I was also suggested to use vpn for stable network for deployment but that did not solve the issue.
I tried **maticvigil** & **chainstacklabs** as well for rpc url not did not work either. The issue is not very specific. Sometimes I get different issue as
```
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
```

**Comment by fainashalts** [comment] 2021-08-10 16:49
Hi @racetrack0616 thanks for reaching out! Those errors seem to be related to the RPC url you are using, at first glance. 

Have you tried any of the testnets in the [Truffle Polygon Box](https://github.com/truffle-box/polygon-box)?  

Since you are trying to use Alchemy here, you will want to be sure that your Alchemy key is correct and that your url is correct, using their dashboard. 

Please let me know if these suggestions help resolve your issue!

**Comment by racetrack0616** [comment] 2021-08-11 03:12
No doubt my RPC url is correct. It's not just alchemy but I tried everything that is in their documentation.
```
https://rpc-mumbai.maticvigil.com/v1/<key>
https://matic-testnet-archive-rpc.bwarelabs.com/
https://polygon-mumbai.g.alchemy.com/v2/<key>
wss://polygon-mumbai.g.alchemy.com/v2/<key>
https://matic-mumbai.chainstacklabs.com
```

**Comment by racetrack0616** [comment] 2021-08-11 04:56
> Hi @racetrack0616 thanks for reaching out! Those errors seem to be related to the RPC url you are using, at first glance.
> 
> Have you tried any of the testnets in the [Truffle Polygon Box](https://github.com/truffle-box/polygon-box)?
> 
> Since you are trying to use Alchemy here, you will want to be sure that your Alchemy key is correct and that your url is correct, using their dashboard.
> 
> Please let me know if these suggestions help resolve your issue!

Yes I gave a try [Truffle Polygon Box](https://github.com/truffle-box/polygon-box). I tried deploying in **polygon_testnet** using 
```
npm run migrate:polygon --network=polygon_testnet
```
Still the issue persists.
![image](https://user-images.githubusercontent.com/68948218/128971759-796c9525-86cb-4f1c-b1fc-3e99ac9542b9.png)

**Comment by fainashalts** [comment] 2021-08-11 16:53
Hi @racetrack0616 I am able to deploy using `polygon_infura_testnet` but do see a problem with the regular `polygon_testnet`. That may be offline as Polygon is supported by Infura and Alchemy now. Are you able to deploy if you use the `polygon_infura_testnet`? You will need an Infura key to do so. 

I will update the Polygon box to remove the broken testnet from the config, than you for pointing it out!

**Comment by racetrack0616** [comment] 2021-08-12 03:46
Keep it open unless legit information on every other rpc urls are failing except infura.

**Comment by racetrack0616** [comment] 2021-08-12 03:50
But I don't agree that other rcp urls are failing because when I deployed with **remix** and other urls than **infura_testnet** it worked. It doesn't make sense at all.

**Comment by bwpunks** [comment] 2021-09-12 23:40
I have the same problem :( 

Works fine with Remix but not for Truffle

**Comment by racetrack0616** [comment] 2021-09-13 03:17
Its definitely a bug and I don't find a proper solution for this. Everything one is dropping there version of solution everywhere which is not relevant for all the problems. :(

**Comment by ethernetweb** [comment] 2021-09-13 22:24
I can confirm the same issue. It seems to be a recent issue since the ETH London Hardfork. I don't know the solution.
I have also tried with HARDHAT, and have the exact same issue. Nothing will publish to the matic testnet now using either TRUFFLE or HARDHAT.

**Comment by fainashalts** [comment] 2021-09-13 22:28
Hello there! 👋 This is a duplicate of this issue on the Polygon Box repo: https://github.com/truffle-box/polygon-box/issues/4

I am looking into this and will update this issue as well as that one once I have a resolution.

**Comment by racetrack0616** [comment] 2021-09-14 03:55
Thank you very much for looking into the issue. Its been lingering there for long time. Please help me through.

**Comment by PxGnome** [comment] 2021-11-25 07:07
> This is still not working. Not even `initial_migration` file got deployed. It freezes as in screenshot. ![image](https://user-images.githubusercontent.com/68948218/137686077-fb91815e-1f38-46d0-92bc-aa944f86bb8f.png) :(

Did you manage to resolve? We used infura to mint and it works on Mumbai but not on mainnet. Seeing a similar issue with an error about Json rpc

**Comment by dkillen** [comment] 2021-11-29 03:05
Hi @racetrack0616 

I have looked into this issue further and have responded in [truffle-box/polygon-box#4](https://github.com/truffle-box/polygon-box/issues/4)

**Comment by haltman-at** [comment] 2022-02-09 19:33
Closing this as duplicate of truffle-box/polygon-box#4.

**Closed by haltman-at** 2022-02-09 19:33 UTC
Labels: L2
