### ISSUE TITLE
Migrations for multiple instances of same contract?

### ISSUE THREAD

**Issue by harlantwood** [trufflesuite/truffle#237] opened 2016-08-13 08:04 UTC
We're trying to figure out if migrations will work for our use case... We have one solidity contract (which creates a currency/tokens), which we deploy multiple instances of, often from the same ethereum account (owner). It doesn't seem to us like the migration system is set up to track multiple instances of the same solidity code. Is there a way this can work? Such that we can run migrations against multiple instances of a contact... Thanks for any help.

**Comment by tcoulter** [comment] 2016-08-22 21:08
This is a good feature. On the list.

**Comment by harlantwood** [comment] 2016-08-22 21:23
Excellent!

**Comment by petermunnings** [comment] 2016-10-10 12:42
We need this as well

**Comment by paulhauner** [comment] 2017-06-11 06:18
I post this comment not to dispute the need for this feature, instead to illustrate a potentially superior design which mitigates this issue.

If you are deploying multiple instances of the same contract, it may be in your best interest  to use the 'factory' pattern. It allows you to compile and deploy a single contract which then performs the creation of further contracts. This provides consistency among contracts and provides easier deployment and testing in truffle.

```
pragma solidity ^0.4.8;


contract CarFactory {

    function CarFactory() {
    }

    function newCar(string _color) public returns (address newCar) {
        Car c = (new Car(_color));
        return address(c);
    }
}


contract Car {
    string color;
    
    function Car(string _color) {
        color = _color;  
    }
    
  function getColor() public constant returns (string color) {
    return color;
  }    
}
```

**Comment by shuppyloh** [comment] 2017-07-07 16:39
I really think this is a good feature to have. I am trying to build a test environment that will facilitate a cross-transfer between 2 token types and ideally, I would want to deploy the 2 different token types from the same generalised token contract. I am not sure if using the factory method as suggested by @paulhauner will allow you to use contract abstractions when interacting with the newly spawned contract. What I have done so far is to make my 2 token types 2 different contracts that inherit from the same generalised token contract and deploying them explicitly.

**Comment by tcoulter** [comment] 2017-07-10 20:47
Proposal: 

```
deployer.deploy(ERC20Token, {as: “SilverToken”});
deployer.deploy(ERC20Token, {as: “GoldToken”});
```

Triaging and looking for a good technical solution.

**Comment by victorwiebe** [comment] 2018-02-16 15:59
Following up on this feature, or what is the alternative to this approach in truffle deployment. Regards.

**Comment by yaoshiang** [comment] 2018-04-06 05:43
My solution to this was to create a container of multiple instances in the contracts folder. For example, if you have a MyERC20 contract, and need to have a few of them deployed... you could create a container of them: 
```
contract MyERC20Container {
  address public a = new MyERC20(...);
  address public b = new MyERC20(...);
}
```
Deploy that in a migration script (e.g. 2_deploy_MyERC20Container.js)

Then in your TestStuff.sol, you can grab them:
```
MyERC20Token tokenA = MyERC20Token(MyERC20TokenContainer(DeployedAddresses.MyERC20TokenContainer()).a());

MyERC20Token tokenB = MyERC20Token(MyERC20TokenContainer(DeployedAddresses.MyERC20TokenContainer()).b());
```
I had this exact use case and now the problem is that if you are using an ERC20 library like Zeppelin... the contracts are inheriting from Ownable... and the owner of the contract is txn.origin, not, your TestStuff.sol contract. 

What I did is then created a child class of MyERC20Token that's solely for testing with some additional hooks. In this case, that hook is a way for your TestStuff contract to forcibly transfer ownership. So you need to implement a new function in your TestOnlyMyERC20Token to xfer the ownership to the TestStuff contract, and, call it from TestStuff. 

```
contract TestOnlyMyERC20Token is MyERC20Token {
  function forceTransferOwnership(address newOwner) external {
    owner = newOwner;
  }
}
```

This is not elegant but, it's the only workaround I could figure out.

**Comment by k-misztal** [comment] 2018-06-20 10:37
Any update on that feature?

**Comment by cgewecke** [comment] 2018-06-20 14:28
@k-misztal This is a key part of a refactor of the artifacts format we have scheduled for this summer, but work on that is just beginning. It will probably be a couple months before Migrations supports this.

**Comment by lychees** [comment] 2018-08-09 20:42
+1

**Comment by alsco77** [comment] 2018-08-21 03:49
As a workaround to (for example) deploy multiple ERC20 tokens, I have created extra `OneERC20.sol` and `TwoERC20.sol` files which inherit ERC20, and deploy as individual entities. Not ideal but whatever, it works.

**Comment by nikola-wyatt** [comment] 2018-08-25 03:17
+1

**Comment by gakonst** [comment] 2018-08-31 12:53
Thanks @mryellow this did the trick for me. I imagine this could be included in truffle to accompany the syntax @tcoulter mentioned?

**Comment by gnidan** [comment] 2018-10-24 18:06
This is part of a task on our roadmap. For more information, please see requirements listed the [artifact-updates doc](https://trufflesuite.github.io/artifact-updates/trufflesuite/master/docs/use-cases.html)

**Comment by mryellow** [comment] 2018-10-24 21:10
One issue with the above hacky code is that it requires that a build already exists, so running in tests it gets those paths wrong and will fail unless a build directory full of artefacts has previously been created.

**Comment by gnidan** [comment] 2019-01-09 18:37
Copying proposal from duplicate issue:
```javascript
deployer.deploy(A, {as: 'GoldToken'}); // => GoldToken.json
GoldToken = deployer.resolve(A, {from: 'GoldToken'})
deployer.deploy(B, GoldToken);
```

**Comment by CQBinh** [comment] 2019-07-25 07:33
You can do like this:
```
module.exports = async function(deployer) {
    const token1 = await deployer.deploy(MyToken);
    const token2 = deployer.deploy(MyToken);
  };
```
After migrate, you'll have 2 addresses of your contracts, say `0x1` and `0x2`
Then, on `truffle console`:
```
token1 = await MyToken.at(`0x1`)
token2 = await MyToken.at(`0x2`)
```

**Comment by SwJay** [comment] 2019-09-10 00:13
Any update now?

**Comment by captainheart** [comment] 2020-10-07 03:52
Is this resolved?

**Comment by eggplantzzz** [comment] 2020-10-12 15:37
@captainheart Can you let me know more specifically which part you are referring to? You should be able to implement @CQBinh's solution above.

**Comment by captainheart** [comment] 2020-10-13 02:32
@eggplantzzz   `contractInstance.new()` was just fine for my needs. No problem.

**Comment by eggplantzzz** [comment] 2020-10-13 16:20
Is there anything else actionable here or can we close this issue?

**Comment by eggplantzzz** [comment] 2020-11-11 18:59
Closing this for issue maintenance.

**Closed by eggplantzzz** 2020-11-11 18:59 UTC
Labels: enhancement
