### ISSUE TITLE
A cryptic "Error: sender doesn't have enough funds to send tx"

### ISSUE THREAD

**Issue by mushketyk** [trufflesuite/truffle#1062] opened 2018-06-24 15:00 UTC
Out of the blue, I started having issues with running my unit tests with Truffle. Now when I run `truffle test` I see the following error message:

```
truffle test                                                                                        
Using network 'test'.

Error: sender doesn't have enough funds to send tx. The upfront cost is: 672197500000000000 and the sender's account only has: 645096100000000000
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

Few things that puzzle me here:

1. It seems that my tests are not even executed
2. This happens even with a version of my code that passed all tests before
3. Nothing that reduces a transaction cost helps. I've even removed all code from the constructor of my contract and yet the _upfront cost_ stays the same
4. `672197500000000000` is `0.6721975` ether! This seems like too much for a small contract with an empty constructor
5. I am not sure where this balance is coming from: `645096100000000000`
6. If I run tests for another Truffle project everything works fine.

I guess that Truffle keeps a state (per project?) between executions and now it prevents tests execution.

Is there any way I can fix this?

**Comment by mushketyk** [comment] 2018-06-24 15:06
I've restarted my machine, and now all tests are passing.

This is still an odd behavior though.

**Comment by cgewecke** [comment] 2018-06-24 16:44
@mushketyk Thanks, for reporting. A few questions:

+ Are you running ganache-cli separately as a long running process? 
+ Are you using `truffle develop`?
+ Have you defined a `test` network in `truffle.js`? 
+ Have you defined your own accounts in any way? 

It would be nice to have simple reproduction steps for this although from your description it seems like it might difficult to get those . . .

**Comment by mushketyk** [comment] 2018-06-24 17:57
Hi @cgewecke 

1. I am running Ganache as a separate process
2. No
3. No
3. No

**Comment by daithi-coombes** [comment] 2018-08-12 15:25
I am having the same issue.

underTest:
```solidity
pragma solidity ^0.4.24;

contract myContract{

    address owner;
    uint balance;

    constructor() public payable {
        owner = msg.sender;
        balance = msg.value;
    }

    function() public payable{
        balance += msg.value;
    }
}
```

test suite:
```solidity
pragma solidity ^0.4.24;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/MyContract.sol";

contract TestMyContract {

  MyContract public underTest;
  uint public initialBalance = 100 ether;

  function beforeEach() public{
    underTest = MyContract(DeployedAddresses.MyContract());
  }

  function testIsPayable() public {
    address(underTest).transfer(1 wei);
  }
}
```

Also seems my error is happending before the test cases are called:
```bash
"before all" hook: prepare suite:
     Error: sender doesn't have enough funds to send tx. The upfront cost is: 100672197500000000000 and the sender's account only has: 99295519300000000000
      at Object.InvalidResponse (/home/daithi/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /home/daithi/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /home/daithi/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/home/daithi/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/daithi/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/home/daithi/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/home/daithi/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/home/daithi/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1054:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by seesemichaelj** [comment] 2018-08-12 15:51
@mushketyk what version of Ganache CLI are you using? v6.1.5 introduced a similar error that got fixed in v6.1.6

@daithi-coombes same for you; are you using Ganache/ganache-cli in the loop? If so, Is it v6.1.5?

**Comment by daithi-coombes** [comment] 2018-08-12 15:57
Using `v6.1.6`

Here's my stack:
```
Debian 9 Stretch
Ganache CLI v6.1.6 (ganache-core: 2.1.5)
Truffle v4.1.13
```

**Comment by cgewecke** [comment] 2018-08-12 16:39
@daithi-coombes Does setting the `initialBalance` value lower fix this error? Ganache initializes accounts with 100 ether and the entire amount is being sent to the Solidity test for use within that context. 

Ex:
```solidity
uint public initialBalance = 50 ether;
```

**Comment by SwJay** [comment] 2018-08-22 10:26
@cgewecke solves my problem. 
Each time for a test, you consume `initialBalance` out of initial 100 ETH of Ganache account. If you set `initialBalance` to be 100, the test only passes the first time and you will have no ethers next time to run another test.

**Comment by iwkse** [comment] 2018-08-25 15:48
Having a similar issue here when I run ganache-cli with --db for persistence.
Without --db it's going to be fine. Any hint?

**Comment by PochenriederAlex** [comment] 2018-09-12 18:28
Happens to me too. In my case the test i was running had an incorrect amount in the value of the transaction (a javascript number with decimals) that made the transaction cost a lot and throw the error.

**Comment by timothywangdev** [comment] 2018-12-16 22:00
same error

```
Error: sender doesn't have enough funds to send tx. The upfront cost is: 1024628448149621997816844960494848980548232143211 and the sender's account only has: 99717527600000000000

```

**Comment by roschler** [comment] 2018-12-16 22:07
To all who come here.  There may be multiple causes to the error referenced on this thread but in my case it had to do with passing values to the Web3JS functions that were not all Big Numbers.  If you are having this error and are not already converting all gas related values to a Big Number, give that a try using the `toBN()` function found in the `web3-utils` package.  This may also clean up a host of other odd error messages you may see intermittently, even seemingly unrelated errors like intermittent "Internal JSON RPC response" error.

**Comment by gnidan** [comment] 2019-01-16 18:53
Next steps here seem to involve figuring out what is actionable. Maybe improve problem detection and messaging?

**Comment by abuaesh** [comment] 2020-03-02 20:08
Hello everyone, it's 2020 and I got the same problem :) 
I'm using Ganache CLI v6.9.0. 
The error says: sender doesn't have enough funds to send tx. The upfront cost is: 672197500000000000 and the sender's account only has: 0

Anyone help?

**Comment by abuaesh** [comment] 2020-03-03 03:23
I was able to solve it by changing the mnemonic in my truffle-config.js to match the mnemonic given by Ganache CLI

**Closed** 2020-03-04 18:43 UTC

**Comment by hswopeams** [comment] 2020-04-08 08:36
> changing the mnemonic in my truffle-config.js to match the mnemonic given by Ganache CLI

Hello. Can you explain how you did that? I have looked up documentation on truffle configuration and couldn't find any information on how to specific the mnemonic in truffle-config.js. Thanks.

**Comment by abuaesh** [comment] 2020-04-08 13:56
> > changing the mnemonic in my truffle-config.js to match the mnemonic given by Ganache CLI
> 
> Hello. Can you explain how you did that? I have looked up documentation on truffle configuration and couldn't find much information on how to specify the mnemonic in truffle-config.js. It looks like it can only be specified if you define n HDWalletProvider. Is that correct? Thanks.

Sure @hswopeams 👍Here are the steps:
1. When you run ganache-cli it shows the mneumonic (a group of 12 random words that display in the CLI right below the list of public and private keys). Copy these words.

2. Now, in the truffle-config.js file, look for the instantiation of the HDWalletProvider . This should normally be somewhere in setting a value to module.exports (under the networks > development > provider) 
3. In the constructor call for HDWalletProvider, make sure you pass the correct mneumonic as the first argument. Example:
new HDWalletProvider(paste_the_mnemonic_here, "http://127.0.0.1:8545/", 0, 10)

Note: if your truffle-config.js file does not have module.exports set, or you are starting the file from scratch, consider adding following code to it:

var HDWalletProvider = require("truffle-hdwallet-provider");
var mnemonic = "Get this text from the mneumonic in your Ganache CLI - they are 12 words- also to the seed to your wallet";

module.exports = {
  networks: {
    development: {
      provider: function() {
        return new HDWalletProvider(mnemonic, "http://127.0.0.1:8545/", 0, 10);
      },
      network_id: '*',
      gas: 9999999
    }
  },
  compilers: {
    solc: {
      version: "^0.4.25"  //the version of solidity used in writing your contract
    }
  }
};

Hope this helps, good luck!

**Comment by hswopeams** [comment] 2020-04-09 13:54
Thanks! I'll give it a try.

**Comment by 4vadim4** [comment] 2020-06-11 14:48
@abuaesh , hi,
i have same issue and i have a question:  this is one of my docker container:  
```
  ganache:
    image: trufflesuite/ganache-cli:v6.9.1
    command: >
      --account="<here my PRIVATE KEY>,1000000000000000000000"
        ports:
      - "8545:8545"
```
and then i build locally platform from my docker-compose it doesn't show mneumonic only this:
```
Pulling ganache (trufflesuite/ganache-cli:v6.9.1)...
v6.9.1: Pulling from trufflesuite/ganache-cli
5d20c808ce19: Pull complete
50ae34e155d6: Pull complete
110da5c7c0b0: Pull complete
079df574cabd: Pull complete
b79af1dd6747: Pull complete
193662870f41: Pull complete
a4eae2a98dc3: Pull complete
f861a39b24c3: Pull complete
ba6d7dcbe4fe: Pull complete
c75f29973692: Pull complete
1b02bfb4f598: Pull complete
Digest: sha256:9aed1a7bcf25524557f63aba92a444043cb1913b171cfe570dbe11b9094718cf
Status: Downloaded newer image for trufflesuite/ganache-cli:v6.9.1
```

**Comment by valmack** [comment] 2020-11-26 03:21
Having the same issue running `truffle test` but using `Ganache.provider` like so

```
this.provider = Ganache.provider({
      default_balance_ether: toBN("134439500000000000"),
      time: start,
      unlocked_accounts: this.providedAccounts
    });
```

And using `"ganache-core": "^2.13.1",` and `"truffle": "^5.1.52"`

When I check balances with web3 they definitely have a balance but the error says balance is `0`.

I've tried setting the web3.eth.defaultAccount to one that for sure has a balance but same error.

**Comment by stoplion** [comment] 2021-02-26 05:08
2021 same issue. 
` * Message:  sender doesn't have enough funds to send tx. The upfront cost is: 994313868000000000 and the sender's account only has: 297068575000000000`

That's almost 1 Eth!!! Is that for real?

**Comment by kader46** [comment] 2021-05-30 10:05
I'm dealing with same issue ! any solutions found ?
The Error Message : 
RPCError: got code -32000 with msg "sender doesn't have enough funds to send tx. The upfront cost is: 1800000000000000 and the sender's account only has: 0"

**Comment by pinajmr** [comment] 2021-05-31 12:35
Hey @kader46  I have the same issue,  If you found the solutions please write here, I think the problem is with truffle-hdwallet-provider version

**Comment by kader46** [comment] 2021-05-31 13:27
Hey @pinajmr, I found a solution. Are you using flutter ? 
the solution is that i limited the gas price  in the web3Client call 
it's something like this : 
`ethClient.sendTransaction(
        cred,
        Transaction.callContract(
            contract: contract,
            function: etherFunction,
            parameters: args,
            maxGas: 99999999),
        fetchChainIdFromNetworkId: true);`
i hope you find this usefull.

**Comment by AuroraLantean** [comment] 2021-06-04 07:20
In Hardhat, setting the gas and gasPrice solves it for me!
hardhat: {
gas: 678880,
gasPrice: 1000000,
}

**Comment by ChiefMateStarbuck** [comment] 2021-06-05 03:15
having the same issue

**Comment by LarryNxumalo** [comment] 2021-09-17 21:14
> Hi @cgewecke
> 
> 1. I am running Ganache as a separate process
> 2. No
> 3. No
> 4. No

run  `truffle develop` then run `truffle migrate`, if you have already run the migration or you just want to test then run `truffle test` right after running  `truffle develop`
