### ISSUE TITLE
“Migrations” -- Unknown address - unable to sign transaction for this address: “0x63585*************”.

### ISSUE THREAD

**Issue by chahakshah111** [trufflesuite/truffle#4139] opened 2021-06-24 07:13 UTC
I'm getting this error while running below command:
truffle migrate --network rinkeby, how can i solve this error?

**Comment by eggplantzzz** [comment] 2021-06-24 15:26
Can you show us your project? It looks like you may have some account stuff misconfigured.

**Comment by haltman-at** [comment] 2022-02-09 19:14
Closing this for issue maintenance, but if you can get us further reproduction steps we can reopen this!

**Closed by haltman-at** 2022-02-09 19:14 UTC
