### ISSUE TITLE
wrong version of solc in chain.bundled.js

### ISSUE THREAD

**Issue by eepstein** [trufflesuite/truffle#671] opened 2017-11-08 06:05 UTC
Truffle references solc 0.4.18 in its package.json file, but ships a chain.bundled.js that references 0.4.8 instead

typo somewhere perhaps?

**Comment by owocki** [comment] 2017-11-15 16:59
could you add reproduction steps to this issue?

**Comment by tcoulter** [comment] 2017-11-28 19:32
Hi there,

Checked up on this. The only reference to Solidity 0.4.8 is in a definition of `ganache-core` (see below). It looks like it's accounting for some `ganache-core` dependencies even if they don't exist in the bundle (see `inBundle: false`). 

I used a webpack analyzer and it confirmed the intention of our webpack configuration, which is to no put solc into the bundle.

I'm going to close this. If you find more info that suggests solc _is_ in the bundle, let me know.

```
{
   "_from":"ganache-core@1.1.3",
   "_id":"ganache-core@1.1.3",
   "_inBundle":false,
   "_integrity":"sha512-lkYXFpVV6sqxzWHew3bHP2eTq9hIMwlelxzoFcoWcBXVWa0gZlbX9Vny0uQ6PobmuTIrnxcUoKvqll/sDiFSbg==",
   "_location":"/ganache-core",
   "_phantomChildren":{
      "acorn":"5.1.1",
      "acorn-dynamic-import":"2.0.2",
      "big.js":"3.1.3",
      "co":"4.6.0",
      "code-point-at":"1.1.0",
      "decamelize":"1.2.0",
      "emojis-list":"2.1.0",
      "enhanced-resolve":"3.4.1",
      "get-caller-file":"1.0.2",
      "graceful-fs":"4.1.11",
      "interpret":"1.0.3",
      "is-fullwidth-code-point":"1.0.0",
      "is-utf8":"0.2.1",
      "json-loader":"0.5.7",
      "json-stable-stringify":"1.0.1",
      "json5":"0.5.1",
      "lcid":"1.0.0",
      "loader-runner":"2.3.0",
      "lodash":"4.17.4",
      "memory-fs":"0.4.1",
      "mkdirp":"0.5.1",
      "node-libs-browser":"2.0.0",
      "normalize-package-data":"2.4.0",
      "object-assign":"4.1.1",
      "parse-json":"2.2.0",
      "pify":"2.3.0",
      "pinkie-promise":"2.0.1",
      "require-directory":"2.1.1",
      "require-main-filename":"1.0.1",
      "set-blocking":"2.0.0",
      "source-map":"0.5.7",
      "strip-ansi":"3.0.1",
      "tapable":"0.2.8",
      "uglify-js":"2.8.29",
      "watchpack":"1.4.0",
      "webpack-sources":"1.0.1",
      "wrap-ansi":"2.1.0",
      "y18n":"3.2.1"
   },
   "_requested":{
      "type":"version",
      "registry":true,
      "raw":"ganache-core@1.1.3",
      "name":"ganache-core",
      "escapedName":"ganache-core",
      "rawSpec":"1.1.3",
      "saveSpec":null,
      "fetchSpec":"1.1.3"
   },
   "_requiredBy":[
      "#DEV:/"
   ],
   "_resolved":"https://registry.npmjs.org/ganache-core/-/ganache-core-1.1.3.tgz",
   "_shasum":"f5763d2624c7cde8d9a52ad6ec3bc92babcc789f",
   "_spec":"ganache-core@1.1.3",
   "_where":"/Users/tim/Documents/workspace/Consensys/testrpc",
   "bugs":{
      "url":"https://github.com/trufflesuite/ganache-core/issues"
   },
   "bundleDependencies":false,
   "dependencies":{
      "async":"~1.5.0",
      "bip39":"~2.4.0",
      "cachedown":"^1.0.0",
      "chai":"^3.5.0",
      "ethereumjs-account":"~2.0.4",
      "ethereumjs-block":"~1.2.2",
      "ethereumjs-tx":"^1.3.0",
      "ethereumjs-util":"~5.1.0",
      "ethereumjs-vm":"~2.2.0",
      "ethereumjs-wallet":"~0.6.0",
      "fake-merkle-patricia-tree":"~1.0.1",
      "heap":"~0.2.6",
      "js-scrypt":"^0.2.0",
      "level-sublevel":"^6.6.1",
      "levelup":"^1.1.0",
      "localstorage-down":"^0.6.7",
      "merkle-patricia-tree":"^2.2.0",
      "mocha":"~2.2.5",
      "on-build-webpack":"^0.1.0",
      "prepend-file":"^1.3.1",
      "seedrandom":"~2.4.2",
      "shebang-loader":"0.0.1",
      "solc":"0.4.8",
      "temp":"^0.8.3",
      "tmp":"0.0.31",
      "web3":"^0.19.1",
      "web3-provider-engine":"~8.1.0",
      "webpack":"^2.2.1",
      "yargs":"^7.0.2"
   },
   "deprecated":false,
   "description":"This is the core code that powers the Ganache application and the
the Ganache command line tool.",
   "directories":{
      "lib":"./lib"
   },
   "homepage":"https://github.com/trufflesuite/ganache-core#readme",
   "main":"./index.js",
   "name":"ganache-core",
   "repository":{
      "type":"git",
      "url":"git+https://github.com/trufflesuite/ganache-core.git"
   },
   "scripts":{
      "test":"mocha"
   },
   "version":"1.1.3"
}
```

**Closed by tcoulter** 2017-11-28 19:32 UTC
