### ISSUE TITLE
Error : PollingBlockTracker

### ISSUE THREAD

**Issue by kallolborah** [trufflesuite/truffle#3365] opened 2020-09-16 04:06 UTC
- I've asked for help in the Truffle Gitter before filing this issue.

---------------------------

## Issue

When I run truffle migrate --network ropsten, I get the following error

```
C:\Engineering\Via\via-issuer\node_modules\request\request.js:848
          var e = new Error('ETIMEDOUT')
                  ^
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: ETIMEDOUT
    at Timeout.<anonymous> (C:\Engineering\Via\via-issuer\node_modules\request\request.js:848:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
    at PollingBlockTracker._performSync (C:\Engin
a\via-issuer\node_modules\eth-block-tracker\src\p
:51:24)
    at processTicksAndRejections (internal/proces
eues.js:97:5)
    at runNextTicks (internal/process/task_queues

    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)
```

## Steps to Reproduce

Migrating to any test net using hdwallet-provider with mnemonic of metamask account stored in a .secret file and infura key stored in a env file causes this error.

## Expected Behavior

Migrate to the --network in truffle command

## Actual Results

I am unable to deploy to any test net. I also updated hdwallet-provider to v1.0.44

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): 5.1.44
* node version (`node --version`): 12.16.2
* npm version (`npm --version`): 6.14.8

**Comment by eggplantzzz** [comment] 2020-09-16 17:53
Thanks for the issue report! Looks like this is a duplicate of #3356. Closing this.

**Closed by eggplantzzz** 2020-09-16 17:53 UTC
