### ISSUE TITLE
add a command line option to specify the truffle config file to be used

### ISSUE THREAD

**Issue by naddison36** [trufflesuite/truffle#2354] opened 2019-08-30 23:23 UTC
This is an enhancement request to add a command line option to specify the truffle config file to be used on compilation.

The use case I have is I'm using the Gnosis MultiSigWallet which requires Solidity `0.4.15` while the other contracts in my app are using `0.5.11` as I need ABIEncoderV2. At the moment I put the MultiSigWallet contract in a different folder and manually modify my `truffle-config.js` file to specify the compiler version to use for the folder I want to compile.

Ideally, I'd like to have two truffle config files and just use a command line option to specify which config file to use when compiling. That means in a continuous integration build, two truffle compile commands would be run.

**Comment by CruzMolina** [comment] 2019-08-31 01:45
Related #1879.

**Comment by gnidan** [comment] 2019-08-31 04:36
Oh, maybe that other one can be closed as a duplicate of this, since it's less general? Let's figure that out when we triage this.

**Comment by naddison36** [comment] 2019-09-04 22:33
An update on how I work around this issue. I have separate folders for my Solidity 0.5 and 0.4 contracts with separate `truffle-config.js` files in each folder. I then run `truffle compile` from the folder I want to compile.

**Comment by eggplantzzz** [comment] 2019-09-27 18:11
@naddison36 This feature has been merged and released with version 5.0.38. https://github.com/trufflesuite/truffle/releases/tag/v5.0.38

**Closed by eggplantzzz** 2019-09-27 18:11 UTC
Labels: Config, enhancement, help wanted
