### ISSUE TITLE
download latest uuid version 

### ISSUE THREAD

**Issue by yu5ufyilmaz** [trufflesuite/truffle#5569] opened 2022-09-27 17:24 UTC
npm WARN deprecated uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details. 
*****************************************************************************************************************
I have this issue but when i install latest version or 7.02th version of uuid i cant update. still keep 3.2.1st version itself

**Comment by gnidan** [comment] 2022-09-29 17:47
Thanks for raising this! Sorry about this. As a reminder, I'd encourage you to avoid using any private keys generated by Truffle (or any JS project) for anything with strong security requirements.

In the meantime, I think this is part of the bigger issue that a lot of our dependencies are out of date. Closing this issue as duplicate of https://github.com/trufflesuite/truffle/issues/3986.

**Closed by gnidan** 2022-09-29 17:47 UTC
