### ISSUE TITLE
sourcemap "source index" unspecified in build/contracts

### ISSUE THREAD

**Issue by rocky** [trufflesuite/truffle#1645] opened 2019-01-20 16:08 UTC
## Issue

The "source index" number (3rd field in _s:l:f_ of https://solidity.readthedocs.io/en/v0.5.2/miscellaneous.html#source-mappings ) is unspecified in `build/contracts/*.json`

## Steps to Reproduce

Consider this simple contract as the only contract in a truffle project: 

```solidity
pragma solidity ^0.5.0;

contract PublicStorageArray {
    bytes32[] public states = [bytes32(0)];
}
```

When compiled, here is an excerpt of the `build/contracts/PublicStorageArray.json`:

```json
{
    "contractName": "PublicStorageArray",
    ...
    "sourceMap": "25:75:1:-;...",
    "deployedSourceMap": "25:75:1:-;...",
    ...
    "ast": {
      "nodes": [
        {
        "nodeType": "PragmaDirective",
        "src": "0:23:1"
        } ...
      ]
    }
}
```
Note that the 1 isn't really reconstructable from the rest of the file.

## Expected Behavior

Best in my opinion would be to add a "sources" which refers to all of the contracts that were in the collection compiled, where the 1 position is in fact the file that contans the contract. In other words:

```json
{
    "contractName": "PublicStorageArray",
    "sources": ["/tmp/foo/contracts/Migrations.sol", "/tmp/foo/contracts/PublicStorageArray.sol"],
   ...
}
```

Another less good possibility is change all of the 1's to 0's and assume 0 refers to the "sourcePath" field. A potential problem here is that this assumes that it assmes that code from a contract can come from only one file. (I am not sure that is true and will always be true; e.g. do "imports" change this?) 

Finally, I should note, nothing might be done and would-be consumers of this information would have to adjust ast "src" and source and "sourceMap" reading to ingore the source index field.

## Environment

* Operating System: Ubuntu
* Ethereum client:
* Truffle version: 
```
Truffle v5.0.0-next.24 (core: 5.0.0-beta.2)
Solidity v0.5.0 (solc-js)
Node v10.13.0
```
* npm version (`npm --version`): 6.6.0

## Possible Fix concept. 

In `truffle-workflow-compile` `writeContracts()` add before the call to `saveAll()`: 

```javascript
    const contractNames = Object.keys(contracts).sort();
    const sources = contractNames.map(c => contracts[c].sourcePath);
    for (let c of contractNames) {
	contracts[c].sources = sources;
    }
```
which creates a `sources` field. And in `truffle-contract-schema/index.js` add before "userdoc":
```javascript
  "sources": {},
```

**Comment by gnidan** [comment] 2019-01-22 00:04
Hey @rocky,

Thanks for opening this. Wanted to say first that this is a problem we're extremely aware of and currently looking at solutions for.

Besides that, however, simply including `sources` does not work because Truffle does partial compilations: not all sources are compiled every time, and so there is the risk of mismatch between file index and the current revision of a particular sourcePath.

Feel free to reach out if you'd like me to go into more detail. This particular issue has been an enormous pain-point internally and so I can tell you that you are not alone in this frustration.

**Comment by rocky** [comment] 2019-01-22 00:13
Hmm. Given the complexity of what can be compiled when and the dynamic nature of files getting renamed, added and removed, the only sane solution woiuld be to make sure that each JSON file written is self consistent. 

When a compilation is passed off to `solc-js`, it has a consistent, fixed view of what files it is dealing with. So it seems to me that this list of files needs to be recorded somewhere, in the JSON.  In other words, means adding something like `sources` in each written JSON file, right? 

Please, if I am missing something, have faulty logic, or things are more complex, please do educate me.

**Comment by rocky** [comment] 2019-01-22 02:16
Ok @gnidan will wait to see what you come up with. I hope allowing what's in there to be user/tool configurable is possible. 

Otherwise developers like the MythX folks who use truffle packages as a library will need a separate artifacts folder or files.

**Comment by rocky** [comment] 2019-01-22 02:19
@gnidan I wrote that comment before I looked at the issue - my bad.  I do see you are considering this. Great!

**Comment by gnidan** [comment] 2019-01-22 07:40
@rocky more than only the query side! goal is a viable upgrade path for an improved system of record-keeping. See some wip docs [here](https://trufflesuite.github.io/artifact-updates) if you're curious about the current requirements/design.

**Comment by gnidan** [comment] 2019-03-13 17:49
Closing this as duplicate of #1236. Thanks for raising this @rocky!

**Closed by gnidan** 2019-03-13 17:49 UTC
