### ISSUE TITLE
Syntax error on Node 6, (Node 8 is ok)

### ISSUE THREAD

**Issue by etsangsplk** [trufflesuite/truffle#1053] opened 2018-06-21 17:18 UTC

**Comment by cgewecke** [comment] 2018-06-21 17:21
@etsangsplk Node 6. Please let us know if you're seeing problems with that version.

 Node's LTS is currently 8 and it should work on that as well. 

We've seen a few unusual problems/crashes with the latest Node version (10).

**Comment by cgewecke** [comment] 2018-06-21 20:05
Closing, lmk if you are having trouble with this an I will re-open.

**Comment by etsangsplk** [comment] 2018-06-22 18:04
@cgewecke 
```
nvm install v6.12.2
v6.12.2 is already installed.
Now using node v6.12.2 (npm v3.10.10)
```

```
/usr/lib/node_modules/truffle/build/cli.bundled.js:60353
!function(e,a){ true?module.exports=a():"function"==typeof define&&define.amd?define("ganache",[],a):"object"==typeof exports?exports.ganache=a():e.ganache=a()}(global,function(){return function(e){var a={};function t(c){if(a[c])return a[c].exports;var n=a[c]={i:c,l:!1,exports:{}};return e[c].call(n.exports,n,n.exports,t),n.l=!0,n.exports}return t.m=e,t.c=a,t.d=function(e,a,c){t.o(e,a)||Object.defineProperty(e,a,{configurable:!1,enumerable:!0,get:c})},t.r=function(e){Object.defineProperty(e,"__esModule",{value:!0})},t.n=function(e){var a=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(a,"a",a),a},t.o=function(e,a){return Object.prototype.hasOwnProperty.call(e,a)},t.p="",t.w={},t(t.s=1036)}([function(e,a,t){try{var c=t(1);if("function"!=typeof c.inherits)throw"";e.exports=c.inherits}catch(a){e.exports=t(1021)}},function(e,a){e.exports=__webpack_require__(3)},function(e,a,t){"use strict";var c="function"==typeof Symbol&&"sym

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by cgewecke** [comment] 2018-06-22 18:20
@etsangsplk Thanks!

+ Which the command are you running? 
+ If you `nvm use 8`, does that work? 

Trying to identify what's going wrong here . . .

**Comment by etsangsplk** [comment] 2018-06-22 18:25
@cgewecke 
8 works but because of some project constraint, have to stick with 6
whihc on the website it says it is supporting

**Comment by cgewecke** [comment] 2018-06-22 18:28
@etsangsplk Which truffle version are you using? You're error doesn't have a stack trace so it's hard to tell where the problem is. If you're using a newer version of Truffle you should have a non-webpacked trace.

**Comment by cgewecke** [comment] 2018-06-22 18:30
@etsangsplk Also: which command are you running?

**Comment by etsangsplk** [comment] 2018-06-22 22:31
It just show up right from the start 
truffle 
that is it

**Comment by cgewecke** [comment] 2018-06-22 22:35
@etsangsplk Yes - we've identified the problem and we're going to try fix it. We updated a dependency that uses newer JS syntax and we have to bump it down.

**Comment by gnidan** [comment] 2018-06-25 19:17
@etsangsplk what are the constraints that force Node 6 for you?

For Truffle v5, we are currently planning to drop support for Node 6, but I'd like to know more about why users might be constrained. Node 8 is now LTS, mind you.

**Comment by etsangsplk** [comment] 2018-06-25 21:10
Using truffle as api. Node version released with internal project is pinned to that node 6.  There is nothing I can do about that part.

**Comment by cgewecke** [comment] 2018-06-27 18:53
@etsangsplk This should be fixed in `4.1.13`. Please ping if you continue have problems with it.

**Closed by cgewecke** 2018-06-27 18:53 UTC
Labels: in progress

**Comment by etsangsplk** [comment] 2018-06-28 17:46
Looks like you are using async which is not available in node6?

**Comment by cgewecke** [comment] 2018-06-28 17:55
@etsangsplk Are you still seeing this error in `4.1.13`?  We downgraded the dependency that used async (in one of its dependencies) and now have Truffle's unit tests running against Node 6 in CI where it seems to be [passing](https://travis-ci.org/trufflesuite/truffle/builds/397482993).

**Comment by etsangsplk** [comment] 2018-06-28 18:02
```Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)
~/Projects/splunk-di/packages/splunk_app_di/src/main/resources/splunk/bin$ truffle test
/home/rmoore/Projects/splunk-di/packages/splunk_app_di/src/main/resources/splunk/bin/truffle-config.js:13
   );
   ^

SyntaxError: Unexpected token )
   at createScript (vm.js:56:10)
   at Object.runInThisContext (vm.js:97:10)
   at Module._compile (module.js:542:28)
   at Object.Module._extensions..js (module.js:579:10)
   at Module.load (module.js:487:32)
   at tryModuleLoad (module.js:446:12)
   at Function.Module._load (module.js:438:3)
   at Module.require (module.js:497:17)
   at require (internal/module.js:20:19)
   at Function.Config.load (/home/rmoore/.nvm/versions/node/v6.12.2/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:254:1)
   at Function.Config.detect (/home/rmoore/.nvm/versions/node/v6.12.2/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:243:1)
   at Object.run (/home/rmoore/.nvm/versions/node/v6.12.2/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/test.js:17:1)
   at Command.run (/home/rmoore/.nvm/versions/node/v6.12.2/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:101:1)
   at Object.<anonymous> (/home/rmoore/.nvm/versions/node/v6.12.2/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:16:1)
   at __webpack_require__ (/home/rmoore/.nvm/versions/node/v6.12.2/lib/node_modules/truffle/build/webpack:/webpack/bootstrap f3b0126a12cf2ee05457:19:1)
   at /home/rmoore/.nvm/versions/node/v6.12.2/lib/node_modules/truffle/build/webpack:/webpack/bootstrap f3b0126a12cf2ee05457:65:1
   at Object.<anonymous> (/home/rmoore/.nvm/versions/node/v6.12.2/lib/node_modules/truffle/build/cli.bundled.js:71:10)
   at Module._compile (module.js:570:32)
   at Object.Module._extensions..js (module.js:579:10)
   at Module.load (module.js:487:32)
   at tryModuleLoad (module.js:446:12)
   at Function.Module._load (module.js:438:3)
   at Module.runMain (module.js:604:10)
   at run (bootstrap_node.js:383:7)
   at startup (bootstrap_node.js:149:9)
   at bootstrap_node.js:496:3
```

**Comment by cgewecke** [comment] 2018-06-28 19:32
@etsangsplk I need a reproduction case because locally I see this:
```shell
code cgewecke$ mkdir metacoin
code cgewecke$ cd metacoin
metacoin cgewecke$ nvm use 6
Now using node v6.14.3 (npm v3.10.10)
Users-MacBook-Air:metacoin cgewecke$ truffle version
Truffle v4.1.13 (core: 4.1.13)   # <-- Which truffle version are you using?
Solidity v0.4.24 (solc-js)
metacoin cgewecke$ truffle unbox metacoin
Downloading...
Unpacking...
Setting up...
Unbox successful. Sweet!

Commands:

  Compile contracts: truffle compile
  Migrate contracts: truffle migrate
  Test contracts:    truffle test
metacoin cgewecke$ truffle test
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./test/TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...


  TestMetacoin
    ✓ testInitialBalanceUsingDeployedContract (80ms)
    ✓ testInitialBalanceWithNewMetaCoin (60ms)

  Contract: MetaCoin
    ✓ should put 10000 MetaCoin in the first account
    ✓ should call a function that depends on a linked library (51ms)
    ✓ should send coin correctly (109ms)


  5 passing (1s)

metacoin cgewecke$ 
```

**Comment by cgewecke** [comment] 2018-06-28 19:33
@etsangsplk If you are running `ganache-cli` separately, you will need to downgrade to `6.1.0-beta.5`

**Comment by etsangsplk** [comment] 2018-06-29 18:48
Doubt if any of those tests are hitting the other libraries like eth-block-tracker.
For example for yarn.lock, these libraries are all using async
```
https://github.com/trufflesuite/truffle/blob/62e1554d86ccb91b861e494e790a67251c77d494/yarn.lock#L3453
```

**Comment by cgewecke** [comment] 2018-06-29 20:06
@etsangsplk What's your crash?

**Comment by cgewecke** [comment] 2018-06-29 20:43
It looks like it might be coming from `hd-wallet-provider`? 
```
at require (internal/module.js:20:19)
    at Object.<anonymous> (/src/main/resources/bin/node_modules/truffle-hdwallet-provider/index.js:3:22)
    at Module._compile (module.js:570:32)
```
Could you try the following:
+ Make sure your providers are wrapped in a function closure in your config as shown in the docs [here](https://truffleframework.com/docs/advanced/configuration#providers). This will stop them from automatically loading when truffle pulls the config in.
+ Pin `truffle-hd-walletprovider` to `0.0.3`, which should be Node 6 safe. (We had to upgrade that recently because `npm audit` was throwing security warnings, and it's a wallet).

**Comment by etsangsplk** [comment] 2018-06-29 21:09
@cgewecke 

this solves it: truffle-hd-walletprovider to 0.0.3,

**Comment by cgewecke** [comment] 2018-06-29 21:47
Fantastic, thank you @etsangsplk.
