### ISSUE TITLE
NPM version of truffle has solc 0.4.15

### ISSUE THREAD

**Issue by elie222** [trufflesuite/truffle#722] opened 2017-12-16 19:09 UTC
NPM version of truffle has solc 0.4.15 and needs to be updated to be like this package that has 0.4.18.

**Comment by cgewecke** [comment] 2018-01-12 21:26
Hi @elie222. I can't reproduce this issue. When I install truffle globally and run `truffle version` I see:
```
Truffle v4.0.4 (core: 4.0.4)
Solidity v0.4.18 (solc-js)
```
and I'm able to compile contracts that use `pragma solidity ^0.4.18`. Are you still seeing this problem?

**Comment by elie222** [comment] 2018-01-14 15:02
It's been a few weeks since I posted this. I don't remember how I got around this issue. A manual install in the correct place for solc or a reinstall. We've been working fine the past few weeks.

**Comment by cgewecke** [comment] 2018-01-16 02:20
Thanks @elie222! Closing.

**Closed by cgewecke** 2018-01-16 02:20 UTC
