### ISSUE TITLE
Difference in behavior between absolute import paths starting with multiple slashes and ones starting with a single one

### ISSUE THREAD

**Issue by cameel** [trufflesuite/truffle#4165] opened 2021-07-08 14:23 UTC
## Issue
As far as I can tell, Truffle no longer resolves absolute paths in imports (i.e. `/a/b/c.sol`) - it simply does not add the file to compiler's JSON input, which results in a compilation error. This is perhaps not the best way to report it (an explicit error saying that absolute paths are not supported would be better) but overall dropping support for them is a good thing in the light of #4119.

The problem is that a single leading slash is not the only way to specify an absolute path. `//a/b/c.sol` or `///a/b/c.sol` still results in an absolute path in compiler's input.

I haven't checked this on Windows but `\\` or `C:\\` might be producing similar results. Note that paths starting with `//` (and `\\` on Windows) are actually [UNC paths](https://en.wikipedia.org/wiki/Path_(computing)#UNC). On Windows they are used for network shares while on Unix-like systems they often work like absolute paths, though they're still considered different - `//`, unlike `///` or more slashes is not squashed into a single `/` by shell.

## Steps to Reproduce
```bash
cd /tmp/
mkdir truffle-test/
cd truffle-test/
npm install truffle
npx truffle init
echo 'module.exports.compilers.solc.version = "0.8.6";' >> truffle-config.js

echo 'contract C {}' > contracts/C.sol
echo 'import "//tmp/truffle-test/contracts/C.sol";' > contracts/D.sol
echo 'import "///tmp/truffle-test/contracts/C.sol";' > contracts/E.sol
npx truffle compile
```
## Actual Results
```
> Artifacts written to /tmp/truffle-test/build/contracts
> Compiled successfully using:
   - solc: 0.8.6+commit.11564f7e.Emscripten.clang


> Duplicate contract names found for C.
> This can cause errors and unknown behavior. Please rename one of your contracts.

> Duplicate contract names found for C.
> This can cause errors and unknown behavior. Please rename one of your contracts.
```

The `sources` dict in the JSON input contains these entries:
```json
"project:/contracts/C.sol": { "content": "contract C {}\n" },
"project:/contracts/D.sol": { "content": "import \"//tmp/truffle-test/contracts/C.sol\";\n" },
"project:/contracts/E.sol": { "content": "import \"///tmp/truffle-test/contracts/C.sol\";\n" },
"//tmp/truffle-test/contracts/C.sol": { "content": "contract C {}\n" },
"///tmp/truffle-test/contracts/C.sol": { "content": "contract C {}\n" }
```

## Expected Behavior
Paths starting with more than one slash should be disallowed just like paths with a single slash:
```bash
echo 'interface C {}' > contracts/C.sol
echo 'import "/tmp/truffle-test/contracts/C.sol";' > contracts/D.sol
npx truffle compile
```
```solidity
ParserError: Source "/tmp/truffle-test/contracts/C.sol" not found: File import callback not supported
 --> project:/contracts/D.sol:1:1:
  |
1 | import "/tmp/truffle-test/contracts/C.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compilation failed. See above.
```

## Environment

* Operating System: Arch Linux
* Truffle version: both `5.3.14` and current `develop` (abfb3646eea9d57e0a6f9186c12bb51680c181d8)
* node version: `v16.4.2`
* npm version: `7.17.0`

**Comment by haltman-at** [comment] 2021-08-02 22:07
Huh, that's certainly odd.  Thanks for the report, I'll have to go see what's causing this.  I can reproduce the problem on latest develop, so this is definitely happening...

**Comment by haltman-at** [comment] 2021-08-02 22:15
Oh, I think I know why this is happening.

The problem is that absolute paths in imports *aren't* actually disallowed, per se.  Rather, they're just *effectively* disallowed because we transform paths to use `project:/` before feeding them to the compiler.  Something starting with a double-slash wouldn't be caught by that transformation, and so would get fed in with its double-slash path.

I guess we could just filter out any absolute paths that don't start with the appropriate string (the project directory)?  That should do the trick, I think...

**Comment by cameel** [comment] 2021-08-02 22:23
Does the transformation handle Windows absolute paths? Stuff like `C:\path\file.sol`, `C:/path/file.sol` or `C:///path/file.sol`? I could not easily test the Windows behavior (I only have access to a Windows VM in CI and it's a pain to use the shell in that) so it might be worth checking.

**Comment by haltman-at** [comment] 2021-08-02 22:24
I'm pretty sure that should already be handled, yes.  But @cds-amal is working on adding some Windows testing and fixing remaining Windows bugs though so he may want to take a look at that...

**Comment by haltman-at** [comment] 2021-08-02 23:58
(More specifically, the PR where @cds-amal is working on Windows stuff is #4206.)

**Comment by fainashalts** [comment] 2021-09-11 00:26
https://github.com/trufflesuite/truffle/pull/4216 is now live -- can this issue be closed, or is there more to do? Thanks!

**Comment by haltman-at** [comment] 2021-09-11 02:31
I'm going to go ahead and just close this per normal process unless @cameel objects.

**Closed by haltman-at** 2021-09-11 02:31 UTC
Labels: needs investigated
