### ISSUE TITLE
Win 10 Install error

### ISSUE THREAD

**Issue by rfikki** [trufflesuite/truffle#411] opened 2017-05-23 03:25 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.
https://gist.github.com/rfikki/5554651b135341ac044293556ddba92c
## Steps to Reproduce
Install latest version
Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior
clean error free install
What you expected to happen.

## Actual Results
https://gist.github.com/rfikki/5554651b135341ac044293556ddba92c
What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System:  Win 10
* Truffle version: 3.2.4
* Ethereum client: geth
* node version: node v7.4.0
* npm version: npm  v4.2.0

**Comment by ripper234** [comment] 2017-05-23 16:20
+1 I'm having the same issue

**Comment by bvrooman** [comment] 2017-05-26 01:31
For one, it looks like the dependency, fs-ext, is currently failing on Windows builds: https://ci.appveyor.com/project/baudehlo/node-fs-ext/branch/master. It seems that it is currently impossible to use Truffle on Windows as long as this dependency is failing.

**Comment by ripper234** [comment] 2017-05-26 12:50
Seems to be relatively easy to resolve then.

1. fs-ext seems to be used mostly for ```copySync``` and ```readFileSync```. I opened [an issue](https://github.com/baudehlo/node-fs-ext/issues/69) on fs-ext repo, not sure how easy it is to resolve, but at least as a workaround I believe (correct me if wrong) that fs-ext functionality can be manually implemented instead of adding it as a dependency.

2. execSync module seems to be unneeded, as
> both iojs and node.js v0.12 have execSync function

**Comment by bvrooman** [comment] 2017-05-27 22:52
I agree with the solutions you propose - the dependencies could be replaced with the alternatives you suggest. The problem, unfortunately, seems that they are not dependencies of Truffle itself, but dependencies of dependencies. I will put together a list of Truffle dependencies that use these problematic libraries. However, short of replacing these dependencies, I don't have a good action plan to propose at the moment.

**Comment by bvrooman** [comment] 2017-05-27 23:30
Here's the result of a quick analysis on Truffle dependencies: 

**Dependent on fs-ext**
lock-me (dependencies and optionalDependencies)

**Dependent on execSync**
codecov@1.0.1

**Dependent on codecov@1.0.1**
request
ignore
shelljs
node-fetch
regenerate
babylon
aegir
interface-datastore

The funny thing is that the codecov main branch is at 2.2.0. The execSync library was removed from its dependencies a while ago. Unfortunately, a lot of libraries within the dependency tree still use 1.0.1.

**Comment by ripper234** [comment] 2017-05-28 02:08
So, how about we fork codecov & lock-me and make the fixes there? (And push upstream as well)
That should do it, no?

**Comment by bvrooman** [comment] 2017-05-28 14:46
I think that _should_ do it, so I'm looking into that now (but I don't know if that covers all the errors in the installation log).

I forked lock-me to see what would be involved in replacing fs-ext with a Windows compatible option. However, I'm noticing a discrepancy.  In the lock-me library, package.json defines fs-ext as **only** an optional dependency. However, it when we install Truffle and navigate to truffle/node_modules/lock-me/package.json, fs-ext is listed under **both** dependencies and optional dependencies. I can actually install lock-me locally without problem because installation skips the optional dependency fs-ext! When installing Truffle, however, lock-me installation seems to think fs-ext is mandatory.

Perhaps this is a result of some npm behaviour that I'm not aware of. Do you have any ideas why it might want to install the optional dependencies? We still might be able to get around this problem by replacing fs-ext entirely, so I'll continue looking at that option.

**Comment by ProphetDaniel** [comment] 2017-05-28 16:09
Well, to get rid of that same problem, we installed truffle version 3.2.1 with the following command: 
```npm install -g truffle@3.2.1```

@rfikki and @ripper234, please let me know if that version installs in windows 10 for you too. If it is so we can find out the latest truffle version that does install in win 10 and git compare with the subsequent where it doesn't install anylonger to help identifying the problem.

**Comment by ripper234** [comment] 2017-05-28 19:39
Installs perfectly 😎 

Added a PR to include the workaround in the readme. #419

**Comment by bvrooman** [comment] 2017-05-29 01:12
Version 3.2.1 appears to still work, so that's good news. 
As you suggest, @ProphetDaniel, a git compare could reveal what the issue is.

**Comment by ProphetDaniel** [comment] 2017-05-29 17:24
> Installs perfectly :sunglasses:

That is great @ripper234.

Latest version installation that still worked in my windows 10 was 3.2.2. The problem started to happen on truffle 3.2.3. So this is something related to windows 10 and with truffle starting with version 3.2.3.

That means @bvrooman , git comparing truffle 3.2.3 with 3.2.2 should reveal the problematic change.

Linux OS
Both latest truffle 3.2.4 and the previous 3.2.3 installations work in my KDE neon linux OS.

**Comment by bvrooman** [comment] 2017-05-30 03:24
I'll try comparing those versions and see what I find. Unfortunately, I have a lot on my plate at the moment and I might not be able to get around to it just yet. That said, if anyone else wants to have a go at it, I won't stop you ;)

**Comment by ripper234** [comment] 2017-05-30 08:15
I confirm that version 3.2.2 works for me as well.

**Comment by rfikki** [comment] 2017-06-04 12:30
Yes, I mentioned in the truffle Gitter channel awhile back that 3.2.2 works the problem started with version 3.2.3 truffle.

**Comment by GitSpree23** [comment] 2017-06-04 12:59
Okae. Well, I got it done after installing windows-build-updates in my Win
10.
I suppose there's no fix for Ubuntu 16.10 yet?

**Comment by tcoulter** [comment] 2017-06-05 21:21
Hi all. A new beta has been pushed out that should fix this issue. Details in the blog post [here](http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past). Can you give it a shot and report back?

**Comment by bvrooman** [comment] 2017-06-05 22:00
@tcoulter Great, I'll give that a shot tonight and tell you all how it goes. I like the direction you are taking the dependency management, based on what I read in your post.

**Comment by ProphetDaniel** [comment] 2017-06-06 01:13
It installed like a breeze in my windows 10 setup with `npm install truffle@beta`. I tested main functionalities like init, compile, migrate and test and it looks alright.

**Comment by bvrooman** [comment] 2017-06-06 03:03
Installing the beta version appears to work well. I was able to installing with `npm uninstall truffle` followed by `npm install truffle@beta`.
I have a couple comments:
- The beta version appears to introduce some breaking changes. For example, the following no longer works: `var Compiler = require('truffle/lib/contracts')` . Has this been replaced by truffle-compiler? Will this be the same for things like `require('truffle/lib/commands/migrate')`?
- I forked Truffle and tried `npm install`. On Windows 10, this still fails with the same log as posted in this issue.

**Comment by GitSpree23** [comment] 2017-06-06 06:09
Installed using `npm install -g truffle@beta` on 32-bit Win 10. Tried out truffle init, compile, migrate and test. Works fine.

But then I tried `truffle init webpack` on another dir, and it shows the following error:

> Error: Cannot find module "."
>     at webpackMissingModule (C:\Users\user\AppData\Roaming\npm\node_modules\truf                                                                                                                fle\build\cli.bundled.js:209703:61)
>     at C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.                                                                                                                js:209703:139
>     at <anonymous>

But some initialization has been made as the folder now contains:

> app/  contracts/  migrations/  package.json  README.md  test/  truffle.js  webpack.config.js

Subsequently, running compile or migrate says:

> Error: Cannot find module 'babel-register'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\Users\user\uffle\truffle.js:2:1)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)

**Comment by johnmiroki** [comment] 2017-06-08 06:02
npm install -g truffle failed on windows 10
got error when wrtc is being installed. Seems msbuild related. scratched my head for hours after midnight, until I stumbled upon this post

npm install -g truffle@3.2.1 and npm install -g truffle@3.2.2 both are successful.

Thanks.

**Comment by rfikki** [comment] 2017-06-09 20:44
$ truffle init webpack
Downloading project...
Installing dependencies...
Error: Cannot find module "."
    at webpackMissingModule (C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:209703:61)
    at C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:209703:139

**Comment by tcoulter** [comment] 2017-07-13 17:08
Hi all. These issues *should* be fixed in our latest version of Truffle, as the beta has now been pushed to production.

@bvrooman Yes, that is a breaking change. You should now use the `truffle-core` repository instead if you need that functionality. The `truffle` repository has changed to become an distribution/bundled cli package and not a development package. 

@rfikki That issue should also be fixed. Also, consider [Truffle Boxes](http://truffleframework.com/boxes/). 

If you all run into more issues, please open a new ticket and we'll address each issue individually. Thanks!

**Closed by tcoulter** 2017-07-13 17:08 UTC
