### ISSUE TITLE
Unable to catch exception when making an asynchronous call in a test in Truffle 4.0.3

### ISSUE THREAD

**Issue by ripern** [trufflesuite/truffle#738] opened 2018-01-05 20:39 UTC
## Issue
Unable to catch exception when making an asynchronous call in a test in 4.0.3/4 but works in 4.0.1

## Steps to Reproduce
truffle test

## Expected Behavior
It should catch the exception

## Actual Results
A huge error message

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

The test works in truffle 4.0.1 but not in 4.0.3/4

The test code:
`const expectThrow = async promise => {
  try {
    console.log("Before promise");
    await promise;
    console.log("After promise");
  } catch (error) {
    console.log("Entering catch");
    const invalidOpcode = error.message.search('invalid opcode') >= 0;
    const outOfGas = error.message.search('out of gas') >= 0;
    const revert = error.message.search('revert') >= 0;
    assert(
      invalidOpcode || outOfGas || revert,
      'Expected throw, got \'' + error + '\' instead',
    );
    console.log("Exiting catch, returning...")
    return;
  }
  console.log("After catch, shouldn't get here");
  assert.fail('Expected throw not received');
};`

The test call:
`it('should not allow pausing from a non-owner account', async function () {
        await expectThrow(instance.setPaused(true, { from: account1 }));
    });`

The error:
`/Users/xyz/.npm-packages/lib/node_modules/truffle/build/cli.bundled.js:128709
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIR

Error: [ethjs-rpc] rpc error with payload {"id":1211807879902,"jsonrpc":"2.0","params":[{"from":"0x1a3dc992570ac206f4fc02992006d2b1ede07582","gas":"0x4c4b40","to":"0x5f59f941fb6fd4368be556b4c2c77e79ab353582","data":"0x3ccfd60b"}],"method":"eth_sendTransaction"} {"message":"VM Exception while processing transaction: revert","code":-32000}
    at /Users/xyz/git/demo/node_modules/ethjs-rpc/lib/index.js:56:28
    at XMLHttpRequest.request.onreadystatechange (/Users/xyz/git/demo/node_modules/ethjs-provider-http/lib/index.js:91:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/xyz/git/demo/node_modules/ethjs-provider-http/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/xyz/git/demo/node_modules/ethjs-provider-http/node_modules/xhr2/lib/xhr2.js:353:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/xyz/git/demo/node_modules/ethjs-provider-http/node_modules/xhr2/lib/xhr2.js:507:12)
    at IncomingMessage.<anonymous> (/Users/xyz/git/demo/node_modules/ethjs-provider-http/node_modules/xhr2/lib/xhr2.js:468:24)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

## Environment

* Operating System: macOS Sierra 10.12.6 (same problem on Windows 10)
* Truffle version: 4.0.3
* Ethereum client: -
* node version: 9.2.1
* npm version: 5.5.1

**Comment by cgewecke** [comment] 2018-01-12 02:39
Hi @ripern! Unfortunately I'm not able to reproduce this. It looks like you're using `ethjs-rpc` to wrap your method calls and I see some [activity](https://github.com/ethjs/ethjs-rpc/pull/2) from the beginning of December over there that specifically touches the error message code. 

Could you debug by running?
```javascript
console.log(error)  // Does this output a string?
error.toString().search('revert') // Does this work?
```

**Comment by cgewecke** [comment] 2018-01-16 02:12
cc: @ripern Are you still having trouble with this?

**Comment by cgewecke** [comment] 2018-01-24 02:35
@ripern Closing for house keeping and because it's been a while since we looked at this. Please re-open if this is still happening for you. Thanks!

**Closed by cgewecke** 2018-01-24 02:35 UTC
