### ISSUE TITLE
The contract code couldn't be stored, please check your gas amount during successful deployment

### ISSUE THREAD

**Issue by Mc01** [trufflesuite/truffle#558] opened 2017-09-05 11:32 UTC
## Issue

After running `truffle migrate` for mainnet network i've got:

```
Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
```

On etherscan i see:
```
0xe728474cc7b4bf31749fb6b5f4d377f58afb4a2bf1abe9283b4c03ceb7d8619f | (pending) | 32 secs ago | 0x71544d4d42daab49d9f634940d3164be25ba03cc | OUT | Contract Creation | 0 Ether | (pending)
```

Transaction completes successfully: https://etherscan.io/tx/0xe728474cc7b4bf31749fb6b5f4d377f58afb4a2bf1abe9283b4c03ceb7d8619f
Contract is created: https://etherscan.io/address/0x1d3d6458065f3cd778541f0676db6837be9252ec

Its regular issue we have with truffle framework...

**Comment by charltonh** [comment] 2017-09-08 15:51
Experienced this issue trying to run truffle test on rinkeby testnet from gentoo linux.

I've discovered that Assert.sol generates an EVM binary that is just too big to be deployed without it choking. I ended up manually editing Assert.sol and taking out a couple of funcs that I wasn't using.

Now the EVM binary is slightly smaller and deploys on rinkeby, and my tests complete successfully.

**Comment by dylanseago** [comment] 2017-10-31 15:53
Related: https://github.com/trufflesuite/truffle-migrate/issues/15

**Comment by 7flash** [comment] 2017-12-21 17:13
The same issue. That's why I have deployed a lot of pointless Migrations.sol
```
	config.networks["mainnet"] = {
		provider: new HDWalletProvider(mnemonic, "https://mainnet.infura.io/"+infuraToken),
		network_id: 1,
		gas: 4e6,
		gasPrice: 2e10
	};
```

**Comment by delormemarie240** [comment] 2017-12-22 13:43
Hello,
Is there any update on this issue ? I have same problem, an it's very annoying -__- I do not find any solution on other forum

**Comment by charltonh** [comment] 2017-12-22 18:13
Try the latest beta release of truffle, or try finding the Assert.sol file in truffle and manually editing it to take out a couple of functions that you don't need.

**Comment by 7flash** [comment] 2017-12-23 14:36
@delormemarie240 Check https://github.com/ethereum/web3.js/pull/1243
You can fix this line manually: https://github.com/ethereum/web3.js/pull/1243/commits/e7d7d80c08dd9014b7860a80096577c2c956e50d#diff-430c9c02bef6a7661c5b4e7b34142f7cL120

**Comment by liyihe96** [comment] 2018-01-13 05:49
@7flash Hi, I used yarn to download dependencies and I tried your suggestion by changing the line you mentioned in `node_submodules/web3` and `node_submodules/web3-engine-provider`, but still didn't work. The error is either `check your gas amount` or `exceeds 240 seconds`. Could you please help? Thanks so much!

**Comment by liyihe96** [comment] 2018-01-13 05:53
@charltonh Thanks for the info! Could you please specify which functions are not used and safe to delete?

**Comment by charltonh** [comment] 2018-01-13 08:13
@liyihe96 Depends on which functions you are using in your program.  I took out just a couple small functions that I knew I'd never use, which amounted to just a few lines.  Then the Assert.sol compiled code was able to 'fit' and it deployed successfully.

**Comment by 7flash** [comment] 2018-01-13 09:21
@liyihe96 `exceeds 240 seconds` - Probably you should just raise gas price up to 50 GWei for mainnet.

**Comment by max-l** [comment] 2018-01-30 03:20
Getting the same issue, I have a contract that deploys on Ganache (truffle test),
the contract implements the EIP20Interface, if I declare "contract TTC is EIP20Interface"
in the contract, I get the error.


```
truffle migrate 
Compiling ./contracts/EIP20Interface.sol...
Compiling ./contracts/TTC.sol...
Writing artifacts to ./build/contracts

Using network 'development'.

Running migration: 2_deploy_contracts.js
  Deploying TTC...
  ... 0x76abb97563016f18eb1eeedeab4ddf3d7da760a7b2669af96a3f1ceabd8224c6
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:328412:46)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:37990:25
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:330356:9
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:176198:11
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:326008:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:329052:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176427:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176717:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176872:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176832:24)


```

**Comment by max-l** [comment] 2018-01-31 00:05
@nickjm this is my migration script :

```
var TTC = artifacts.require("./TTC.sol");
var EIP20Interface = artifacts.require("./EIP20Interface.sol");

module.exports = function(deployer) {
  deployer.deploy(EIP20Interface);
  deployer.link(EIP20Interface, TTC);
  deployer.deploy(TTC);
};

```

and my contract: 
```

contract TTC is EIP20Interface {
...
```
The "The contract code couldn't be stored, please check your gas amount." seems to apply to the deployment  of EIP20Interface 

This is a test settup, where can I increase the gas amount for the store transaction to succeed ? 

I am using Ganache and the account doing the deploy starts with 100 ETH, is that not enough, or is the error message about another gas treshold being busted ?

**Comment by mahendra-panchal** [comment] 2018-04-03 19:58
If any one still facing problem 

simply set constructor as payable.

**Comment by jbarros35** [comment] 2018-04-06 14:46
not work for me see my sol file please

pragma solidity ^0.4.21;

    /**
    * Example script for the Ethereum development walkthrough
    */

contract Wrestling {
    /**
    * Our wrestlers
    */
	address public wrestler1;
	address public wrestler2;

	bool public wrestler1Played;
	bool public wrestler2Played;

	uint private wrestler1Deposit;
	uint private wrestler2Deposit;

	bool public gameFinished; 
    address public theWinner;
    uint gains;

    /**
    * The logs that will be emitted in every step of the contract's life cycle
    */
	event WrestlingStartsEvent(address wrestler1, address wrestler2);
	event EndOfRoundEvent(uint wrestler1Deposit, uint wrestler2Deposit);
	event EndOfWrestlingEvent(address winner, uint gains);

    /**
    * The contract constructor
    */
	function Wrestling() public payable {
		wrestler1 = msg.sender;
	}

    /**
    * A second wrestler can register as an opponent
    */
	function registerAsAnOpponent() public {
        require(wrestler2 == address(0));

        wrestler2 = msg.sender;

        WrestlingStartsEvent(wrestler1, wrestler2);
    }

    /**
    * Every round a player can put a sum of ether, if one of the player put in twice or 
    * more the money (in total) than the other did, the first wins 
    */
    function wrestle() public payable {
    	require(!gameFinished && (msg.sender == wrestler1 || msg.sender == wrestler2));

    	if(msg.sender == wrestler1) {
    		require(wrestler1Played == false);
    		wrestler1Played = true;
    		wrestler1Deposit = wrestler1Deposit + msg.value;
    	} else { 
    		require(wrestler2Played == false);
    		wrestler2Played = true;
    		wrestler2Deposit = wrestler2Deposit + msg.value;
    	}
    	if(wrestler1Played && wrestler2Played) {
    		if(wrestler1Deposit >= wrestler2Deposit * 2) {
    			endOfGame(wrestler1);
    		} else if (wrestler2Deposit >= wrestler1Deposit * 2) {
    			endOfGame(wrestler2);
    		} else {
                endOfRound();
    		}
    	}
    }

    function endOfRound() internal {
    	wrestler1Played = false;
    	wrestler2Played = false;

    	EndOfRoundEvent(wrestler1Deposit, wrestler2Deposit);
    }

    function endOfGame(address winner) internal {
        gameFinished = true;
        theWinner = winner;

        gains = wrestler1Deposit + wrestler2Deposit;
        EndOfWrestlingEvent(winner, gains);
    }

    /**
    * The withdraw function, following the withdraw pattern shown and explained here: 
    * http://solidity.readthedocs.io/en/develop/common-patterns.html#withdrawal-from-contracts
    */
    function withdraw() public {
        require(gameFinished && theWinner == msg.sender);

        uint amount = gains;

        gains = 0;
        msg.sender.transfer(amount);
    }
}

**Comment by itinance** [comment] 2018-04-29 14:01
Any news on this?

**Comment by piggyman007** [comment] 2018-07-30 07:41
@SumitRajpal 

thanks, your working around works

**Comment by gnidan** [comment] 2019-01-09 18:51
Closing this as duplicate of #522.

**Closed by gnidan** 2019-01-09 18:51 UTC
Labels: Migrations, bug
