### ISSUE TITLE
Get SyntaxError: Unexpected identifier when migrate contract

### ISSUE THREAD

**Issue by hiimnhan** [trufflesuite/truffle#3746] opened 2021-01-28 15:15 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

SyntaxError: Unexpected identifier

## Steps to Reproduce

running truffle migrate in terminal

## Expected Behavior

migrate successfully
## Actual Results

```
/Users/nhanncv/Desktop/ARAM2021/bs-blockchain/contracts/Bean.sol:1
pragma solidity ^0.4.24;
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:54:1)
    at /Users/nhanncv/Desktop/ARAM2021/bs-blockchain/migrations/2_deploy_contracts.js:1:14
    at Script.runInContext (vm.js:143:18)
    at Script.runInNewContext (vm.js:148:17)
    at Object.file (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:92:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/migration.js:43:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/migration.js:167:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:148:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:253:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:218:1
```
## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):v5.1.27
* node version (`node --version`):v14.5.4
* npm version (`npm --version`): v6.14.10

**Comment by davidmurdoch** [comment] 2021-02-03 18:43
Hey @hiimnhan, thanks for opening this issue! It looks like you are trying to import the `.sol` file in your javascript/typescript. If you are doing something like `require("../contracts/Bean.sol")` can you try `artifacts.require("Bean")` instead? If that's not the issue could you provide some more information so we can try to reproduce this locally?

**Comment by davidmurdoch** [comment] 2021-04-28 18:35
Closing for issue maintenance.

**Closed by davidmurdoch** 2021-04-28 18:35 UTC
