### ISSUE TITLE
Truffle not installing on Mac via Node

### ISSUE THREAD

**Issue by ericlam1114** [trufflesuite/truffle#4306] opened 2021-09-15 19:56 UTC
How do I get Truffle to install it keeps failing?

I uninstalled and reinstalled and still get the same errors. at the end it always gives me a bash command not found type error. 

Screenshot below. 

<img width="1357" alt="Screen Shot 2021-09-15 at 11 37 25 AM" src="https://user-images.githubusercontent.com/83894250/133500684-54c6f829-b27d-4a31-ab56-696bff2b6b2c.png">

Eric

**Comment by eggplantzzz** [comment] 2021-09-15 20:41
Hey @ericlam1114, what version of npm and Node are you using? Currently we think there may be something up with npm version 7. So if you are using 7, maybe try downgrading to 6. Let me know how it goes if you try it!

**Comment by ericlam1114** [comment] 2021-09-15 20:53
Hi @eggplantzzz I am using node v14.16.1 and npm v6.14.12

Does this change anything?

**Comment by ericlam1114** [comment] 2021-09-15 22:20
"npx truffle" in the terminal brings up the command options. should i be interacting with truffle via npx instead of npm?

**Comment by fainashalts** [comment] 2021-09-22 17:33
Hi @ericlam1114 can you try installing the latest Truffle version and testing again? I am unable to reproduce this error using the versions provided so I just want to make sure you are still experiencing this issue. Can you also tell us what Mac you are using? We have seen some issues with the new M1 so I just want to be sure how best to categorize what you're reporting. Thanks so much!

**Comment by eggplantzzz** [comment] 2021-10-03 16:55
Hey @ericlam1114, sorry for the delay in getting back to you! So this is not really a Truffle problem but rather it looks like there might be something up with your npm installation. You need to make sure that you have your npm bin directory in your $PATH variable. The $PATH variable contains all the directories that bash will look in for executables. I would recommend re-installing npm using nvm which is a Node version manager. This is what npm recommends and it should add to your $PATH. You can find an npm article that will tell you how you might go about doing this [here](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally). 

Give it a try and let me know how it goes!

**Comment by ericlam1114** [comment] 2021-10-06 17:33
Hi @eggplantzzz thanks for your reply. This might be a noob question on my end but what exactly is a $PATH variable? I have a mac and am not sure what that is? 

I'm trying to research it and have not found a clear answer.

**Comment by eggplantzzz** [comment] 2021-10-11 11:06
The first message means it can't find a configuration file for the shell you are using. Looks like it is bash, you could try creating it. Go ahead and just run `touch ~./bashrc`. Then try that script again.

**Comment by ericlam1114** [comment] 2021-10-18 18:42
Thank you @cds-amal and @eggplantzzz 

So I did touch ~/.bashrc . No error messages which seems like a good thing. 

I installed nvm manager 

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

then created new folder on desktop called "Folder"

I did npm install -g truffle

Then I navigate to the folder I created on my desktop and enter:

npx truffle

That shows a loading bar in the terminal and appears to be setting up something in the folder

When finished it says Truffle v5.4.15 - a development framework for Ethereum and lists commands below. (build, compile, run, etc.)

I then open the folder I did npx truffle in and nothing is there. in my terminal i do:

truffle init

it says "-bash: truffle: command not found"

This is the same error I was having before. Am I missing something? Still doesn't seem to be working. 

What do you think?

**Comment by haltman-at** [comment] 2021-12-22 19:28
@ericlam1114 Any updates on this?  Thanks!

**Comment by ericlam1114** [comment] 2021-12-22 21:25
I got a new macbook pro and started fresh. Didn’t move any of my old files onto the computer. Downloaded vscode etc. Everything works perfectly. I probably had things installed in weird places on my old computer. Thank you everyone for your help.

**Comment by haltman-at** [comment] 2021-12-23 00:46
OK, I'm going to go ahead and close this then if you don't mind!  Thanks again!

**Closed by haltman-at** 2021-12-23 00:46 UTC

**Comment by insivika** [comment] 2021-12-24 17:53
Hello I've got the same issue and would like to avoid having to buy a new mac to get this working lol

**Comment by kwakyebrilliant** [comment] 2022-09-30 13:40
Use brew install truffle

**Comment by cds-amal** [comment] 2022-09-30 14:24
@kwakyebrilliant, Please do not install Truffle from brew, we have no idea about that project and cannot vouch for it.
