### ISSUE TITLE
 Test fails at beforeAll hook prepare suite with Truffle 5.1.18

### ISSUE THREAD

**Issue by kartojal** [trufflesuite/truffle#2876] opened 2020-03-10 09:46 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

We detected in our CI pipeline that after the truffle version bump in npm the tests stopped working, so me and my peer debugged locally and found this error since truffle 5.1.16 and with latest 5.1.18.

Our current fix is to set truffle to 5.1.13 at package.json, without a carot to set it fixed. 

Since truffle 5.1.16 , cant run tests. Tried with 5.1.18 with no luckl. The test fails before running the test suite.
```
1) Contract: Authorization module
       "before all" hook: prepare suite:
     TypeError: Cannot read property 'deployedContext' of undefined
      at Object.getEventAllocations (node_modules/truffle/build/webpack:/packages/codec/dist/lib/abi-data/allocate/index.js:662:1)                                                        
      at new WireDecoder (node_modules/truffle/build/webpack:/packages/decoder/dist/decoders.js:204:1)                                                                                    
      at Object.<anonymous> (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:223:1)                                                                                    
      at step (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:164:1)     
      at Object.next (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:145:45)                                                                                          
      at /home/kartojal/repos/contracts-solidity/node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:139:1                                                                 
      at new Promise (<anonymous>)                                                           
      at __awaiter (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:135:1)
      at Object.forProject (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:219:1)                                                                                     
      at TestRunner.initialize (node_modules/truffle/build/webpack:/packages/core/lib/testing/testrunner.js:84:1)                                                                         
      at processTicksAndRejections (internal/process/task_queues.js:86:5)                    

  2) Contract: Lending module
       "before all" hook: prepare suite:
     TypeError: Cannot read property 'deployedContext' of undefined
      at Object.getEventAllocations (node_modules/truffle/build/webpack:/packages/codec/dist/lib/abi-data/allocate/index.js:662:1)                                                        
      at new WireDecoder (node_modules/truffle/build/webpack:/packages/decoder/dist/decoders.js:204:1)                                                                                    
      at Object.<anonymous> (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:223:1)                                                                                    
      at step (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:164:1)     
      at Object.next (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:145:45)                                                                                          
      at /home/kartojal/repos/contracts-solidity/node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:139:1                                                                 
      at new Promise (<anonymous>)                                                           
      at __awaiter (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:135:1)
      at Object.forProject (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:219:1)                                                                                     
      at TestRunner.initialize (node_modules/truffle/build/webpack:/packages/core/lib/testing/testrunner.js:84:1)                                                                         
      at processTicksAndRejections (internal/process/task_queues.js:86:5)                    

  3) Contract: Subscription module
       "before all" hook: prepare suite:
     TypeError: Cannot read property 'deployedContext' of undefined
      at Object.getEventAllocations (node_modules/truffle/build/webpack:/packages/codec/dist/lib/abi-data/allocate/index.js:662:1)                                                        
      at new WireDecoder (node_modules/truffle/build/webpack:/packages/decoder/dist/decoders.js:204:1)                                                                                    
      at Object.<anonymous> (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:223:1)                                                                                    
      at step (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:164:1)     
      at Object.next (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:145:45)                                                                                          
      at /home/kartojal/repos/contracts-solidity/node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:139:1                                                                 
      at new Promise (<anonymous>)                                                           
      at __awaiter (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:135:1)
      at Object.forProject (node_modules/truffle/build/webpack:/packages/decoder/dist/index.js:219:1)                                                                                     
      at TestRunner.initialize (node_modules/truffle/build/webpack:/packages/core/lib/testing/testrunner.js:84:1)                                                                         
      at processTicksAndRejections (internal/process/task_queues.js:86:5)    
```
## Steps to Reproduce
Tested with Node 11
```
git clone --single-branch --branch LP-000-truffle-5.1.18 https://gitlab.com/raisehq/contracts-solidity.git/
touch private.key # create empty file to prevent an error check in the repo config, priv key not needed for local reproduction.
npm i
npm run compile
npm run test
```

## Expected Behavior

What you expected to happen.
Test should run normaly

## Actual Results

Test exited at `"before all" prepare suite`

Tests should fail with next error
`TypeError: Cannot read property 'deployedContext' of undefined
      at Object.getEventAllocations (node_modules/truffle/build/webpack:/packages/codec/dist/lib/abi-data/allocate/index.js:662:1)  `

## Environment

* Operating System: Ubuntu 16.04
* Ethereum client: ganache
* Truffle version (`truffle version`): 5.1.18
* node version (`node --version`): v11.15.0
* npm version (`npm --version`): 6.7.0

PD1: At Truffle GItter there was another guy with the same issue, he pointed that MAYBE was pragma mismatch between openzeppelin contracts and the repository contracts. After he upgraded all to Solidity v6 all worked. This current reproduction case is with openzeppeling at ^0.5.0 and the cotnracts with pragma at 0.5.12 .

**Comment by haltman-at** [comment] 2020-03-10 19:52
Thanks for reporting this!  Do you have a reproduction example we could use to help narrow downt he problem?  Thank you!

**Comment by haltman-at** [comment] 2020-03-10 19:52
Also, you mentioned it works on 5.1.13; do you know just which version the problem first appeared on?

**Comment by Alexangelj** [comment] 2020-03-15 22:49
Hi, I've asked in gitter about this same issue. I was using the latest truffle version before I found uninstalled and reinstalled to an earlier version.

I fixed the problem using these two commands:
`npm uninstall -g truffle`
`npm install -g truffle@5.14`

I tried v5.15 and still got this exact same error.

When I run truffle version this is the output:
`Truffle v5.1.14 (core: 5.1.14)
Solidity - 0.6.2 (solc-js)
Node v12.3.1
Web3.js v1.2.1`

Here is my truffle.js solc settings:
`compilers: {
    solc: {
      version: "0.6.2",    // Fetch exact version from solc-bin (default: truffle's version)
      docker: false,        // Use "0.5.1" you've installed locally with docker (default: false)
      settings: {          // See the solidity docs for advice about optimization and evmVersion
       optimizer: {
         enabled: false,
         runs: 200
       },
       evmVersion: "constantinople"
      }
    }
  }`

Tried to replicate this in truffle boxes, but couldn't do it.

**Comment by haltman-at** [comment] 2020-03-16 19:50
OK, do you have a reproduction example I could inspect?  It would make it a lot easier to determine what's going on.  Thank you!

**Comment by kartojal** [comment] 2020-03-17 11:23
Check **Steps to Reproduce** please

**Comment by haltman-at** [comment] 2020-03-17 16:52
Ah, I see, I misread and missed that.  Thanks, will take a look!

**Comment by haltman-at** [comment] 2020-03-17 21:16
@kartojal Um, sorry, but I'm getting a repository not found error when I try to clone your repo:

```
Cloning into 'LP-000-truffle-5.1.16'...
fatal: repository 'https://gitlab.com/raisehq/contracts-solidity/-/tree/LP-000-truffle-5.1.16/' not found
```

Any idea why / any other way I could get my hands on a copy?  Thanks!

**Comment by juwitaw** [comment] 2020-03-20 05:01
It happened on truffle version 5.1.17, too.

**Comment by haltman-at** [comment] 2020-03-20 18:15
@juwitaw OK, good to know.  Do you have a reproduction example I chould check out by any chance?

**Comment by juwitaw** [comment] 2020-03-21 07:35
I tried to reproduce with a simple token contract.
Please check on this repo:
https://github.com/juwitaw/simple-test-token/tree/repro-truffle-5.1.17

It runs on docker.
1. Build the image, `docker build -t simpletests:dev .`
2. Run using docker-compose command, `docker-compose -f docker_compose_test.yml up --abort-on-container-exit`
It will show this kind of error like the below picture.
![image](https://user-images.githubusercontent.com/17060491/77221703-b1b98c00-6b7e-11ea-98a4-6d203f62d499.png)

To try the expected result,
1. Change `Dockerfile` first line into `FROM juwitaw/truffle-base-image:truffle5.1.13-0.6.3`
2. Build the image, `docker build -t simpletests:dev .`
3. Run using docker-compose command, `docker-compose -f docker_compose_test.yml up --abort-on-container-exit`
It will show the expected result as below,
![image](https://user-images.githubusercontent.com/17060491/77221733-03faad00-6b7f-11ea-8cc2-14ce0fd1734b.png)

Enviroment:
    Operating System: Alpine Linux
    Ethereum client: ganache-cli v6.9.1
    Truffle version (truffle version): 5.1.17
    node version (node --version): v12.16.1

While reproducing this error, I found that if I remove `SashimiToken` file and test file, the test runs well even with truffle 5.1.17 version. 
And if I remove all the `SushiToken` and left the `SashimiToken` alone, the test still runs as expected result.
I thought if the contract didn't have any or only little dependency with other contracts, the test will run well. But it still just my thought.

Hope it will help.

**Comment by haltman-at** [comment] 2020-03-23 21:36
OK, thanks!  I'm going to first try to see if I can reproduce it without Docker for simplicity.  Also thanks for doing a bit to narrow down the interaction here.  Anyway, I'll take a look!

**Comment by haltman-at** [comment] 2020-03-23 22:30
@juwitaw So, um, your example that you put up doesn't actually seme to include this `SashimiToken` that you mention; only the `SushiToken`?  As  a result I was not able to reproduce the error.  Could you include the `SashimiToken` as well?  Thank you!

**Comment by juwitaw** [comment] 2020-03-24 02:53
@haltman-at Hi, thank you for your time.
I included the `SashimiToken` on the repo. Please checkout to branch `repro-truffle-5.1.17`. 
I'm sorry, I think I forget to mention it before.

**Comment by haltman-at** [comment] 2020-03-24 02:59
Oh, silly me!  Yes, I see it now.  Great, I'll take a look, thanks again!

**Comment by haltman-at** [comment] 2020-03-24 07:07
OK, thanks a bunch for the example, I've put up #2908 to address this!

**Comment by haltman-at** [comment] 2020-03-27 01:38
OK, fix has been released, so closing this.  Let me know if there's still a problem.

**Closed by haltman-at** 2020-03-27 01:38 UTC

**Comment by G-TipSolutions** [comment] 2022-05-14 02:49
$ node -v
v17.9.0

const RWD = artifacts.require('RWD')
const Tether = artifacts.require('Tether')
const DecentralBank = artifacts.require('DecentralBank')

require('chai')
.use(require('chai-as-promised'))
.should()

contract('DecentralBank', ([owner, customer]) => {
    let tether, rwd, decentralBank

    function tokens(number) {
        return web3.utils.toWei(number, 'ether')
    }

    before(async () => {
        // Load Contracts
        tether = await Tether.new()
        rwd = await RWD.new()
        decentralBank = await DecentralBank.new(rwd.address, tether.address)

        // Transfer all tokens to DecentralBank (1 million)
        await rwd.transfer(decentralBank.address, tokens('1000000'))
        
        // Transfer 100 mock Tethers to Customer
        await tether.transfer(customer, tokens('100000000000000'), {from: owner})
    })
    

    describe('Mock Tether Deployment', async () => {
        it('matches name successfully', async () => {
            const name = await tether.name()
            assert.equal(name, 'Mock Tether Token') 
        })
    })

    describe('Reward Token Deployment', async () => {
        it('matches name successfully', async () => {
            const name = await rwd.name()
            assert.equal(name, 'Reward Token') 
        })
    })

    describe('Decentral Bank Deployment', async () => {
        it('matches name successfully', async () => {
            const name = await decentralBank.name()
            assert.equal(name, 'Decentral Bank') 
        })
    })
})




```
$ truffle test
Using network 'development'.

Compiling your contracts...
===========================
- Fetching solc version list from solc-bin. Attempt #1
- Fetching solc version list from solc-bin. Attempt #1
- Fetching solc version list from solc-bin. Attempt #1
- Fetching solc version list from solc-bin. Attempt #1
> Compiling .\src\contracts\DecentralBank.sol
> Compiling .\src\contracts\Migrations.sol
> Compiling .\src\contracts\RWD.sol
> Compiling .\src\contracts\Tether.sol
> Artifacts written to C:\Users\bgsho\AppData\Local\Temp\test--13180-QWOdJc01e279
> Compiled successfully using:
   - solc: 0.8.13+commit.abaa5c0e.Emscripten.clang

I have all the newest versions of everything and does the same thing.....

```
  Contract: DecentralBank
    1) "before all" hook in "Contract: DecentralBank"

  0 passing (3s)
  1 failing

  1) Contract: DecentralBank
       "before all" hook in "Contract: DecentralBank":
     Error: Returned error: VM Exception while processing transaction: revert
      at Context.<anonymous> (C:/Users/bgsho/Solidity/defi-staking-app/test/decentralBank.tests.js:23:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```

**Comment by haltman-at** [comment] 2022-05-16 17:45
@G-TipSolutions That appears to be an unrelated problem.  It also appears to be because the transaction you've put in there is reverting.  I'd suggest opening a [support request](https://trufflesuite.zendesk.com/hc/en-us/requests/new).  Thanks!
