### ISSUE TITLE
"No source code found" Error while debugging a ganache transaction sent to a web3x-deployed contract 

### ISSUE THREAD

**Issue by Melvillian** [trufflesuite/truffle#3294] opened 2020-08-22 23:30 UTC
Background:
I am using truffle@5.1.41

I am trying to locally debug my dapp, which uses web3x@4.0.6 to to deploy a contract to a ganache-cli@6.5.0 blockchain. I deploy the contract and then call several of the contract's methods until the final one, which fails and reverts on chain. The error message returned to me by Metamask + Remix is a cryptic `[object Object]` so I am trying to use the truffle-debugger to figure out what happened.

What I do:
```
cd /path/to/contract/project_root
truffle debug <tx_hash>
```

What I expect to happen:
I expect the debugger to jump to the source code line with the method call on the contract

What actually happens:
I enter the debug terminal and see the error "No source code found", and above that it lists 3 addresses that the tx interacted with that it also couldn't find.

Theories:
I'm not understanding which CLI configs need to be passed to make it read the correct code. I would expect to pass some path to the contract.sol of the contract I'm interacting with, but there is no option to do so. There is --fetch-external, but that is not useful to me as I'm trying to test my unverified contract locally before I deploy to etherscan.

P.S.: I will have some free time soon and have experience with JS/TS cryptocurrency-related software so if you give me sufficient suggestions on where to look and what to modify I could push a PR fix for this.

**Comment by haltman-at** [comment] 2020-08-24 23:52
Hm, troublesome!  Do you by any chance have a reproduction example we could check out?  I don't know offhand what would cause this.  I agree that from your `--fetch-external` shouldn't be relevant here.  Thank you!

**Comment by eggplantzzz** [comment] 2020-09-23 18:11
Closing for issue maintenance, please let us know if this is still something to be investigated and we'll re-open and try to help!

**Comment by XOCODE-OP** [comment] 2021-07-23 06:58
There is always the possibility that I am doing something wrong, but it seems to me this is still a bug. I cannot use the debugger at all.
Very simple project, induced a VM Exception. Using truffle test. This is a ganache local setup.
Running `truffle debug txhash`
And the result is 

> Starting Truffle Debugger...
>√ Gathering information about your project and the transaction...
>Addresses affected:
> 0x02F030dA1cB001B71Cd1FFB5A0dF554edF413Baf(UNKNOWN)
> Warning: The source code for one or more contracts could not be found.
>?:
> 1: // No source code found.

Also not sure what that question mark is supposed to show.

**Comment by XOCODE-OP** [comment] 2021-07-23 08:55
@eggplantzzz  just gonna ping you here, not sure this will be seen otherwise.

Does truffle usually work by now and its just me? I did see multiple issues and threads with this problem online.

**Comment by haltman-at** [comment] 2021-07-23 17:22
Hi @XOCODE-OP, do you have a reproduction example we could inspect?  The debugger certainly works in general; in order to solve your particular problem we're going to need some idea of what you're doing in particular.

**Comment by XOCODE-OP** [comment] 2021-07-23 18:47
Alright well. I created a new project and copied my files into there, the debugger worked.
In order to find this issue, I duplicated my problematic folder, changed only a tiny amount, it worked.
I went back to my original folder, where I just could not get it to work at all: it worked.

I really do not think that I messed up the tx hash but, at this point it seems like the most likely scenario, I got messed up.
So my bad, let's close this issue again, if I find the issue again, I will make sure, and in that case post in this thread again.

**Comment by haltman-at** [comment] 2021-07-23 21:51
OK, I'll close this again.  Thanks!

**Closed by haltman-at** 2021-07-23 21:51 UTC

**Comment by hawkofsky** [comment] 2021-08-24 18:08
This issue is still happening.
I tried to copy files to other location but the same.
What is the reason and a way to fix this issue?

**Comment by haltman-at** [comment] 2021-08-24 19:05
@hawkofsky We're going to need more information to get an idea what's going on.  Would you mind opening a new issue for this with more detail?  Thank you!

**Comment by hawkofsky** [comment] 2021-08-24 19:19
okay.
https://github.com/trufflesuite/truffle/issues/4278

**Comment by earizon** [comment] 2021-09-08 09:10
Related problem. I compile, and pass test for and smart-contract. No issues. Then I reuse the deployed contract into another code. The EVM reverts with a TX hash. It looks to me that something fails before even reaching the invoked function (wrong param, ...) and so some internal truffle mechanism used to map the failed tx-hash to the contract address/metadata fails. Does anybody knows how to debug this problem?

**Comment by concave-dash** [comment] 2021-12-17 17:43
Is it somehow possible to tell truffle where the source code is? Compiled and deployed contracts using remix IDE.

**Comment by haltman-at** [comment] 2021-12-17 20:00
@concave-dash Right now, you basically have two options.  You could either put the source code into a Truffle project, and run the debugger inside that; or you could verify your contracts on Etherscan and Sourcify, and use the debugger's `--fetch-external` (`-x` for short) option to tell it to use verified sources where available.

**Comment by redigaffi** [comment] 2022-04-14 17:33
Had the same issues, make sure to delte code/build folder before making a new deployment
