### ISSUE TITLE
Error: Missing parameter: provider

### ISSUE THREAD

**Issue by princesinha19** [trufflesuite/truffle#1667] opened 2019-01-28 07:35 UTC
```
node_modules/web3-core/dist/web3-core.cjs.js:148
      throw new Error("Missing parameter: ".concat(name));

Error: Missing parameter: provider
```

I am getting this error when using web3 version "web3": "^1.0.0-beta.39"
truffle version: ^4.0.2

Can anyone help me with this error?

**Comment by filips123** [comment] 2019-01-28 08:20
Package Web3 have many changes in last version (see ethereum/web3.js#2000). It looks like that Truffle currently doesn't support them.

This should really be fixed, because it is currently impossible to use `truffle-contract` with three latest `web3` versions (previous versions also caused errors in #1617 and #1614).

Temporary solution may be do downgrade Web3, possibly to `1.0.0-beta.33`.

**Comment by princesinha19** [comment] 2019-01-28 08:50
Thanks, @filips123 for your quick response. 
So, you guys are downgrading web3 in your package?
How much time it will take to do this?

**Comment by princesinha19** [comment] 2019-01-28 08:54
`Temporary solution may be do downgrade Web3, possibly to 1.0.0-beta.33.
`

How to do this inside truffle-contract @filips123?

**Comment by princesinha19** [comment] 2019-01-28 08:57
@filips123 I have asked the same question on web3 but they are saying that you guys are using unofficial API.
![web3 issue](https://user-images.githubusercontent.com/28489437/51824638-d1ea1400-2308-11e9-8513-83e8ce3398e3.png)

**Comment by daniyarchambylov** [comment] 2019-01-29 12:17
I'm experiencing this issue too and downgraded Web3 package, but it's blocking from publishing a package. No end user should do workarounds.

**Comment by rocky** [comment] 2019-01-29 12:19
For what it is worth:

```
        "web3": "^1.0.0-beta.37",
        "web3-core-promievent": "^1.0.0-beta.37",
```

work for me

**Comment by Levino** [comment] 2019-01-30 07:53
This is the most urgent bug of all here I would say. I just created a new truffle project. Wont run.

**Comment by gnidan** [comment] 2019-01-30 18:32
We are looking into this issue as a matter of top priority.

Can someone provide reproduce steps so we can validate potential fixes?

Heads up, we are planning to release today without web3 fixes, but we will look into getting another release shortly after that.

**Comment by alcuadrado** [comment] 2019-01-30 18:51
A smaller reproduction script is:

* `npm init -y`
* `npm install truffle-contract`
* `node --eval 'require("truffle-contract")'`

It results in this error:

```sh
/private/tmp/repro/node_modules/web3-core/dist/web3-core.cjs.js:148
      throw new Error("Missing parameter: ".concat(name));
      ^

Error: Missing parameter: provider
    at Function.throwIfMissing (/private/tmp/repro/node_modules/web3-core/dist/web3-core.cjs.js:148:13)
    at Web3.AbstractWeb3Module (/private/tmp/repro/node_modules/web3-core/dist/web3-core.cjs.js:17:107)
    at new Web3 (/private/tmp/repro/node_modules/web3/dist/web3.cjs.js:30:68)
    at Object.<anonymous> (/private/tmp/repro/node_modules/truffle-contract/lib/utils.js:7:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/tmp/repro/node_modules/truffle-contract/lib/execute.js:4:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

**Comment by gnidan** [comment] 2019-01-30 19:08
Awesome! Between this and the PR, these three reproduce methods should be sufficient. Thanks all.

I just opened #1685 to upgrade web3 to latest. This includes pinning the versions. We'll see what Travis says.

**Comment by filips123** [comment] 2019-01-30 19:58
@gnidan The PR won't fix the issue. It still has the same error in Travis Ci test.

**Comment by gnidan** [comment] 2019-01-30 20:11
@filips123 I saw that. @eggplantzzz is working on another PR to ping to beta.37, to give us time to upgrade later.

**Comment by Levino** [comment] 2019-01-30 21:37
The beauty is that you have to pin all `web3*` packages because now there are twenty of them. As if anyone would include anything but the top level `web3`.

**Comment by rocky** [comment] 2019-01-30 21:49
> PR to pin to beta.37, 

Hmm.... So it was decided that you don't have to go back to beta.33 as it seemed to be suggested above?

**Comment by gnidan** [comment] 2019-01-30 21:51
@rocky we *can't* downgrade web3, or we lose support for the new ABI encoder

**Comment by gnidan** [comment] 2019-01-30 23:11
OK Truffle v5.0.3 has been released. Closing this because I'm an optimist. Let me know if the issue persists and I'll re-open :D 

Thanks everyone!

**Closed by gnidan** 2019-01-30 23:11 UTC

**Comment by Levino** [comment] 2019-01-31 09:19
Fix working for me.

**Comment by Levino** [comment] 2019-01-31 16:56
Yes, that is right. But the software was not working! Good quick fix. Now one can work on a long term solution.

**Comment by filips123** [comment] 2019-01-31 17:00
@Levino Yes, I know that this is a quick fix, so you could now work on a long term solution. You could maybe open another issue for compatibility with new Web3 versions.

**Comment by Levino** [comment] 2019-01-31 18:30
Ahem. Or you do it???

**Comment by filips123** [comment] 2019-01-31 18:33
Ok. I will create an issue for this.

**Comment by baiye225** [comment] 2019-02-13 00:28
> @filips123 I saw that. @eggplantzzz is working on another PR to pin to beta.37, to give us time to upgrade later.

web3@1.0.0-beta.37 works for me!
Here is the command:

```
npm uninstall web3
npm install web3@1.0.0-beta.37

```
