### ISSUE TITLE
Truffle test issues "segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by Akabanes** [trufflesuite/truffle#5667] opened 2022-11-02 09:52 UTC
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

When i try to connect to Blockchain, terminal issues says that program try to get access to unavaible part of memory
Maybe it's happend because i used virtual machine, not a whole operating system

## Steps to Reproduce
![1](https://user-images.githubusercontent.com/112565541/199458863-5ae27341-f742-4b7c-b746-79b50e8e26aa.jpg)

## Environment
*VirtualBox (6.1)
* Ubuntu 22.04 
* Ethereum client:
* Truffle version (5.6.1):
* node version (16.10.0):
* npm version (7.24.0):

**Comment by kevinbluer** [comment] 2022-11-03 17:44
Hey @Akabanes, thanks for opening this! Any chance you'd be able to share the project / repo so we can test it on our side? In addition, it could be worth seeing if you can allocate more memory to the VM just to see if that helps resolve things.

**Comment by sachintha00** [comment] 2022-11-18 04:22
I have the same error. But I'm running Ubuntu without a virtual machine. 

![image](https://user-images.githubusercontent.com/80079235/202616196-549ed923-711d-4361-b9cb-e7d6df132975.png)

**Comment by cds-amal** [comment] 2022-11-18 04:47
Hey @sachintha00, could you share a git repo with reproduction steps, so I can investigate?

**Comment by truegff** [comment] 2022-11-30 19:44
Hi @cds-amal ,

I'm experiencing the same issue.
Here's the project repo as you've asked:
https://github.com/truegff/cbde_practice/tree/main/02_supply_chain_app


Environment:

alexander@alexander-ThinkPad-X250:~/Documents/blockchain_workspace/02_supply_chain_app$ truffle --version
Truffle v5.6.6 (core: 5.6.6)
Ganache v7.5.0
Solidity - 0.8.17 (solc-js)
Node v16.18.1
Web3.js v1.7.4
alexander@alexander-ThinkPad-X250:~/Documents/blockchain_workspace/02_supply_chain_app$ uname -a
Linux alexander-ThinkPad-X250 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Reproduction steps:
execute "truffle test" command

alexander@alexander-ThinkPad-X250:~/Documents/blockchain_workspace/02_supply_chain_app$ truffle test
Segmentation fault (core dumped)

**Comment by truegff** [comment] 2022-11-30 23:36
Uninstalling and reinstalling of nodejs and truffle fixed the issue:
```
alexander@alexander-ThinkPad-X250:~/Documents/blockchain_workspace/02_supply_chain_app$ truffle version
Truffle v5.6.8 (core: 5.6.8)
Ganache v7.5.0
Solidity - 0.8.17 (solc-js)
Node v16.18.1
Web3.js v1.7.4
```

I can't reproduce this issue anymore.

**Comment by cliffoo** [comment] 2022-12-01 18:36
@truegff  Looks like it was an issue related specific to your system? Closing. If you run into it again feel free to re-open! Thanks.

**Closed by cliffoo** 2022-12-01 18:36 UTC
