### ISSUE TITLE
Having "-" in import filename break compilation in weird way (5.1.66)

### ISSUE THREAD

**Issue by hellwolf** [trufflesuite/truffle#3799] opened 2021-02-15 08:42 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Since "5.1.66", there are certain import stops working in weird way. And it's been observed that it happens when the file name contains "-" symbol.

## Steps to Reproduce

Using truffle version: 5.1.66
Using solidity version: 0.7.6

- truffle init
- install `@openzeppelin/contracts`
- create a test contract, starting:

```
pragma solidity ^0.7.0;
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
```

truffle compile, it should pass.

But change to the following deliberately:

```
import "@open-zeppelin/contracts/token/ERC20/IERC20.sol";
```

Noticing a "-" in between, it fails with a mysterious error:

```
CompileError: /home/hellwolf/tmp/truffle-test/contracts/ERC20.sol:5:1: ParserError: Source "Ȣbn-zeppelin/contracts/utils/Context.sol" not found: Callback not supported.
import "@open-zeppelin/contracts/utils/Context.sol";
^--------------------------------------------------^
```

Note that, the project I am working on unfortunately has a "-" in the file name, namely https://www.npmjs.com/package/@superfluid-finance/ethereum-contracts. It really made a head scratchier!

## Expected Behavior

Should import file with its name containing "-" and compile correctly.

## Actual Results

Truffle 5.1.66 failed with mysterious error.

## Environment

* Operating System:  ubuntu
* Ethereum client: n/a
* Truffle version (`truffle version`): 5.1.66
* node version (`node --version`): 12.20.2
* npm version (`npm --version`): 6.14.11

**Comment by haltman-at** [comment] 2021-02-16 22:10
Hi, I'm a little confused by this report.  Of course importing from `@open-zeppelin/contracts` doesn't work because that's not the name of the project; it's `@openzeppelin` rather than `@open-zeppelin`.  As for the mysterious error you're seeing, that's simply solc's error message when it can't locate an imported source; we recently decided to start exposing those error messages rather than replacing them with our own as we had been.

However, you say that imports with dashes in them don't work more generaly?  Do you have a reproduction example for that we could check out?  (One that doesn't rely on trying to import a non-existent source, that is.)  Meanwhile I'll try to reproduce this myself, I suppose, and see if I can figure out what's going on.

**Comment by hellwolf** [comment] 2021-02-16 22:27
> However, you say that imports with dashes in them don't work more generaly?

Yes, that's what I am saying. Using openzeppelin was just a convenient way to show that the error message is indicating something is off.

To reproduce:

1. download the folder `https://github.com/superfluid-finance/protocol-monorepo/tree/dev/examples/dividends-rights-token-demo`
2. change the truffle version to 5.1.66 in package.json.
3. yarn install & yarn build

It will fail. but if you skip step (2), it will succeed.

**Comment by haltman-at** [comment] 2021-02-16 22:31
OK, I was able to reproduce an error compiling Superfluid, and was able to confirm that the error is new in 5.1.66.  I'll have to look into this and see what's causing it.  It's not clear to me that dashes are actually the cause; relative imports with dashes worked fine, for instance.  Still, something's clearly going wrong here, so I'll look into it.

**Comment by haltman-at** [comment] 2021-02-16 23:13
OK, I've put up PR #3802 to fix this.  Sorry about the problem, thanks for the report!

**Comment by hellwolf** [comment] 2021-02-16 23:40
thanks for the fast response!

**Comment by haltman-at** [comment] 2021-02-19 23:14
Fix is released now, closing!

**Closed by haltman-at** 2021-02-19 23:14 UTC
