### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by tanhuiya** [trufflesuite/truffle#1384] opened 2018-10-26 09:42 UTC
I test in my private network, and the address of the account has 10 eth.
when I `truffle migrate`, it failed.

```
truffle migrate --reset
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
insufficient funds for gas * price + value
```

const privateKey ="05530B3575CD37DA646E51AABDC9E02271809DE......";

The private key was exported from metamask.

here is my network config
```
development:{
        // gas:    7500000,
        // gasPrice:   6000000000,
        provider:function(){
            return new HDWalletProvider(privateKey,"http://47.100.215.121:8555")
        },
        network_id: "*"
      }
```

**Comment by fainashalts** [comment] 2018-11-01 17:57
Hi, and thanks for reaching out about this issue! I believe the actual problem is in the "Network state unknown" portion of the error you're getting. You seem to be trying to put your private network info into `networks.development`, but you should have a `networks.private` with this information and be using that if you're using the private network. The key here is you want your migration to be accessing the correct network. 

I'm going to close this issue since it doesn't seem the problem is due to Truffle's codebase. I hope my comment is helpful and feel free to open a new issue if you feel I've missed something!

**Closed by fainashalts** 2018-11-01 17:57 UTC
