### ISSUE TITLE
The contract code couldn't be stored, please check your gas amount.

### ISSUE THREAD

**Issue by freshonline** [trufflesuite/truffle#800] opened 2018-02-16 22:48 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I building this exemple: http://truffleframework.com/tutorials/robust-smart-contracts-with-openzeppelin

## Steps to Reproduce

[code]Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
[/code]

truffle.js:
[code]
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*",
      from: "eth_address",
      gas: 1000000,
      gasPrice: 10000000000,
    }
  }
};
[/code]

## Environment

ubuntu 16.04.3
Truffle v4.0.6 (core: 4.0.6)
Solidity v0.4.19 (solc-js)
Geth Version: 1.8.0-stable
node version: v9.4.0
npm version: 5.6.0

**Comment by cgewecke** [comment] 2018-02-18 19:28
@freshonline There's an open issue (#721) about running migrations with geth `1.8.0-stable`.

Could you try downgrading to `1.7.3` and see if that helps? There may be additional issues you're facing but `1.8.0` is known to be unusable at the moment. We're actively investigating the cause the and will hopefully fix this in next patch release. 

Closing as duplicate of #721

**Closed by cgewecke** 2018-02-18 19:28 UTC
