### ISSUE TITLE
Truffle returns `UnimplementedFeatureError` when compiling contracts with public struct return types

### ISSUE THREAD

**Issue by Arachnid** [trufflesuite/truffle#2410] opened 2019-09-24 04:58 UTC
I'm using Truffle 5.0.37, with solc 0.5.8, and I have a contract that returns an array of structs using `pragma experimental ABIEncoderV2`. [Here's](https://github.com/ensdomains/resolvers/compare/multicoin?expand=1#diff-d52ef609ec88a2eb218f95fa4e33cdd5) the code.

When I use remix with the same solc version, the code compiles fine with no errors. When I run `truffle build`, though, I get the error `UnimplementedFeatureError: Encoding type "struct AddrResolver.AddressInfo memory[] memory" not yet implemented.`.

The format of the error message and the lack of source line reference makes me think this is a truffle error, rather than a solc one.

**Comment by haltman-at** [comment] 2019-09-24 07:36
That's a solc error message you're getting, not a Truffle error message; but it's very possible that it's a Truffle error that's causing it to come up.  Thanks for bringing this up -- we'll have to check this out.  (I just tried this with your code and, yup, same error.)

My initial thought was that maybe something was causing Truffle to not actually be using 0.5.8 like it should be, but I tried explicitly setting a version in `truffle.js` and this didn't help (indeed, even setting it to 0.5.11 didn't help).  So, we'll have to look into it.  That said, it may be worth bringing this up with the `solc` people too.

**Comment by haltman-at** [comment] 2019-09-24 07:42
Here's something odd I noticed while playing around with this -- the error seems to be coming from `profiles/AddrResolver.sol`, that being the only one that makes use of anything of type `AddressInfo[] memory` (specifically, the return value of `addresses`).  However, if I strip down the project by removing all contracts other than `profiles/AddrResolver.sol`, `ResolverBase.sol` (which it imports), and `Migrations.sol` (because of course let's keep that), the error goes away.  Weird.  So there's some sort of interaction with some other file going on there?  No idea.  No other file seems to even call the `addresses` function, so that's not it...

**Comment by haltman-at** [comment] 2019-09-24 07:50
Ah, here's something -- the problem is likely related to import handling.  (Whether on our end or solc's, I don't know.)  If you delete just the three files that import things from outside the project, the error goes away.  Interesting...

**Comment by eggplantzzz** [comment] 2019-09-25 00:27
So I deleted all the contracts except for 3: OwnedResolver, ResolverBase, and AddrResolver. For OwnedResolver, I deleted all the imports except for Ownable and AddrResolver and adjusted the contract code (i.e. made the first line `contract OwnedResolver is Ownable, AddrResolver {`.
This will still generate the error.

**Comment by eggplantzzz** [comment] 2019-09-25 14:01
So it seems like there is something up with `OwnedResolver` and `PublicResolver`. They both have functions named `isAuthorised`. If you change the name of this function in both contracts to something (even `isAuthorise`) else the project will compile successfully.

**Comment by Arachnid** [comment] 2019-09-25 21:23
@eggplantzzz That seems completely disconnected from the error message, though? And `OwnedResolver` isn't imported by the contract in question.

**Comment by eggplantzzz** [comment] 2019-09-27 13:09
@Arachnid Yes but I'm thinking this might be a Solidity bug of some sort. I'm going to get the raw input for the compiler and ask the Solidity people about this.

**Comment by eggplantzzz** [comment] 2019-09-27 13:18
So @Arachnid, turns out if you add the experimental pragma statement to the contracts that import `AddrResolver` then the project compiles successfully with warnings. I'm not sure if this is what should be expected or not.

**Comment by eggplantzzz** [comment] 2019-09-27 17:42
So I created a stripped down example that illustrates this whole issue. https://github.com/eggplantzzz/toySolidityExample

**Comment by eggplantzzz** [comment] 2019-09-30 14:58
Does adding the extra experimental pragma statements solve it for you @Arachnid?

**Comment by Arachnid** [comment] 2019-09-30 20:54
I've actually since rewritten the code to not return an array of structs - but when it did I tried adding the pragma to PublicResolver.sol - which I think is the only file to import AddrResolver.sol - and it didn't solve it.

**Comment by eggplantzzz** [comment] 2019-10-01 14:58
You also would need to add it to `OwnedResolver` which imports that file as well.

**Comment by eggplantzzz** [comment] 2019-10-09 14:14
Closing this for issue maintenance.

**Closed by eggplantzzz** 2019-10-09 14:14 UTC
Labels: Compiler

**Comment by Arachnid** [comment] 2019-10-09 22:02
I feel like the larger issue here isn't my specific contract - it's how Truffle doesn't provide any context to the error message (file or line number).

**Comment by CruzMolina** [comment] 2019-10-09 22:34
Hey @Arachnid , definitely sounds like something worth looking into. It's been a while since I've used `solc` from the command line, so I'm curious to know if `solc` already provides more context and we're just missing/dropping it somewhere on our end. Can you open a Feature Request for this?

Btw, looks like your original error _is_ coming from solc `0.5.8`, [see line 8](https://solidity.readthedocs.io/en/v0.5.8/using-the-compiler.html?highlight=unimplementedfeatureerror#error-types).

**Comment by Arachnid** [comment] 2019-10-09 22:51
@CruzMolina I thought *this* was the feature request? Can't we just reopen this issue to address it?

**Comment by CruzMolina** [comment] 2019-10-09 23:08
>The format of the error message and the lack of source line reference makes me think this is a truffle error, rather than a solc one.

You're reporting this as a Truffle error, which it isn't. I can open one for you and ref this issue. Would like to cut down the signal to noise ratio.

**Comment by eggplantzzz** [comment] 2019-10-10 16:55
Well, the thing is, we just forward the `solc` error on to the user here. Is there something more that we could do that you would suggest @Arachnid?

**Comment by Arachnid** [comment] 2019-10-12 04:35
Is there any additional information at all available from solc?

At a minimum it'd be good to know which file was being compiled when the error occurred.

**Comment by gnidan** [comment] 2019-10-12 05:25
> At a minimum it'd be good to know which file was being compiled when the error occurred.

Hm, check the metadata section on the Solidity docs, but I believe Solidity just compiles input sources en masse.

**Comment by Arachnid** [comment] 2019-10-12 20:01
Truffle must be compiling a particular contract, though, right? I don't think there's a way to tell solidity "compile all of these files at once"?

**Comment by gnidan** [comment] 2019-10-13 01:41
Telling Solidity "compile all these files all at once" is exactly what we do! See [this section](https://solidity.readthedocs.io/en/v0.5.12/using-the-compiler.html#compiler-input-and-output-json-description) of the docs to see how that works, or see [this part](https://github.com/trufflesuite/truffle/blob/develop/packages/compile-solidity/run.js#L25) of Truffle's code to see how we integrate.
