### ISSUE TITLE
npm install -g truffle > truffle version > Error: Cannot find module 'truffle-hdwallet-provider'

### ISSUE THREAD

**Issue by SvenMeyer** [trufflesuite/truffle#3539] opened 2020-11-15 07:50 UTC
```
$ npm uninstall -g truffle
$ npm install -g truffle
$ truffle version

$ truffle version
Error: Cannot find module 'truffle-hdwallet-provider'
Require stack:
- /home/sum/DEV/truffle.js
- /home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/node_modules/original-require/index.js
- /home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sum/DEV/truffle.js:25:24)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Object.require (internal/modules/cjs/helpers.js:74:18)
    at Function.load (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:161:1)
    at Function.detect (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:150:1)
    at Object.run (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/version.js:16:1)
    at Command.run (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
    at Object.<anonymous> (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/core/cli.js:56:1)
    at __webpack_require__ (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at /home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/cli.bundled.js:89:10)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
Truffle v5.1.53 (core: 5.1.53)
Node v12.19.0
```

**Comment by eggplantzzz** [comment] 2020-11-16 15:46
Hey @SvenMeyer, I think that error might be coming from your code. Check the contents of `/home/sum/DEV/truffle.js`. I assume it is requiring `truffle-hdwallet-provider` and you don't have it installed there.

Do note that that package has been renamed. So in the future make sure to install `@truffle/hdwallet-provider` instead. Let me know if you are able to resolve this!

**Comment by eggplantzzz** [comment] 2020-12-16 19:07
Closing this for issue maintenance. If this is still a problem and you'd like to troubleshoot it further, then let us know and we'll re-open it. Thanks!

**Closed by eggplantzzz** 2020-12-16 19:07 UTC

**Comment by SvenMeyer** [comment] 2021-01-17 09:57
I actually had not any project setup, just did a global install of truffle and wanted to check the version (see above). Shouldn't that work ?
```
$ npm uninstall -g truffle
$ npm install -g truffle
$ truffle version
```

**Comment by SvenMeyer** [comment] 2021-01-17 10:04
installing hdwallet (globally) as well gives me an error as well 
```
$ npm install -g @truffle/hdwallet-provider
...
$ truffle version
Error: Cannot find module 'truffle-hdwallet-provider'
...
```

A remember that 'a while ago' somebody suggested to install it locally, but as far as I remember it did work for me globally ... or was it with truffle globally and a local install of @truffle/hdwallet-provider ?

Is that the setup how it should be ?

**Comment by cds-amal** [comment] 2021-01-17 13:54
Hi @SvenMeyer ,

If you change all occurrences of`truffle-hdwallet-provider` to `@truffle/hdwallet-provider` in the source code the issue should be resolved.

**Comment by SvenMeyer** [comment] 2021-01-17 14:19
I do not have any source code or a project yet at this stage (see above).

... or is that mandatory to make a fresh global install of truffle work ?

**Comment by 1anre** [comment] 2021-05-18 18:30
Wow, I'm in a similar boat now. Earlier I noticed upon installing truffle for the very first time, there were so many deprecated files notifications, before the installation completed and I then got a summary at the end saying:


"
+ truffle@5.3.6
added 1732 packages from 1178 contributors in 1129.425s
"

I next ran the 'truffle version' command, just to be sure that everything regarding the global installation was ok, and I got this result, which I think looks ok:

```
C:\Users\user>truffle version
Truffle v5.3.6 (core: 5.3.6)
Solidity v0.5.16 (solc-js)
Node v14.17.0
Web3.js v1.3.5
```

But now I want to deploy a project's SmartContract, and I ran the 'truffle develop' command from the project's local folder on my machine, and I am getting the below errors.

```
Error: Cannot find module '@truffle/hdwallet-provider'
Require stack:
- C:\Users\user\Documents\GitHub\Projects\eattheblocks\screencast\345-deploy-smart-contract-bsc\truffle-config.js
- C:\Users\user\AppData\Roaming\npm\node_modules\truffle\node_modules\original-require\index.js
- C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js
```

**Comment by SvenMeyer** [comment] 2021-05-19 05:26
Did you do a 
`npm install -g @truffle/hdwallet-provider` or 
`npm install @truffle/hdwallet-provider` in your project directory ?

... but not `npm install truffle-hdwallet-provider` ?

**Comment by webbooo** [comment] 2022-04-11 14:12
Hey @SvenMeyer did you get a resolution on this?  I'm having a lot of issues trying to get truffle dashboard to run..

Interested to know how you went.

**Comment by EagleJRM** [comment] 2022-05-04 08:59
I'm also in the same boat with the same error of 

Error: Cannot find module '@truffle/hdwallet-provider'
Require stack:

I then updated my node.js  and also installed an NVM so that I could use different versions as I thought it might have been the problem. Nope was not node.js at all. I uninstalled truffle and reinstalled it and now I'm getting this error:

Error: Cannot find module 'C:\Users\jbear\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by tmarb3** [comment] 2022-05-08 03:13
I also get Cannot find module 'C:\Users\Admin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js' 

were you able to figure it out?

**Comment by tmarb3** [comment] 2022-05-08 03:19
This is what I found and it worked for me. All you need to do is to run "npm install -g truffle@5.4.29" This will install an older version of truffle. Turns out the issue is with "npm install -g truffle" since it installs the latest version, and the latest version is currently having glitches.

Just run "npm install -g truffle@5.4.29" or an older version of truffle and your issue will be solved.

**Comment by EagleJRM** [comment] 2022-05-09 05:53
> This is what I found and it worked for me. All you need to do is to run "npm install -g truffle@5.4.29" This will install an older version of truffle. Turns out the issue is with "npm install -g truffle" since it installs the latest version, and the latest version is currently having glitches.
> 
> Just run "npm install -g truffle@5.4.29" or an older version of truffle and your issue will be solved.

Hi Thank you for the feedback. I'm getting this error again:

Error: Cannot find module '@truffle/hdwallet-provider'
Require stack:
- C:\Users\jbear\workspace\SupplyChainApp\truffle-config.js
- C:\Users\jbear\AppData\Roaming\npm\node_modules\truffle\node_modules\original-require\index.js
- C:\Users\jbear\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\jbear\workspace\SupplyChainApp\truffle-config.js:1:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Object.require (node:internal/modules/cjs/helpers:102:18)
    at Function.load (C:\Users\jbear\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\index.js:159:1)
    at Function.detect (C:\Users\jbear\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\index.js:148:1)
    at Object.module.exports [as run] (C:\Users\jbear\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\compile\run.js:8:1)
    at Command.run (C:\Users\jbear\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command.js:189:1)
Truffle v5.4.29 (core: 5.4.29)
Node v16.13.2

I just can't think of where to begin with this error anymore. If you may have some more insight to this error I would greatly appreciate it.

**Comment by codewizard26** [comment] 2022-08-28 20:07
Using  "truffle init" first and then "truffle development " worked for me successfully
