### ISSUE TITLE
How to set a custom gas limit globally for all truffle tx in JS testing? Also misleading error logs during out-of-gas errors

### ISSUE THREAD

**Issue by SidSethi** [trufflesuite/truffle#4319] opened 2021-09-21 18:42 UTC
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

We have a large truffle test suite in JS that was passing entirely on truffle v 5.1.23. We needed to upgrade it to get a new package that requires truffle v >= 5.1.35. We encountered several weird errors so decided to upgrade to latest truffle, which is 5.4.11. With this I am seeing some odd behavior where tests that previously were passing are now failing with "out of gas" errors.

In addition to the "out of gas" errors, logs are showing several `Ambiguous event, possible interpretations` errors, which don't really make any sense.

Perhaps truffle's default transaction gas limit changed to a lower value somewhere in between these two versions, but there is no documentation about this. I also can't find any way to override this value globally, as opposed to setting a `gas` field on every single transaction.

2 issues: 1) how to set global gas limit on every truffle tx? 2) why does truffle show "Ambiguous event, possible interpretations" errors when the real error is out-of-gas?

## Environment

* Operating System: Linux
* Ethereum client: (?) solc version 0.5.17
* Truffle version (`truffle version`): 5.4.11
* node version (`node --version`): 14.17.3
* npm version (`npm --version`): 6.14.13

**Comment by haltman-at** [comment] 2021-09-21 19:42
OK, so, there are several different things going on here.  I think this should be multiple issues.

So, what changed regarding gas?  (Thanks to @fainashalts for this explanation.)  Prior to 5.4.11, the default gas limit was the block limit, which was a gross overestimation for most use cases. Now a call to the `estimateGas()` function is made to estimate the gas needed for a transaction. This is then multiplied by 1.5 for the gas limit. If 1.5 x gas is higher than the blockLimit for the latest block, the blockLimit is used instead.

This change *shouldn't* have broken anything, but apparently it did.  So that's one issue.  Why did it break things?  I don't know; but if you have a reproduction example, we'd be glad to inspect it and see what's going on.

Secondly, we have the question of how to set `gas` globally for tests.  Well, you can set `gas` globally for a network with the `gas` setting for that network in your Truffle config.  However, if you're running Truffle Test where you're not running it against an existing network (such as a separately-running instance of Ganache), um, I'm not sure we support setting global config options in that case.  So that's a second issue (but also a workaround -- use a separately-running instance of Ganache and put it in your Truffle Config -- or possibly a solution for your use case if you were already using a separately-running instance of Ganache).

As for the event thing: I have no idea.  That's a third issue.  However, if you have a reproduction example, I can check it out and see what's up with that.

So, would you mind renaming this and splitting it up?  Thanks!  (We can add the second issue if you don't, since we don't really need reproduction information for that one.  But we're going to need repro information to proceed with the first and third.)

**Comment by SidSethi** [comment] 2021-09-21 21:51
Thanks for the quick and helpful response @haltman-at 

I'm not sure if its a gas limit thing anymore. I tried to set gas limit globally via truffle config, which I believe worked. I'm still seeing some issues. There is some non-determinism happening. Sometimes when running a lot of tests across multiple files, I see an error in certain tests, but when running fewer tests or a single test / file the previously erroring test succeeds.

Here is a screen recording showing the issue: https://github.com/AudiusProject/audius-protocol/pull/1891#issuecomment-924410200

You can also see the entire test suite in that same PR, https://github.com/AudiusProject/audius-protocol/tree/ad101e71757dd1a7ec58ea6c8e9e865900ca114f/eth-contracts

The event thing is lowest pri since it basically seems to be a mis-representation of an out-of-gas error. I'm not really sure how to repro it but I'll open an issue afterward if I can

**Comment by SidSethi** [comment] 2021-09-21 22:27
The latest behavior seems more consistent with the issues laid out here https://github.com/trufflesuite/ganache/issues/990

Not sure if you have any insight?

**Comment by haltman-at** [comment] 2021-09-22 03:20
Again, you seem to be combining together what is potentially a number of different issues.  If we are to address these problems, we need to first break it down into discrete problems, and have clear reproduction steps for each.  If you change things, and you get different problems as a result, then those new problems are different issues, not the same issue; if you are seeing new problems that you did not see before, then you should file new issues, not comment on them here.

I would really suggest that you should split this up into multiple issues, with explicit reproduction steps for each and records of the resulting problems, if we are to make progress on solving it.  Trying to reproduce and investigate some of these multiple problems, based solely on the information provided here, seems like it could potentially be quite difficult.  Like, when you discuss non-determinism, what non-determinism exactly are you seeing?  What precisely differs between runs that should be identical?  (Again, though, you should file a new issue for this, not answer here.)

Since you have linked your test suite, though, we can use that as a starting point for investigation.  So that's helpful; thanks for that.  I'll try it out and see what I can find regarding the problems you initially reported, i.e., an out of gas that shouldn't happen (on the one hand) and this ambiguous event message (on the other hand).  Maybe the nondeterminism will even turn up, who knows!

**Comment by fainashalts** [comment] 2021-09-22 18:23
Hi @SidSethi I just want to speak to the gas issues you are facing, it sounds like there are a couple of other things going on here but hopefully I can help. 

-- can you update your node version? We only support versions 10 and up (perhaps this was a typo? We don't think Truffle would run at all on Node 4!)
-- you cannot set `gasPrice` at the configuration level at this time. You will need to add it in each transaction, like `{ gasPrice: ____ }`
-- you can set `gas` at the configuration level, which I see you have done. However, the gas * 1.5 (our default gas multiplier) should be less than the latest `blockLimit` (`gas` is the most gas you are willing to spend, `blockLimit` is the most gas that can be spent in the block). 
-- I suggest you add gasMultiplier to your contracts and set it to 1 (i.e. `Registry.gasMultiplier = 1`) before deployment steps happen.  

I see you have a `development` network specified in your config. I am assuming that this is what you are using in your tests, as Truffle will try to use that by default if it is specified.

The event issues should be in another issue so we can properly track them. Can you please write up a separate issue for that so we can dig in? Thanks!

**Comment by haltman-at** [comment] 2021-09-22 21:44
Some notes to anyone trying to reproduce this:
1. Make sure you use bundled Truffle.
2. Make sure you start up Ganache with at least 20 accounts.

**Comment by SidSethi** [comment] 2021-09-22 22:58
hey @haltman-at and @fainashalts thank you for digging into this and for your helpful responses. sorry for the lack of specificity in my issue description. I'll re-open this as more specific issues now and close this one afterward

**Comment by haltman-at** [comment] 2021-09-22 23:03
So I was able to get some cases of "ambiguous events" messages where this didn't seem to make sense.  However, I should note that this didn't in any way seem to be related to, or a replacement for, an out of gas message.  Indeed, that wouldn't make sense; if the transaction ran out of gas, its events would be reverted, and so there would be no events (ambiguous or otherwise) to show.  I think the fact that you're seeing "ambiguous events" messages is simply unrelated.

I can look into the ambiguous events messages (because some of the ones I am seeing are... not really ambiguous?) but depending on exactly what's going on there it may be a while before it's fixed.  I would be helpful to know exactly how these ambiguous events messages differed from your expectations and what you considered to be wrong with them!

@SidSethi I think you can leave this open, I think we've agreed to use this one for what I called the first issue?  But yeah filing issues for the others would be good.

**Comment by haltman-at** [comment] 2021-09-23 04:32
OK, I figured out why you're getting so many ambiguous event messages!  It's because you're using a proxy contract.  Sorry, Truffle has some trouble with these at the moment.  We're hoping to address these problems eventually; see issues #3826 and #3941.  It may be a while before we get to those, sorry.  But, at least the decodings are correct, even if there's no real ambiguity? :)

Anyway, that still leaves the other problems, but at least I figured out what's up with the events.  I don't think you need to file a new issue for the event problems; we can track it in #3826 and #3941.  Thanks again for bringing this up!

**Comment by haltman-at** [comment] 2021-12-22 19:25
OK, we're going to close this particular issue; the problems uncovered here are already tracked on other issues.  Thanks for bringing this up!

**Closed by haltman-at** 2021-12-22 19:25 UTC
Labels: needs investigated
