### ISSUE TITLE
Error: Could not find artifacts for "only structs" solidity file

### ISSUE THREAD

**Issue by ericnordelo** [trufflesuite/truffle#4256] opened 2021-08-12 15:25 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Tests written in Solidity fail to run, because of the Structs.sol files containing only structs, and not contracts neither libraries. This happens because the compiler doesn't generate ABI (artifacts) for these files.

## Steps to Reproduce

Create on contract importing a Structs.sol file with only structs. Try to test that contract with Solidity test file. 

## Expected Behavior

Test runs successfully (like tests in javascript and project in general)

## Actual Results

The test fails with the next error:

Error: Could not find artifacts for /path/to/file/Structs.sol

This happens because the compiler doesn't generate ABI (artifacts) for these files.

A workaround is to add an empty library to the file, but this is a bad design and I think shouldn't be necessary 

## Environment

* Operating System: Ubuntu 20.04
* Ethereum client: testrpc
* Truffle version (`truffle version`): v5.4.5 (core: 5.4.5)
* node version (`node --version`): v10.19.0
* npm version (`npm --version`): 6.14.4

**Comment by gnidan** [comment] 2021-08-13 19:14
Yep. This is a known issue. Thanks for reporting!

**Comment by cds-amal** [comment] 2021-08-18 17:52
This is a duplicate of #3124, please follow progress there.

**Closed by cds-amal** 2021-08-18 17:52 UTC
