### ISSUE TITLE
Failed to install truffle

### ISSUE THREAD

**Issue by satchon** [trufflesuite/truffle#5129] opened 2022-05-19 14:57 UTC
Hi, I'm a beginner and sticking to install truffle.

I tried to install truffle via nvm and npm on ubuntu that was installed on a docker container.

- MacBook Air (13-inch, Mid 2013)
- Big Sur v11.6.5

- nvm : v16.15.0
- npm : v8.10.0

- failed command
`npm isntall -g truffle`

After failed to first try, I tried to as below to make node to build gyp.
`$ npm config set unsafe-perm true`

Then I retried to install truffle but the result was same.

Questions:
1. I'm not sure why `node-gyp-build` is denied.
2. How can I resolve `npm ERR! code 127`.

---------------------------
## Issue
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.15.0/lib/node_modules/truffle/node_modules/bufferutil
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! sh: 1: node-gyp-build: Permission denied
---------------------------

**Comment by realcliffzhang** [comment] 2022-05-19 15:32
Hmm your `nvm` is installed in `/root` which is why it may be giving you permission issues. Try logging in to your ubuntu machine as a non-root user, install `nvm` and give it another try? Thanks.

**Comment by cds-amal** [comment] 2022-05-19 15:40
Hey @satchon, images won't show up in searches and that diminishes the user experience. Can you share text instead? Thanks.

**Comment by satchon** [comment] 2022-05-19 15:45
@realcliffzhang 
Thanks. I try it.

**Comment by eggplantzzz** [comment] 2022-05-19 18:08
Hey @satchon, I think you still have a problem with your nvm installation and configuration. [Here is an npm article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) that gives more details on how to do this. What I mean is I don't think your `.nvm` folder should be installed in `/root`. On my local it is installed at `/Users/<myUserName>/.nvm`. This is likely the cause of your problems.

**Comment by satchon** [comment] 2022-05-29 16:39
@eggplantzzz, @realcliffzhang
Sorry for late reply. I'd been far from it for a while.
I tried to change the .nvm directory along the article. Then I could completed to install.
But now I'm sticking with truffle's 'permission denied'.
Anyway, I could one step forward thanks to your advices.
I'll keep it up.

**Comment by MicaiahReid** [comment] 2022-06-30 12:43
Closing for issue maintenance.

**Closed by MicaiahReid** 2022-06-30 12:43 UTC
