### ISSUE TITLE
 File import callback not supported

### ISSUE THREAD

**Issue by ygizhitsa** [trufflesuite/truffle#402] opened 2017-05-12 08:07 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

truffle migrate produces following output

PS C:\Projects\CTBaas\init> truffle migrate
Compiling .\contracts\ConvertLib.sol...
Compiling .\contracts\MetaCoin.sol...
Compiling .\contracts\Migrations.sol...

C:\Projects\CTBaas\init\contracts\MetaCoin.sol:3:1: : Source "ConvertLib.sol" not found: File import callback not supported
import "./ConvertLib.sol";
^------------------------^
Compilation failed. See above.

## Steps to Reproduce
1. run testrpc
2. run truffle migrate

## Expected Behavior

sol contracts are compiled and loaded to the testrpc 

## Actual Results
 PS C:\Projects\CTBaas\init> truffle migrate
Compiling .\contracts\ConvertLib.sol...
Compiling .\contracts\MetaCoin.sol...
Compiling .\contracts\Migrations.sol...

C:\Projects\CTBaas\init\contracts\MetaCoin.sol:3:1: : Source "ConvertLib.sol" not found: File import callback not supported
import "./ConvertLib.sol";

## Environment

* OS: Windows 10 /PowerShell 5.1
* Truffle version: Truffle v3.2.2
* Ethereum client:  name: 'ethereumjs-testrpc',
  description: '[![npm](https://img.shields.io/npm/v/ethereumjs-testrpc.svg)]() [![npm](https://img.shields.io/npm/dm/ethereumjs-testrpc.svg)]()',
  'dist-tags': { latest: '3.0.5', beta: '3.9.0' },

* node version: v7.10.0
* npm version:  4.5.0

**Comment by kowalski** [comment] 2017-05-12 12:13
I think this issue and https://github.com/trufflesuite/truffle/issues/400 are the same.

**Comment by tcoulter** [comment] 2017-05-12 18:09
Yep, this is a dupe of #400. Just fixed #400 (again). Closing this one in favor of that one.

**Closed by tcoulter** 2017-05-12 18:09 UTC

**Comment by niuwenchen** [comment] 2018-09-11 06:45
I just change  to
 import "../node_modules/openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol"; 
it done.

**Comment by AndreiD** [comment] 2019-05-28 17:03
or in VS Code settings

"solidity.packageDefaultDependenciesContractsDirectory": "",
 "solidity.packageDefaultDependenciesDirectory": "node_modules"

**Comment by Leocn** [comment] 2019-11-18 07:33
thx

**Comment by durgeshkmr** [comment] 2020-01-27 07:46
@niuwenchen  it worked , thanks
