### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by BaldyAsh** [trufflesuite/truffle#3076] opened 2020-05-27 15:14 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

While I compile the project (sorry, can’t provide any source), I got 2 different errors cases:

1) As I understand it happens when there are too many contracts in project
```sh
RuntimeError: memory access out of bounds
at wasm-function[6963]:639
at wasm-function[6197]:449
at wasm-function[6187]:691
at wasm-function[7439]:13
at invoke_ii (/Users/antongrigorev/.config/truffle/compilers/node_modules/soljson-v0.6.8+commit.0bbfe453.js:1:8756802)
at wasm-function[6194]:1333
at wasm-function[6187]:539
at wasm-function[7439]:13
at invoke_ii (/Users/antongrigorev/.config/truffle/compilers/node_modules/soljson-v0.6.8+commit.0bbfe453.js:1:8756802)
at wasm-function[6194]:1333
at wasm-function[6187]:539
at wasm-function[7439]:13
at invoke_ii (/Users/antongrigorev/.config/truffle/compilers/node_modules/soljson-v0.6.8+commit.0bbfe453.js:1:8756802)
at wasm-function[6194]:1333
at wasm-function[6187]:539
at wasm-function[6182]:453
at wasm-function[6181]:35
at wasm-function[7586]:21
at invoke_iiiiii (/Users/antongrigorev/.config/truffle/compilers/node_modules/soljson-v0.6.8+commit.0bbfe453.js:1:8757662)
at wasm-function[6104]:255
at wasm-function[7523]:17
at invoke_iiii (/Users/antongrigorev/.config/truffle/compilers/node_modules/soljson-v0.6.8+commit.0bbfe453.js:1:8757302)
at wasm-function[262]:104
at wasm-function[136]:331
at ccall (/Users/antongrigorev/.config/truffle/compilers/node_modules/soljson-v0.6.8+commit.0bbfe453.js:1:8312)
at /Users/antongrigorev/.config/truffle/compilers/node_modules/soljson-v0.6.8+commit.0bbfe453.js:1:8662
at runWithCallbacks (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/node_modules/solc/wrapper.js:151:1)
at compileStandard (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/node_modules/solc/wrapper.js:207:1)
at Object.compileStandardWrapper [as compile] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/node_modules/solc/wrapper.js:214:1)
at invokeCompiler (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:254:1)
at <anonymous>
```

2)When the project has more contracts than in the first case

```sh
Line 1, Column 1
Syntax error: value, object or array expected.

Line 1, Column 3
Extra non-whitespace after JSON value.
```
I can solve it with scripts for project compilation in parts. But I don’t like this decision

## Steps to Reproduce

Create a lot of contracts and try to compile. I have 371 contracts.

## Expected Behavior

Successfully compile

## Actual Results

Described at Issue section

## Environment

* Operating System: macOS 10.15.3
* Ethereum client: ganache
* Truffle version (`truffle version`): v5.1.20
* node version (`node --version`): v8.17.0
* npm version (`npm --version`): 6.13.4

**Comment by eggplantzzz** [comment] 2020-05-27 17:51
So this error looks like it is coming from the compiler. You might consider reporting this to the Solidity team. Can you provide a repo that we can use to try and reproduce your error? Thanks!

**Comment by gnidan** [comment] 2020-05-27 21:02
Have you tried using Docker or native solc? See [configuration docs](https://www.trufflesuite.com/docs/truffle/reference/configuration#solc) to learn how to switch. By default, we use the JS version of solc, and that's bound to cause memory problems with so many contracts. If you already have Docker installed on your machine, that's probably the easiest way to go (just add that `docker: true`, as described in the docs I linked)

**Comment by haltman-at** [comment] 2020-07-01 17:42
Closing this for issue maintenance.  Let us know if there's still a problem!

**Closed by haltman-at** 2020-07-01 17:42 UTC
