### ISSUE TITLE
Adding an `Event` breaks migration using `ABIEncoderV2`

### ISSUE THREAD

**Issue by pepoospina** [trufflesuite/truffle#2357] opened 2019-09-02 11:49 UTC
I am seeing a weird error after adding an event to a function of a contract that uses the `ABIEncoderV2`.

It compiles and migrates to gananche-cli correctly, but if I add an `Event` and `emit` it inside a function, it won't compile anymore and will show the error:

```
> Artifacts written to /tmp/test-119730-17164-1xtp5v5.yl35
> Compiled successfully using:
   - solc: 0.5.0+commit.1d4f565a.Emscripten.clang

Error: Error: Error: while migrating Uprtcl: components found but type is not tuple; report on GitHub
```

[This is the code compiling correctly](https://github.com/uprtcl/eth-uprtcl/commit/42af41692d3bc3fd87d335b25514e6157e41633f)
[This is the code not compiling](https://github.com/uprtcl/eth-uprtcl/commit/3ef3ded16adabef0a752f956ea6ac2784d7ee099)

The only difference is an event added to `Uprtcl.sol`.

## Steps to Reproduce

start `ganache-cli`
run `truffle test`

## Expected Behavior

Adding events should not break migrations.

## Actual Results

Migration stops working.

## Environment

- Ubuntu 16.04
- Truffle v5.0.19 (core: 5.0.19)
- Solidity v0.5.0 (solc-js)
- Node v12.9.1
- Web3.js v1.0.0-beta.37
- npm: '6.10.2',

**Comment by haltman-at** [comment] 2019-09-03 20:05
Wondering if this is a duplicate of [this](https://github.com/trufflesuite/truffle/issues/2085) earlier, seemingly fixed, issue.  Could you try this again after recompiling with the latest version of Truffle? Thanks!

**Comment by pepoospina** [comment] 2019-09-04 14:36
It might be, indeed it seems the problem is not always reproduced. I will give it a try by updating.

**Comment by haltman-at** [comment] 2019-09-18 18:06
Hi, was this issue successfully resolved?  Thank you!

**Comment by pepoospina** [comment] 2019-09-20 09:41
I am not sure. It was not reproducible.

**Comment by eggplantzzz** [comment] 2019-09-25 18:21
Closing for now for maintenance. If you find this problem consistently occurring then please let us know! Thanks!

**Closed by eggplantzzz** 2019-09-25 18:21 UTC
