### ISSUE TITLE
truffle compile started failing today - TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by d-sfounis** [trufflesuite/truffle#4039] opened 2021-05-18 09:05 UTC
- [ X ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Reinstalled truffle today, to get it to 5.3.6. A new project I'm working on, as well as old projects, now fail to compile.
Using solc 8.4, although my smart contracts are ^8.2 in dependencies.

I see my search history is littered with similar searches of getting the same `TypeError`, but I cannot remember the solution.

## Steps to Reproduce

`truffle compile` or `truffle compile --all`

## Expected Behavior

My contract to compile.

## Actual Results

```
Compiling your contracts...
===========================
TypeError: Cannot read property 'slice' of undefined
    at convertJsFunctionToWasm (/home/dimitris/.config/truffle/compilers/node_modules/soljson-v0.8.2+commit.661d1103.js:1:4559)
    at addFunctionWasm (/home/dimitris/.config/truffle/compilers/node_modules/soljson-v0.8.2+commit.661d1103.js:1:5839)
    at addFunction (/home/dimitris/.config/truffle/compilers/node_modules/soljson-v0.8.2+commit.661d1103.js:1:6092)
    at runWithCallbacks (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/solc/wrapper.js:143:1)
    at compileStandard (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/solc/wrapper.js:207:1)
    at Object.compileStandardWrapper [as compile] (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/solc/wrapper.js:214:1)
    at Object.parseImports (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/parser.js:41:1)
    at parseImports (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/loadParser.js:24:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:23:1)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:8:1
    at new Promise (<anonymous>)
    at exports.modules.824302.__awaiter (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:4:1)
    at Object.getImports (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/resolveAllSources.js:58:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/resolveAllSources.js:5:42)
Truffle v5.3.6 (core: 5.3.6)
Node v14.17.0
```

## Environment

* Operating System: Ubuntu 20.04
* Ethereum client: --
* Truffle version (`truffle version`): 5.3.6
* node version (`node --version`): 14.17.0
* npm version (`npm --version`): 7.13.0

**Comment by haltman-at** [comment] 2021-05-18 19:20
Hm, that's odd.  Yes we've had this problem with Solidity 0.8.2 specifically; it seems to be an issue with Solidity and its soljson; likely you should file an issue there about it.  However you say you're using Solidity 0.8.4.  Now, looking at the stacktrace, you can see it calls into 0.8.2, so evidently something is causing Truffle to use 0.8.2 in this case.  You're certain you're using 0.8.4?  Can you check your project's Truffle config?  Thanks!

**Comment by d-sfounis** [comment] 2021-05-18 19:24
Hey haltman,

Thanks for the heads-up, it worked.

My `packages.json` had `solc >=0.8.4` in its dependencies, but `truffle-config.js` called `solc 0.8.2`. Switched to solc 0.8.4 and things compile just fine now.

Would you like me to close the issue?

**Comment by cds-amal** [comment] 2021-05-19 17:49
Hi @d-sfounis,

I'm going to close this issue as this is a Solidity issue. Can you [open an issue with them](https://github.com/ethereum/solidity/issues)? Thanks!

**Closed by cds-amal** 2021-05-19 17:49 UTC

**Comment by nogo10** [comment] 2021-11-23 14:53
According to [Solidity #11489](https://github.com/ethereum/solidity/issues/11489)   it's a truffle unresolved issue for me. As posted on gitter:

! I tried changing config solidity versions to 0.8.7, 0.8.10 same error:


```
# truffle deploy                                                                                                                                                   

Compiling your contracts...
===========================
TypeError: Cannot read property 'slice' of undefined
    at convertJsFunctionToWasm (/root/.config/truffle/compilers/node_modules/soljson-v0.8.10+commit.fc410830.js:1:4130)
    at addFunction (/root/.config/truffle/compilers/node_modules/soljson-v0.8.10+commit.fc410830.js:1:5488)
    at runWithCallbacks (/root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/node_modules/solc/wrapper.js:143:1)
    at compileStandard (/root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/node_modules/solc/wrapper.js:207:1)
    at Object.compileStandardWrapper [as compile] (/root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/node_modules/solc/wrapper.js:214:1)
    at Object.parseImports (/root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/parser.js:41:1)
    at parseImports (/root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/loadParser.js:24:1)
    at Object.<anonymous> (/root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:23:1)
    at Generator.next (<anonymous>)
    at /root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:8:1
    at new Promise (<anonymous>)
    at exports.modules.824302.__awaiter (/root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:4:1)
    at Object.getImports (/root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:19:1)
    at /root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/resolveAllSources.js:58:1
    at Generator.next (<anonymous>)
    at fulfilled (/root/.nvm/versions/node/v12.16.3/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/resolveAllSources.js:5:42)
Truffle v5.3.9 (core: 5.3.9)
Node v12.16.3
```

**Comment by haltman-at** [comment] 2021-11-23 21:07
@nogo10 Can you try reproducing the issue on the latest Truffle version?  Thanks!

**Comment by nogo10** [comment] 2021-11-24 01:30
Upgrade to Truffle v5.4.22 , now deploy works again.

**Comment by haltman-at** [comment] 2021-11-24 09:29
OK, thanks, going to leave this closed then!

**Comment by Justice-Orogun** [comment] 2022-12-19 08:52
> @nogo10 Can you try reproducing the issue on the latest Truffle version? Thanks!

@nogo10 it seems like I am having the same issues right now...

**Comment by Justice-Orogun** [comment] 2022-12-19 08:56
My Solidity version is ^0.8.17
I wanted to compile using "truffle compile" command prompt. Unfortunately, it couldn't compile. It threw back the error below. Who has experienced something like this? Any help, please? 


$ truffle compile
- Fetching solc version list from solc-bin
TypeError: Error parsing C:/Users/USER/Justice Orogun Token/src/contracts/DaiToken.sol: Cannot read properties of undefined (reading 'addFunction')
    at runWithReadCallback (C:\Users\USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\solc\wrapper.js:37:1)
    at compileStandard (C:\Users\USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\solc\wrapper.js:78:1)
    at Object.compileStandardWrapper (C:\Users\USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\solc\wrapper.js:85:1)
    at Object.parseImports (C:\Users\USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-compile\parser.js:47:1)
    at Object.getImports (C:\Users\USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-compile\profiler.js:374:1)
    at C:\Users\USER\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-compile\profiler.js:346:1
Truffle v5.0.5 (core: 5.0.5)
Node v18.12.1

**Comment by haltman-at** [comment] 2022-12-19 21:56
@Justice-Orogun Can you reproduce the issue on the latest version of Truffle?  Thanks!  (If not, I'm going to leave this closed.)

**Comment by whileMeAwakeMeCode** [comment] 2023-06-27 02:52
Got the same error using 
- truffle ^5.4.22
- solc 0.8.19
- node 14.15.5 or 16.15.0

I wanted to use a relatively recent solc version but I'm unable to do so.
solc 0.8.4 seem to work when `truffle deploy` but is failing during some chai/ganache tests.

Does anyone have found a coherent config ? I need to set a clean forkable public repo so bad !

**Comment by haltman-at** [comment] 2023-06-27 17:42
@whileMeAwakeMeCode Can you reproduce this issue with the latest Truffle version?  Thanks!  (Or did you mean you're unable to use a recent Truffle version, rather than a recent Solc version?  If so, why is that, if you don't mind me asking?)
