### ISSUE TITLE
"truffle/Assert.sol" &  "truffle/DeployedAddresses.sol" not found: File not supplied initially.

### ISSUE THREAD

**Issue by KurtLorey** [trufflesuite/truffle#787] opened 2018-01-31 16:15 UTC
Issue

With truffle 4.0.5 on windows, test files fail to "import" with error:

'Error'
ParserError: Source "truffle/Assert.sol" not found: File not supplied initially.
import "truffle/Assert.sol";
ParserError: Source "truffle/DeployedAddresses.sol" not found: File not supplied initially.
import "truffle/DeployedAddresses.sol";

Steps to Reproduce

Created a test file and try to import truffle/Assert.sol and truffle/DeployedAddresses.sol

Expected Behavior

Test script should import scripts identified

Actual Results

Error not found: File not supplied initially.

Environment

    Operating System: Windows 10
    Visual Studio Code
    Truffle version: 4.0.5
    ganache-cli@6.0.3
    node version: 8.9.4
    npm version:  5.6.0

**Comment by malaravannm** [comment] 2018-02-03 22:57
truffle/Assert.sol and DeployedAddresses.sol files are missing for me also. I am following Truffle's metacoin example steps, at what stage these files should have been created. I noticed when test command showed  0 passing message. Didn't receive any error message till this point.

truffle(develop)> truffle test
Using network 'develop'.
  0 passing (0ms)

**Comment by cgewecke** [comment] 2018-02-11 20:30
@KurtLorey @malaravannm This issue has also been raised in #756. In that instance, the poster re-installed their project and the issue self-resolved. They were also on Windows using VS Code. If someone discovers why this is happening or if the steps suggested don't work please feel free to re-open or comment here. 

Closing as duplicate of #756.

**Closed by cgewecke** 2018-02-11 20:30 UTC

**Comment by nukec** [comment] 2018-05-15 15:00
reinstalling project doesn't work.

**Comment by chainchaser** [comment] 2018-05-29 10:16
same here... not working on windows 10 environment.

VS Code, 
Windows10,
truffle 4.1.11
node 8.11.2
npm 5.6.2

is there any way to solve it?

**Comment by FahdLihidheb** [comment] 2018-07-26 10:33
what is mean by reinstalling the project ?
i deleted the project that i am working on ( pet-shop tutorial ) and cloned ( pet-shop-box ) and nothing changed. 
and where should the global Truffle files be ?

**Comment by birutavideo** [comment] 2018-08-12 02:31
It seems that this issue is related to [naming conflict](https://truffleframework.com/docs/truffle/reference/configuration#resolving-naming-conflicts-on-windows) in Win env.
Try moving/renaming **truffle.js** in project root dir to truffle-config.js. This works for me.

**Comment by sebastiankozub** [comment] 2018-09-24 23:55
Try to install truffle with -g option...

**Comment by souravk9709** [comment] 2018-12-12 11:44
> From the windos command line (i.e. the gitbash command line) it didn't work for me (Windows 7). But it worked from the truffle develop command line
> truffle develop
> truffle(develop)> test
> or
> truffle(develop)> test ./test/TestMetacoin.sol
> truffle(develop)> test ./test/metacoin.js

Thanks it worked over truffle(develop)>

**Comment by JamesEarle** [comment] 2021-03-25 16:54
I am working through the [Pet Shop](https://www.trufflesuite.com/tutorials/pet-shop) tutorial and was having the same issue. Truffle's "magic" files that aren't anywhere in your repository were causing errors to show up in my tests, although the tests still ran and passed fine.

> Try to install truffle with -g option...

Doing this with `npm install truffle -g` and restarting VS Code fixed the issue. Thanks @sebastiankozub

**Comment by ndrslmpk** [comment] 2021-11-13 23:24
Same issue here on Windows 10.
Truffle v5.4.5 (core: 5.4.5)
Solidity - ^0.8.0 (solc-js)
Node v16.6.1
Web3.js v1.5.1

Isn't there a way to locally download the truffle folders?

**Comment by cds-amal** [comment] 2021-11-17 06:34
@ndrslmpk Can you open a new issue please? This will help us track and investigate the problem more efficiently. Thanks you!

**Comment by DigiCris** [comment] 2023-01-04 03:25
Also happening on my ubuntu and I can't find a way to fix it.

**Comment by cds-amal** [comment] 2023-01-04 04:25
Hi @DigiCris, can you open a new issue for this, please? What version of truffle are you using, and, if possible, do you have a repo you can share?
