### ISSUE TITLE
Problem installing truffle-hdwallet-provider

### ISSUE THREAD

**Issue by Chococoin** [trufflesuite/truffle#2159] opened 2019-07-06 14:43 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I can't install truffle-hdwallet-provider on different platforms getting the same error.

## Steps to Reproduce

Here a Dockerfile
https://gist.github.com/Chococoin/08c0b3cc05f48dd8b0ec75997e2719c9

The error triggers with:
npm install -g truffle-hdwallet-provider

## Expected Behavior

truffle-hdwallet-provider installed successfully.

## Actual Results

gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/truffle-hdwallet-provider/node_modules/scrypt/.node-gyp'

Here also the long error log:
https://gist.github.com/Chococoin/08c0b3cc05f48dd8b0ec75997e2719c9

## Environment

* Operating System: I've tried with Ubuntu 16, 18 / Window 10 / Alpine 3.8 / macOs Mojavi.
* Ethereum client:
* Truffle version (`truffle version`): 5.0.26
* node version (`node --version`): v8.16.0
* npm version (`npm --version`): 6.4.1

**Comment by gnidan** [comment] 2019-07-06 16:45
Looks like you need to add `/usr/local/lib/node_modules` to the `node` user group and ensure the permissions are set.

**Comment by eggplantzzz** [comment] 2019-07-10 17:38
We're going to close this. If the problem is different from what we thought, then we can re-open it. Thanks!

**Closed by eggplantzzz** 2019-07-10 17:38 UTC

**Comment by Chococoin** [comment] 2019-07-21 21:50
Sorry, I didn't understand the solution given. But if you said it's Ok... Ok.
