### ISSUE TITLE
Invalid number of parameters for "undefined". Got 3 expected 5!

### ISSUE THREAD

**Issue by marcpre** [trufflesuite/truffle#4947] opened 2022-03-26 21:55 UTC
## Issue

I am currently developing a new contract and when I try to migrate the contract I get:

```

"rNFT" -- Invalid number of parameters for "undefined". Got 3 expected 5!.

```

## Steps to Reproduce

Find below my contract. All imports are openzeppelin contracts:

```

pragma solidity >=0.7.0 <0.9.0;

import "./IERC165.sol";
import "./IERC721.sol";
import "./IERC721Enumerable.sol";
import "./ERC165.sol";
import "./Strings.sol";
import "./Address.sol";
import "./IERC721Metadata.sol";
import "./IERC721Receiver.sol";
import "./ERC721.sol";
import "./ERC721Enumerable.sol";
import "./Ownable.sol";

contract rNFTs is ERC721Enumerable, Ownable {
  using Strings for uint256;

  string baseURI; //NFT json is saved
  string linkURL;
  string public baseExtension = ".json";
  uint256 public cost; // = 0.0 ether;
  uint256 public maxMintAmount = 1;
  bool public isInVault = false;

  constructor(
    string memory _name,
    string memory _symbol,
    string memory _initBaseURI
  ) ERC721(_name, _symbol) {
    setBaseURI(_initBaseURI);
  }

  // internal
  function _baseURI() internal view virtual override returns (string memory) {
    return baseURI;
  }

  // public
  function mint(string memory _linkURL) public payable {
    uint256 supply = totalSupply();

    if (msg.sender != owner()) {
      require(msg.value >= cost);
    }

    setLinkURL(_linkURL);

    _safeMint(msg.sender, supply + 1);
  }

  function walletOfOwner(address _owner)
    public
    view
    returns (uint256[] memory)
  {
    uint256 ownerTokenCount = balanceOf(_owner);
    uint256[] memory tokenIds = new uint256[](ownerTokenCount);
    for (uint256 i; i < ownerTokenCount; i++) {
      tokenIds[i] = tokenOfOwnerByIndex(_owner, i);
    }
    return tokenIds;
  }

  function tokenURI(uint256 tokenId)
    public
    view
    virtual
    override
    returns (string memory)
  {
    require(
      _exists(tokenId),
      "ERC721Metadata: URI query for nonexistent token"
    );

    string memory currentBaseURI = _baseURI();
    return bytes(currentBaseURI).length > 0
        ? string(abi.encodePacked(currentBaseURI, tokenId.toString(), baseExtension))
        : "";
  }

  //only owner
  function setIsInVault() public onlyOwner {
      isInVault = true;
  }

  function setLinkURL(string memory _linkUrl) public onlyOwner {
      linkURL = _linkUrl;
  }

  function setCost(uint256 _newCost) public onlyOwner {
    cost = _newCost;
  }

  function setmaxMintAmount(uint256 _newmaxMintAmount) public onlyOwner {
    maxMintAmount = _newmaxMintAmount;
  }

  function setBaseURI(string memory _newBaseURI) public onlyOwner {
    baseURI = _newBaseURI;
  }

  function setBaseExtension(string memory _newBaseExtension) public onlyOwner {
    baseExtension = _newBaseExtension;
  }

  function withdraw() public payable onlyOwner {

    // Do not remove this otherwise you will not be able to withdraw the funds.
    (bool os, ) = payable(owner()).call{value: address(this).balance}("");
    require(os);
  }
}

```

## Expected Behavior

Successful migration.

## Actual Results

I get the following error message:

```

1_initial_migration.js
======================

   Replacing 'rNFT'
   ----------------
 *** Deployment Failed ***

"rNFT" -- Invalid number of parameters for "undefined". Got 3 expected 5!.


Exiting: Review successful transactions manually by checking the transaction hashes above on Etherscan.


Error:  *** Deployment Failed ***

"rNFT" -- Invalid number of parameters for "undefined". Got 3 expected 5!.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:379:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
    at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:121:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:86:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:78:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)
UnhandledRejections detected
Promise {
  <rejected> Error: Invalid number of parameters for "undefined". Got 3 expected 5!
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:348:1
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
      at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
      at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
      at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
      at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
      at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:121:1)
      at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:86:1)
      at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:78:1)
      at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
      at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1) {
    hijackedStack: 'Error: Invalid number of parameters for "undefined". Got 3 expected 5!\n' +
      '    at Object.InvalidNumberOfParams (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/lib/errors.js:33:1)\n' +
      '    at Object._createTxObject (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:669:1)\n' +
      '    at Contract.deploy (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:501:1)\n' +
      '    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:275:1\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  _events: Events <[Object: null prototype] {}> {},
  emit: [Function: emit],
  on: [Function: on],
  once: [Function: once],
  off: [Function: removeListener],
  listeners: [Function: listeners],
  addListener: [Function: on],
  removeListener: [Function: removeListener],
  removeAllListeners: [Function: removeAllListeners],
  _eventsCount: 0
} Error: Invalid number of parameters for "undefined". Got 3 expected 5!
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:348:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
    at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:121:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:86:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:78:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1) {
  hijackedStack: 'Error: Invalid number of parameters for "undefined". Got 3 expected 5!\n' +
    '    at Object.InvalidNumberOfParams (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/lib/errors.js:33:1)\n' +
    '    at Object._createTxObject (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:669:1)\n' +
    '    at Contract.deploy (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:501:1)\n' +
    '    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:275:1\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}


```

My migration file looks like the following:

```

var rNFT = artifacts.require("../contracts/rNFT.sol");

/*
module.exports = function(deployer) {
  deployer.deploy(rNFT);
};
*/
// convert ether to wei - https://ethereum.stackexchange.com/questions/124350/how-to-fix-underflow/124354#124354
module.exports = function(deployer) {
  //deployer.deploy(rNFT, "rNFT", "rNFT", "http://localhost:3000/", "120000000000000000");
  deployer.deploy(rNFT, "rNFT", "rNFT", "http://localhost:3000/");
};

```

As you can see in the above contract my constructor only takes 3 parameter, not 5.

## Environment

* Operating System: Ubuntu 20.4
* Ethereum client: Ganach
* Truffle version (`truffle version`): Truffle v5.5.5
* node version (`node --version`): v16.14.0
* npm version (`npm --version`): 8.3.1

I appreciate your reply!

**Comment by marcpre** [comment] 2022-03-27 09:36
Even when deploying on `JS VM - London` in remix I only use three parameters in the constructor: 

![image](https://user-images.githubusercontent.com/30902582/160275613-f4d5ad5b-24ef-4259-9980-cefbfbc08dba.png)

**Comment by marcpre** [comment] 2022-03-27 10:48
One more question for this issue: Is there a way to completely reset `ganache` and `truffle`?

**Comment by eggplantzzz** [comment] 2022-03-28 15:15
Is your project on GitHub somewhere that we can take a look? It's hard to help troubleshoot with just pasted contracts :)

If you wan to clear out your compiled contracts you can delete the `build` folder - and for Ganache you can just restart it. Is that what you are looking for?

**Comment by haltman-at** [comment] 2022-03-28 18:55
@marcpre It looks to me like the problem is that you're using `artifacts.require` incorrectly.  The argument to `artifacts.require` should be the name of the contract, not the file the contract is defined in.  So `const rNFT = artifacts.require("rNFTs")`.

**Comment by haltman-at** [comment] 2022-04-27 03:00
Closing this for issue maintenance.  @marcpre, let us know if there's still a problem and if so we can perhaps reopen this.

**Closed by haltman-at** 2022-04-27 03:00 UTC
