### ISSUE TITLE
Provide better error messaging when Truffle fails to compile due to missing compiler version

### ISSUE THREAD

**Issue by Aniket-Engg** [trufflesuite/truffle#2156] opened 2019-07-04 20:10 UTC
Truffle is not able to download solidity compiler 0.5.10 even it is show in the compiler list.

## Issue

$ truffle compile --list
[
 "0.5.10",
 "0.5.9",
 "0.5.8",
 "0.5.7",
 "0.5.6",
 "0.5.5",
 "0.5.4",
 "0.5.3",
 "0.5.2",
 "0.5.1",
 ".. and 45 more. Use `--all` to see full list."
]

$ truffle compile
Error: Could not find a compiler version matching 0.5.10. Please ensure you are specifying a valid version, constraint or build in the truffle config. Run `truffle compile --list` to see available versions.

## Steps to Reproduce

Compile a smart contract with version 0.5.10

## Expected Behavior

It should download version as it is mentioned in truffle-config.js file and compile the contract.

## Environment
* Truffle version (`truffle version`): 5.0.26
* node version (`node --version`): 11.10.0

**Comment by icherkashin** [comment] 2019-07-05 07:33
Hello @Aniket-Engg 

I cannot reproduce your problem: the compiler is downloaded. However, I am using `node v11.15.0`, not `v11.10.0`: perhaps it will work if you update `node`?

Here is my `truffle-config.js`, which specifies the `0.5.10` compiler:

```
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*"
    },
  },
  compilers :{
    solc: {
      version: '0.5.10'
    }
  }
}
```

**Comment by Aniket-Engg** [comment] 2019-07-05 18:45
@icherkashin I updated node js version, keep the truffle-config.js same as yours, still error persists.

**Comment by eggplantzzz** [comment] 2019-07-05 19:45
@Aniket-Engg I also am able to use the latest Solidity compiler on that version of Truffle. Can you post your Truffle config here?

**Comment by Aniket-Engg** [comment] 2019-07-05 20:24
Here it is: 
```
/**
 * Use this file to configure your truffle project. It's seeded with some
 * common settings for different networks and features like migrations,
 * compilation and testing. Uncomment the ones you need or modify
 * them to suit your project as necessary.
 *
 * More information about configuration can be found at:
 *
 * truffleframework.com/docs/advanced/configuration
 *
 * To deploy via Infura you'll need a wallet provider (like truffle-hdwallet-provider)
 * to sign your transactions before they're sent to a remote public node. Infura accounts
 * are available for free at: infura.io/register.
 *
 * You'll also need a mnemonic - the twelve word phrase the wallet uses to generate
 * public/private key pairs. If you're publishing your code to GitHub make sure you load this
 * phrase from a file you've .gitignored so it doesn't accidentally become public.
 *
 */

// const HDWalletProvider = require('truffle-hdwallet-provider');
// const infuraKey = "fj4jll3k.....";
//
// const fs = require('fs');
// const mnemonic = fs.readFileSync(".secret").toString().trim();

module.exports = {
  /**
   * Networks define how you connect to your ethereum client and let you set the
   * defaults web3 uses to send transactions. If you don't specify one truffle
   * will spin up a development blockchain for you on port 9545 when you
   * run `develop` or `test`. You can ask a truffle command to use a specific
   * network from the command line, e.g
   *
   * $ truffle test --network <network-name>
   */

  networks: {
    // Useful for testing. The `development` name is special - truffle uses it by default
    // if it's defined here and no other network is specified at the command line.
    // You should run a client (like ganache-cli, geth or parity) in a separate terminal
    // tab if you use this network and you must also set the `host`, `port` and `network_id`
    // options below to some value.
    //
    development: {
     host: "127.0.0.1",     // Localhost (default: none)
     port: 8545,            // Standard Ethereum port (default: none)
     network_id: "*",       // Any network (default: none)
    },

    // Another network with more advanced options...
    // advanced: {
      // port: 8777,             // Custom port
      // network_id: 1342,       // Custom network
      // gas: 8500000,           // Gas sent with each transaction (default: ~6700000)
      // gasPrice: 20000000000,  // 20 gwei (in wei) (default: 100 gwei)
      // from: <address>,        // Account to send txs from (default: accounts[0])
      // websockets: true        // Enable EventEmitter interface for web3 (default: false)
    // },

    // Useful for deploying to a public network.
    // NB: It's important to wrap the provider as a function.
    // ropsten: {
      // provider: () => new HDWalletProvider(mnemonic, `https://ropsten.infura.io/v3/YOUR-PROJECT-ID`),
      // network_id: 3,       // Ropsten's id
      // gas: 5500000,        // Ropsten has a lower block limit than mainnet
      // confirmations: 2,    // # of confs to wait between deployments. (default: 0)
      // timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
      // skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
    // },

    // Useful for private networks
    // private: {
      // provider: () => new HDWalletProvider(mnemonic, `https://network.io`),
      // network_id: 2111,   // This network is yours, in the cloud.
      // production: true    // Treats this network as if it was a public net. (default: false)
    // }
  },

  // Set default mocha options here, use special reporters etc.
  mocha: {
    // timeout: 100000
  },

  // Configure your compilers
  compilers: {
    solc: {
       version: "0.5.10",    // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
      //  optimizer: {
      //    enabled: false,
      //    runs: 200
      //  },
      //  evmVersion: "byzantium"
      // }
    }
  }
}

```

**Comment by gnidan** [comment] 2019-07-05 20:50
Can you try to do `truffle obtain --solc=0.5.10` and see if that works for you?

**Comment by Aniket-Engg** [comment] 2019-07-05 20:54
@gnidan Yeah this works !
```
> Warning: possible unsupported (undocumented in help) command line option: --solc=0.5.10
    > successfully downloaded and cached 0.5.10+commit.5a6ea5b1.Emscripten.clang
```

**Comment by gnidan** [comment] 2019-07-05 20:54
Huh that warning shouldn't be there. That's good to know! Does it compile now?

**Comment by Aniket-Engg** [comment] 2019-07-05 20:55
yes

**Comment by gnidan** [comment] 2019-07-05 20:56
Great! Weird. Not sure why this was failing; your config looks correct. You don't have two config files, do you? (We were using `truffle.js` AND `truffle-config.js` both for awhile, but now we've standardized on only the latter)

**Comment by Aniket-Engg** [comment] 2019-07-05 20:57
No, I have only truffle-config.js with almost all other default options. It was accepting only till 0.5.8

**Comment by gnidan** [comment] 2019-07-05 20:57
Gosh. I hope my #2109 PR didn't break anything! I'll see what I can figure out.

**Comment by gnidan** [comment] 2019-07-05 20:58
(leaving this open as a task to improve messaging)

**Comment by icherkashin** [comment] 2019-07-06 05:54
@gnidan @Aniket-Engg 

Probably, the presence of an equal sign `=` in `--solc=0.5.10` causes the warning. I.e. the command should have been `truffle obtain --solc 0.5.10`, not `truffle obtain --solc=0.5.10`.

https://github.com/trufflesuite/truffle/blob/03119a1c193ac5425e8c8d0bd4e466d822bf2d6d/packages/truffle-core/lib/commands/obtain.js#L8

**Comment by eggplantzzz** [comment] 2019-07-10 15:53
Yes @icherkashin, that is right. I suppose we need to replace the `=` with ` ` before checking the options.

**Comment by haltman-at** [comment] 2020-04-08 18:05
This should be fixed in most recent version of Truffle, so I'm closing this.  Let us know if there are further issues.

**Closed by haltman-at** 2020-04-08 18:05 UTC
Labels: error better
