### ISSUE TITLE
truffle unboox webpack ,but it is  failed!  TypeError: Cannot read property 'status' of undefined. how to solve it.

### ISSUE THREAD

**Issue by ouxiaobai** [trufflesuite/truffle#4057] opened 2021-05-20 13:56 UTC
## Issue

TypeError: Cannot read property 'status' of undefined

## Steps to Reproduce

truffle unboox webpack

## Actual Results

Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
TypeError: Cannot read property 'status' of undefined
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:41:1
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:6:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.3.6 (core: 5.3.6)
Node v10.19.0
## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`v5.3.6`):
* node version (`v10.19.0`):
* npm version (`6.14.4`):

**Comment by eggplantzzz** [comment] 2021-05-20 16:55
Hi, I saw your other issue https://github.com/trufflesuite/truffle/issues/4053. Is that one no longer relevant?

**Comment by ouxiaobai** [comment] 2021-05-21 01:46
> Hi, I saw your other issue #4053. Is that one no longer relevant?

I updated the truffle to the latest version. Truffle init succeeded, but truffle unbox webpack failed.

**Comment by haltman-at** [comment] 2021-05-21 04:54
Can you try this again with Truffle 5.3.7?  This sounds like the error that was just fixed in #4046, which we just released in 5.3.7.  Could you try it with the latest Truffle and see if there's still a problem?  Thanks!

**Comment by gnidan** [comment] 2021-07-28 18:10
Closing this one for issue maintenance. If the problem is still giving you trouble @ouxiaobai, please let us know so we can get eyes back on it. Thank you!

**Closed by gnidan** 2021-07-28 18:10 UTC
