### ISSUE TITLE
Can not install truffle

### ISSUE THREAD

**Issue by narendrabluecrest** [trufflesuite/truffle#3104] opened 2020-06-13 13:27 UTC
Node and npm version are as given below
nkt@nkt-OptiPlex-3020:~$ node -v
v12.18.0
nkt@nkt-OptiPlex-3020:~$ nodejs -v
v10.21.0
nkt@nkt-OptiPlex-3020:~$ npm -v
6.14.4

I am getting the below mentioned errors after running the command

nkt@nkt-OptiPlex-3020:~$ npm install -g truffle
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > undefined prepare /home/nkt/truffle
npm ERR! prepareGitDep > lerna run prepare --stream --concurrency=1
npm ERR! prepareGitDep 
npm ERR! prepareGitDep @truffle/blockchain-utils: yarn run v1.22.4
npm ERR! prepareGitDep @truffle/blockchain-utils: $ yarn build
npm ERR! prepareGitDep @truffle/blockchain-utils: $ tsc
npm ERR! prepareGitDep @truffle/blockchain-utils: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! prepareGitDep @truffle/blockchain-utils: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep lerna notice cli v3.22.1
npm ERR! prepareGitDep lerna info versioning independent
npm ERR! prepareGitDep lerna info Executing command in 14 packages: "yarn run prepare"
npm ERR! prepareGitDep @truffle/blockchain-utils: /bin/sh: 1: tsc: not found
npm ERR! prepareGitDep @truffle/blockchain-utils: error Command failed with exit code 127.
npm ERR! prepareGitDep @truffle/blockchain-utils: error Command failed with exit code 127.
npm ERR! prepareGitDep lerna ERR! yarn run prepare exited 127 in '@truffle/blockchain-utils'
npm ERR! prepareGitDep lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! syscall spawn
npm ERR! prepareGitDep npm ERR! file sh
npm ERR! prepareGitDep npm ERR! errno ENOENT
npm ERR! prepareGitDep npm ERR! undefined prepare: `lerna run prepare --stream --concurrency=1`
npm ERR! prepareGitDep npm ERR! spawn ENOENT
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the undefined prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/nkt/.npm/_logs/2020-06-13T13_22_07_616Z-debug.log
npm ERR! prepareGitDep 
npm ERR! code 1
npm ERR! null: npm exited with code 1 while attempting to build undefined. Clone the repository manually and run 'npm install' in it for more information.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nkt/.npm/_logs/2020-06-13T13_22_07_708Z-debug.log

**Comment by CruzMolina** [comment] 2020-06-17 15:08
Hi @narendrabluecrest !

Can you run `npm config ls` and `npm config get unsafe-perm` and share your output?

**Comment by fainashalts** [comment] 2020-06-17 17:38
There's a chance this is due to needing to have git installed. Can you make sure you have git installed on your machine and see if that fixes the issue?

**Comment by CruzMolina** [comment] 2020-06-22 18:29
Ran into this issue and the stack trace led me to `nvm`.
Sourcing the alias appropriately resolved the issue.

I'm guessing this must be an issue with `npm`. Maybe the alias or something with the installation/setup of `npm`.

**Comment by CruzMolina** [comment] 2020-06-22 18:36
Closing this as a duplicate of #3100.

**Closed by CruzMolina** 2020-06-22 18:36 UTC

**Comment by CruzMolina** [comment] 2020-06-23 00:13
@narendrabluecrest , do you happen to have the `truffle` monorepo cloned locally when you run into this issue?
