### ISSUE TITLE
npx truffle unbox webpack.but it is not success.how to solve it? thanks.

### ISSUE THREAD

**Issue by ouxiaobai** [trufflesuite/truffle#4053] opened 2021-05-20 02:10 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

npx truffle unbox webpack

## Actual Results

Downloading...
Error: Error making request to https://raw.githubusercontent.com/truffle-box/webpack-box/master/truffle-box.json. Got error: Client network socket disconnected before secure TLS connection was established. Please check the format of the requested resource.
    at Request._callback (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-box/lib/utils/unbox.js:45:1)
    at self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:877:1)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`4.1.15`):
* node version (`v10.19.0`):
* npm version (`6.14.4`):

**Comment by fainashalts** [comment] 2021-05-26 17:39
Hi @ouxiaobai can you try this with a newer version of Truffle (5+)? Please let us know if that solves the issue, thanks!

**Comment by fainashalts** [comment] 2021-05-26 17:45
Closing as duplicate of #4057.

**Closed by fainashalts** 2021-05-26 17:45 UTC
