### ISSUE TITLE
how to open the truffledemo in Visual studio code

### ISSUE THREAD

**Issue by vidhyaramani** [trufflesuite/truffle#874] opened 2018-03-28 11:37 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by vidhyaramani** [comment] 2018-03-28 11:39
I have unbox metacoin and compiled it every was fine! But need to know how this demo comes to the visual studio code... I have also installed solidity....Please help me   thanks!

**Comment by cgewecke** [comment] 2018-03-28 14:36
@vidhyaramani Hi. This is a good question for the gitter channel rather than the Github issues. Here we just try address bug reports and feature proposals. There's some additional discussion project setup issues in visual studio [here](https://github.com/trufflesuite/truffle/issues/756).

Closing as duplicate of #756

**Closed by cgewecke** 2018-03-28 14:36 UTC
