### ISSUE TITLE
Debugging a transaction in (develop) mode gives Error

### ISSUE THREAD

**Issue by TechBeatle** [trufflesuite/truffle#2732] opened 2020-01-08 07:44 UTC
I've seen someone asked for help about the same issue in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue. But no answer was provided.

---------------------------

## Issue

I am using React with truffle for development.
I am trying to use the Debugger package to debug a transaction. I have used both truffle and truffle(debug) and face the same issue. 

## Steps to Reproduce

- compile the simplestorage.sol contract.
- migrate
- perform a transaction
- Debug that transaction with Tx_hash or Tx_ID

## Expected Behavior

It should start debugging

## Actual Results

```
truffle(develop)> debug 0x712d374ee26d599439899ca2b82f4322f586db14b7d680b2406d5cd4f700141d
Starting Truffle Debugger...
√ Compiling your contracts...
- Gathering information about your project and the transaction...Error: Cannot find module "."
    at webpackMissingModule (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\debugger\node_modules\semver\index.js:3:52)
    at lazyRequire (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\debugger\node_modules\semver\index.js:3:52)
    at Object.get [as satisfies] (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\debugger\node_modules\semver\index.js:10:1)
    at contextRequiresPhantomStackframes (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\debugger\dist\debugger.js:1015:1)
    at C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\reselect\es\index.js:70:1
    at C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\reselect\es\index.js:30:1
    at C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\reselect\es\index.js:84:1
    at C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\reselect\es\index.js:30:1
    at runSelectEffect (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:730:1)
    at runEffect (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:1204:1)
    at digestEffect (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:1271:1)
    at next (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:1161:1)
    at currCb (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:1251:1)
    at C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:481:1
    at exec (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:31:1)
    at flush (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:87:1)
    at asap (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:46:1)
    at runPutEffect (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:468:1)
    at runEffect (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:1204:1)
    at digestEffect (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:1271:1)
    at next (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:1161:1)
    at currCb (C:\Users\CS4389\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\@redux-saga\core\dist\redux-saga-core.esm.js:1251:1) {
  code: 'MODULE_NOT_FOUND'
}
The above error occurred in task session.saga
Tasks cancelled due to error:
listenerSaga
controller.saga
data.saga
evm.saga
solidity.saga
trace.saga
web3.saga
```

## Environment

* Operating System: Windows 10
* Ethereum client: Ganache and development network
* Truffle version (`truffle version`): 5.1.7
* node version (`node --version`): 12.14.0
* npm version (`npm --version`): 6.13.4

**Comment by fainashalts** [comment] 2020-01-08 18:56
Hi @TechBeatle, thank you for bringing this to our attention! Can you try this on 5.1.6 and/or 5.1.4 and let us know if you encounter the same problem?

**Comment by TechBeatle** [comment] 2020-01-09 01:47
@fainashalts Thank you. Working on 5.1.4

**Comment by theoretical2019** [comment] 2020-01-10 23:08
Also experiencing same issue.  Fixed by downgrading to 5.1.4.

```
$ truffle version
Truffle v5.1.8 (core: 5.1.8)
Solidity v0.5.12 (solc-js)
Node v10.16.0
Web3.js v1.2.1
```

Perhaps this ticket should be re-opened, if the issue still occurs in `master`?

**Comment by gnidan** [comment] 2020-01-10 23:54
Yep, @theoretical2019! Guess we didn't get all the 5.1.5 bugs yet :/

Sorry about that!

cc @haltman-at

**Comment by haltman-at** [comment] 2020-01-22 00:33
I can't seem to reproduce this issue, unfortunately.  To be clear, this is the `SimpleStorage.sol` contract from `react-box`?  (Not like it seems like the particular contract is that relevant here, but just being sure.)

**Comment by TechBeatle** [comment] 2020-01-22 02:32
@haltman-at, Yes it was `SimpleStorage.sol` contract from 'react-box'.

**Comment by haltman-at** [comment] 2020-01-22 07:25
OK, thanks, just checking.  We'll see if we can get anywhere on reproducing this.  Let us know if you can think of any unusual details of your setup that might be relevant.  In the meantime, until we do reproduce this, you can try upgrading Truffle and see whether perhaps we've fixed it accidentally? :-/

**Comment by dmigwi** [comment] 2020-01-22 12:58
Its seems like the temporary solution to this, is downgrading to `v5.14`:
```
✗ truffle console             
You can improve web3's peformance when running Node.js versions older than 10.5.0 by installing the (deprecated) scrypt package in your project
truffle(development)> version
Truffle v5.1.4 (core: 5.1.4)
Solidity - 0.5.11 (solc-js)
Node v8.16.2
Web3.js v1.2.1
truffle(development)> debug 0x4894eed7f37f5df72e8913551fed34364a4b81827ea3b3385ad64c9cfbc5e926
Starting Truffle Debugger...
✔ Compiling your contracts...
✔ Gathering information about your project and the transaction..
```

**Comment by haltman-at** [comment] 2020-01-22 22:49
OK I have finally successfully reproduced the problem!  Thanks for bringing it to our attention, I'll have to see about fixing this...

**Comment by haltman-at** [comment] 2020-01-22 23:20
OK, I've put up PR #2777 to fix this.

**Comment by akrolak** [comment] 2020-03-14 21:44
I have exactly the same problem on 5.1.9, should I still downgrade to 5.1.4?

**Comment by haltman-at** [comment] 2020-03-17 00:17
I'm a little confused here @akrolak... there is no Truffle 5.1.9 (not yet, anyway).  Could you confirm what version you are having the problem on?  Also, you are certain it is the same error?  Posting the error message may be helpful here.

**Comment by eggplantzzz** [comment] 2020-03-23 15:55
@haltman-at Actually there is a Truffle version 5.1.9! https://www.npmjs.com/package/truffle/v/5.1.9

**Comment by haltman-at** [comment] 2020-03-23 19:21
Oh, oops, I misread.  I thought it said 5.1.19.  Sorry about that, @akrolak!  OK.  If you are having the problem on 5.1.9, could you try upgrading to the latest Truffle, 5.1.18?

I'm going to re-close this for now since it turns out the report is for an old version of Truffle.  I'll re-open it if you can confirm it still happens on current Truffle.  Thanks!

**Closed by haltman-at** 2020-03-23 19:21 UTC
Labels: bug, needs investigated, priority2 ⚠️
