### ISSUE TITLE
hdwallet-provider@1.3.0 not letting deploy

### ISSUE THREAD

**Issue by aster2709** [trufflesuite/truffle#4000] opened 2021-04-26 12:07 UTC
- [✅] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
@truffle/hdwallet-provider@1.3.0 not letting deploy contracts, however works just as fine for 1.2.6
// with 1.3.0
![image](https://user-images.githubusercontent.com/39130640/116079745-cf2c2400-a6b5-11eb-9484-7ed5c1215a9c.png)
// with earlier versions
![image](https://user-images.githubusercontent.com/39130640/116079794-df440380-a6b5-11eb-818f-debf0e151fcb.png)

## Steps to Reproduce
try to deploy with @truffle/hdwallet-provider@1.3.0
```const provider = new HDWalletProvider(mnemonic, provider);```

## Expected Behavior
expected to deploy 

## Actual Results
```
node deploy.js 
deploying from 0x31Dac9cD8B4fDc7B1d4F139e47a5703512460240
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

```

## Environment

* Operating System: linux ubuntu
* Ethereum client:infura api
* Truffle version (`truffle version`): @truffle/hdwallet-provider@1.3.0
* node version (`node --version`):@15.14.0
* npm version (`npm --version`): @7.7.6

**Comment by christoph2806** [comment] 2021-04-27 21:16
Hi, I experienced a similar problem today while deploying to xDai (chainId = 100).
```
$ truffle migrate --reset --network xdai

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'xdai'
> Network id:      100
> Block gas limit: 12500000 (0xbebc20)


01_initial_migration.js
=======================

   Replacing 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- Invalid chain id..

    at /home/christoph/.nvm/versions/node/v10.15.3/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.3.1 (core: 5.3.1)
Node v10.15.3
```

Steps to reproduce: 
- clone https://github.com/etherisc/flightdelay-contracts/tree/82e7eec844ecdebcce2eda0b9ba239c8fe0a7db9
- npm i
- npm i @truffle/hdwallet-provider@latest
- (edit truffle-config.js with your HDWallet Parameters)
- truffle migrate --reset --network xdai

It works with @1.2.1, but still gives a lot of timeout errors which cannot be fixed by setting networkCheckTimeout or pollingInterval.

**Comment by nicezic0** [comment] 2021-04-28 05:58
I have the similar problem.
https://github.com/trufflesuite/truffle/issues/4010

**Comment by Xinayder** [comment] 2021-04-28 17:18
To fix this issue, you need to pass a `chainId` parameter when creating the `HDWalletProvider`:

```
provider = new HDWalletProvider({
  mnemonic: mnemonicPhrase,
  providerOrUrl: "http://localhost:8545",
  chainId: 42
});
```

I just had this issue and spent a lot of time trying to figure out why it happened, until I found a question on StackOverflow with the same error and the author mentioned a named parameter.

**Comment by nicezic0** [comment] 2021-04-28 17:24
wow!!!!

**Comment by nicezic0** [comment] 2021-04-28 17:24
> 
> 
> To fix this issue, you need to pass a `chainId` parameter when creating the `HDWalletProvider`:
> 
> ```js
> provider = new HDWalletProvider({
>   mnemonic: mnemonicPhrase,
>   providerOrUrl: "http://localhost:8545",
>   chainId: 42
> });
> ```
> 
> I just had this issue and spent a lot of time trying to figure out why it happened, until I found a question on StackOverflow with the same error and the author mentioned a named parameter.

wow!!!

**Comment by davidmurdoch** [comment] 2021-04-28 18:08
Thanks everyone for providing your experience with this issue!

A recent geth update has started defaulting to requiring EIP-155 signed transactions, which HDWalletProvider doesn't automatically do unless a chainId option is passed in, and the chainId is the ID of a "known network" (ethereum testnets and mainnet, currently).

We need to do a couple of things here:

 * error better, so it is clear what is failing and why
 * improve HDWalletProvider so that it automatically fetches the chain ID from the network and signs the transaction with an EIP-155 signature.

**Comment by gakonst** [comment] 2021-04-29 18:46
Minimal repro here: https://github.com/gakonst/truffle-bug-repro.

The problem is that when using the `chainId: 1337`(e.g. with `geth --dev`), I get: `Error: Chain with ID 1337 not supported`, which [comes from ethereumjs-vm/common](https://github.com/ethereumjs/ethereumjs-monorepo/blob/cc9872972a657583eb1e3ef8d04b9f5b72562466/packages/common/src/index.ts#L103-L108)

**Comment by gnidan** [comment] 2021-05-03 17:30
Plan for fixing this issue:
- Make hdwallet-provider fetch the chainId upfront (using a pattern like [this](https://github.com/trufflesuite/truffle/blob/develop/packages/db/src/meta/pouch/adapters/base.ts#L47) to assign a Promise in the constructor). Then await that promise inside `provider.send`.
- If `chainId` is not available on the chain; it means we're pre-spurious dragon
- Allow specifying `chainId` to skip this behavior
- Add a `chainSettings` property to the constructor args (as a more verbose form of `chainId`). `chainSettings` would be type `{ chainId?: number | string; networkId?: number | string; hardfork?: string }`. Each of these properties is optional, with the following implications:
  - `chainId` not being specified means we fetch it
  - `hardfork` not being specified means we default to some post-`"spurious dragon"` fork (maybe we default to `"instanbul"`?)
  - `networkId` not being specified likely can just be ignored, since ethereumjs-common doesn't appear to use it. If it is necessary, we can treat it the same as `chainId` and fetch when missing.
- Do we need a way (separately from hardfork) to allow non-EIP155 transactions? A flag in `chainSettings` called `disableReplayProtection`?

Other thoughts:
- We want to eliminate the positional arguments form for hdwallet's constructor - this form is already deprecated, do we want to remove this form now? Seems like "not yet; we should plan for this separately"

**Comment by aster2709** [comment] 2021-05-15 06:09
I can confirm that I cannot reproduce the error with the latest version i.e 1.4.0 keeping the same environment.
I am calling the HDWalletProvider constructor without chainId as usual and it works.
```const provider = new HDWalletProvider(mnemonic, infuraRinkeby);```
![image](https://user-images.githubusercontent.com/39130640/118350003-fd44ab80-b571-11eb-91df-030af9925108.png)

**Closed** 2021-05-15 06:11 UTC
Labels: L2, Optimism, bug, error better, priority2 ⚠️

**Comment by sandeshwalunj** [comment] 2022-11-18 06:02
> 

Hii Have you got solution i also got this error today...plz tell me a solution...?thank you!

**Comment by lsqproduction** [comment] 2022-11-22 20:25
@sandeshwalunj Can you please help to open a new issue with the exact error message you got as well as the reproduction steps to get the error message?
