### ISSUE TITLE
accounts[0]   undefined  in truffle develop mode

### ISSUE THREAD

**Issue by wangjunbao2018** [trufflesuite/truffle#2135] opened 2019-06-27 04:07 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have been created a project following the doc  [Truffle Quick Start](https://www.trufflesuite.com/docs/truffle/quickstart),  After I run `truffle develop`, I depolyed a  contract,  then I tried to test it. But it has a error like this:

```
truffle(develop)> let instance = await MetaCoin.deployed()
undefined
truffle(develop)> let accounts = web3.eth.getAccounts()
undefined
truffle(develop)> let balance = await instance.getBalance(accounts[0])
{ Error: invalid address (arg="addr", coderType="address", value=undefined)
    at ABICoder.encodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:96:1)
    at AbiCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:897:1)
    at CoderTuple.encode (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:764:1)
    at pack (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:604:1)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:605:21
    at CoderAddress.encode (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/abi-coder.js:467:1)
    at Object.throwError (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/~/ethers/utils/errors.js:68:1)
  reason: 'invalid address',
  code: 'INVALID_ARGUMENT',
  arg: 'addr',
  coderType: 'address',
  value: undefined }
truffle(develop)> accounts
[ '0xd04b2F14Ba1a4910680C194CA58Bf9352ab18b0A',
  '0xe8daBBF20f6780E3f7973DAF2ED03614f5fAD318',
  '0x849503356359Bea28414491DfFF350c1c5bF0428',
  '0x851ADb73b53f81F4E635891e0100B3C0277400df',
  '0x2DE47bd4fD5fc173BaEB79F18918f55dDea73942',
  '0x9C8eF1dDE0232624a1EF0176C5E81E90BEaF4405',
  '0xdC92EcaC83aC7aD8de6EBF35C451369F26A27e69',
  '0xCE9D3EBfC9398Fa02430368bfbdbda761d9F95f1',
  '0x81d9D4f1E0B58a6a83F1dCC9d429D3D5E6E4A40D',
  '0x94e9EC24259f213621Dc67C6e2c14bC26473a6bF' ]

```

Then I found:

```
truffle(develop)> accounts
[ '0xd04b2F14Ba1a4910680C194CA58Bf9352ab18b0A',
  '0xe8daBBF20f6780E3f7973DAF2ED03614f5fAD318',
  '0x849503356359Bea28414491DfFF350c1c5bF0428',
  '0x851ADb73b53f81F4E635891e0100B3C0277400df',
  '0x2DE47bd4fD5fc173BaEB79F18918f55dDea73942',
  '0x9C8eF1dDE0232624a1EF0176C5E81E90BEaF4405',
  '0xdC92EcaC83aC7aD8de6EBF35C451369F26A27e69',
  '0xCE9D3EBfC9398Fa02430368bfbdbda761d9F95f1',
  '0x81d9D4f1E0B58a6a83F1dCC9d429D3D5E6E4A40D',
  '0x94e9EC24259f213621Dc67C6e2c14bC26473a6bF' ]
truffle(develop)> accounts[0]
undefined
truffle(develop)> accounts[1]
undefined
```
How could I solve this problem? thx

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System:  MacOS Mojave 10.14
* Ethereum client:
* Truffle version (`truffle version`):  Truffle v5.0.18 (core: 5.0.18)
* node version (`node --version`):  Node v10.15.3
* npm version (`npm --version`):   6.4.1
* web3js version (`npm --version`):  Web3.js v1.0.0-beta.37

**Comment by wangjunbao2018** [comment] 2019-06-27 04:13
BTW,  I quit and run agin, it has the following problem:

```
truffle(develop)> let balance = await instance.getBalance(accounts[0])
Error: Returned values aren't valid, did it run Out of Gas?
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-requestmanager/src/index.js:147:1
    at sendTxCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:473:1)
    at Method.formatOutput (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:163:1)
    at Method.outputFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:818:1)
    at Contract._decodeMethodReturn (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:465:1)
    at ABICoder.decodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:226:1)
```

**Comment by haltman-at** [comment] 2019-06-27 04:18
So, what's going on here is that `web3.eth.getAccounts` is an `async` method.  Since you didn't `await` it, in your code above, the `accounts` variable holds a promise rather than the array you want.  If you just type `accounts`, Truffle develop automatically resolves the promise for you and prints out the array.  However, if you type `accounts[0]`, then you're trying to take the 0th element of the promise, which doesn't exist, which is why you're getting a problem.

So, that's what you can do to solve your immediate problem.  It's possible that this behavior is sufficiently confusing that it should be changed, though.  Obviously it's not reasonable to make `accounts[0]` work in this situation, but perhaps the printout for `accounts` here could be in some way changed to reduce confusion?

**Comment by gnidan** [comment] 2019-06-27 04:44
Alternatively, we could just set up the `truffle develop` globals to pre-resolve the `accounts` promise!

**Comment by wangjunbao2018** [comment] 2019-06-27 06:40
> So, what's going on here is that `web3.eth.getAccounts` is an `async` method. Since you didn't `await` it, in your code above, the `accounts` variable holds a promise rather than the array you want. If you just type `accounts`, Truffle Develop automatically resolves the promise for you and prints out the array. However, if you type `accounts[0]`, then you're trying to take the 0th element of the promise, which doesn't exist, which is why you're getting a problem.
> 
> So, that's what you can do to solve your immediate problem. It's possible that this behavior is sufficiently confusing that it should be changed, though. Obviously it's not reasonable to make `accounts[0]` work in this situation, but perhaps the printout for `accounts` here could be in some way changed to reduce confusion?

Thx,   The reason is that  I forgot the keyword `await`, It's right after I added it.  But there is another error.

```
truffle(develop)> let balance = await instance.getBalance(accounts[0])
Error: Returned values aren't valid, did it run Out of Gas?
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-requestmanager/src/index.js:147:1
    at sendTxCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:473:1)
    at Method.formatOutput (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:163:1)
    at Method.outputFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:818:1)
    at Contract._decodeMethodReturn (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:465:1)
    at ABICoder.decodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:226:1)
```

Why does it say `Out of gas` for this is a query operation?
What should I do?

**Comment by wangjunbao2018** [comment] 2019-06-27 06:41
> Alternatively, we could just set up the `truffle develop` globals to pre-resolve the `accounts` promise!

Thx, I will try this method.

**Comment by CruzMolina** [comment] 2019-07-03 17:42
@wangjunbao2018 Can you provide exact reproduction steps within the `truffle develop` context?

**Comment by CruzMolina** [comment] 2019-07-03 17:47
Disregard the above, closing since the other issue is covered in #2136

**Closed by CruzMolina** 2019-07-03 17:47 UTC
Labels: needs investigated

**Comment by mohsennaserikish** [comment] 2022-01-16 21:33
try this way:
accounts = web3.eth.getAccounts().then(function(ac){accounts = ac;})
> account[1]
so you should see exact you want.
