### ISSUE TITLE
Debugger produces error message when printing state while debugging mainnet transaction `0x1c796d1e9867ee9b5f3ae57fa9e7a8623a5baf7eb2419ca7c1a371071a12896a`

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4616] opened 2022-01-12 06:20 UTC
## Issue

(Thanks to @gnidan for finding this issue.)  While debugging mainnet transaction `0x1c796d1e9867ee9b5f3ae57fa9e7a8623a5baf7eb2419ca7c1a371071a12896a` with `--fetch-external`, the debugger encounters an error while trying to print the state (i.e., the source code).

## Steps to Reproduce

In one terminal, using Ganache 7, fork mainnet with `ganache --fork`.

In another terminal, using Node 14, run `truffle debug -x 0x1c796d1e9867ee9b5f3ae57fa9e7a8623a5baf7eb2419ca7c1a371071a12896a --url http://localhost:8545/`.  Make sure you use Node 14!  If you use Node 12, you will instead encounter issue #4617, which will prevent you from reproducing this one!

Type `; 8011` to advance to step 8012, then type `n` to advance again.  Observe the error message.  Or, if you prefer to skip directly to the error, it first occurs at step 8240, so you can get there with `; 8239` from the start of the transaction.

## Expected Behavior

The debugger should correctly print the source location, if possible; if impossible, it should do better than erroring.

## Actual Results

```
debug(inline_config:0x1c796d1e...)> 

ChiToken.sol:

Uncaught TypeError: Cannot read property 'length' of undefined
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at DebugInterpreter.interpreter (/home/sniffnoy/truffle/truffle/packages/core/lib/debug/interpreter.js:684:24)
    at DebugPrinter.printState (/home/sniffnoy/truffle/truffle/packages/core/lib/debug/printer.js:178:18)
    at Object.formatRangeLines (/home/sniffnoy/truffle/truffle/packages/debug-utils/index.js:499:20)
    at Object.formatLinePointer (/home/sniffnoy/truffle/truffle/packages/debug-utils/index.js:420:30)
```

## Environment

* Truffle version (`truffle version`): 5.4.28
* node version (`node --version`): v14.18.2

**Comment by dongmingh** [comment] 2022-01-16 22:24
The issue can be reproduced with Node v16.10.0 and Truffle v5.4.29.

The cause is that the source code range are `null` at this location
```
debug(inline_config:0x1c796d1e...)> :!<controller.current.location.sourceRange>
{
  start: 31412,
  length: 155,
  lines: {
    start: {
      line: null,
      column: null
    },
    end: {
      line: null,
      column: null
    }
  }
}

```

**Comment by haltman-at** [comment] 2022-01-18 19:17
How odd.  I wouldn't really say that's "the cause", though, because then the question is why that is happening.  I'd call that an intermediate cause.  You still have to trace it further back.

**Comment by leeftk** [comment] 2022-03-11 00:41
Fixed in latest release.

**Closed by leeftk** 2022-03-11 00:41 UTC
Labels: bug, Debugger, needs investigated, priority2 ⚠️
