### ISSUE TITLE
truffle test fails if migration used Truffle Artifactor

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/truffle#2174] opened 2019-07-10 20:30 UTC
## Steps to Reproduce

```bash
rm -rf build
npx truffle compile
npx truffle test
```
Create migration script in special way:
https://github.com/peppersec/truffle_bug/blob/master/migrations/2_deploy.js#L14

## Expected Behavior

should be working

## Actual Results

Errors out on the first run
## Environment

* Operating System: 
* Ethereum client: ganache
* Truffle version (`truffle version`): 5.0.26
* node version (`node --version`): 10

Please check out the full repo
https://github.com/peppersec/truffle_bug
![truffle](https://user-images.githubusercontent.com/9360827/61002688-ec440700-a316-11e9-8304-4984d1889420.gif)

**Comment by CruzMolina** [comment] 2019-07-10 22:32
Hey @rstormsf ! As an aside, you probably want to change `unlinked_binary` to `bytecode` in `2_deploy.js`. Looks like it's been deprecated in the contract json spec.

**Comment by gnidan** [comment] 2019-07-10 22:49
Ugh `unlinked_binary` is a mess. It should be working, though. Maybe something is up with the deprecation mechanisms in contract-schema.

**Comment by CruzMolina** [comment] 2019-07-10 23:14
@rstormsf , looked into your issue a bit. it looks like the way migrations are currently rigged, the resolver expects to be passed artifacts (via `artifact.require`'s) _before_ the deployer module.exports. I'm not familiar with `circom`, but you might be able to hook it up to truffle as an external compiler rather than running a script in-between normal compilation and testing (`npx truffle compile && node makeMiMC.js && npx truffle test...`)

**Comment by rstormsf** [comment] 2019-07-11 20:59
@CruzMolina I don't think I understand what you mean by that. 
What should I do to fix it?

**Comment by rstormsf** [comment] 2019-07-11 21:05
@CruzMolina 
I wish it could be possible:
https://github.com/iden3/circomlib/blob/master/src/mimc_gencontract.js
take a look at it ;-)

**Comment by fainashalts** [comment] 2019-07-17 17:35
Hey @rstormsf are you still having trouble with this? It looks like Artifactor is working as expected, and you'd need to set up a separate script as @CruzMolina mentioned before you can migrate this way. We're going to go ahead and close this issue. Please bring this up in the Truffle Spectrum if you'd like to discuss it further!

**Closed by fainashalts** 2019-07-17 17:35 UTC

**Comment by HarryR** [comment] 2019-07-30 16:40
I encountered this problem too.

Running the code which uses `truffle-artifactor` into a separate stage between `truffle compile` and `truffle test` seems to have avoided the problem of having to run `truffle test` multiple times.

However, I still run into the blank 'Error: Error: Error' message whenever I try and use any of those contracts, that's really frustrating because getting any meaningful stack trace or debug information from Truffle seems to be harder than extracting blood from a stone.

**Comment by CruzMolina** [comment] 2019-07-30 16:48
@HarryR are you trying to do something similar as rstormf?

If you're trying to migrate than I believe you will have to "make" the contract artifact and import into the migrations scripts.

**Comment by HarryR** [comment] 2019-07-30 17:01
I'm doing something very similar to @rstormsf - generating EVM bytecode

The fix described above has fixed half the problem - I have a separate script 'generate-artifacts.js' which is run in between `compile` and `test`, then i can import the artifacts normally using `artifact.require(...)` so `truffle-artifactor` isn't used at any point in the migration .js scripts.

However, whenever I include the `library Name { ... }` code in a Solidity I get the blank `Error: Error: Error` message, before it's even run any of the migrations code. That seems unrelated to the bug described in this ticket (or.. maybe it is tangentially related?)

I'll open a ticket if I can't find a workaround.

**Comment by CruzMolina** [comment] 2019-07-30 17:52
@HarryR can you provide a reproduction repo for your `Library` error?

Thinking about this some more, there _might_ be a way to use the external compiler feature to get the `circom` compiler lib to work. Are you using this lib?

**Comment by HarryR** [comment] 2019-07-30 20:28
Hi.

 I'm not using `circom`.

 My problem has nothing to do with artifactor.

 I am working around it in a different way.
