### ISSUE TITLE
truffle migrate: Unexpected Identifier

### ISSUE THREAD

**Issue by rahul7668gupta** [trufflesuite/truffle#3083] opened 2020-05-30 07:56 UTC
I am getting this error while running 'truffle migrate' or 'truffle test' on my truffle project.
Can anyone help me with this?

```solidity
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.5.9 <0.7.0;

import "./Crowdsale.sol";


contract MyTokenSale is Crowdsale {
    constructor(
        uint256 rate, // rate in TKNbits
        address payable wallet,
        IERC20 token
    ) public Crowdsale(rate, wallet, token) {}
}
```

```
pragma solidity >=0.5.9 <0.7.0;
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at require (C:\Users\Rahul Gupta\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\require\require.js:54:1)     
    at F:\Workspace\Ethereum\BDB - 2020\tokenization\migrations\2_deploy_contracts.js:2:19
    at Script.runInContext (vm.js:133:20)
    at Script.runInNewContext (vm.js:139:17)
    at Object.file (C:\Users\Rahul Gupta\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\require\require.js:92:1) 
    at Migration._load (C:\Users\Rahul Gupta\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\migration.js:43:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by haltman-at** [comment] 2020-06-03 17:59
Hm, could you tell us the name of this file and where in your project it lives?  It looks like it's being parsed as Javascript rather than Solidity, causing the problem. (If you have a repo we could check out that would be especially helpful, although that may not be necessary.)  Thank you!

**Comment by wbt** [comment] 2020-06-04 20:42
Specifically, I'd expect this file to be `contracts/MyTokenSale.sol` relative to the root of your Truffle project.

**Comment by eggplantzzz** [comment] 2020-07-08 18:10
Closing this for issue maintenance. Feel free to tell us to re-open it if you think there is a problem that we should investigate further! Thanks!

**Closed by eggplantzzz** 2020-07-08 18:10 UTC

**Comment by hiimnhan** [comment] 2021-01-28 12:59
I have the same problem. It says: `pragma solidity ^0.4.24;
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:979:16)`

**Comment by wbt** [comment] 2021-01-29 16:01
What's the backtick at the start of the line for? 
Is that pragma line in a Javascript file? It's expected at the start of a .sol file; not on line 979 of a .js file.

**Comment by wbt** [comment] 2022-01-13 19:02
...and you still haven't answered the question about where that pragma line is.

**Comment by revanthmadasu** [comment] 2022-01-14 07:09
@wbt its in line 1 of a .sol file (contract file).

**Comment by haltman-at** [comment] 2022-01-18 19:15
If you have an actual reproduction project we can check out, we can reopen this!

**Comment by malik672** [comment] 2022-03-16 20:04
am facing the same problem

**Comment by xkazm04** [comment] 2022-07-28 07:33
not sure if helpful, but for example in Hardhat this error occurs while running .sol contract instead of .js deployment script

`npx hardhat run contracts/Token.sol --network rinkeby`
