### ISSUE TITLE
Unit tests written in Solidity, how to change msg.sender address, msg.value,...

### ISSUE THREAD

**Issue by berar** [trufflesuite/truffle#644] opened 2017-10-30 20:10 UTC
- [ x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I would like to know if it's possible to change the address of the message sender of contract's function call when writing unit tests in solidity. It really should be, I was trying to find out how but could not. 

## Steps to Reproduce

`pragma solidity ^0.4.4;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";

contract A {

  event Test(address add);

  function test() {
    Test(msg.sender);
  }
}

contract TestA {

  function test01() {
    A a = A(DeployedAddresses.A());
    a.test(); // <--- msg.sender is address(this), but how do we use a different account from testrpc?
  }
}`

## Expected Behavior

In gitter I got a response so I have tried to run it like this: 
`a.test({from: 0xf6a948bff792e4f42d7f17e5e4ebe20871d160f2});`

## Actual Results

It gives the following error:
`TypeError: Wrong argument count for function call: 1 arguments given but expected 0.
    a.test({from: 0xf6a948bff792e4f42d7f17e5e4ebe20871d160f2});`

## Environment

* Operating System: Windows 10
* Truffle version:  v3.4.11
* Ethereum client: testrpc v4.1.3
* node version: v8.7.0
* npm version: 5.4.2

**Comment by adklempner** [comment] 2017-10-30 20:30
You can't change `msg.sender` in Solidity. Its value will always be the address making the call.
`a.test({from: 0xf6a948bff792e4f42d7f17e5e4ebe20871d160f2});` is JavaScript code, not Solidity.

**Comment by berar** [comment] 2017-10-30 21:37
Is it possible to implement this? Along with the possibility of a change of msg.value and the likes? To be frank, I am surprised that this isn't possible currently since it should play a major part of the test cases given the scope.

**Comment by adklempner** [comment] 2017-10-30 21:39
It's already possible with Javascript tests, which is what most people use.
Read more here: [http://truffleframework.com/docs/getting_started/javascript-tests](http://truffleframework.com/docs/getting_started/javascript-tests)

**Comment by berar** [comment] 2017-10-30 21:42
I know, except that I am getting `eth_call: invalid opcode` error when I am calling functions with parameters. Still, given that there is a possibility of writing tests in solidity, a way to access 'from' field should exist.

**Comment by mickys** [comment] 2017-11-01 02:34
@berar - You can always take the hard way, by having a "testMethod" that instantiates a contract, that will then call your specified method, that way the msg.sender is the "new instance", thus allowing you to test for cases where the "code needs to revert / throw" in case of a different sender.

Just remember you will most likely need to use the low level "call" and check for true / false on the execution.
Problem with call is that you can only use it to determine if execution was successful or not. And in order to retrieve the method's return value you're going to have to go into assembly and do some memory assignment yourself.

It's nice to think of "solidity tests" as unit tests, and JS ones as integration, but in reality you probably want to stick to JS, as that's what everyone seems to be using these days.

**Comment by Adrion** [comment] 2017-11-06 07:43
Speaking about unit test, since I updated the package to 4.0.1 with testrpc 6.0.1 
I now have `Error: VM Exception while processing transaction: revert` instead of `VM Exception while executing eth_call: invalid opcode'`
Which breaks all my tests.

**Comment by tcoulter** [comment] 2017-11-28 19:51
Hi all,

@micky has the correct answer here - if you want to change your `msg.sender` in solidity tests, you need to make your test contract (`TestSomething.sol`) the owner of contract under test. 

`invalid opcode` and `revert` are separate issues; what they mean is that your Solidity code had a runtime error when executing your transaction. _Why_ it had a runtime error depends on your code.

I'd recommend using the Truffle debugger any time you run into this error. 

I'm going to close this ticket as @micky's answer is correct. Cheers!

**Closed by tcoulter** 2017-11-28 19:51 UTC

**Comment by EnchanterIO** [comment] 2018-03-13 16:10
@tcoulter but what if i want to test if my contract is properly storing/responding to multiple addresses? 

E.g. if I have a Contract attribute of type array or some mapping with key being the sender address, i want to make sure the array is properly storing multiple users data. 

I can only interact with my solidity test contract under 1 address?

**Comment by EnchanterIO** [comment] 2018-03-13 18:40
I think I found an example how to do it in JS, which seems to be more capable: https://github.com/gustavoguimaraes/smart-contract-testing-javascript-example-/blob/master/test/fundRaise.js

**Comment by pradhumn28** [comment] 2018-06-18 12:31
@EnchanterIO  Did you find something in solidity to do it? Having hard time to switch b/w accounts in testrpc . How can i interact with my solidity test contract with more then 1 address?

**Comment by digulla** [comment] 2019-11-19 14:34
Bug was probably introduced in 5.0.31. 5.0.30 works for me on Linux.

**Comment by mickys** [comment] 2019-11-19 15:58
@digulla this issue is not a bug, it's the way msg.sender works in solidity, you probably have the wrong thread.

**Comment by TCGV** [comment] 2020-12-19 21:04
For those looking for a way to manipulate `msg.sender` in unit tests written in solidity, here's an alternative approach I've been using effectively:

1. Create "actor" contracts, i.e., contracts that implement a unit test actor behavior and makes calls to the contract under test (CUT)
2. Deploy one actor contract for each individual address you need for writing your unit tests. For instance, if you're writing tests cases for an ERC20 contract you can implement a `BuyerContract` and a `SellerContract`, each one will have its own address and when they call the CUT functions `msg.sender` will be set to their deployed addresses
3. Now when writing unit tests instead of calling the CUT functions directly compose the test case as a sequence of actor function calls
