### ISSUE TITLE
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ code: -32000, message: 'header not found' })

### ISSUE THREAD

**Issue by iPSWeb** [trufflesuite/truffle#4498] opened 2021-12-07 04:15 UTC
bsc: {
      provider: () => new HDWalletProvider(mnemonic, `https://bsc-dataseed.binance.org`),
      network_id: 56,
      confirmations: 10,
      timeoutBlocks: 200,
      skipDryRun: true
    },

truffle migrate --network bsc --reset

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ code: -32000, message: 'header not found' })

**Comment by fainashalts** [comment] 2021-12-08 19:22
Hi @iPSWeb, it looks like you are deploying to bsc. Your config seems right from a quick glance, but there isn't much info here for us to dig further. Can you provide a repo or other additional information? 

We attempted to ping https://bsc-dataseed.binance.org and can get the latest block, but there may be syncing issues at play. You may want to reach out to BSC for assistance: https://github.com/binance-chain/bsc

**Comment by iPSWeb** [comment] 2021-12-09 18:33
> 

Thanks for your reply.
This configuration works fine on testnet.
As soon as I try to work with the mainnet I get this error. I passed my code to my friend in another country - and he has the same error.
I tried using HardHat and I get the same error

**Comment by hrs23** [comment] 2021-12-19 14:45
Hello, I'm having the same issue with exactly the same config above. 
I tried several endpoints listed in the [official doc](https://docs.binance.org/smart-chain/developer/rpc.html) but none of them worked.
@iPSWeb Did you resolve the issue? I would like to know if there is any workaround. Thanks!

**Comment by hrs23** [comment] 2021-12-19 15:21
I created a repo to reproduce the issue: https://github.com/hrs23/truffle-bsc-deploy-investigation.git
It would be greatly appreciated if someone can take a look.

**Comment by wainguo** [comment] 2021-12-20 11:27
I have the same issue, Did you resolve the issue?

**Comment by Jamesmallon1** [comment] 2021-12-20 13:11
This also is a recurring problem for myself.

Over the past week or so it has been occurring intermittently and now I cannot deploy to bsc mainnet at all. I hope this information helps.

MacOS - BigSur 11.6

**Comment by Jamesmallon1** [comment] 2021-12-20 13:15
On typing `truffle migrate -network bsc --reset`

This can occur:
```
Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
⠹ Fetching solc version list from solc-bin. Attempt #1Error: Unhandled error. ({ code: -32000, message: 'header not found' })
    at new NodeError (node:internal/errors:371:5)
    at Web3ProviderEngine.emit (node:events:379:17)
    at /Users/jamesmallon/node_modules/@trufflesuite/web3-provider-engine/index.js:57:14
    at afterRequest (/Users/jamesmallon/node_modules/@trufflesuite/web3-provider-engine/index.js:151:21)
    at /Users/jamesmallon/node_modules/@trufflesuite/web3-provider-engine/index.js:176:21
    at /Users/jamesmallon/node_modules/@trufflesuite/web3-provider-engine/index.js:238:9
    at /Users/jamesmallon/node_modules/async/internal/once.js:12:16
    at replenish (/Users/jamesmallon/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/jamesmallon/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/jamesmallon/node_modules/async/eachLimit.js:43:36)
    at /Users/jamesmallon/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/jamesmallon/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at Request._callback (/Users/jamesmallon/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:70:28)
    at Request.self.callback (/Users/jamesmallon/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/Users/jamesmallon/node_modules/request/request.js:1154:10)

```

Or it can occur on actual deployment. Not just fetching the lists

**Comment by wainguo** [comment] 2021-12-21 02:56
I got the issue，but check bscscan I found the contract deployed successfully------------------ Original ------------------From: James Mallon  ***@***.***>Date: Mon,Dec 20,2021 9:11 PMTo: trufflesuite/truffle ***@***.***>Cc: wainguo ***@***.***>, Comment ***@***.***>Subject: Re: [trufflesuite/truffle] Error [ERR_UNHANDLED_ERROR]: Unhandlederror. ({ code: -32000, message: 'header not found' }) (Issue #4498)
This also is a recurring problem for myself.
Over the past week or so it has been occurring intermittently and now I cannot deploy to bsc mainnet at all. I hope this information helps.
MacOS - BigSur 11.6

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/trufflesuite/truffle/issues/4498#issuecomment-997911616",
"url": "https://github.com/trufflesuite/truffle/issues/4498#issuecomment-997911616",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ZaidAhed-Halim** [comment] 2022-01-04 11:06
hello everyone, i am facing the same issue is it been solved to anyone ? 
if so please share the solution

**Comment by kevinbluer** [comment] 2022-01-12 19:49
Hey @iPSWeb, thanks for the follow-up and additional detail. Are you able to try another RPC endpoint (assuming alternatives exist)? We'll also do some further digging on our side and loop back shortly.

**Comment by kevinbluer** [comment] 2022-01-12 21:40
@iPSWeb @ZaidAhed-Halim @hrs23 I've just completed some additional digging into this and early conclusion is that it's an intermittent issue with the RPC gateway (perhaps related to server load). Approximately every 8th attempt resulted in the following valid response (given the address with which I'm attempting to deployed doesn't have a `BNB` balance)...

```Starting migrations...
======================
> Network name:    'bsc'
> Network id:      56
> Block gas limit: 79331155 (0x4ba7f53)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" could not deploy due to insufficient funds
   * Account:  0x72371f25d38C3D656A14929e9CcfF55710790933
   * Balance:  0 wei
   * Message:  insufficient funds for gas * price + value
```

By extension, the other attempts resulted in the same `{ code: -32000, message: 'header not found' }` response.

As such my current recommendation would be to keep trying. In addition, it could be worth seeing if there are any alternative gateways or by running your own node if this possible / viable. Note we'll keep this issue open for the time being. Let us know how you get on 🤞

**Comment by Morinohtar** [comment] 2022-02-22 11:51
Im getting the same issue with mainnet, though the testnet works fine.
And like @wainguo said, the contract happens to be deployed, went to bscan and it is there. But because the process failed i dont have the deployed info related to the mainnet created in the truffle project...
What do we do? Any news about fixing this?

**Comment by leeftk** [comment] 2022-02-22 19:16
Hey @Morinohtar can you try a different RPC endpoint? I recommend looking at https://www.portal.pokt.network/#1 and seeing if maybe the RPC is the issue? Let me know if that helps fix it on your end. Thanks!

**Comment by Morinohtar** [comment] 2022-02-22 20:41
Hi @leeftk 

Tks for the help, but we kept the deployed contract, so we are not going to try again. Maybe in the future if we happen to deploy something else and the issue still exists we can try your suggestion.

**Comment by cds-amal** [comment] 2022-04-13 18:35
Closing for issue maintenance

**Closed by cds-amal** 2022-04-13 18:35 UTC
