### ISSUE TITLE
HDWalletProvider; Execution Reverted when trying to 'setRecord' to claim ENS domain.

### ISSUE THREAD

**Issue by gsiros** [trufflesuite/truffle#4308] opened 2021-09-16 13:21 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this 

---------------------------

## Issue

Using Truffle's HDWalletProvider causes an error when trying to claim an ENS domain via the web3.js `web3.eth.ens.setRecord` function. The execution gets reverted.

## Steps to Reproduce

The process is very straight forward;
1. Create a provider instance for web3. (12word mnemonic + infura's rinkeby link)
2. Call the `web3.eth.ens.setRecord` function as;
`result = await web3.eth.ens.setRecord('blablabla.eth', accounts[0], "0xf6305c19e814d2a75429Fd637d01F7ee0E77d615",             
 0, { from: accounts[0] });`

## Expected Behavior

The expected outcome is some message of affirmation, that the domain has been claimed.

## Actual Results

The execution of the transaction gets reverted. The NodeJS terminal output is `{ code: -32000, message: 'execution reverted' }`

## Environment

* Operating System: macOS (10.15.7)
* Ethereum client: -
* Truffle's HDWalletProvider version `1.5.0`
* node version `14.17.3`
* npm version `6.14.13`

**Comment by fainashalts** [comment] 2021-09-22 17:49
Hi @gsiros this doesn't appear to be an issue with HDWalletProvider, but rather with the parameters being passed to `web3.eth.ens.setRecord` -- you may want to change the `ttl` param to something else to get this working. I am sure you have already seen this but here are the [docs](https://web3js.readthedocs.io/en/v1.3.4/web3-eth-ens.html#setrecord) for the `setRecord `function.

I'm closing this issue since it is not a bug with Truffle's code but please feel free to open a new issue if you find that there is something that needs to be investigated on the Truffle side. Thanks!

**Closed by fainashalts** 2021-09-22 17:49 UTC
Labels: needs reproduced, needs investigated, hdwallet-provider

**Comment by gsiros** [comment] 2021-09-22 17:58
No! I've tried changing it to any value greater than 0... it doesn't work. The error is still the same!
