### ISSUE TITLE
`truffle test --compile-none ./path/to/test/file` ignores specific test file and runs all tests

### ISSUE THREAD

**Issue by RatanRSur** [trufflesuite/truffle#4793] opened 2022-03-03 02:53 UTC

**Comment by lsqproduction** [comment] 2022-03-08 20:10
@RatanRSur thank you for opening this issue. We will work on reproducing this. 
May I also confirm does this also happens without --compile-none?

**Comment by gnidan** [comment] 2022-05-05 17:10
Let's close this as duplicate of #5066, since that issue has slightly more detail that might be helpful in reproducing.

Thanks for opening this @RatanRSur!

**Closed by gnidan** 2022-05-05 17:10 UTC
Labels: bug, needs reproduced, priority3 🔧
