### ISSUE TITLE
Events across multiple contracts do not display in transaction receipt

### ISSUE THREAD

**Issue by Grapefruit19** [trufflesuite/truffle#1161] opened 2018-08-01 15:53 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Events across multiple contracts do not display in transaction receipt

## Steps to Reproduce

Please see this repository for test code and reproduction steps:

https://github.com/Grapefruit19/ethereum-event-bug

## Expected Behavior

When one contract calls another contract that emits an event (i.e., ParentContract emits an event, then calls Logger, and Logger emits an event), both events should display in the transaction receipt.

This output is the expected output, running truffle version 4.1.3

```
   { transactionHash: '0x85771e58760e0dcbe08a099f535c5649ca5a263c48c1e8452f7b7319016ad1ab',
     transactionIndex: 0,
     blockHash: '0x163016b3016b4227c92e80820a220cc7124eec421375f00c354b7fae18b137cc',
     blockNumber: 15,
     gasUsed: 45850,
     cumulativeGasUsed: 45850,
     contractAddress: null,
     logs: [ [Object], [Object] ],
     status: '0x1',
     logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000800000000000400000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000010000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000' },
  logs:
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash: '0x85771e58760e0dcbe08a099f535c5649ca5a263c48c1e8452f7b7319016ad1ab',
       blockHash: '0x163016b3016b4227c92e80820a220cc7124eec421375f00c354b7fae18b137cc',
       blockNumber: 15,
       address: '0x2223f064c1a2391637ce8365703a0dddf196d9c6',
       type: 'mined',
       event: 'TestEvent',
       args: [Object] },
     { logIndex: 1,
       transactionIndex: 0,
       transactionHash: '0x85771e58760e0dcbe08a099f535c5649ca5a263c48c1e8452f7b7319016ad1ab',
       blockHash: '0x163016b3016b4227c92e80820a220cc7124eec421375f00c354b7fae18b137cc',
       blockNumber: 15,
       address: '0xc622e2d82da6707d602d7bdd8c1a8123bdaca9eb',
       type: 'mined',
       event: 'TestEvent',
       args: [Object] } ] }
```

## Actual Results

No events display. This output is from truffle version 4.1.13

```
 { blockHash: '0x24f04a1b8d8bf8a7d291c14b4e2c61b6ca6b2783e4988660d65916628a99157c',
     blockNumber: 5402,
     contractAddress: null,
     cumulativeGasUsed: 6721975,
     from: '0xcd53d707046431992698e2046f16430c4175694f',
     gasUsed: 6721975,
     logs: [],
     logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
     root: '0x5e9b690d34b97253026e20c3152edf40e532bdfefb48d6f494c4b040c9e8eb74',
     to: '0xa9c143794d72c2bf0aa84118c6d5f3f68973772c',
     transactionHash: '0xed56e905b638927bcf2a8a625df213805662c2c9e5987c8f4c83b }
```

## Environment

* Operating System: OSX High Sierra
* Ethereum client: Geth version 1.8.13
* Truffle version (`truffle version`): Problems occur on truffle versions higher than 4.1.3
* node version (`node --version`): 8.9.4
* npm version (`npm --version`): 5.6.0

**Comment by cgewecke** [comment] 2018-08-01 19:41
Hi @Grapefruit19 we're tracking this issue at #555. That thread also [links](https://github.com/trufflesuite/truffle/issues/555#issuecomment-404204133) to some small utilities that should help to get around this limitation.

Closing as duplicate of #555

**Closed by cgewecke** 2018-08-01 19:41 UTC
