### ISSUE TITLE
Using @truffle/contracts in Angular 12 project. "fs" problem

### ISSUE THREAD

**Issue by MarekDzw** [trufflesuite/truffle#4302] opened 2021-09-14 07:11 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------
## Link to the project
[Blockchain shop](https://github.com/MarekDzw/Blockchain-Shop)
## Issue

After adding 
```ts
declare let require: any;
const contract = require('@truffle/contract');
```
in Angular 12 component I get errors in terminal and project want start.
Errors:
```bash
./node_modules/@truffle/compile-common/dist/src/profiler/updated.js:33:24-37 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Repositories\blockchain-shop\node_modules\@truffle\compile-common\dist\src\profiler'

./node_modules/fs.realpath/index.js:8:9-22 - Error: Module not found:
Error: Can't resolve 'fs' in 'C:\Repositories\blockchain-shop\node_modules\fs.realpath'

./node_modules/fs.realpath/old.js:24:9-22 - Error: Module not found: 
Error: Can't resolve 'fs' in 'C:\Repositories\blockchain-shop\node_modules\fs.realpath'

./node_modules/glob/glob.js:43:9-22 - Error: Module not found: 
Error: Can't resolve 'fs' in 'C:\Repositories\blockchain-shop\node_modules\glob'

./node_modules/glob/sync.js:4:9-22 - Error: Module not found: 
Error: Can't resolve 'fs' in 'C:\Repositories\blockchain-shop\node_modules\glob'
```

## Steps to Reproduce

Add below line in any Angular 12 component
```ts 
const contract = require('@truffle/contract'); 
```

## Expected Behavior

Working lib where I can use `contract` object in project.

## Actual Results

Errors in terminal: 
```bash
./node_modules/@truffle/compile-common/dist/src/profiler/updated.js:33:24-37 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Repositories\blockchain-shop\node_modules\@truffle\compile-common\dist\src\profiler'

./node_modules/fs.realpath/index.js:8:9-22 - Error: Module not found:
Error: Can't resolve 'fs' in 'C:\Repositories\blockchain-shop\node_modules\fs.realpath'

./node_modules/fs.realpath/old.js:24:9-22 - Error: Module not found: 
Error: Can't resolve 'fs' in 'C:\Repositories\blockchain-shop\node_modules\fs.realpath'

./node_modules/glob/glob.js:43:9-22 - Error: Module not found: 
Error: Can't resolve 'fs' in 'C:\Repositories\blockchain-shop\node_modules\glob'

./node_modules/glob/sync.js:4:9-22 - Error: Module not found: 
Error: Can't resolve 'fs' in 'C:\Repositories\blockchain-shop\node_modules\glob'
```

## Environment

* Operating System: ` Win 10 `
* Ethereum client: ` Metamask `
* Truffle version (`truffle version`): `  v5.4.9 (core: 5.4.9) `
* node version (`node --version`): `  v14.17.5 `
* npm version (`npm --version`):  ` 7.20.5  `

**Comment by Morenar** [comment] 2021-09-14 20:25
same issue, tried it with different versions and a clean angular 11 project. 

node v14
npm 7.6.3
truffle 5.4.10

@truffle/contract ^4.3.34

**Comment by MicaiahReid** [comment] 2021-09-15 18:21
Thanks for reporting this, @MarekDzw! We'll be looking into this and will hopefully have a fix soon.

**Comment by eggplantzzz** [comment] 2021-10-01 15:33
Hey @MarekDzw, this should be fixed in the latest version of @truffle/contract (4.3.37). Could you try upgrading and confirm/deny that this resolves the issue for you? Thanks!!

**Comment by MarekDzw** [comment] 2021-10-02 10:38
> Hey @MarekDzw, this should be fixed in the latest version of @truffle/contract (4.3.37). Could you try upgrading and confirm/deny that this resolves the issue for you? Thanks!!

After updating to 4.3.37 there is no `fs` error anymore but  there is new error in Chrome Dev Tools console:
```js
Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at module.exports (vendor.js:145699)
    at Object.646 (vendor.js:145749)
    at __webpack_require__ (runtime.js:23)
    at Object.75290 (vendor.js:144986)
    at __webpack_require__ (runtime.js:23)
    at Object.76348 (vendor.js:145463)
    at __webpack_require__ (runtime.js:23)
    at Object.94450 (vendor.js:88737)
    at __webpack_require__ (runtime.js:23)
    at Object.86302 (vendor.js:88787)
```
I've tried in linked project and in clean Angular project, same error.
What I do is requiring lib in service: 
```js
declare let require: any;
const contract = require("@truffle/contract")
```

**Comment by haltman-at** [comment] 2021-12-22 19:20
@MarekDzw Since the original issue has been fixed, we're going to close this.  However, if the new issue you encountered is still a problem, I would suggest opening a new issue for it with more detailed reproduction steps, and we'll do our best to fix it.  Thanks for bringing this to our attention!

**Closed by haltman-at** 2021-12-22 19:20 UTC
Labels: priority2 ⚠️
