### ISSUE TITLE
Upgrade issue for truffle to 5.4.30

### ISSUE THREAD

**Issue by keshari1arya** [trufflesuite/truffle#4640] opened 2022-01-23 14:31 UTC
### Discussed in https://github.com/trufflesuite/truffle/discussions/4638

<div type='discussions-op-text'>

<sup>Originally posted by **keshari1arya** January 22, 2022</sup>
Hi,
I am trying to upgrade truffle to the latest version but after uninstalling and installing I am getting bellow error. 

truffle init
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\<username>\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

npm -v 8.3.2
node -v v16.13.0

commands i used:
npm uninstall truffle -g
npm install truffle -g

fortunately when i downgraded to 5.4.29 things are awesome
OS: Windows 10 
</div>

**Comment by cds-amal** [comment] 2022-01-23 18:56
Hi @keshari1arya, 

I could not reproduce the error. Can you share some more information about your Windows version by running the following command in PowerShell? 
``` powershell
Get-ComputerInfo -Property "*version"
```


## My results
App versions
``` console
PS C:\Users\labrat\dev\supply-chain> truffle version
Truffle v5.4.30 (core: 5.4.30)
Solidity - 0.7.3 (solc-js)
Node v16.13.0
Web3.js v1.5.3
PS C:\Users\labrat\dev\supply-chain> npm --version
8.1.0
```

OS Versions
``` console
PS C:\Users\labrat\dev\supply-chain> Get-ComputerInfo -Property "*version"

WindowsCurrentVersion              : 6.3
WindowsVersion                     : 2009
BiosVersion                        : ALASKA - 1072009
OsVersion                          : 10.0.19044
OsServicePackMajorVersion          : 0
OsServicePackMinorVersion          : 0
```

**Comment by keshari1arya** [comment] 2022-01-24 06:49
Hello @cds-amal 
Below are the details of my system.

WindowsCurrentVersion              : 6.3
WindowsVersion                     : 2009
OsVersion                          : 10.0.19044
OsServicePackMajorVersion          : 0
OsServicePackMinorVersion          : 0

seems like same as you.

**Comment by gnidan** [comment] 2022-01-26 19:16
Hi @keshari1arya, we're having trouble reproducing this. Maybe you could try `npm cache clear` to see if that resolves this for you. You might need to pass the `--force` flag (`npm cache clear --force`), but I'd try without first because that flag sounds scary to me.

Please let us know if that helps. Thanks!

**Comment by cds-amal** [comment] 2022-02-02 19:28
This [comment](https://github.com/trufflesuite/truffle/issues/4658#issuecomment-1027084879) may be relevant

**Comment by lsqproduction** [comment] 2022-03-08 20:44
closing for issue maintenance.

**Closed by lsqproduction** 2022-03-08 20:44 UTC
Labels: needs reproduced
