### ISSUE TITLE
Migrations" exceeded the block limit (using Truffle's estimate).    * Block limit: 0x50e7c

### ISSUE THREAD

**Issue by Unmesha1** [trufflesuite/truffle#2384] opened 2019-09-12 18:24 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by haltman-at** [comment] 2019-09-18 17:38
Hi, it's hard to tell what's going on here.  Could you explain this in more detail, including reproduction steps and what behavior was expected?  Thank you!

**Comment by Unmesha1** [comment] 2019-09-18 18:30
actually i was following the step by step tutorial of dapp university to
create a voting dapp, setup was complete. But i got an error as gas limit
exceded( as was estimated by truffle) , i was using powershell, there it
was written try changing it manually in migrations folder, or ask in github
link.

**Comment by eggplantzzz** [comment] 2019-09-25 18:10
Hi @Unmesha1! Is your code available somewhere to look at? And if it is, could you please tell us exactly what you were doing when you got this message?

**Comment by haltman-at** [comment] 2019-10-16 18:15
@Unmesha1, could you link us to this tutorial you're referring to?

**Comment by Unmesha1** [comment] 2019-10-17 15:15
The link is
https://www.dappuniversity.com/articles/the-ultimate-ethereum-dapp-tutorial.
Thanks for the help!

**Comment by gnidan** [comment] 2021-09-03 18:05
Looks like we can close this as duplicate of #3992. Thanks!

**Closed by gnidan** 2021-09-03 18:05 UTC
Labels: needs reproduced, Migrations, priority6 💭
