### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by freshonline** [trufflesuite/truffle#803] opened 2018-02-18 22:39 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

```
truffle migrate
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: insufficient funds for gas * price + value
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:165:20)
```

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

```
geth --rpc --port 30304 --rpcport 8599 --targetgaslimit 9000000000000 --gasprice 18000000000 --rpcapi db,eth,web3,net,admin,miner,personal --cache 1024 --maxpeers 25 --datadir /home/testnet/.ethereum --keystore /home/testnet/.ethereum/keystore --nousb --fast --testnet --mine --minerthreads 1 --unlock 0xC1320531dF2612B85e6FEDFd4d6358ed711bbe66 --password /home/testnet/pass
```
cat truffle.js

```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8599,
      network_id: 3,
      from: "0xC1320531dF2612B85e6FEDFd4d6358ed711bbe66",
      gas: 1000000,
      gasPrice: 10000000000,
    }
  }
};
```
```
cat contracts/TutorialToken.sol
pragma solidity ^0.4.18;

import 'zeppelin-solidity/contracts/token/ERC20/StandardToken.sol';

contract TutorialToken is StandardToken {

string public name = 'TutorialToken';
string public symbol = 'TT';
uint8 public decimals = 2;
uint public INITIAL_SUPPLY = 12000;

function TutorialToken() public {
  totalSupply_ = INITIAL_SUPPLY;
  balances[msg.sender] = INITIAL_SUPPLY;
 }

}
```

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: Ubuntu 16.04.3 LTS
* Truffle v4.0.6 (core: 4.0.6)
* Solidity v0.4.19 (solc-js)
* Ethereum client: go-ethereum-1.7.3
* node version: v9.4.0
* npm version: 5.6.0

**Comment by cgewecke** [comment] 2018-02-18 23:12
@freshonline Could you look at [this issue](https://github.com/ethereum/go-ethereum/issues/15983) at Geth and see if the error seeing is related to configuring the chainID?

**Comment by cgewecke** [comment] 2018-02-19 17:01
@freshonline Was that the cause of the error? Is this issue closable?

**Comment by cgewecke** [comment] 2018-02-20 15:14
@freshonline Closing because this is likely a geth configuration issue and you've stopped responding, but please feel free to re-open if that's not the case and there's more to investigate here. Thanks!

**Closed by cgewecke** 2018-02-20 15:14 UTC

**Comment by freshonline** [comment] 2018-02-21 12:00
I have problem configuring the chainID. Do not can use genesis.json.
https://github.com/ethereum/go-ethereum/issues/16137#
