### ISSUE TITLE
`Cannot find module 'fs'` from contract/debug-utils

### ISSUE THREAD

**Issue by dmihal** [trufflesuite/truffle#3293] opened 2020-08-24 16:16 UTC
I'm using a library that includes @truffle/contract. This package has child dependencies of @truffle/debug-utils, which contains node-dir. 

When webpack tries to build the app, i get the following error:

    Module not found: Error: Can't resolve 'fs' in '/node_modules/node-dir/lib'

**Comment by eggplantzzz** [comment] 2020-08-25 15:06
Interesting, can you provide us with the full error message? This is surprising since Truffle itself uses these packages and is itself webpacked without an issue. If you are able, could you provide us with some reproduction steps if your project is not private?

**Comment by gnidan** [comment] 2020-08-26 17:44
@haltman-at states that he thinks we should get rid of this dependency :)

**Comment by gnidan** [comment] 2020-08-26 17:48
Removing that debug-utils dependency seems like the best solution, but in the meantime, @dmihal, could you provide us with any additional information? Is your project available online, for instance?

**Comment by eggplantzzz** [comment] 2020-08-27 19:07
A fix was released with Truffle 5.1.42. Thanks for the heads up!

**Comment by shuiyunfeng** [comment] 2020-12-31 08:22
It stills exist in Truffle 5.1.59.

**Comment by haltman-at** [comment] 2021-01-04 23:08
Hi @shuiyunfeng, could you provide more information?  The `debug-utils` package no longer contains the offending dependency (nor does it perform any filesystem operations), so I'm confused how this could be so.  Do you have reproduction steps or an error message we could investigate?  Thank you!

**Comment by haltman-at** [comment] 2021-09-30 22:04
I just noticed this is still open.  Closing again for issue maintenance.  If anyone is still encountering any problems here, please file a new issue.  Thanks!

**Closed by haltman-at** 2021-09-30 22:04 UTC
Labels: bug, priority3 🔧
