### ISSUE TITLE
Freshly init'd truffle environment doesn't migrate Migrations contract

### ISSUE THREAD

**Issue by erickearns** [trufflesuite/truffle#1111] opened 2018-07-17 17:02 UTC
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

In the process of troubleshooting a migrations-related issue, I wanted to verify the deployment of the Migrations contract in a completely stripped down truffle environment. A freshly init'd truffle environment fails to properly perform the default deployment of the Migrations contract.

## Steps to Reproduce

```
npm install truffle
mkdir truffletest
cd truffletest
truffle init
(fiddle with truffle.js to specify ganache-cli local network)
truffle migrate --network <network_name>
```

## Expected Behavior

The Migrations contract would be deployed and its networks object within the build artifact would be updated

## Actual Results

Nothing was actually migrated. Truffle outputs the following:

```
Writing artifacts to ./build/contracts

Using network 'local'.

Network up to date.
```

## Environment

* Operating System: `Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`
* Ethereum client: `Ganache CLI v6.1.6 (ganache-core: 2.1.5)`
* Truffle version (`truffle version`): `Truffle v4.1.13 (core: 4.1.13); Solidity v0.4.24 (solc-js)`
* node version (`node --version`): Same behavior with `6.14.3`, `8.11.3`, `9.11.2`, `10.6.0`
* npm version (`npm --version`): `6.1.0`

**Comment by cgewecke** [comment] 2018-07-17 23:20
Thanks @erickearns . . . will take a look at fixing for the Truffle V5 shortly. 

For record keeping this is a duplicate of #777

**Comment by cgewecke** [comment] 2018-07-18 17:10
@erickearns We just published a fix for this to truffle's V5 alpha - `truffle@next`.  I'm going to close this as duplicate but continue to track the issue at #777

**Closed by cgewecke** 2018-07-18 17:10 UTC
Labels: Migrations
