### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by andreafspeziale** [trufflesuite/truffle#2176] opened 2019-07-11 15:04 UTC
- [√] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have the following error when running solidity test with truffle: 
`Error: Callback was already called.`
I found something similar on the internet here: https://ethereum.stackexchange.com/questions/69406/callback-was-already-called-during-truffle-test-using-a-solidity-testfile

## Steps to Reproduce

When running on the development network `truffle test` of the following contract:
```javascript
pragma solidity ^0.5.10;

import "truffle/Assert.sol";

contract TestUnpackFixed {

  function testUnpackFixed() public {
    uint expectedLength = 1;
    uint a = 1;
    Assert.equal(
      a,
      expectedLength,
      "unpack array length should equal expectedLength");
  }
}
```
truffle-config.js
```javascript
module.exports = {
  networks: {
    development: {
      host: '127.0.0.1',
      port: 7545,
      network_id: '47',
      gas: 4700000,
      gasPrice: 6000000000,
    },
  },

  mocha: {
    reporter: 'eth-gas-reporter',
  },

  compilers: {
    solc: {
      version: '0.5.10',
      settings: {
        optimizer: {
          enabled: true,
          runs: 200,
        },
      },
    },
  },
}
```

## Actual Results

```
➜  yarn truffle test test/TestUnpackFixed.sol
yarn run v1.16.0
$ /Users/andreaspeziale/Repository/.../node_modules/.bin/truffle test test/TestUnpackFixed.sol
Using network 'development'.


Compiling your contracts...
===========================
> Compiling ./test/TestUnpackFixed.sol
> Artifacts written to /var/folders/vn/t04s12zd5dq7h5p30xb8qybw0000gp/T/test-119611-20131-18jjcic.o0o3
> Compiled successfully using:
   - solc: 0.5.10+commit.5a6ea5b1.Emscripten.clang


  TestUnpackFixed
Error: Callback was already called.
    at /Users/andreaspeziale/Repository/.../node_modules/truffle/build/webpack:/packages/truffle-core/~/async/dist/async.js:966:1
    at /Users/andreaspeziale/Repository/.../node_modules/truffle/build/webpack:/packages/truffle-core/~/async/dist/async.js:3885:1
    at <anonymous>
{ _deepCopy: [ 'compilers' ],
  _values:
```

## Environment
```
MacOsX
Truffle v5.0.26 (core: 5.0.26)
Solidity - 0.5.10 (solc-js)
Node v10.16.0
Web3.js v1.0.0-beta.37
```

**Comment by CruzMolina** [comment] 2019-07-11 15:48
Hey @andreafspeziale ! I don't see your actual contract (`UnpackFixed`) imported in your test file.

**Comment by andreafspeziale** [comment] 2019-07-11 16:25
@CruzMolina Hey, yes because it is a kind of a mock to check that was working. There are any requirements that I'm missing? Should not running anyway?

**Comment by andreafspeziale** [comment] 2019-07-11 16:36
@CruzMolina By the way I get the same error even:
- Importing MyContract.sol
- Calling the file TestMyContract.sol
- Calling the contract TestMyContract.sol

**Comment by CruzMolina** [comment] 2019-07-11 16:37
Hmm, testing this locally, I seem to be able to run your commands successfully 🤔.

If you comment out the `development` network does your test run?

**Comment by andreafspeziale** [comment] 2019-07-11 16:51
From where? From the config? If yes it wont even start. If u mean turn off my ganache and the config and let truffle do it fail in the same way. By the way you can find me on gitter to speed it up.

**Comment by andreafspeziale** [comment] 2019-07-11 19:18
Ok we fixed this specific issue simply by removing the `build` folder.

**Comment by unboxedtype** [comment] 2019-11-15 10:22
Same issue happening.

**Comment by gnidan** [comment] 2019-11-15 18:27
@unboxedtype can you please provide additional reproduction steps?

**Comment by canercidam** [comment] 2019-11-17 02:30
Magic steps :)

1) `truffle unbox metacoin`

2) Create `contracts/Foo.sol`:
```solidity
pragma solidity ^0.5;

contract Bar {}
```

3) `truffle test test/TestMetaCoin.sol`

<details><summary>Full output:</summary>

```
Compiling your contracts...
===========================
> Compiling ./contracts/ConvertLib.sol
> Compiling ./contracts/Foo.sol
> Compiling ./contracts/MetaCoin.sol
> Compiling ./contracts/Migrations.sol
> Compiling ./test/TestMetaCoin.sol



  TestMetaCoin
Error: Callback was already called.
    at /usr/lib/node_modules/truffle/build/webpack:/packages/core/~/async/dist/async.js:966:1
    at /usr/lib/node_modules/truffle/build/webpack:/packages/core/~/async/dist/async.js:3885:1
    at <anonymous>
TruffleConfig {
  _deepCopy: [ 'compilers' ],
  _values: 
   { truffle_directory: '/usr/lib/node_modules/truffle',
     working_directory: '/home/caner/gbg/foobb',
     network: 'test',
     networks: { test: [Object] },
     verboseRpc: false,
     gas: null,
     gasPrice: null,
     from: null,
     confirmations: 0,
     timeoutBlocks: 0,
     production: false,
     skipDryRun: false,
     build: null,
     resolver: 
      TestResolver {
        resolver: [Object],
        source: [Object],
        search_path: '/tmp/test-1191017-28455-1w2m6zf.8igl',
        seen: [],
        require_cache: [Object],
        cache_on: true },
     artifactor: Artifactor { destination: '/tmp/test-1191017-28455-1w2m6zf.8igl' },
     ethpm: 
      { ipfs_host: 'ipfs.infura.io',
        ipfs_protocol: 'https',
        registry: '0x8011df4830b4f696cd81393997e5371b93338878',
        install_provider_uri: 'https://ropsten.infura.io/truffle' },
     ens: { enabled: false, registryAddress: null },
     compilers: { solc: [Object], vyper: {} },
     logger: 
      Console {
        log: [Function: bound consoleCall],
        debug: [Function: bound consoleCall],
        info: [Function: bound consoleCall],
        warn: [Function],
        error: [Function: bound consoleCall],
        dir: [Function: bound consoleCall],
        time: [Function: bound consoleCall],
        timeEnd: [Function: bound consoleCall],
        trace: [Function: bound consoleCall],
        assert: [Function: bound consoleCall],
        clear: [Function: bound consoleCall],
        count: [Function: bound consoleCall],
        countReset: [Function: bound countReset],
        group: [Function: bound consoleCall],
        groupCollapsed: [Function: bound consoleCall],
        groupEnd: [Function: bound consoleCall],
        Console: [Function: Console],
        dirxml: [Function: dirxml],
        table: [Function: table],
        markTimeline: [Function: markTimeline],
        profile: [Function: profile],
        profileEnd: [Function: profileEnd],
        timeline: [Function: timeline],
        timelineEnd: [Function: timelineEnd],
        timeStamp: [Function: timeStamp],
        context: [Function: context],
        [Symbol(counts)]: Map {} },
     build_directory: '/home/caner/gbg/foobb/build',
     contracts_directory: '/home/caner/gbg/foobb/contracts',
     contracts_build_directory: '/tmp/test-1191017-28455-1w2m6zf.8igl',
     migrations_directory: '/home/caner/gbg/foobb/migrations',
     migrations_file_extension_regexp: /^\.(js|es6?)$/,
     test_directory: '/home/caner/gbg/foobb/test',
     test_file_extension_regexp: /.*\.(js|ts|es|es6|jsx|sol)$/,
     example_project_directory: '/usr/lib/node_modules/truffle/example' },
  truffle_directory: '/usr/lib/node_modules/truffle',
  working_directory: '/home/caner/gbg/foobb',
  network: 'test',
  networks: 
   { test: 
      { network_id: 4447,
        provider: [Function: provider],
        from: '0x627306090abaB3A6e1400e9345bC60c78a8BEf57' } },
  verboseRpc: false,
  build: null,
  resolver: 
   Resolver {
     options: 
      TruffleConfig {
        _deepCopy: [Array],
        _values: [Object],
        truffle_directory: [Getter/Setter],
        working_directory: [Getter/Setter],
        network: [Getter/Setter],
        networks: [Getter/Setter],
        verboseRpc: [Getter/Setter],
        build: [Getter/Setter],
        resolver: [Getter/Setter],
        artifactor: [Getter/Setter],
        ethpm: [Getter/Setter],
        logger: [Getter/Setter],
        compilers: [Getter/Setter],
        ens: [Getter/Setter],
        build_directory: [Getter/Setter],
        contracts_directory: [Getter/Setter],
        contracts_build_directory: [Getter/Setter],
        migrations_directory: [Getter/Setter],
        migrations_file_extension_regexp: [Getter/Setter],
        test_directory: [Getter/Setter],
        test_file_extension_regexp: [Getter/Setter],
        example_project_directory: [Getter/Setter],
        network_id: [Getter/Setter],
        network_config: [Getter/Setter],
        from: [Getter/Setter],
        gas: [Getter/Setter],
        gasPrice: [Getter/Setter],
        provider: [Getter/Setter],
        confirmations: [Getter/Setter],
        production: [Getter/Setter],
        timeoutBlocks: [Getter/Setter],
        _: [Array],
        'show-events': false,
        showEvents: false,
        debug: false,
        'runner-output-only': false,
        runnerOutputOnly: false,
        'debug-global': 'debug',
        debugGlobal: 'debug' },
     sources: [ [Object], [Object], GlobalNPM {}, [Object] ] },
  artifactor: Artifactor { destination: '/tmp/test-1191017-28455-1w2m6zf.8igl' },
  ethpm: 
   { ipfs_host: 'ipfs.infura.io',
     ipfs_protocol: 'https',
     registry: '0x8011df4830b4f696cd81393997e5371b93338878',
     install_provider_uri: 'https://ropsten.infura.io/truffle' },
  logger: 
   Console {
     log: [Function: bound consoleCall],
     debug: [Function: bound consoleCall],
     info: [Function: bound consoleCall],
     warn: [Function],
     error: [Function: bound consoleCall],
     dir: [Function: bound consoleCall],
     time: [Function: bound consoleCall],
     timeEnd: [Function: bound consoleCall],
     trace: [Function: bound consoleCall],
     assert: [Function: bound consoleCall],
     clear: [Function: bound consoleCall],
     count: [Function: bound consoleCall],
     countReset: [Function: bound countReset],
     group: [Function: bound consoleCall],
     groupCollapsed: [Function: bound consoleCall],
     groupEnd: [Function: bound consoleCall],
     Console: [Function: Console],
     dirxml: [Function: dirxml],
     table: [Function: table],
     markTimeline: [Function: markTimeline],
     profile: [Function: profile],
     profileEnd: [Function: profileEnd],
     timeline: [Function: timeline],
     timelineEnd: [Function: timelineEnd],
     timeStamp: [Function: timeStamp],
     context: [Function: context],
     [Symbol(counts)]: Map {} },
  compilers: { solc: { settings: [Object] }, vyper: {} },
  ens: { enabled: false, registryAddress: null },
  build_directory: '/home/caner/gbg/foobb/build',
  contracts_directory: '/home/caner/gbg/foobb/contracts',
  contracts_build_directory: '/tmp/test-1191017-28455-1w2m6zf.8igl',
  migrations_directory: '/home/caner/gbg/foobb/migrations',
  migrations_file_extension_regexp: /^\.(js|es6?)$/,
  test_directory: '/home/caner/gbg/foobb/test',
  test_file_extension_regexp: /.*\.(js|ts|es|es6|jsx|sol)$/,
  example_project_directory: '/usr/lib/node_modules/truffle/example',
  network_id: 4447,
  network_config: 
   { gas: 6721975,
     gasPrice: 20000000000,
     from: '0x627306090abaB3A6e1400e9345bC60c78a8BEf57',
     network_id: 4447,
     provider: [Function: provider] },
  from: '0x627306090abaB3A6e1400e9345bC60c78a8BEf57',
  gas: 6721975,
  gasPrice: 20000000000,
  provider: 
   HttpProvider {
     host: 'http://127.0.0.1:7545/',
     httpAgent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     withCredentials: false,
     timeout: 0,
     headers: undefined,
     connected: false,
     send: [Function],
     _alreadyWrapped: true },
  confirmations: undefined,
  production: undefined,
  timeoutBlocks: undefined,
  _: [ 'test/TestMetaCoin.sol' ],
  'show-events': false,
  showEvents: false,
  debug: false,
  'runner-output-only': false,
  runnerOutputOnly: false,
  'debug-global': 'debug',
  debugGlobal: 'debug',
  test_files: [ 'test/TestMetaCoin.sol' ] }

/home/caner/.config/truffle/compilers/node_modules/soljson-v0.5.12+commit.7709ece9.js:33
(Module.asmGlobalArg,Module.asmLibraryArg,buffer);var __GLOBAL__I_000101=Module["__GLOBAL__I_000101"]=asm["__GLOBAL__I_000101"];var __GLOBAL__sub_I_ABIFunctions_cpp=Module["__GLOBAL__sub_I_ABIFunctions_cpp"]=asm["__GLOBAL__sub_I_ABIFunctions_cpp"];var __GLOBAL__sub_I_ABI_cpp=Module["__GLOBAL__sub_I_ABI_cpp"]=asm["__GLOBAL__sub_I_ABI_cpp"];var __GLOBAL__sub_I_ASTJsonConverter_cpp=Module["__GLOBAL__sub_I_ASTJsonConverter_cpp"]=asm["__GLOBAL__sub_I_ASTJsonConverter_cpp"];var __GLOBAL__sub_I_AST_cpp=Module["__GLOBAL__sub_I_AST_cpp"]=asm["__GLOBAL__sub_I_AST_cpp"];var __GLOBAL__sub_I_ArrayUtils_cpp=Module["__GLOBAL__sub_I_ArrayUtils_cpp"]=asm["__GLOBAL__sub_I_ArrayUtils_cpp"];var __GLOBAL__sub_I_AsmAnalysis_cpp=Module["__GLOBAL__sub_I_AsmAnalysis_cpp"]=asm["__GLOBAL__sub_I_AsmAnalysis_cpp"];var __GLOBAL__sub_I_BMC_cpp=Module["__GLOBAL__sub_I_BMC_cpp"]=asm["__GLOBAL__sub_I_BMC_cpp"];var __GLOBAL__sub_I_CHC_cpp=Module["__GLOBA
abort({}). Build with -s ASSERTIONS=1 for more info.
```
</details>

**Comment by Shirikatsu** [comment] 2019-11-18 10:40
I'm also having this issue and could reproduce steps above. Removing build folder did nothing.

I've found that testing a contract that does not have any functions to test does not result in the error.

**Comment by eggplantzzz** [comment] 2019-11-18 14:37
Thanks for the repro steps @canercidam! I think this was closed because there was a bug fix for an error with similar symptoms. We probably thought this was the same problem when closing it.

I was able to reproduce your error and I'll investigate this week!

**Comment by digulla** [comment] 2019-11-22 14:42
Bug was probably introduced in 5.0.31. 5.0.30 works for me on Linux.

**Closed** 2019-11-22 22:04 UTC
Labels: priority3 🔧
