### ISSUE TITLE
Already installed Solc via NPM and truffle not detecting it

### ISSUE THREAD

**Issue by jhay006** [trufflesuite/truffle#2389] opened 2019-09-13 07:11 UTC
---------------------------

## Issue

I have already solc installed via npm , and install truffle . how should truffle detect it ?

when i run truffle compile it is trying to connect to internet to download solc and then cached it.

But i don't want truffle to behave like that because like i said . i've already a solc installed.

Any suggesstion?

## Steps to Reproduce

truffle obtain solc 0.5.11

## Expected Behavior

will cached the solc that was already installed via npm not from truffle

## Actual Results

It connects to solc-bin through internet.
## Environment

* Operating System: Windows 7 

* Truffle version 5.0.36
* node version v10.16.3:
* npm version 6.9.0

**Comment by CruzMolina** [comment] 2019-09-13 15:57
Hey @jhay006! 

You should be able to pass your local solc-js compiler to Truffle by specifying the path to it within your `truffle-config.js` file:

```
module.exports = {
  compilers: {
    solc: {
      version: "./some/path"
    }
  }
}
```

**Comment by eggplantzzz** [comment] 2019-09-13 18:08
You can also specify the keyword "native" for the version property in the config example above.

**Comment by eggplantzzz** [comment] 2019-09-18 16:30
@jhay006 Were you able to resolve this? Can I close this issue?

**Comment by gnidan** [comment] 2019-09-24 00:09
Hm I wonder if this is related to the build failure (fixed temporarily by #2403, failure currently seen in #2404)

**Comment by eggplantzzz** [comment] 2019-09-27 18:14
@jhay006 Just a note, if you use `truffle obtain` to install the package, this is not the same as the "native" setting. If you use "native", Truffle assumes that you have installed solc externally to Truffle through something like `brew` or `apt-get`. See [this doc](https://solidity.readthedocs.io/en/v0.5.11/installing-solidity.html#binary-packages) for more info.

**Comment by gnidan** [comment] 2019-10-02 17:50
@jhay006 since this looks like the issue is just "Truffle's not as clear as it could be", not sure what to do here. Closing this for issue maintenance, but please feel free to weigh in if something could be more clear. Thank you!

**Closed by gnidan** 2019-10-02 17:50 UTC
Labels: needs investigated
