### ISSUE TITLE
"No source code found" Error while debugging a ganache transaction

### ISSUE THREAD

**Issue by hawkofsky** [trufflesuite/truffle#4278] opened 2021-08-24 19:19 UTC
## Issue

I tried to debug transaction with ganache-cli but it shows "1: // No source code found."

## Steps to Reproduce

- run ganache-cli with fork of mainnet of etherem
- truffle migrate
- truffle test
- truffle debug <tx_hash>

## Actual Results

It shows "1: // No source code found."
and if i step next(n), the debugging reach to the final step. (Transaction completed successfully.)
If I make script file and run it, then debug transaction it works correctly, but if I use truffle test, it fails with "No source code found."

## Environment

* Operating System: Ubuntu 20.02
* Ethereum client: ganache-cli@6.12.2
* Truffle version (`truffle version`): v5.4.7
* node version (`node --version`): v14.16.0
* npm version (`npm --version`): v6.14.11

**Comment by haltman-at** [comment] 2021-09-08 18:49
Hi, could we get more reproduction information here?  Like, what mainnet transaction were you trying to debug?  Did you intend to use the `--fetch-external` option?  Do you have a reproduction project we chould check out?

**Comment by hawkofsky** [comment] 2021-09-08 19:42
I'm trying to debug BSC mainnet transaction.
it's the same result whether to use `--fetch-external` or not.

**Comment by haltman-at** [comment] 2021-09-09 20:13
OK, what transaction? Are you doing this inside the context of a Truffle project with any of the source code? Can you show us any of this? We need enough information to reproduce the problem. Thank you!

**Comment by Gdcorbijn** [comment] 2021-11-04 16:52
Hi Guys,
I was experiencing the exact same problem, this is what I found:

1. Transactions are "tied" to the contract deployed code.
2. If I deploy a version of the smart contract, perform a transaction and debug it, it works OK
3. If change the smart contract code, build, deploy and try to debug the same transaction, it FAILS.
4. In order to be able to debug my new code changes, I have to execute a new transaction that will be impacted by the new deployed code. If I try to debug this new transaction, it works OK.

My environment:
OS Win10
ganache UI
truffle v5.4.17
node v16.13.0
npm v8.1.0

Hope it helps,
G

**Comment by haltman-at** [comment] 2021-12-22 19:36
Since there's no usable reproduction information here, I'm afraid we're going to have to close this.  Please let us know if you have further reproduction information and perhaps we can take another look.  Thanks!

**Closed by haltman-at** 2021-12-22 19:36 UTC
