### ISSUE TITLE
Contract name collisions on truffle projects

### ISSUE THREAD

**Issue by anxolin** [trufflesuite/truffle#1162] opened 2018-08-01 17:04 UTC
## Issue

Error compiling a contract that depends on two different truffle projects, if these dependency projects have a contract with the same name.

## Steps to Reproduce

Follow the steps in:
https://github.com/anxolin/truffle-dep-error

In the example I try to compile `CoolApp` contract that depends on `DepA` contract (in `./depA` project), and `DepB` contract (in `./depB` project).

`DepA` depends on a contract called `Token`, and `DepB` depends on a **different contract called also `Token`**.

Since truffles tries to output the files in `truffle/contract` folder, it fails to compile the second `Token` contract.

`DeclarationError: Identifier already declared.`

## Expected Behavior

To be able to depend on different contracts with the same name.

## Actual Results

`DeclarationError: Identifier already declared.`

## Environment

N/A

**Comment by gnidan** [comment] 2018-09-26 18:51
Closing this as duplicate of #1087

**Closed by gnidan** 2018-09-26 18:51 UTC
