### ISSUE TITLE
TypeError: Cannot convert undefined or null to object when deploying to testnet

### ISSUE THREAD

**Issue by dblockunity** [trufflesuite/truffle#1810] opened 2019-03-12 21:17 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I keep getting an error when trying to run truffle migrate.

## Steps to Reproduce

Create a project directory called my-project
Ensure truffle is installed
Type in "truffle init" in the terminal while in the my-project directory
cd contracts
git clone https://github.com/OpenZeppelin/openzeppelin-solidity.git
Create a file called Example.sol
Paste the following code into the Example.sol file.

```
pragma solidity ^0.5.0;
import "openzeppelin-solidity/contracts/token/ERC20/ERC20.sol";
import "openzeppelin-solidity/contracts/token/ERC20/ERC20Detailed.sol";
contract ExampleToken is ERC20, ERC20Detailed {
    uint private INITIAL_SUPPLY = 10000e18;
    constructor () public
        ERC20Detailed("ExampleToken", "EGT", 18)
    {
        _mint(msg.sender, INITIAL_SUPPLY);
    }
}
```

cd .. # To get into the parent directory
create a file called secrets.json and paste the following into it
{
  "mnemonic": "x x x x x x x x x x x x"
}
Ensure that the mnemonic matches the mnemonic from the local instance of geth.

npm init
npm install --save web3
npm install --save truffle-hdwallet-provider
modify truffle.js to match the following...

```
var secrets = require("./secrets.json");
var HDWalletProvider = require("truffle-hdwallet-provider");
var Web3 = require('web3'); // Set variable to the web3 module
var web3 = new Web3(Web3.givenProvider || "ws://localhost:8545");

module.exports = {
    // See <http://truffleframework.com/docs/advanced/configuration>
    // to customize your Truffle configuration!
    networks: {
        development: {
            host: "127.0.0.1",
            port: 8545,
            network_id: "*", // Match any network id
            gas: 10000000,
            gasLimit: 26000000000
        },
        ropsten: {
            provider: new HDWalletProvider(secrets.mnemonic, "https://ropsten.infura.io/"),
            network_id: "*",
            gas: 1000000,
            gasLimit: 67000000,
            gasPrice: 20000000000
        },
        // network_id: 3,
        // host: "localhost",
        // port:  8545,
        // gas:   2900000
        mainnet: {
            provider: new HDWalletProvider(secrets.mnemonic, "https://mainnet.infura.io/"),
            network_id: 1,
            gas: 1000000,
            gasLimit: 67000000
        }
    },
    compilers: {
        solc: {
            version: "0.5.2"
        }
    }
};
```
In 1_initial_migration.js file in migrations folder:

```
module.exports = function(deployer) {
};
```

In 2_deploy_contracts.js file remove all the code:
```
module.exports = function(deployer) {
};
```

type in `truffle migrate --network ropsten` into terminal

## Expected Behavior

For no contracts to be deployed, but for no errors to be thrown either.

## Actual Results

I get the following message in terminal:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at supplier.load.then.solc (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/index.js:184:1)
    at <anonymous>
Truffle v5.0.5 (core: 5.0.5)
Node v8.11.1

## Environment

* Operating System: Version 10.14.2
* Ethereum client: Version: 1.8.5-unstable
* Truffle version (`truffle version`): Truffle v5.0.5 (core: 5.0.5)
* node version (`node --version`): Node v8.11.1
* npm version (`npm --version`): 5.6.0

**Comment by dblockunity** [comment] 2019-03-13 15:21
I followed the steps listed in this bug report and what I found was that the migration worked when I reproduced the problem. When creating the report I had to create an environment that matched my proprietary codebase, but the new environment gives different results.

**Comment by dblockunity** [comment] 2019-03-13 16:00
In my original repository, I deleted the contracts folder and tried the migration again and it was successful. The issue seems to be caused by old null references after a migration takes place with migration scripts where javascript variables reference invalid artifacts.

**Comment by panicape** [comment] 2019-03-19 11:13
@dblockunity hi, i just got the same error and i want to ask you which repository are you taking as the original one? do you mean the blockchain where the contracts are being deployed? some concrete folder in the project? any other?
Thanks for your help

**Comment by CruzMolina** [comment] 2019-04-09 21:20
Just to clarify (in case it helps anyone), `truffle-hdwallet-provider` and truffle in general is currently compatible w/ web3.js up to 1.0.0-beta.37.

**Comment by gnidan** [comment] 2019-04-17 17:49
I'm a bit unclear what the problem is. Tried to assign labels that seem to match. I'll move this to our backlog so we make sure to circle back on it, but any additional information would be helpful! Thanks!

**Comment by CruzMolina** [comment] 2019-04-17 18:06
FWIW @dblockunity , the `network_id` for the `ropsten` network in your `truffle.js` should be `3`, instead of `"*"`.

**Comment by eggplantzzz** [comment] 2020-03-11 18:02
Is this still a problem on the latest Truffle (version 5.1.6)? If so, are the reproduction steps above still relevant?

**Comment by gnidan** [comment] 2020-04-15 18:09
This issue's gotten pretty stale. I would be very surprised if it were still a problem on latest Truffle. As such (and after some additional head-scratching)... closing for issue maintenance!

Let us know if this needs to be re-opened! Thanks all!

**Comment by k0d3d** [comment] 2021-03-27 19:40
I had this issue when compiling using my global truffle module. i switched to `npx truffle compile` after installing it as a dev dependency. The global module was v5.0.5 and the local module was v5.2.6 . so you might want to check your compiler version.

**Comment by drachs** [comment] 2021-06-23 06:54
I'm having this problem today on 5.3.10 :(   For the life of me I can't get it to deploy to the rinkeby network.

**Comment by cds-amal** [comment] 2021-06-23 14:03
Hi @drachs, are the reproduction steps above accurate? If not, would you mind opening a new issue with updated reproduction steps?

**Comment by haltman-at** [comment] 2022-02-09 19:23
Closing this again for issue maintenance; if anyone is still having this issue, I would suggest opening a new one.  Thanks!

**Closed by haltman-at** 2022-02-09 19:23 UTC
Labels: needs reproduced, Migrations, error better
