### ISSUE TITLE
Upgrade web3 instance in test suite to 1.0.0

### ISSUE THREAD

**Issue by kyriediculous** [trufflesuite/truffle#887] opened 2018-04-06 23:50 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The web3 instance provided in tests with truffle is still version 0.20.5. 
Some functions that are useful to make assertions do not work properly in this version:
eg. web3.toAscii still adds padding. 
This is supposedly fixed in web1.0.0 with web3.utils.hexToAscii() or web3.utils.hexToUtf8()

please see https://github.com/ethereum/web3.js/issues/337

## Actual Results
`AssertionError: Not the same name: expected 'John Doe' to equal 'John Doe\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'`

## Environment

* Operating System: Ubuntu 16.04
* Ethereum client: Ganache 
* Truffle version (`truffle version`):4.1.3

**Comment by cgewecke** [comment] 2018-04-06 23:57
@kyriediculous There's are PRs for web3 1.0 in progress across various modules in the project, centered on [truffle-contract 95](https://github.com/trufflesuite/truffle-contract/pull/95). 

Web3 1.0's new interface is a significant breaking change so upgrading will require a major release here. We're hoping to make the Web3 1.0 work available on a nightly build fairly soon, possibly next week (pending its completion and review). 

Closing as duplicate of [truffle-contract 56](https://github.com/trufflesuite/truffle-contract/issues/56)

**Closed by cgewecke** 2018-04-06 23:57 UTC

**Comment by kyriediculous** [comment] 2018-04-07 00:00
Apologies for the dupe, looking forward.

**Comment by cgewecke** [comment] 2018-04-07 00:02
@kyriediculous No worries! Will ping [truffle-contract 95](https://github.com/trufflesuite/truffle-contract/pull/95) when the nightly ships.
