### ISSUE TITLE
Compatibility with newer Web3 versions

### ISSUE THREAD

**Issue by filips123** [trufflesuite/truffle#1690] opened 2019-01-31 18:43 UTC
Truffle has many problems with Web3 since `1.0.0-beta.38`.

There were many changes in this version including refactoring, porting to ES6 and implementing EthereumProvider. You can see a summary of all changes [here](https://github.com/ethereum/web3.js/releases/tag/v1.0.0-beta.38). It looks like some of that changes are incompatible with Truffle, so it has many problems.

There was already fix for that (see #1667 and #1689), but it only locked Web3 to `1.0.0-beta.37` which had no problems.

This should only be a quick temporary solution because it now uses outdated Web3 version. There should be support for newer versions.

**Comment by Levino** [comment] 2019-01-31 18:58
> It looks like some of that changes are incompatible with Truffle, so it has many problems.

This should be expected if one uses a software clearly marked as "beta", right? I honestly wonder what exactly the "many problems" are. I did not encounter any when using truffle. Maybe you can add some links to issues that are caused by using the old version of the web3 beta.37?

**Comment by filips123** [comment] 2019-01-31 19:12
Problems are not caused by the old version (`beta.37`), but with new (`beta.38` and later). Some of them are #1667.

For now, there is nothing wrong with using that old version, but I opened that issue because Truffle would need to move to a new Web3 version (if not earlier when 1.0 becomes stable).

**Comment by gnidan** [comment] 2019-01-31 21:46
Thanks for opening this!

**Comment by gnidan** [comment] 2019-01-31 21:47
FWIW this is related https://github.com/ethereum/web3.js/issues/2266

**Comment by filips123** [comment] 2019-06-02 13:31
@Levino @gnidan Now this seems like a very important bug. Because of #2070, Truffle is unusable on Node.js 12.

**Comment by gnidan** [comment] 2019-06-02 17:37
I'm labeling this on hold because the newer Web3.js versions include breaking changes, not only for Web3.js itself, but also for Truffle, since Truffle exposes Web3.js's external interface. These breaking changes will have to wait until Truffle v6.

We've identified a path forward; expect an announcement from Web3.js soon!

Thanks!

**Comment by filips123** [comment] 2019-06-02 17:41
When will Truffle v6 be released? I know it would be hard, but it is needed. Node.js 12 will become LTS in October, so if it won't be fixed until then, it could be a problem.

**Comment by filips123** [comment] 2019-07-23 09:50
@gnidan Web3 beta 37 is now released as `1.2.0`. Can Truffle now be updated to use it?

**Comment by eggplantzzz** [comment] 2019-07-23 12:15
Yes, I will get in a PR for Truffle to use `1.2.0` today.

**Comment by gnidan** [comment] 2019-07-26 00:00
It's released! Closing this, as Truffle v5.0.29 now comes with `web3@latest`

Thanks all!

**Closed by gnidan** 2019-07-26 00:00 UTC
Labels: on hold

**Comment by Levino** [comment] 2019-07-26 07:01
How about linking the PR or commit?

**Comment by Levino** [comment] 2019-07-26 07:05
https://github.com/trufflesuite/truffle/commit/aaacccc6e85b914d295d3f1e14e60ac8ed2e568a
