### ISSUE TITLE
Looks like function overrides are not supported by test framework

### ISSUE THREAD

**Issue by aleybovich** [trufflesuite/truffle#820] opened 2018-02-27 02:30 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

If a contract has an override function, unit tests for that function break.

## Steps to Reproduce

Simplest example I could create to reproduce the issue

Contract: 
```
pragma solidity ^0.4.18;

contract BaseExample {
    function approve(address _spender, uint _value) public returns (bool) {
        return true;
    }

    function increaseApproval(address _spender, uint _addedValue) public returns (bool) {
        return true;
    }
}

contract OverrideExample is BaseExample {

    function approve(address _spender, uint _value, bytes _data) public returns (bool) {
        return true;
    }

    function increaseApproval(address _spender, uint _addedValue, bytes _data) public returns (bool) {
        return true;
    }
}
```

Unit test:

```
const OverrideExample = artifacts.require("OverrideExample");

contract("OverrideExample", (accounts) => {
    let instance;

    before(async () => {
        instance = await OverrideExample.deployed();
    })

    it("Test lowercase method - base", async () => {
        await instance.approve(0x0, 1);
    });

    it("Test lowercase method - override", async () => {
        await instance.approve(0x0, 1, 0x0); // BREAKS
    });

    it("Test camelCase method - base", async () => {
        await instance.increaseApproval(0x0, 1); // BREAKS
    });

    it("Test camelCase method - override", async () => {
        await instance.increaseApproval(0x0, 1, 0x0);
    });
})
```

Run `truffle migrate` and then `truffle test`.

## Expected Behavior

No errors, all tests pass

## Actual Results

When I run `truffle migrate` and then `truffle test`, I get the following error:

```
1) Contract: OverrideExample Test lowercase method - override:
     Error: Invalid number of arguments to Solidity function
      at Object.InvalidNumberOfSolidityArgs (/Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:25:1)
      at SolidityFunction.validateArgs (/Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:74:1)
      at SolidityFunction.toPayload (/Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:90:1)
      at SolidityFunction.sendTransaction (/Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:163:1)
      at SolidityFunction.execute (/Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
      at /Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:202:1
      at /Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:155:1
      at process._tickCallback (internal/process/next_tick.js:109:7)

  2) Contract: OverrideExample Test camelCase method - base:
     Error: Invalid number of arguments to Solidity function
      at Object.InvalidNumberOfSolidityArgs (/Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:25:1)
      at SolidityFunction.validateArgs (/Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:74:1)
      at SolidityFunction.toPayload (/Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:90:1)
      at SolidityFunction.sendTransaction (/Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:163:1)
      at SolidityFunction.execute (/Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
      at /Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:202:1
      at /Users/leyboan1/.local/share/npm/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:155:1
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

## Environment

* Operating System:  Mac OSX
* Ethereum client: Ganache 
* Truffle version (`truffle version`): 4.0.7
* node version (`node --version`): 7.7.3
* npm version (`npm --version`): 4.0.3

**Comment by cgewecke** [comment] 2018-02-27 02:39
@aleybovich Yes that's true. `truffle-contract` doesn't support this although it's been implemented in [truffle-contract 95](https://github.com/trufflesuite/truffle-contract/pull/95) where an upgrade to `web3 1.0` is happening. Do you mind if I close this as a duplicate of #737?

I believe you should be able to access `web3's` own syntax for function overloading through the `.contract` property on an instance. e.g:
```
myInstance.contract.myMethod['uint256'](5000)
```

(I think that's their syntax but it might be good to check over there).

**Comment by aleybovich** [comment] 2018-02-27 02:50
Thank you for replying! Looks like it was you who submitted that pull request - any ideas when it's going to be released?

**Comment by cgewecke** [comment] 2018-02-27 02:54
@aleybovich No. It breaks a lot of stuff for people so it will wait for a major release. There are still some things that have to be done there too . . . small bugs and some features. But we might start continuously deploying patch fixes and experimental branches here soon so it could be available as an `alpha` soon-ish.

**Comment by aleybovich** [comment] 2018-02-27 03:05
Ok, I'll keep an eye. You can close it as a duplicate. Thank you!

**Closed** 2018-02-27 03:05 UTC

**Comment by aleybovich** [comment] 2018-02-27 16:26
@cgewecke I have tried using `.contract` as you have suggested above, and seems like it has the same issue. 

`await instance.contract.increaseApproval.sendTransaction(ownerAddress, 47, { from: user1Address });`

causes `Error: Invalid number of arguments to Solidity function`

That makes sense as it's using the same version of web3 as truffle. Sounds like there is no good workaround, and sound like I can't use `truffle-contracts` in my prod code either.

**Comment by cgewecke** [comment] 2018-02-27 16:41
@aleybovich The key part of their syntax is the way you specify *which* function signature you want to use using array notation:
```
myMethod['uint256']               // Specifies e.g myMethod(5) 
myMethod['uint256,uint256'] // Specified eg myMethod(5,5)
```

I'm looking for an example somewhere because I'm not sure exactly what a call that works looks like in web3 0.x.x . . .
