### ISSUE TITLE
Truffle init without internet connection throws unhandled error

### ISSUE THREAD

**Issue by ana0** [trufflesuite/truffle#621] opened 2017-10-16 04:04 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
`Truffle init` on a computer without wifi throws unhandled error

## Steps to Reproduce
Turn off wifi, `truffle init`

## Expected Behavior

Some kind of message that indicates truffle needs internet to run this command

## Actual Results

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com:443
    at Object.exports._errnoException (util.js:1050:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

## Environment

* Operating System:  Tried on windows 10 and ubuntu 16.04, same behaviour
* Truffle version: Truffle v3.4.9 (core: 3.4.8)
* Ethereum client: n/a
* node version: v7.10.1
* npm version: 5.4.2

**Comment by gnidan** [comment] 2017-10-17 21:04
Thanks for reporting this! Closing as duplicate of #617

**Closed by gnidan** 2017-10-17 21:04 UTC
