### ISSUE TITLE
Truffle does not show proper error message when attempting to migrate abstract contract

### ISSUE THREAD

**Issue by Qqwy** [trufflesuite/truffle#499] opened 2017-07-15 13:49 UTC
## Issue

When you call `truffle migrate --reset` or `truffle test` while you have a contract that does not implement all calls of its abstract interface(s), we will get an error akin to:

```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:207913:46)
    at /home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:31866:25
    at /home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:209746:9
    at XMLHttpRequest.request.onreadystatechange (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:208522:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:210395:18)
    at XMLHttpRequest._setReadyState (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:210685:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:210840:12)
    at IncomingMessage.<anonymous> (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:210800:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)

```

## Steps to Reproduce

```
contract Supply {
    function totalSupply() constant returns (uint totalSupply);
}

contract MyContract is Supply {
    uint8 public number;
    function set(uint8 new_number) {
        number = new_number;
    }
}
```

Migrations file:
```
var MyContract = artifacts.require("./MyContract.sol");

module.exports = function(deployer) {
    deployer.deploy(MyContract);
};

```

## Expected Behavior

I'd expect an error message that is useful to debug the issue. In this case, something stating that we're trying to deploy an abstract or otherwise invalid contract. (Its bytecode is `0x`.)

## Actual Results

```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:207913:46)
    at /home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:31866:25
    at /home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:209746:9
    at XMLHttpRequest.request.onreadystatechange (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:208522:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:210395:18)
    at XMLHttpRequest._setReadyState (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:210685:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:210840:12)
    at IncomingMessage.<anonymous> (/home/qqwy/.asdf/installs/nodejs/7.8.0/.npm/lib/node_modules/truffle/build/cli.bundled.js:210800:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)

```

## Environment

* Operating System: Linux Mint Serena.
* Truffle version:
  * Truffle v3.4.3 (core: 3.4.1)
  * Solidity v0.4.11 (solc-js)

* Ethereum client: testrpc
* node version: 7.8.0
* npm version: 4.2.0 (yarn version 0.24.5)

**Comment by tcoulter** [comment] 2017-07-17 16:48
Thanks for the report! I'm marking this as a dupe of trufflesuite/truffle-contract#34. Cheers!

**Closed by tcoulter** 2017-07-17 16:48 UTC
