### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'return')

### ISSUE THREAD

**Issue by fabianorodrigo** [trufflesuite/truffle#4639] opened 2022-01-22 16:42 UTC
Hi,

I have some tests that run fine on ganache 2.5.4 but got this exception when I tried to run on ganache 7.

`1) Contract: BetToken
       "before each" hook for "Should Ether goes to ERC20 owner after destroy contract":
     Uncaught TypeError: Cannot read properties of null (reading 'return')
      at Object._extract (/home/fabianorodrigo/.nvm/versions/node/v16.13.2/lib/node_modules/truffle/build/webpack:/packages/contract/lib/reason.js:29:1)
      at /home/fabianorodrigo/.nvm/versions/node/v16.13.2/lib/node_modules/truffle/build/webpack:/packages/contract/lib/reason.js:64:1
      at /home/fabianorodrigo/.nvm/versions/node/v16.13.2/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
      at XMLHttpRequest.request.onreadystatechange (/home/fabianorodrigo/.nvm/versions/node/v16.13.2/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/fabianorodrigo/.nvm/versions/node/v16.13.2/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (/home/fabianorodrigo/.nvm/versions/node/v16.13.2/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpResponseEnd (/home/fabianorodrigo/.nvm/versions/node/v16.13.2/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (/home/fabianorodrigo/.nvm/versions/node/v16.13.2/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
`

Repository: https://github.com/fabianorodrigo/dappsoccerbet

> truffle test --network ganache

**Comment by cds-amal** [comment] 2022-01-23 19:35
Thanks for reporting this @fabianorodrigo! At first glance, it looks like we're not presenting the revert reason correctly. I will verify this tomorrow.

**Comment by cds-amal** [comment] 2022-01-24 19:54
@fabianorodrigo, confirmed, related to this [issue](https://github.com/trufflesuite/ganache/issues/2133#issuecomment-1018935138). I'm going to discuss how to proceed with the team. Will post updates here.

**Comment by cds-amal** [comment] 2022-01-26 02:13
Well, it looks like the next release of truffle which includes #4641 and a Ganache dependency update should address this. Thanks again for reporting the issue @fabianorodrigo

**Comment by fabianorodrigo** [comment] 2022-01-26 10:51
It's was pleasure to be of service. Thanks a lot!

**Comment by gnidan** [comment] 2022-01-29 22:11
This is addressed and released in [Truffle v5.4.31](https://github.com/trufflesuite/truffle/releases/tag/v5.4.31). Thank you so much!!

**Closed by gnidan** 2022-01-29 22:11 UTC
Labels: bug, needs investigated
