### ISSUE TITLE
Truffle not found cmd

### ISSUE THREAD

**Issue by BenWute** [trufflesuite/truffle#1396] opened 2018-10-31 16:09 UTC
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Hi,
I'm following the video "How to Build Ethereum Dapp (Decentralized Application Development Tutorial)" from the DappUniversity and I were able to install everything but when I had to call truffle there was a problem.
![image](https://user-images.githubusercontent.com/44647135/47801131-d153d880-dd2d-11e8-90a1-610ac49769e2.png)
I tried to fix it by uninstalling and reinstalling truffle and restarting my computer but it didn't work

## Steps to Reproduce

npm install -g truffle

mkdir election

cd election

truffle unbox pet-shop -> Error

## Expected Behavior

Unbox the pet-shop

## Actual Results

It is the same error as in another issue I found here (https://github.com/trufflesuite/truffle/issues/542), but with the answer in the other issue I couldn't solve my problem

Hopefully you can help me fix the problem.

I have read about changig something in the environment variables, but I sadly didn't understand it.

Thanks!!

**Comment by fainashalts** [comment] 2018-11-01 16:09
Hi there, I was not able to reproduce this issue. I do believe that the advice in #542 is correct regarding your need to fix the path setup to ensure you can access truffle appropriately. 

This stackoverflow discussion should make things a lot clearer: https://stackoverflow.com/questions/14803978/npm-global-path-prefix

Basically, you'll need to check if your path is correct for npm and truffle. When I run` npm config get prefix` in my terminal I get `/usr/local`, which should be the default on a mac. If you are using a different operating system, I think the stackoverflow discussion above should be very helpful in figuring this out. 

I'm going to close this issue as it doesn't look to be a problem with the Truffle code, but if you find that is not the case or run across a different problem, please feel free to open a new issue. Thanks!

**Closed by fainashalts** 2018-11-01 16:09 UTC
