### ISSUE TITLE
Truffle test fails with payable fallback function

### ISSUE THREAD

**Issue by jasontwong** [trufflesuite/truffle#743] opened 2018-01-09 22:04 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Payable fallback functions will crash with a `VM Exception` during `truffle test` if it modifies the state.

## Steps to Reproduce

- Create any contract with a payable fallback function that modifies state. Example:
```
pragma solidity ^0.4.18;

contract MyContract {
  uint256 public money;

  function () external payable {
    money = 5;
  }
}
```
- Write a test that sends ether to the contract. Example:
```
pragma solidity ^0.4.18;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/MyContract.sol";

contract TestMyContract {
  uint public initialBalance = 1 ether;

  function testSend() public {
    MyContract token = MyContract(DeployedAddresses.MyContract());

    Assert.equal(token.money(), 0, "money should be 0.");

    token.transfer(1000);

    Assert.equal(token.money(), 5, "money should be 5.");
    Assert.notEqual(this.balance, initialBalance, "Balance should have changed.");
  }
}
```
- Run `truffle test`.

## Expected Behavior

- I expect the state of the contract to change. In this case, money should change to `5`.

## Actual Results

- I receive a `VM Exception`.
```
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/Users/jwong/.config/yarn/global/node_modules/truffle/build/cli.bundled.js:41484:16)
      at /Users/jwong/.config/yarn/global/node_modules/truffle/build/cli.bundled.js:329530:36
      at /Users/jwong/.config/yarn/global/node_modules/truffle/build/cli.bundled.js:325200:9
      at XMLHttpRequest.request.onreadystatechange (/Users/jwong/.config/yarn/global/node_modules/truffle/build/cli.bundled.js:328229:7)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/jwong/.config/yarn/global/node_modules/truffle/build/cli.bundled.js:176415:18)
      at XMLHttpRequest._setReadyState (/Users/jwong/.config/yarn/global/node_modules/truffle/build/cli.bundled.js:176705:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/jwong/.config/yarn/global/node_modules/truffle/build/cli.bundled.js:176860:12)
      at IncomingMessage.<anonymous> (/Users/jwong/.config/yarn/global/node_modules/truffle/build/cli.bundled.js:176820:24)
```

## Environment

* Operating System: macOS High Sierra 10.13.2 (17C88)
* Truffle version: Truffle v4.0.4 (core: 4.0.4)
* Ethereum client: Truffle Test
* node version: v8.2.1
* npm version: 5.3.0

**Comment by Tmeister** [comment] 2018-01-12 01:32
Same issue here.

I'm using the StandardToken contract as follows:

```
pragma solidity ^0.4.18;

import 'zeppelin-solidity/contracts/token/StandardToken.sol';


contract MyTestToken is StandardToken {
    string public name = 'TEST';
    string public symbol = 'TST99';
    uint8 decimals = 18;
    uint public INITIAL_SUPPLY = 30000000e18;

    function TestToken () public {
        totalSupply = INITIAL_SUPPLY;
        balances[msg.sender] = INITIAL_SUPPLY;
    }
}

```

The test function:

```
function test_transfer_with_invalid_amount() public {
        bool transferSuccessful = _fundaryTestToken.transfer(_owner, 31000000000000000000000000);
        Assert.isFalse(transferSuccessful, 'Addresses should not be able to transfer more tokens than allocated');
    }
```

Run `truffle test`

```
➜  mastercoin git:(master) ✗ truffle test
Using network 'development'.

Compiling ./contracts/TestToken.sol...
Compiling ./test/MyTestToken.sol...
Compiling truffle/Assert.sol...
Compiling zeppelin-solidity/contracts/math/SafeMath.sol...
Compiling zeppelin-solidity/contracts/token/BasicToken.sol...
Compiling zeppelin-solidity/contracts/token/ERC20.sol...
Compiling zeppelin-solidity/contracts/token/ERC20Basic.sol...
Compiling zeppelin-solidity/contracts/token/StandardToken.sol...


  MyTestToken
    ✓ test_constructor (88ms)
    ✓ test_transfer_with_valid_amount (148ms)
    1) test_transfer_with_invalid_amount
    > No events were emitted
    ✓ test_totalSupply (84ms)
    ✓ test_approve_whit_valid_amount (100ms)
    ✓ test_allowance_with_no_allocated_balance (121ms)
    ✓ test_allowance_with_allocated_balance (149ms)

  Contract: MyTestToken
    ✓ Should contain 30000000000000000000000000 MyTestToken in circulation


  7 passing (3s)
  1 failing

  1) MyTestToken test_transfer_with_invalid_amount:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/Users/tmeister/.nvm/versions/node/v6.11.1/lib/node_modules/truffle/build/cli.bundled.js:41484:16)
      at /Users/tmeister/.nvm/versions/node/v6.11.1/lib/node_modules/truffle/build/cli.bundled.js:329530:36
      at /Users/tmeister/.nvm/versions/node/v6.11.1/lib/node_modules/truffle/build/cli.bundled.js:325200:9
      at XMLHttpRequest.request.onreadystatechange (/Users/tmeister/.nvm/versions/node/v6.11.1/lib/node_modules/truffle/build/cli.bundled.js:328229:7)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/tmeister/.nvm/versions/node/v6.11.1/lib/node_modules/truffle/build/cli.bundled.js:176415:18)
      at XMLHttpRequest._setReadyState (/Users/tmeister/.nvm/versions/node/v6.11.1/lib/node_modules/truffle/build/cli.bundled.js:176705:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/tmeister/.nvm/versions/node/v6.11.1/lib/node_modules/truffle/build/cli.bundled.js:176860:12)
      at IncomingMessage.<anonymous> (/Users/tmeister/.nvm/versions/node/v6.11.1/lib/node_modules/truffle/build/cli.bundled.js:176820:24)
```

Logs

```
[7:26:15 PM] eth_sendTransaction
[7:26:15 PM]   Transaction: 0x4e99c36525a65e9451f68a5f373bec2c9d99858107d750da0e5bd552a5ebee09
[7:26:15 PM]   Gas usage: 24281
[7:26:15 PM]   Block Number: 84
[7:26:15 PM]   Block Time: Thu Jan 11 2018 19:26:15 GMT-0600 (CST)
[7:26:15 PM]   Runtime Error: revert
```

Environment

Operating System: macOS High Sierra 10.13.2 (17C88)
Truffle version: Truffle v4.0.4 (core: 4.0.4)
Ethereum client: Truffle Test
Ganache 1.0.1

**Comment by cgewecke** [comment] 2018-01-12 02:18
Hi @jasontwong, @Tmeister. It looks like you're facing separate but similar issues.

@jasontwong: To transfer eth from one contract to another you'll first need to fund the contract from an account that has a balance. There's a nice example of how to do that in the Truffle docs [here](http://truffleframework.com/docs/getting_started/contracts#sending-ether-to-a-contract). Additionally, you should know that using Solidity's `transfer` and `send` methods limits the amount of gas allocated for the execution of the fallback function - typically just enough to fire an event. Setting a variable might be too expensive. There's more about this at the solidity docs [here](http://solidity.readthedocs.io/en/develop/contracts.html#fallback-function).

@Tmeister: It looks like your test is throwing, which is what you want. The issue is that this error should be triggered in a try-catch block, and assertions made for each section. It's a common pattern in Solidity testing and there are nice examples at `zeppelin`'s own test suite [here](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/Claimable.test.js#L35). They've also written some helpful JS utilities for cases like this - [here](https://github.com/OpenZeppelin/zeppelin-solidity/tree/master/test/helpers).

Closing for house-keeping since these don't seem like problems with Truffle as such, but please re-open if you discover otherwise. Or open a new issue. Thanks!

**Closed by cgewecke** 2018-01-12 02:18 UTC
