### ISSUE TITLE
Bug: Truffle fails ungracefully when web3 throws due to an invalid provider.

### ISSUE THREAD

**Issue by dan-turner** [trufflesuite/truffle#1724] opened 2019-02-18 10:43 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

Note: this issue description has been edited from its original content by @benjamincburns to capture our current understanding of the problem:

## Issue

Specifying a `provider` in `truffle-config.js` is broken with web3 versions `>=1.0.0-beta.38`. This issue is captured already by ethereum/web3.js#2266. However, the error thrown by web3 in this case (`Error: Please provide an valid Web3 provider`) is silenced, likely somewhere in `truffle-config`.

## Steps to Reproduce

The following `truffle-config.js` does not notify the user of the issue when using `web3@1.0.0-beta.38` and all later versions (at time of writing):
```
const Web3 = require('web3');

const host = "localhost";
const port = 8545

const httpProvider = new Web3.providers.HttpProvider(`http://${host}:${port}`);
const web3 = new Web3(httpProvider);

/* The following line does actually work */
web3.eth.getBlockNumber().then(d => console.log(`Current block: ${d}`));

module.exports = {
  networks: {
    development: {
      provider: function() {
        return httpProvider;
      },
      network_id: '*'
    }
  }
};
```
Output:
```
› yarn truffle console --network development --verbose-rpc
yarn run v1.13.0
$ /Users/dan/code/consensys/drizzle/node_modules/.bin/truffle console --network development --verbose-rpc
   > {
   >   "jsonrpc": "2.0",
   >   "id": 1,
   >   "method": "net_version",
   >   "params": []
   > }
Current block: 0
✨  Done in 7.40s.
```

## Expected Behavior

Truffle should inform the user that web3 has failed to accept the provider, either by bubbling up the exception message directly, or by wrapping it in an error of our own.

## Actual Results

The provider scenario silently fails.

## Environment

* Operating System:  MacOS
* Ethereum client: Any
* Truffle version (`truffle version`): Truffle (unbundled) (core: 5.0.4)
* node version (`node --version`): v11.7.0
* npm version (`npm --version`): 6.7.0

**Comment by benjamincburns** [comment] 2019-02-20 00:39
Users experiencing this problem should pin their web3 dependency to `1.0.0-beta.37` until a workaround for ethereum/web3.js#2266 is developed. I'd advise users impacted by this issue can voice their concerns  over on that thread.

ethereum/web3.js#2266, which was introduced in `web3@1.0.0-beta.38` and at time of writing is still present in the current version of web3.

To confirm this was the cause of the issue, we asked @dan-turner to pin his web3 dependency to `1.0.0-beta.37` (was previously `^1.0.0-beta.35`). This corrected the problem. We think that this was likely resolving to some version of web3 that is `>=1.0.0-beta.38`. 

There's an outside chance that this was actually caused by other truffle breaking bugs that were present in `web3@1.0.0-beta.35`, but these issues were fixed in the `1.0.0-beta.37` release.

**Comment by benjamincburns** [comment] 2019-02-20 00:41
Closing this issue, as it's redundant to the one over on the web3 issue tracker.

**Comment by benjamincburns** [comment] 2019-02-20 00:48
Actually, it's a bug that the error from ethereum/web3.js#2266 didn't bubble up to the user in any form. Reopening this case (and lightly editing the description) so we can action that change.

**Comment by gnidan** [comment] 2019-04-10 17:51
Is this still an issue? We can improve the error handling here to notify unsupported web3 versions. Thanks!

**Comment by eggplantzzz** [comment] 2020-03-11 17:50
I believe this got solved a while back with [this](https://github.com/trufflesuite/truffle/pull/2510). Thanks for suggesting this kind of thing!

**Closed by eggplantzzz** 2020-03-11 17:50 UTC
Labels: error better
