### ISSUE TITLE
Truffle debug `TypeError: Cannot read property 'id' of undefined`

### ISSUE THREAD

**Issue by isaacsultan** [trufflesuite/truffle#1752] opened 2019-02-21 20:20 UTC
## Issue

Receiving `TypeError: Cannot read property 'id' of undefined` whenever truffle `debug` is used with `ganache-cli`

NB: the string 'id' does not appear anywhere in my `.sol` contract or `.js` unit test that produced the transaction.

## Steps to Reproduce

```
truffle debug 0xa1e863b7859a74ab256060bcba215f8669f57fc932c00971b44450000160c387
```

## Actual Results

```
Gathering transaction data...

TypeError: Cannot read property 'id' of undefined
    at newScope.variables.concat.filter.variable (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1738:1)
    at Array.filter (<anonymous>)
    at map (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1735:1)
    at Array.map (<anonymous>)
    at data.info.scopes._ (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1720:125)
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:76:1
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
    at Function._ (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
    at args (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1)
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
    at Function._ (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
    at args (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1)
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at runSelectEffect (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:723:1)
    at runEffect (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1191:1)
    at digestEffect (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1258:1)
    at next (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1148:1)
    at currCb (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1238:1)
    at checkEnd (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/chunk-585b854f.js:154:1)
    at chCbAtKey (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/chunk-585b854f.js:170:1)
    at Object.currCb [as cont] (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1238:1)
    at end (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1001:1)
    at Object.task.cont (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:829:1)
    at next (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1157:1)
    at Object.currCb [as cont] (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1238:1)
    at end (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1001:1)
The above error occurred in task session.saga
Tasks cancelled due to error:
controller.saga
data.saga
evm.saga
solidity.saga
trace.saga
web3.saga
```

## Environment

* Operating System: macOS
* Ethereum client: ganache0-cli
* Truffle version: Truffle v5.0.0 
* node version: v8.9.3
* npm version: 6.5.0

**Comment by gnidan** [comment] 2019-02-25 21:19
Could you try upgrading to the latest version of Truffle?
```
npm uninstall -g truffle
npm install -g truffle@5.0.5
```

Note that you will also need to upgrade to Node v8.9.4 or later.

Please let us know if the problem still occurs!

**Comment by isaacsultan** [comment] 2019-02-25 22:44
Thanks @gnidan , I've now upgraded to 5.05. Receiving a new error on truffle debug [x]:

```
TypeError: Cannot read property 'replace' of undefined
    at Object.formatLineNumberPrefix (/anaconda/lib/node_modules/truffle/build/webpack:/packages/truffle-debug-utils/index.js:156:1)
    at Object.formatRangeLines (/anaconda/lib/node_modules/truffle/build/webpack:/packages/truffle-debug-utils/index.js:232:1)
    at printState (/anaconda/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/debug.js:166:1)
    at Object.interpreter (/anaconda/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/debug.js:672:1)
    at Object.interpreter (util.js:1094:13)
    at ReplManager.interpret (/anaconda/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/repl.js:118:1)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:442:10)
    at emitOne (events.js:116:13)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
    at REPLServer.Interface._ttyWrite (readline.js:911:14)
    at REPLServer.self._ttyWrite (repl.js:511:7)
    at ReadStream.onkeypress (readline.js:160:10)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1011:36)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at TTY.onread (net.js:594:20)
```
Not sure if this is related to my original issue or not?

**Comment by isaacsultan** [comment] 2019-02-26 10:22
Thanks @gnidan Having upgraded to truffle v5.0.5 and latest version of ganache-cli, the problem still persists!

```
Gathering transaction data...

TypeError: Cannot read property 'id' of undefined
    at newScope.variables.concat.filter.variable (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1738:1)
    at Array.filter (<anonymous>)
    at map (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1735:1)
    at Array.map (<anonymous>)
    at data.info.scopes._ (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1720:125)
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:76:1
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
    at Function._ (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
    at args (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1)
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
    at Function._ (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
    at args (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1)
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
    at /Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at runSelectEffect (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:723:1)
    at runEffect (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1191:1)
    at digestEffect (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1258:1)
    at next (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1148:1)
    at currCb (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1238:1)
    at checkEnd (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/chunk-585b854f.js:154:1)
    at chCbAtKey (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/chunk-585b854f.js:170:1)
    at Object.currCb [as cont] (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1238:1)
    at end (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1001:1)
    at Object.task.cont (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:829:1)
    at next (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1157:1)
    at Object.currCb [as cont] (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1238:1)
    at end (/Users/isaacsultan/.nvm/versions/node/v10.14.2/lib/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1001:1)
The above error occurred in task session.saga
Tasks cancelled due to error:
controller.saga
data.saga
evm.saga
solidity.saga
trace.saga
web3.saga
```

**Comment by Eugenpaul** [comment] 2019-02-26 15:28
I was having the same issue, but on Ubuntu 16.04. The thing that solved it for me was downgrading truffle to 5.0.3 (5.0.4 and 5.0.5 both appeared to have this problem)
Env:
Ganache CLI v6.3.0 (ganache-core: 2.4.0)
Node v11.9.0
npm 6.8.0

**Comment by gnidan** [comment] 2019-02-26 18:07
Can anyone provide full reproduction steps? Thanks!

**Comment by isaacsultan** [comment] 2019-02-27 14:53
Hi @gnidan, I've pushed up a simple repo that displays this issue: 

https://github.com/isaacsultan/workshop/

Steps:

```
npm i
ganache-cli
truffle test
truffle debug [LAST-TRANSACTION]
```

**Comment by robertmagier** [comment] 2019-02-28 03:59
Having similar problem in all versions: 5.0.0 5.0.1 5.0.2 5.0.3 5.0.4 and 5.0.5
```
truffle version
Truffle v5.0.5 (core: 5.0.5)
Solidity v0.5.0 (solc-js)
Node v11.10.0
```
In 5.0.0 I get message
`TypeError: Cannot destructure property `source` of 'undefined' or 'null'.`


In 5.0.5 it is:
```
TypeError: Cannot read property 'id' of undefined
    at newScope.variables.concat.filter.variable (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-debugger\dist\debugger.js:1738:1)
    at Array.filter (<anonymous>)
    at map (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-debugger\dist\debugger.js:1735:1)
    at Array.map (<anonymous>)
    at data.info.scopes._ (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-debugger\dist\debugger.js:1720:125)
    at C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:76:1
    at C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:36:1
    at C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:90:1
    at Function._ (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:36:1)
    at args (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect-tree\index.js:209:1)
    at C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:86:1
    at Function._ (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:36:1)
    at args (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect-tree\index.js:209:1)
    at C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:86:1
    at C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:36:1
    at runSelectEffect (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:723:1)
    at runEffect (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:1191:1)
    at digestEffect (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:1258:1)
    at next (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:1148:1)
    at currCb (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:1238:1)
    at checkEnd (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\chunk-585b854f.js:154:1)
    at chCbAtKey (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\chunk-585b854f.js:170:1)
    at Object.currCb [as cont] (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:1238:1)
    at end (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:1001:1)
    at Object.task.cont (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:829:1)
    at next (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:1157:1)
    at Object.currCb [as cont] (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:1238:1)
    at end (C:\Users\wild\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\@redux-saga\core\dist\redux-saga-core.esm.js:1001:1)
The above error occurred in task session.saga
Tasks cancelled due to error:
controller.saga
data.saga
evm.saga
solidity.saga
trace.saga
web3.saga

```

I am using -- openzeppelin-solidity@2.1.3 to import Ownable.sol and ERC20 and ERC771 Tokens. 
Don't know if this is important. Let me know if you need my repository.

**Comment by haltman-at** [comment] 2019-03-01 01:20
Thanks @isaacsultan!  With your example I was able to quickly isolate the problem and I have created PR #1779 to fix it.

**Comment by isaacsultan** [comment] 2019-03-01 04:49
Thank you @haltman-at, super glad that I could be of help!

**Comment by akrolak** [comment] 2020-03-14 22:21
the same thing happens to me in:
Truffle v5.1.17 (core: 5.1.17)
Solidity v0.5.16 (solc-js)
Node v10.19.0
Web3.js v1.2.1

**Comment by haltman-at** [comment] 2020-03-17 00:19
Hm, the same thing?  Could you post the error message for certainty here?  Also, do you perhaps have a reproduction example we could check out?

**Comment by passabilities** [comment] 2020-03-27 01:58
Same is happening to me:

```
truffle debug 0x523477b3d1ccad0f8649554524936b2483fd8bb3e93a285cac4f72d7f88c2420
Starting Truffle Debugger...
⠋ Gathering information about your project and the transaction...TypeError: Cannot read property 'id' of undefined
    at /home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/packages/debugger/dist/debugger.js:2842:377
    at Array.map (<anonymous>)
    at /home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/packages/debugger/dist/debugger.js:2842:38
    at Array.map (<anonymous>)
    at /home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/packages/debugger/dist/debugger.js:2842:38
    at /home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/reselect/es/index.js:70:1
    at /home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/reselect/es/index.js:30:1
    at /home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/reselect/es/index.js:84:1
    at /home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/reselect/es/index.js:30:1
    at runSelectEffect (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:730:1)
    at runEffect (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1204:1)
    at digestEffect (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1271:1)
    at next (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1161:1)
    at currCb (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1251:1)
    at runSelectEffect (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:731:1)
    at runEffect (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1204:1)
    at digestEffect (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1271:1)
    at next (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1161:1)
    at currCb (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1251:1)
    at runSelectEffect (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:731:1)
    at runEffect (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1204:1)
    at digestEffect (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1271:1)
    at next (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1161:1)
    at currCb (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1251:1)
    at checkEnd (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/io-6de156f3.js:165:1)
    at chCbAtKey (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/io-6de156f3.js:181:1)
    at Object.currCb [as cont] (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1251:1)
    at end (/home/passa/.nvm/versions/node/v12.7.0/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1012:1)
The above error occurred in task session.saga
Tasks cancelled due to error:
listenerSaga
controller.saga
data.saga
evm.saga
solidity.saga
trace.saga
web3.saga
```

**Comment by haltman-at** [comment] 2020-03-27 02:39
@passabilities That appears to be a different error, but we can group them together, I suppose.  Do you have a reproduction example I could try out?

**Comment by passabilities** [comment] 2020-03-27 02:47
Ahh ok I think the solution was to delete the build folder and recompile before running your tests:

```
rm -rf bulid 
truffle compile
truffle test
truffle debug 0x
```

That did the trick for me

**Comment by xlab** [comment] 2020-04-17 17:02
I still have this probem on

* Truffle v5.1.22 (core: 5.1.22)
* Node v10.19.0

Ran this sequence:

```
$ rm -rf build
$ truffle compile
$ truffle test
$ truffle debug

Starting Truffle Debugger...
⠋ Gathering information about your project...TypeError: Cannot read property 'id' of undefined
    at compilation.sources.findIndex.source (/Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/packages/debugger/dist/debugger.js:5213:1)
    at Array.findIndex (<anonymous>)
    at Function.normalize (/Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/packages/debugger/dist/debugger.js:5213:1)
    at new Session (/Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/packages/debugger/dist/debugger.js:5087:30)
    at /Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/packages/debugger/dist/debugger.js:4941:1
    at Generator.next (<anonymous>)
    at step (/Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:1
    at new Promise (<anonymous>)
    at new F (/Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/node_modules/core-js/library/modules/_export.js:36:1)
    at /Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:1
    at Function.forProject (/Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/packages/debugger/dist/debugger.js:4946:6)
    at CLIDebugger.startDebugger (/Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/packages/core/lib/debug/cli.js:73:1)
    at CLIDebugger.run (/Users/xlab/.config/yarn/global/node_modules/truffle/build/webpack:/packages/core/lib/debug/cli.js:29:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by xlab** [comment] 2020-04-17 17:40
UPD:
Seems to be failing on this line:

<img width="563" alt="Screenshot 2020-04-17 at 20 38 19" src="https://user-images.githubusercontent.com/477998/79597774-8a0d0380-80eb-11ea-91ce-1e9e392beabc.png">

https://github.com/trufflesuite/truffle/blob/eb5b18d8a996ef46d869364c72c69b14362f5630/packages/debugger/lib/session/index.js#L164

**Comment by haltman-at** [comment] 2020-04-17 22:40
@xlab That looks like a different problem to me; it just happens to have the same top line of the error message.  Unfortunately, people seem to have posted a number of different issues under this issue, simply because they involve trying to read the `id` of `undefined`.

Perhaps we could move discussion of your issue to #2977 instead?

**Comment by gnidan** [comment] 2020-04-22 17:55
@akrolak we're closing this for issue maintenance, esp. since it seems like this issue is being used as a catch-all for a number of different problems. If your problem still persists, we'd love to get to the bottom of it. Let us know and we'll reopen.

Everyone else: if you have a different issue, please open a new issue for it! Thank you all!

**Closed by gnidan** 2020-04-22 17:55 UTC
Labels: Debugger, bug
