### ISSUE TITLE
unknown transaction this error ，o(╥﹏╥)o， who help me

### ISSUE THREAD

**Issue by hqxluoyang** [trufflesuite/truffle#749] opened 2018-01-15 01:38 UTC
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xac6d07c119610df3dd7cebd2c7aa8ec60894178b58f65eae196486683f8280ff
  Migrations: 0x89e0a6520db6a901718a4d5c31e3629be91f6817
Saving successful migration to network...
  ... 0x5956945f3fd6ae32f736d3e77f2159ae1f74356ae054d8950e49aa185a42866e
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: unknown transaction
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:41484:16)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:329530:36
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:176186:11
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:325200:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:328229:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176415:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176705:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176860:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176820:24)
    at IncomingMessage.emit (events.js:164:20)

**Comment by cgewecke** [comment] 2018-01-16 02:10
@hqxluoyang Hi - it's very difficult to tell from the error logs you're showing what might be triggering this problem. Which Ethereum client are you using? 
[ ] ganache-cli
[ ] parity
[ ] geth
[ ] other (please specify)

It would also be very helpful if you could link to the public repository where the code you're running is published, or provide with clear steps to reproduce this error. Thanks! 

(Possible duplicate of #721)

**Comment by cgewecke** [comment] 2018-01-16 17:36
Closing as a duplicate of #721 since @hqxluoyang has also commented there.

**Closed by cgewecke** 2018-01-16 17:36 UTC
