### ISSUE TITLE
Deprecated warnings/errors on truffle install

### ISSUE THREAD

**Issue by jackmcd101** [trufflesuite/truffle#4173] opened 2021-07-12 18:33 UTC
Ran $ npm install -g truffle but got a lot of deprecated warnings & errors![image](https://user-images.githubusercontent.com/59311318/125338237-f510ae80-e31d-11eb-9007-dacd82e8fcec.jpeg)![image](https://user-images.githubusercontent.com/59311318/125338275-fe018000-e31d-11eb-8e35-e16aa5e74f3c.jpeg)![image](https://user-images.githubusercontent.com/59311318/125338293-02c63400-e31e-11eb-9aba-b63b01e08cf3.jpeg)![image](https://user-images.githubusercontent.com/59311318/125338318-078ae800-e31e-11eb-804c-714c7174df7f.jpeg)

**Comment by eggplantzzz** [comment] 2021-07-14 21:03
Hey @jackmcd101, thanks for reporting this! This is a duplicate of [this issue](https://github.com/trufflesuite/truffle/issues/3986). So I'm going to close this one as a duplicate of that one. Feel free to add some more info to that issue if you'd like!

**Closed by eggplantzzz** 2021-07-14 21:03 UTC
