### ISSUE TITLE
failed when compiling from from "@truffle/contract" 

### ISSUE THREAD

**Issue by Afrahdev** [trufflesuite/truffle#5152] opened 2022-05-28 08:49 UTC
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
I'm trying to fetch json file and transform them into an object so that I can interact, while using the importing from "@truffle/contract"  and when I run npm start, the compile run out the time. 

![image](https://user-images.githubusercontent.com/82292554/170818181-5a014c32-44ec-484e-9ae4-1c8cdbbb8982.png)

![image](https://user-images.githubusercontent.com/82292554/170818226-24d98b1f-287b-4b77-90a5-907489310cff.png)

### the terminal message

```

Starting the development server...
Starting the development server...
Starting the development server...
Starting the development server...
Starting the development server...


<--- Last few GCs --->

[34044:000001B989A151E0]    92858 ms: Scavenge (reduce) 2013.9 (2051.3) -> 2013.3 (2051.3) MB, 6.4 / 0.0 ms  (average mu = 0.342, current mu = 0.305) allocation failure 
[34044:000001B989A151E0]    92885 ms: Scavenge (reduce) 2014.0 (2051.3) -> 2013.5 (2051.3) MB, 5.7 / 0.0 ms  (average mu = 0.342, current mu = 0.305) allocation failure 
[34044:000001B989A151E0]    92940 ms: Scavenge (reduce) 2014.3 (2051.3) -> 2013.8 (2051.6) MB, 5.4 / 0.0 ms  (average mu = 0.342, current mu = 0.305) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7878F30AF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
 2: 00007FF787882216 DSA_meth_get_flags+65542
 3: 00007FF7878830CD node::OnFatalError+301
 4: 00007FF7881B4B6E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF78819F09D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF78804268C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF78804F339 v8::internal::Heap::PublishPendingAllocations+1129
 8: 00007FF78804C30A v8::internal::Heap::PageFlagsAreConsistent+2842
 9: 00007FF78803EF89 v8::internal::Heap::CollectGarbage+2137
10: 00007FF78804782B v8::internal::Heap::GlobalSizeOfObjects+331
11: 00007FF78808DD5B v8::internal::StackGuard::HandleInterrupts+891
12: 00007FF787D96516 v8::internal::DateCache::Weekday+8038
13: 00007FF788242541 v8::internal::SetupIsolateDelegate::SetupHeap+494417
14: 000001B98BACB35B
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! faucet@0.1.0 start: `react-scripts start`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the faucet@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yxngA\AppData\Roaming\npm-cache\_logs\2022-05-28T08_46_22_629Z-debug.log

Process finished with exit code 134

```

**Comment by impin2rex** [comment] 2022-05-30 10:24
I've faced the same issue today,

`Starting the development server...


<--- Last few GCs --->

[9713:0x130008000]    15588 ms: Scavenge 2029.9 (2072.2) -> 2026.1 (2072.2) MB, 2.0 / 0.0 ms  (average mu = 0.250, current mu = 0.222) allocation failure 
[9713:0x130008000]    15591 ms: Scavenge 2029.8 (2072.2) -> 2027.2 (2072.5) MB, 2.5 / 0.0 ms  (average mu = 0.250, current mu = 0.222) allocation failure 
[9713:0x130008000]    15653 ms: Scavenge 2030.9 (2073.2) -> 2028.8 (2081.9) MB, 60.8 / 0.0 ms  (average mu = 0.250, current mu = 0.222) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10416c5d4 node::Abort() [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
 2: 0x10416c754 node::OnFatalError(char const*, char const*) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
 3: 0x10429c0a4 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
 4: 0x10429c038 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
 5: 0x1043d3fe8 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
 6: 0x1043d68f0 v8::internal::Heap::MarkCompactPrologue() [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
 7: 0x1043d45b0 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
 8: 0x1043d2a30 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
 9: 0x1043d1db0 v8::internal::Heap::HandleGCRequest() [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
10: 0x10439a128 v8::internal::StackGuard::HandleInterrupts() [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
11: 0x1046474c4 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
12: 0x1048c1b4c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
13: 0x10b434940 
14: 0x10b43aea0 
15: 0x1048d48c8 Builtins_ArrayForEach [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
16: 0x1048557d8 Builtins_InterpreterEntryTrampoline [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
17: 0x1048557d8 Builtins_InterpreterEntryTrampoline [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
18: 0x1048557d8 Builtins_InterpreterEntryTrampoline [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
19: 0x10b3d93c4 
20: 0x1048557d8 Builtins_InterpreterEntryTrampoline [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
21: 0x104886fac Builtins_GeneratorPrototypeNext [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
22: 0x10b24a1ec 
23: 0x104886fac Builtins_GeneratorPrototypeNext [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
24: 0x10b5170b4 
25: 0x10b5183bc 
26: 0x10b517838 
27: 0x104909c78 Builtins_PromiseFulfillReactionJob [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
28: 0x1048771b4 Builtins_RunMicrotasks [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
29: 0x1048534a4 Builtins_JSRunMicrotasksEntry [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
30: 0x10437b2a0 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
31: 0x10437b5d8 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
32: 0x10437b6c4 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
33: 0x104397e3c v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
34: 0x104397cc0 v8::internal::MicrotaskQueue::PerformCheckpointInternal(v8::Isolate*) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
35: 0x1040bfbe4 node::InternalCallbackScope::Close() [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
36: 0x1040c01fc node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
37: 0x1040d835c node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
38: 0x104170284 node::fs::FSReqCallback::Resolve(v8::Local<v8::Value>) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
39: 0x10417071c node::fs::AfterNoArgs(uv_fs_s*) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
40: 0x10657b050 uv__work_done [/opt/homebrew/Cellar/libuv/1.44.1/lib/libuv.1.dylib]
41: 0x10657e3ac uv__async_io [/opt/homebrew/Cellar/libuv/1.44.1/lib/libuv.1.dylib]
42: 0x10658e1c4 uv__io_poll [/opt/homebrew/Cellar/libuv/1.44.1/lib/libuv.1.dylib]
43: 0x10657e808 uv_run [/opt/homebrew/Cellar/libuv/1.44.1/lib/libuv.1.dylib]
44: 0x1040c0b60 node::SpinEventLoop(node::Environment*) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
45: 0x1041a12ec node::NodeMainInstance::Run(int*, node::Environment*) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
46: 0x1041a0fbc node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
47: 0x104142670 node::Start(int, char**) [/opt/homebrew/Cellar/node@16/16.14.2/bin/node]
48: 0x106395088 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by davidmurdoch** [comment] 2022-06-02 17:49
@Afrahdev interesting! Looks like the node process is running out of memory. Is the JSON file very large (maybe gigabytes in size)? My hunch is that it is not Truffle Contract that is the problem, as that appears to be on the front-end (in the browser) and it is the react development server that is crashing for some reason; it's hard to say what is going wrong given the information provide. Can you provide reproduction steps?

**Comment by Afrahdev** [comment] 2022-06-23 10:00
> Did you find a solution to this? I just ran into this issue myself.

Not really I think the reason is the package is too big run and it takes a while that time. The only way I can think of is by increasing the usage memory up to 8gb on node

**Comment by cds-amal** [comment] 2022-08-04 14:23
Hey @mmichaud93, @Afrahdev - I'm closing this for issue maintenance. Please comment if you have any information to share, and we'll reopen.

**Closed by cds-amal** 2022-08-04 14:23 UTC
