### ISSUE TITLE
Why does truffle deployment to mainnet fail?

### ISSUE THREAD

**Issue by stoplion** [trufflesuite/truffle#3888] opened 2021-02-26 23:05 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------
[Also asked this question on SO.](https://stackoverflow.com/questions/66394390/why-is-it-impossible-to-deploy-a-smart-contract-to-mainnet-using-truffle). And [this one](https://stackoverflow.com/questions/66415529/truffle-deploy-insufficient-funds-despite-using-truffles-total-price-estimates)

When I deploy with Truffle it asks for almost 1 ETH in upfront cost to deploy

It fails with `"Migrations" could not deploy due to insufficient funds`, but according to the `dry-run` I have enough Eth to deploy.

I've deployed the same contract with Remix and it costs $135 in Eth. 

**Estimate the cost of deploying to Mainnet**
`NODE_ENV=production truffle migrate --network mainnet --reset --dry-run`

```
Summary
=======
> Total deployments:   2
> Final cost:          0.0701912 ETH
```

(That about $100. I have that in my wallet)

Try without `--dry-run`
`NODE_ENV=production truffle migrate --network mainnet --reset`

`"Migrations" could not deploy due to insufficient funds`

Why does this happen? 

Truffle-config
```
const path = require("path");
const dotenv = require("dotenv-flow");
const dotenvExpand = require("dotenv-expand");
const HDWalletProvider = require("@truffle/hdwallet-provider");

const pathToConfig = path.resolve("./env");

const env = dotenv.config({
  path: pathToConfig,
});

dotenvExpand(env);

module.exports = {
  networks: {
    contracts_build_directory: "./client/src/contracts",

    teams: {
      url:
        "https://sandbox.truffleteams.com/df027e94-8bfc-4af8-82de-0205db77e32c",
      network_id: 1,
    },

    development: {
      host: "127.0.0.1", // Localhost (default: none)
      port: 7545, // Standard Ethereum port (default: none)
      network_id: "*", // Any network (default: none)
      gas: 10000000,
      gasLimit: 26000000000,
    },

    kovan: {
      provider: () =>
        new HDWalletProvider({
          mnemonic: { phrase: process.env.MNEMONIC },
          providerOrUrl: process.env.RPC_URL_42,
        }),
      network_id: 42, // Kovan's id
      from: process.env.DEPLOYERS_ADDRESS,
    },

    mainnet: {
      provider: () =>
        new HDWalletProvider({
          mnemonic: { phrase: process.env.MNEMONIC },
          providerOrUrl: process.env.RPC_URL_1_WSS,
        }),
      network_id: 1, // Main's id
      from: process.env.DEPLOYERS_ADDRESS,
      gas: 3000000, // Gas limit used for deploys. Default is 4712388.
      gasPrice: 165000000000, //Gas price in Wei
      confirmations: 2, // # of confs to wait between deployments. (default: 0)
      timeoutBlocks: 200, // # of blocks before a deployment times out  (minimum/default: 50)
      skipDryRun: false, // Skip dry run before migrations? (default: false for public nets )
    },
  },

  // Set default mocha options here, use special reporters etc.
  mocha: {
    timeout: 100000,
  },

  // Configure your compilers
  contracts_build_directory: path.join(__dirname, "client/src/contracts"),
  compilers: {
    solc: {
      version: "0.7.4", // Fetch exact version from solc-bin (default: truffle's version)
      settings: {          // See the solidity docs for advice about optimization and evmVersion
        optimizer: {
          enabled: true,
          // Optimize for how many times you intend to run the code.
          // Lower values will optimize more for initial deployment cost, higher
          // values will optimize more for high-frequency usage.
          runs: 200
        },
      },
    },
  },
};
```

**Contract**
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.4;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@openzeppelin/contracts/math/SafeMath.sol";


contract EthText {
  address payable public owner;
  uint public messagesSentCount = 0;

  uint decimals = 8;
  uint scale = 10**decimals;

  uint public txtPriceUSD = 1.70 * 10**8;
  uint public txtPriceEth;

  using SafeMath for uint;

  AggregatorV3Interface internal priceFeed;

  event Spend(
    string textMsg,
    string recipient
  );
  event TextMsgError(
    string reason
  );

  constructor(address oracleAddress) {
    owner = msg.sender;
    priceFeed = AggregatorV3Interface(oracleAddress);
  }

  function sendTextMessage(
    string calldata textMsg,
    string calldata recipient
  ) external payable returns(bool) {

    (uint newTxtPriceEth,,) = this.pollTxtPrices();

    require(
      msg.value > newTxtPriceEth,
      'Please send the correct amount of ETH to make send a message'
    );

    emit Spend(textMsg, recipient);
    messagesSentCount += 1;
    return true;
  }

  function setTxtPrices(uint _txtPriceUSD) external ownerOnly() {
    (int price,) = getLatestPrice();
    uint ethPriceUSD = uint(price);

    txtPriceEth = scale.mul(_txtPriceUSD).div(ethPriceUSD);
    txtPriceUSD = _txtPriceUSD;
  }

  function pollTxtPrices() external view returns(uint, uint, uint) {
    (int price,) = getLatestPrice();

    uint newTxtPriceEth = scale.mul(txtPriceUSD).div(uint(price));

    return (newTxtPriceEth, txtPriceUSD, decimals);
  }

  function totalBalance() external view returns(uint) {
    return payable(address(this)).balance;
  }

  function withdrawFunds() external ownerOnly() {
    msg.sender.transfer(this.totalBalance());
  }

  function destroy() external ownerOnly() {
    selfdestruct(owner);
  }

  function getLatestPrice() public view returns (int, uint) {
    (
      ,int price,,,
    ) = priceFeed.latestRoundData();

    return (price, decimals);
  }

  modifier ownerOnly() {
    require(msg.sender == owner, 'only owner can call this');
    _;
  }
}
```

**Why is deploying to Mainnet using Truffle so difficult?**

Here is a rundown of trying to deploy to Mainnet...

1. Current Gasprice is 110 Wei. Therefore `110000000000 wei`

Let's plug that in..

```
mainnet: {
      provider: () =>
        new HDWalletProvider({
          mnemonic: { phrase: process.env.MNEMONIC },
          providerOrUrl: process.env.RPC_URL_1_WSS,
        }),
      network_id: 1, 
      from: process.env.DEPLOYERS_ADDRESS,
      gasPrice: 110000000000, /*  GAS PRICE!! */
      confirmations: 2,
      timeoutBlocks: 200,
      skipDryRun: false, public nets )
    },
  },
```

2. Let's get the gas cost estimate of deploying. This will be set in `gas` parameter of `truffle-config`.

`NODE_ENV=production truffle migrate --network mainnet --dry-run`

```
Summary
=======
> Total deployments:   2
> Final cost:          0.001403824 ETH
```

0.001403824 ETH is $2.04.      
So that's probably wrong.      
 
**‼️FAIL‼️**

---------------

3. Second try. Ok the dry run wasn't useful for getting gas estimates. I'll leave `gas` blank and try to deploy with just `gasPrice`.

Results in..
`Message:  insufficient funds for gas * price + value`
**‼️FAIL‼️**

4. Ok, I'm since the `dry-run` didn't give a useful estimate for what the contract costs to deploy, I'll just guess based on other contracts. Going to add the `gas` parameter here.

```
mainnet: {
      provider: () =>
        new HDWalletProvider({
          mnemonic: { phrase: process.env.MNEMONIC },
          providerOrUrl: process.env.RPC_URL_1_WSS,
        }),
      network_id: 1, 
      from: process.env.DEPLOYERS_ADDRESS,
      gasPrice: 110000000000, /*  GAS PRICE!! */
      gas: 140000000000000000, / That's about $200 in Wei/
      confirmations: 2,
      timeoutBlocks: 200,
      skipDryRun: false, public nets )
    },
  },
```

`RuntimeError: abort(Error: Assertion failed). Build with -s ASSERTIONS=1 for more info.`.    

**‼️FAIL AGAIN‼️**

---------------

4. Third attempt. Ok, going to try to just leave `gas` and `gasPrice` blank..

`Block timesout in 750 seconds`.    

**‼️FAIL‼️**

---------

Trying on Remix..
1. Set provider to Injected Web3
2. Set network to Mainnet
3. Deploy
4. Cost $135

This is great, but now I'm not using Truffle's migrations, and it isn't as easy to use Remix ABI with Truffle. 

I'm really really prefer Truffle to just work.

Why is Truffle sooooo difficult to use when deploying to Mainnet? It is impossible to deploy to Mainnet.

**Comment by eggplantzzz** [comment] 2021-03-17 18:21
This is strange, seems like it might be related to gas values if it works on the test nets. We'll see if we can think of ways to test this out and troubleshoot!

**Comment by roo-shy** [comment] 2021-03-17 18:27
@eggplantzzz referencing: 94975 in Zendesk if you need details

**Comment by gnidan** [comment] 2021-04-21 18:34
My hunch is that the specific issue you faced here @stoplion is just due to congested network conditions at the time you were seeking to deploy your project.

I'm not sure if you feel like gambling mainnet ETH to see if it's better now, but maybe it is?

Regardless, I've opened a follow-up issue to address a root cause here, which is that Truffle just doesn't know how much to offer for the transactions it submits to the network.

Let us know if there's more we can help with!

**Comment by fainashalts** [comment] 2021-05-26 18:05
Closing for issue maintenance. Please let us know if this problem persists!

**Closed by fainashalts** 2021-05-26 18:05 UTC
