### ISSUE TITLE
Debugger got wrong source location highlighted

### ISSUE THREAD

**Issue by lwedge99** [trufflesuite/truffle#5914] opened 2023-02-20 07:46 UTC
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Debugger got wrong source location highlighted

## Steps to Reproduce

1. `truffle debug 0xfb6027725ccff056d8fe4065227fecd335fe123e8ab4da3a85a71377f7e9c6f9 --fetch-external`

2. step instructions `;3334`

## Expected Behavior

Debugger should highlight current source location

## Actual Results

<img width="400" alt="Snipaste_2023-02-20_15-30-38" src="https://user-images.githubusercontent.com/116623885/220040671-d07edb17-3eb2-41bf-b6bb-4c7a00971fa6.png">

The highlighting seems weird, and it persists if I keep stepping

<img width="356" alt="Snipaste_2023-02-20_15-44-05" src="https://user-images.githubusercontent.com/116623885/220043455-8b15df06-e057-4e95-8657-d8cedf9a00ef.png">

## Environment

* Operating System: MacOS 13.1
* Ethereum client:
* Truffle version (`truffle version`): 5.7.1
* node version (`node --version`): 18.14.0
* npm version (`npm --version`): 9.3.1

**Comment by cliffoo** [comment] 2023-02-23 18:56
Hey @lwedge99 thanks for opening this issue! I am able to reproduce this and it seems like the highlighting is indeed off.

@haltman-at fyi this is a mainnet transaction.

**Comment by haltman-at** [comment] 2023-04-03 19:40
Unfortunately this is likely due to a bad sourcemap; if it is we won't really be able to do anything.  I guess I can take a look and see sometime...?

**Comment by lwedge99** [comment] 2023-04-10 04:42
Hello, I have submitted a PR to fix this. Maybe you can check it out.

**Comment by eggplantzzz** [comment] 2023-04-20 19:51
looks like this should be fixed in version 5.8.3!

**Closed by eggplantzzz** 2023-04-20 19:51 UTC
Labels: needs investigated, priority3 🔧
