### ISSUE TITLE
Using network 'development'.  Running migration: 1_initial_migration.js   Replacing Migrations...   ... 0x2e09c8647174d6fd5b26e2269d3d725b75d44881f27ad735323aca8fd19a517f   Migrations: 0xecfcab0a285d3380e488a39b4bb21e777f8a4eac Saving successful migration to network...   ... 0xd656595c57159a378d57439d8f0297d077c03ec39adfdac561dbfb8260758db3 Saving artifacts... Running migration: 2_deploy_contracts.js   Deploying SampleCrowdsale... Error encountered, bailing. Network state unknown. Review successful transactions manually. Error: SampleCrowdsale contract constructor expected 7 arguments, received 6     at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:390:1     at new Promise (<anonymous>)     at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:374:1     at <anonymous>     at process._tickCallback (internal/process/next_tick.js:118:7)

### ISSUE THREAD

**Issue by mahiruddinseikh** [trufflesuite/truffle#934] opened 2018-05-03 12:44 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by cgewecke** [comment] 2018-05-03 14:09
@mahiruddinseikh. The core of the error you received is:
```
SampleCrowdsale contract constructor expected 7 arguments, received 6
```

Please see check your migrations js code to make sure you're passing the required arguments to contract constructor. There's some more help about that process [here](https://github.com/trufflesuite/truffle/issues/811#issuecomment-385200065)

Closing as duplicate of #811

**Closed by cgewecke** 2018-05-03 14:09 UTC
