### ISSUE TITLE
Debug failure when Reaching a specific line of code

### ISSUE THREAD

**Issue by johhonn** [trufflesuite/truffle#865] opened 2018-03-23 21:08 UTC
---------------------------

## Issue

I am trying to debug a contract that is failing with ther Error: VM Exception while processing transaction:revert. After getting the transaction hash from the function call and calling truffle debug on it I am able to step through the code until I reach the line that could be causing the  vm exception error. If i proceed any further the debugger crashes with the following error

## Steps to Reproduce
1. compile contracts with truffle dev
2.run `command Book.deployed().then(function(instance){return instance.buyCoin({from:web3.eth.accounts[5], value: 6})})`
3.get transaction hash
4.call debug on hash
5.step through contracts until failure
## Expected Behavior
Truffle debug allows me to step through  the code to see where the error occurs

## Actual Results
Error: Trace and instruction mismatch.
```
trace {
  "depth": 0,
  "error": "",
  "gas": 6583642,
  "gasCost": -103538,
  "memory": [
    "0000000000000000000000002932b7a2355d6fecc4b5c0b6bd44cc31df247a2e",
    "0000000000000000000000000000000000000000000000000000000000000001",
    "0000000000000000000000000000000000000000000000000000000000000100",
    "0000000000000000000000000000000000000000000000000000000000000000",
    "00000000000000000000000000000000000000000000000000000000000000c0",
    "0000000000000000000000000000000000000000000000000000000000000000",
    "0000000000000000000000000000000000000000000000000000000000000009",
    "416e6f6e796d6f75730000000000000000000000000000000000000000000000",
    "3344b72d00000000000000000000000000000000000000000000000000000000",
    "000000110000000000000000000000002932b7a2355d6fecc4b5c0b6bd44cc31",
    "df247a2e00000000000000000000000000000000000000000000000000000000",
    "0000000100000000000000000000000000000000000000000000000000000000"
  ],
  "op": "ISZERO",
  "pc": 2998,
  "stack": [
    "00000000000000000000000000000000000000000000000000000000091e9a60",
    "00000000000000000000000000000000000000000000000000000000000001e4",
    "0000000000000000000000000000000000000000000000000000000000000000",
    "00000000000000000000000075c35c980c0d37ef46df04d31a140b65503c0eed",
    "000000000000000000000000000000000000000000000000000000003344b72d",
    "0000000000000000000000000000000000000000000000000000000000000164",
    "0000000000000000000000000000000000000000000000000000000000000000"
  ],
  "storage": {}
}
instruction {
  "name": "JUMPDEST",
  "fee": 1,
  "in": 0,
  "out": 0,
  "dynamic": false,
  "pc": 1656,
  "index": 860,
  "jump": "-",
  "start": 933,
  "length": 31,
  "range": {
    "start": {
      "line": 37,
      "column": 5
    },
    "end": {
      "line": 37,
      "column": 36
    }
  }
}

This is likely due to a bug in the debugger. Please file an issue on the Truffle issue tracker and provide as much information about your code and transaction as possible.

Fatal Error: See above.
    at REPLServer.Interface._onLine (readline.js:285:10)
    at REPLServer.emit (domain.js:421:20)
    at REPLServer.emit (events.js:180:13)
    at REPLServer.onLine (repl.js:501:10)
    at REPLServer.runBound [as eval] (domain.js:388:12)
    at bound (domain.js:375:14)
    at ReplManager.interpret (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/lib/repl.js:119:1)
    at Object.interpreter (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-core/lib/commands/debug.js:137:1)
    at Debugger.step (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-debugger/debugger.js:211:1)
    at Debugger.advance (/usr/lib/node_modules/truffle/build/webpack:/~/truffle-debugger/debugger.js:179:1)
```
## Environment

* Operating System: Manjaro Linux
* Ethereum client:Geth
* Truffle version (`truffle version`):4.0.6 
* node version (`node --version`):9.8.0
* npm version (`npm --version`): 5.6.0

**Comment by gnidan** [comment] 2018-03-23 21:26
Sounds like this is due to `buyCoin` deferring to a library.

Closing here, duplicate of trufflesuite/truffle-debugger#39

**Closed by gnidan** 2018-03-23 21:26 UTC
