### ISSUE TITLE
Error: PollingBlockTracker - encountered an error while attempting to update latest block:

### ISSUE THREAD

**Issue by TeslaZhou-Xin** [trufflesuite/truffle#3357] opened 2020-09-12 11:52 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by eggplantzzz** [comment] 2020-09-16 17:42
Closing this as a duplicate of issue #3357

**Closed by eggplantzzz** 2020-09-16 17:42 UTC

**Comment by umobiajulu** [comment] 2021-06-08 14:56
I had the sam issue with BSC testnet. I solved mine by replacing 'https' in the provider url with 'wss'

    testnet: {
      provider: () => new HDWalletProvider(mnemonic, `wss://data-seed-prebsc-1-s1.binance.org:8545`),
      network_id: 97,
      confirmations: 10,
      timeoutBlocks: 200,
      skipDryRun: true
    },

**Comment by rafante** [comment] 2021-07-04 05:23
If it helps, I had the exact same error. I could deploy on any ethereum environment, but couldn't deploy on Polygon (neither mumbai or the mainet). When I tried with this https://rpc-mumbai.maticvigil.com/ instead of this https://rpc-mumbai.matic.today, it worked.

Hope it helped!

**Comment by amit221** [comment] 2021-07-05 15:03
> I had the sam issue with BSC testnet. I solved mine by replacing 'https' in the provider url with 'wss'
> 
> ```
> testnet: {
>   provider: () => new HDWalletProvider(mnemonic, `wss://data-seed-prebsc-1-s1.binance.org:8545`),
>   network_id: 97,
>   confirmations: 10,
>   timeoutBlocks: 200,
>   skipDryRun: true
> },
> ```

works like a charm

**Comment by racetrack0616** [comment] 2021-08-05 09:12
> If it helps, I had the exact same error. I could deploy on any ethereum environment, but couldn't deploy on Polygon (neither mumbai or the mainet). When I tried with this https://rpc-mumbai.maticvigil.com/ instead of this https://rpc-mumbai.matic.today, it worked.
> 
> Hope it helped!

I am having the same issue in `matic testnet`. I tried this solution but now,

**Comment by nelsoncerqueira** [comment] 2021-08-05 20:32
> > If it helps, I had the exact same error. I could deploy on any ethereum environment, but couldn't deploy on Polygon (neither mumbai or the mainet). When I tried with this https://rpc-mumbai.maticvigil.com/ instead of this https://rpc-mumbai.matic.today, it worked.
> > Hope it helped!
> 
> I am having the same issue in `matic testnet`. I tried this solution but now,
> 
> ```
>   code: -32603,
>   message: 'Too Many Requests',
>   data: { originalError: {} },
>   stack: 'Error: Too Many Requests\n' +```
> ```

I get the same

**Comment by racetrack0616** [comment] 2021-08-06 03:00
Nothing is actually working for me. Most of time I get TIMEDOUT issue now.

**Comment by umobiajulu** [comment] 2021-08-07 04:47
I later found out that the major cause of this problem is unstable network. your ip changes in the middle of deploying the contract. the solution is to use a stable network or use a vpn which will stabilize your network. in my case I used proton vpn and everything worked perfectly

**Comment by racetrack0616** [comment] 2021-08-09 03:36
Thank you for your response. I used `https://rpc-mumbai.maticvigil.com` URL and used `proton vpn` but now the issue is

![image](https://user-images.githubusercontent.com/68948218/128657963-ec3e37a0-e6b6-47a7-a955-7c7a21bc8211.png)

**Comment by racetrack0616** [comment] 2021-08-09 03:42
The other issue is as in screenshot . It is so frustrating now. I can't get rid of it. :(
![image](https://user-images.githubusercontent.com/68948218/128658173-854cc02d-fa6c-450e-aac0-e6c9b497dedb.png)

**Comment by satoshi-u** [comment] 2021-12-06 14:11
Try this Matic testnet url: 
```bash
https://matic-mumbai.chainstacklabs.com/
```

Worked for me!

**Comment by Oskii** [comment] 2021-12-06 14:13
> Try this Matic testnet url:
> 
> ```shell
> https://matic-mumbai.chainstacklabs.com/
> ```
> 
> Worked for me!

This URL did not work for me - same issue.

**Comment by Fahad67** [comment] 2021-12-28 05:20
I had same issue but resolve it by using speedy node testnet url.

https://speedy-nodes-nyc.moralis.io/*****.......*****/bsc/testnet

**Comment by xxycfhb** [comment] 2022-03-01 13:24
> > I had the sam issue with BSC testnet. I solved mine by replacing 'https' in the provider url with 'wss'
> > ```
> > testnet: {
> >   provider: () => new HDWalletProvider(mnemonic, `wss://data-seed-prebsc-1-s1.binance.org:8545`),
> >   network_id: 97,
> >   confirmations: 10,
> >   timeoutBlocks: 200,
> >   skipDryRun: true
> > },
> > ```
> 
> works like a charm

Amazing! It worked for me.

**Comment by Wwjian-lab** [comment] 2022-03-03 07:33
> I had the sam issue with BSC testnet. I solved mine by replacing 'https' in the provider url with 'wss'
> 
> ```
> testnet: {
>   provider: () => new HDWalletProvider(mnemonic, `wss://data-seed-prebsc-1-s1.binance.org:8545`),
>   network_id: 97,
>   confirmations: 10,
>   timeoutBlocks: 200,
>   skipDryRun: true
> },
> ```

It worked for me.Thx

**Comment by OnahProsperity** [comment] 2022-04-08 08:03
`I had the sam issue with BSC testnet. I solved mine by replacing 'https' in the provider url with 'wss'
testnet: {
  provider: () => new HDWalletProvider(mnemonic, `wss://data-seed-prebsc-1-s1.binance.org:8545`),
  network_id: 97,
  confirmations: 10,
  timeoutBlocks: 200,
  skipDryRun: true
},`
worked for me

**Comment by jstaszynskidev** [comment] 2022-06-17 13:45
> > Try this Matic testnet url:
> > ```shell
> > https://matic-mumbai.chainstacklabs.com/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Worked for me!
> 
> This URL did not work for me - same issue.

This network URL must be the same as you have in MetaMask (New RPC URL)

**Comment by lam268** [comment] 2022-09-21 03:45
Any updates on this problem ? I still got this error sometimes when running my application on bsc testnet

**Comment by anisurrahman072** [comment] 2022-11-03 05:38
Hey I have solved finally ✌️🎉
I didn't use truffle HD Wallet anymore as it gave me a lot of pain 😞. Finally, I used the core etherium web3.js for everything like provider instance creation, wallet selection, pay gass, everything. I used core etherium library https://github.com/ethereum/solc-js  for the ABI (Application Binary Interface) & bytecode generation. 

I used Alchemy for my Polygon mumbai test-network Node communication. Wolla, that's it. Here is the code that will help you:

```
const web3 = new Web3(
    new Web3.providers.HttpProvider(
      "https://polygon-mumbai.g.alchemy.com/v2/<Alchemy-API-key>"
    )
  );
  // Creating a signing account from a private key
  const signer = web3.eth.accounts.privateKeyToAccount(
    <Your Account Private key that will be used as the signer>
  );
  web3.eth.accounts.wallet.add(signer);

  // deploying our contract
  const result = await new web3.eth.Contract(
    contracts["MyContract.sol"]["MyContract"].abi,
    null,
    {
      transactionBlockTimeout: 200,
      transactionConfirmationBlocks: 1000,
      transactionPollingTimeout: 1000,
      blockHeaderTimeout: 100,
    }
  )
    .deploy({
      data: contracts["MyContract.sol"]["MyContract"].evm.bytecode.object,
    })
    .send({
      gas: "5000000",
      from: <Account public address that will pay the gass>,
    });
```

**Comment by bfhh** [comment] 2022-12-01 10:34
I added a property  `networkCheckTimeoutnetworkCheckTimeout`, it works ok.
```
 matic: {
      provider: () => new HDWalletProvider(mnemonic, `https://rpc-mumbai.maticvigil.com`),
      network_id: 80001,
      confirmations: 2,
      networkCheckTimeoutnetworkCheckTimeout: 20000000,
      timeoutBlocks: 200,
      skipDryRun: true
}
```

**Comment by Raviprakash-B** [comment] 2023-02-01 05:05
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({mpt #1
  code: -32603,
  message: 'ESOCKETTIMEDOUT',
  data: { originalError: { code: 'ESOCKETTIMEDOUT', connect: false } },
  stack: 'Error: ESOCKETTIMEDOUT\n' +
    '    at ClientRequest.<anonymous> (C:\\Users\\Admin\\Desktop\\defi-staking-app-starter\\defi-staking-app-starter\
\node_modules\\request\\request.js:816:19)\n' +
    '    at Object.onceWrapper (node:events:627:28)\n' +


If anyone is facing the above error to run with Matic Network 
Solution: - Try to change the actual Provider URL, take out from the mentioned website https://rpc.maticvigil.com/apps/a712bb661daef11c93ef89af396c476dbed54a83

then run using
truffle migrate --network matic

**Comment by Eh1Ka6** [comment] 2023-05-31 12:18
Hey dears! 
had this problem  happening this morning:  compiling the contract first with t
truffle compile --all and then migrating with  truffle migrate --compile-none allowed me to solve this issue.  

Found the answer on this forum:
https://forum.moralis.io/t/client-network-socket-disconnected-before-secure-tls-connection-was-established/9526
