### ISSUE TITLE
1: // No source code found. When Trying to Debug Web3 Tx

### ISSUE THREAD

**Issue by fredfortier** [trufflesuite/truffle#815] opened 2018-02-24 06:04 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

My contract has a state modifying function which I'm able to test successfully by running a JS test. When calling the same function in exactly the same manner from web3, I get a tx which seemingly seems to succeed but it does not fire the expected event not change the state as expected. To troubleshoot, I run `truffle debug my-tx-hash` but get this message `1: // No source code found.` followed by `Transaction halted with a RUNTIME ERROR.`. I'm able to step through it successfully when debugging the tx from the unit test.

## Steps to Reproduce

See above

## Expected Behavior

Tx succeeds in firing event and modifying state, or at least let's me debug.

## Actual Results

`1: // No source code found.` followed by `Transaction halted with a RUNTIME ERROR.`

## Environment

* Operating System:  Mac
* Ethereum client: Web3
* Truffle version (`truffle version`): Truffle (unbundled) (core: 4.0.6)
Solidity v0.4.20 (solc-js)
* node version (`node --version`): v7.2.1
* npm version (`npm --version`): 3.10.9

My code is based on the `react-box` code. I sign my transaction with Metamask.

**Comment by cgewecke** [comment] 2018-02-27 20:26
@fredfortier Truffle just published a huge debugger release a few minutes ago. Do you have any interest in trying it out and reporting back on whether this error is still happening?

**Comment by alexmedkex** [comment] 2018-03-03 16:47
The error is still happening for me, after upgrading. I'm getting No source code found, while attempting to debug a transaction that was done in my js test. The transaction likely failed due to a require() or revert.

**Comment by fredfortier** [comment] 2018-03-13 21:56
@cgewecke I'm still getting this error after upgrading just now.
```
$ truffle --version
Truffle v4.1.3 - a development framework for Ethereum
```

**Comment by alexmedkex** [comment] 2018-03-13 21:59
It seems to fix for me when debugging the transaction while inside the truffle develop console. I.e running a truffle develop instance, and entering "debug <tx_hash>"

**Comment by cgewecke** [comment] 2018-03-31 17:20
@fredfortier If you have a chance could you see if `4.1.5` has fixed this? A bunch of support for inter-contract calls has been added in that release.

**Comment by fredfortier** [comment] 2018-04-01 03:59
Yes, it's working now. But I still don't see the values of my variable when
stepping through (always undefined).

**Comment by cgewecke** [comment] 2018-04-01 17:08
@fredfortier I'd like to close this because the initial issue looks like it's been resolved. 

If you have a chance could you open another issue on the undefined variable problem? A minimal set of reproduction steps would really help us to track down what's going wrong there.

**Closed by cgewecke** 2018-04-01 17:08 UTC

**Comment by 7--** [comment] 2019-07-13 22:37
I get "Warning: The source code for one or more contracts could not be found." when trying to debug this second example
https://www.trufflesuite.com/tutorials/debugging-a-smart-contract#issue-2-an-invalid-error-check
