### ISSUE TITLE
Debugger doesn't cope with imports not from files

### ISSUE THREAD

**Issue by gilesbradshaw** [trufflesuite/truffle#2025] opened 2019-05-16 09:53 UTC
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Debugger doesn't cope with imports not from files.

I hope this makes sense - I am new to all this!

So the app whose contracts I am trying to debug compiles its solidity code with the solc compiler - but it's generating the solidity from templates so they are never files.

for example this is how it is compiling solidity code:

````
import _truffleCompile from 'truffle-compile'

const truffleCompile = solidity =>
  new Promise(
    (resolve, reject) =>
      _truffleCompile(
        solidity,
        {
          contracts_directory: 'i do not care',
          compilers: {
            solc: {
              settings: {
                "optimizer": {
                  "enabled": false,
                  "runs": 200
                },
                "evmVersion": "byzantium",      
                outputSelection: {
                  '*': {
                    '*': ['*']
                  }
                }
              }
            }
          }
        },
        (err, result) => err ? reject(err) : resolve(result))
      )

const contracts = await truffleCompile({
    ...sources,
    [model.id]: model.solidity,
  })  
  
````

This means the imports in the solidity looks like this:

````
import "AbstractRegistry";

````

however I can't get your debugger to compile these contracts by just passing it a directory with the contracts in as the imports aren't from .sol files.  It gives me the error:

````
Starting Truffle Debugger...
⠹ Compiling your contracts...Error: Error: Could not find AbstractRegistry from any sources; imported from /home/giles/ipbm/ipbm/src/truffle/contracts/AbstractProcess.sol
    at async.whilst.error (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:381:1)
    at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:969:1
    at next (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:5222:1)
Truffle v5.0.17 (core: 5.0.16)
Node v11.14.0

````

I can make them compile by changing the import to:

````
import "AbstractRegistry.sol";
````

however now I can't debug them as any change to the source code changes the byte code and they won't be recognised.

I 'fixed' this by hacking your code (truffle/packages/truffle-core/lib/commands/debug.js)

````
let compilePromise = new Promise(function(resolve, reject) {
          
          compileSpinner = ora("Compiling your contracts...").start();

          fs.readdir(process.cwd() + '/contracts', function(err, filePaths) {
            if (err) {
              reject(err);
              return;
            }
            resolve(filePaths);
          });
        })
          .then(
            files => Promise.all(
              files
                .map(
                  (file) => new Promise(
                    (resolve, reject) =>
                      fs.readFile(
                        `${process.cwd()}/contracts/${file}`,
                         (err, text) => {
                           if (err) {
                             return reject(err);
                           }
                           resolve(text);
                         }
                      )
                  )
                  .then(
                    text => ({
                      file,
                      text,
                    })
                  )
                )
            )
          )
            .then(
              files => files
                .reduce(
                  (
                    acc,
                    {
                      file,
                      text
                    }
                  ) => {
                      acc[file.substring( 0, file.indexOf( ".sol" ) )] = text.toString()
                      return acc;
                  },
                  {},
                )
            )
            .then(
              files => new Promise(function(accept, reject) {
                //we need to set up a config object for the compiler.
                //it's the same as the existing config, but we turn on quiet.
                //unfortunately, we don't have Babel here, so cloning is annoying.
                let compileConfig = Object.assign(
                  {},
                  ...Object.entries(config).map(([key, value]) => ({ [key]: value }))
                ); //clone
                compileConfig.quiet = true;

                compile(files, compileConfig, function(err, contracts, files) {
                  if (err) {
                    return reject(err);
                  }
        
                  return accept({
                    contracts: contracts,
                    files: files
                  });
                });
              })
            );
        
````
(lack of babel means I had to do that nasty mutate in the reduce...)

however now it won't work with .sol style imports

Am I missing something here?  Is there another way to make it cope with this use case?  
 
## Steps to Reproduce

I can provide my source files if you'd like..

## Expected Behavior

It to work with non .sol style imports

## Actual Results

It won't

## Environment

* Operating System: ubuntu
* Ethereum client: ganache-cli
* Truffle version Truffle v5.0.17 (core: 5.0.16)
* node version Node v11.14.0
* npm version 6.7.0

**Comment by gnidan** [comment] 2019-05-17 06:09
Hm, I think I concur with the problem, but it's hard to see what the implications of your changes are. It seems like the root of the problem is the mismatch between the use of JSON artifacts vs. the debug compilation step?

I could go into more detail (and I had started to), but lib/commands/debug is too much of a mess, making it difficult to communicate about. This was the last straw, and I just opened #2030 attempting to fix that. Could you perhaps take a look at the new [CLIDebugger](https://github.com/trufflesuite/truffle/blob/await-debug/packages/truffle-core/lib/debug/index.js) class that I put together, which will hopefully make it easier for you to see what's going on?

I'm not certain, but I believe you've identified something with a tractable fix, but I don't believe there's any hope of us fixing it until that PR is merged to untangle the spaghetti. If you could rewrite your hack to conform to how it's done on that `await-debug` branch (or even open a draft PR so we can look at diffs!), that would help tremendously in being able to talk about this limitation you've identified.

Thank you for raising this issue!

**Comment by gilesbradshaw** [comment] 2019-05-17 16:14
Hi I've done just that!  best wishes (sorry to be the last straw :D)

**Comment by eggplantzzz** [comment] 2020-07-22 18:19
Closing this for issue maintenance. @gilesbradshaw we'll be happy to re-open this if you think we still want to create some sort of solution for this!

**Closed by eggplantzzz** 2020-07-22 18:19 UTC
Labels: Debugger
