### ISSUE TITLE
Truffle test can not handle named argument constructors in another file

### ISSUE THREAD

**Issue by bmaurer** [trufflesuite/truffle#779] opened 2018-01-29 07:59 UTC
## Steps to Reproduce
Unbox metacoin and update files as follows:

```
bmaurer-mbp2:mc2 bmaurer$ cat contracts/MetaCoin.sol
pragma solidity ^0.4.18;

import "./ConvertLib.sol";

// This is just a simple example of a coin-like contract.
// It is not standards compatible and cannot be expected to talk to other
// coin/token contracts. If you want to create a standards-compliant
// token, see: https://github.com/ConsenSys/Tokens. Cheers!

contract MetaCoin {
	mapping (address => uint) balances;

	event Transfer(address indexed _from, address indexed _to, uint256 _value);

	function MetaCoin() public {
		balances[tx.origin] = 10000;
	}

	function sendCoin(address receiver, uint amount) public returns(bool sufficient) {
		if (balances[msg.sender] < amount) return false;
		balances[msg.sender] -= amount;
		balances[receiver] += amount;
		Transfer(msg.sender, receiver, amount);
		return true;
	}

	function getBalanceInEth(address addr) public view returns(uint){
		return ConvertLib.convert(getBalance(addr),2);
	}

	function getBalance(address addr) public view returns(uint) {
		return balances[addr];
	}
}
library X {
  struct Y {
    uint z;
  }
}
bmaurer-mbp2:mc2 bmaurer$ cat test/TestMetacoin.sol
pragma solidity ^0.4.2;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/MetaCoin.sol";


contract TestMetacoin {

  function testInitialBalanceUsingDeployedContract() public {

    X.Y memory src = X.Y({z: 0});
  }

}
```
## Expected Behavior

Truffle test should run (or give an obvious compiler error)

## Actual Results
```
bmaurer-mbp2:mc2 bmaurer$ truffle test
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./test/TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

Compilation warnings encountered:

/Users/bmaurer/eth/mc2/test/TestMetacoin.sol:12:5: Warning: Unused local variable.
    X.Y memory src = X.Y({z: 0});
    ^------------^
,/Users/bmaurer/eth/mc2/test/TestMetacoin.sol:10:3: Warning: Function state mutability can be restricted to pure
  function testInitialBalanceUsingDeployedContract() public {
  ^
Spanning multiple lines.


/usr/local/lib/node_modules/truffle/build/cli.bundled.js:306979
      throw e;
      ^
SyntaxError: Expected "!", "!=", "(", ")", "+", "++", "-", "--", "0", "<", "<=", "==", ">", ">=", "[", "^", "delete", "false", "hex", "mapping", "new", "this", "true", "v", "~", [1-9], comment, end of line, identifier, number, string, or whitespace but "{" found. Line: 12, Column: 26
    at peg$buildStructuredError (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:294335:12)
    at Object.peg$parse [as parse] (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:306921:11)
    at Object.parse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:306974:23)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:203438:32
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

## Environment

Truffle v4.0.5 (core: 4.0.5)
Solidity v0.4.18 (solc-js)

**Comment by cgewecke** [comment] 2018-01-29 16:35
>SyntaxError: Expected "!", "!=", "(", ")", "+", "++", "-", "--", "0", "<", "<=", "==", ">", ">=", "[", "^", "delete", "false", "hex", "mapping", "new", "this", "true", "v", "~", [1-9], comment, end of line, identifier, number, string, or whitespace but "{" found. Line: 12, Column: 26
    at peg$buildStructuredError (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:294335:12)

@bmaurer Thanks for reporting this. 

The error here is related to Truffle's use of a deprecated parser for solidity tests. Should be resolved with [truffle-compile 42](https://github.com/trufflesuite/truffle-compile/pull/42) which is scheduled to be published in a patch release later this week. 

Closing as a duplicate of #707 but please feel free to re-open if you discover there's an additional problem for this constructor case.

**Closed by cgewecke** 2018-01-29 16:35 UTC
