### ISSUE TITLE
How to deploy a smart contract on multiple networks and keeping the contract address same in all the networks?

### ISSUE THREAD

**Issue by debo024** [trufflesuite/truffle#5306] opened 2022-07-15 19:22 UTC
### Discussed in https://github.com/orgs/trufflesuite/discussions/5300

<div type='discussions-op-text'>

<sup>Originally posted by **debo024** July 15, 2022</sup>
How to deploy a smart contract on multiple networks and keeping the contract address same in all the networks? Please help me with this situation, if is there any way to do such .</div>

**Comment by eggplantzzz** [comment] 2022-07-21 17:52
Closing as a duplicate of #5141

**Closed by eggplantzzz** 2022-07-21 17:52 UTC
