### ISSUE TITLE
Testing does not reset state

### ISSUE THREAD

**Issue by timothywangdev** [trufflesuite/truffle#727] opened 2017-12-21 09:06 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Testing does not reset state

### Test.sol
```
contract Test {
    uint[] a;
    function length() public view returns (uint) {
        return a.length;
    }

    function add(uint val) public {
        a.push(val);
    }
}
```

### test.js
```
var Test = artifacts.require("Test");
contract('Test', function(accounts) {
    it("test 0", async function() {
        var t = await Test.deployed();
        var l = await t.length.call();
        assert.equal(l.toNumber(), 0, 'array should be empty');
    });

    it("test 1", async function() {
        var t = await Test.deployed();
        await t.add(1);
    });

    it("test 2", async function() {
        var t = await Test.deployed();
        var l = await t.length.call();
        assert.equal(l.toNumber(), 0, 'array should be empty');
    });
});
```

- truffle dev
- test

## Expected Behavior

all tests should pass

## Actual Results
```
Contract: Test test 2:
     AssertionError: array should be empty: expected 1 to equal 0
```
## Environment

* Operating System:  Ubuntu 16.04
* Truffle version: v4.0.4
* Ethereum client: None
* node version: v8.9.1
* npm version: 5.5.1

**Comment by JackPickering** [comment] 2018-01-09 13:17
Truffle tests dont reset state within the same file, if this is an issue for you, you can use a 'beforeEach' hook and specify a function which creates a new instance of your contract using 'MyContract.new([param1],[param2]...)'

**Comment by cgewecke** [comment] 2018-01-12 02:47
Hi @timothywangdev! @JackPickering is correct. You can see some nice examples of the `beforeEach` pattern he's describing at the Cryptokitties contract repository [here](https://github.com/axiomzen/cryptokitties-bounty/blob/master/test/clock-auction.test.js#L23-L36).

By design Truffle resets the state or "reverts" between each `contract` suite - e.g. each block of tests wrapped in Truffle's `contract` test abstraction.  

Closing because this is intended behavior.

**Closed by cgewecke** 2018-01-12 02:47 UTC

**Comment by PhABC** [comment] 2018-04-02 05:13
This might want to be reconsidered @cgewecke . For instance, when using the `evm_increaseTime` feature, the timestamp of all subsequent block will be increased by the previous value, which makes testing timestamp based functionalities quite cumbersome. Ideally, one could have the option of starting from scratch if desired, even it less efficient.
