### ISSUE TITLE
Truffle unbox metacoin

### ISSUE THREAD

**Issue by vidhyaramani** [trufflesuite/truffle#873] opened 2018-03-28 11:25 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by vidhyaramani** [comment] 2018-03-28 11:25
C:\Windows\system32\truffleproject1> truffle unbox metacoin
wnloading...
ror: Something already exists at the destination. Please unbox in an empty folder. Stopping to prevent overwriting dat

  at C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-box\lib\utils\unbox.js:22:1
  at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:118:7)
  at Function.Module.runMain (module.js:692:11)
  at startup (bootstrap_node.js:194:16)
  at bootstrap_node.js:666:3

**Comment by cgewecke** [comment] 2018-03-28 14:31
Closing as duplicate of #831

**Closed by cgewecke** 2018-03-28 14:31 UTC
