### ISSUE TITLE
truffle fails to deploy contracts to goquorum blockchain.

### ISSUE THREAD

**Issue by andychri123** [trufflesuite/truffle#4013] opened 2021-05-03 15:02 UTC
I have a set of smart contracts that I have compiled and deployed to rinkeby test network. I now need to deploy the to a private goquorum blockchain that runs on the IBFT consensus. The blockchain was built with quorum-wizard. It starts when I run ./start.sh

when I'm in the root of my truffle project I run sudo truffle deploy --reset --network quorum
I get the following error.

    > Everything is up to date, there is nothing to compile.
    
    
    /root/dapp1/Dapp/node_modules/web3-core-helpers/src/errors.js:42
            return new Error(message);
                   ^
    Error: PollingBlockTracker - encountered an error while attempting to update latest block:
    Error: Invalid JSON RPC response: ""
        at Object.InvalidResponse (/root/dapp1/Dapp/node_modules/web3-core-helpers/src/errors.js:42:16)
        at XMLHttpRequest.request.onreadystatechange (/root/dapp1/Dapp/node_modules/web3-providers-http/src/index.js:92:32)
        at XMLHttpRequestEventTarget.dispatchEvent (/root/dapp1/Dapp/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
        at XMLHttpRequest._setReadyState (/root/dapp1/Dapp/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
        at XMLHttpRequest._onHttpRequestError (/root/dapp1/Dapp/node_modules/xhr2-cookies/xml-http-request.ts:379:8)
        at ClientRequest.<anonymous> (/root/dapp1/Dapp/node_modules/xhr2-cookies/xml-http-request.ts:266:37)
        at ClientRequest.emit (events.js:315:20)
        at Socket.socketOnEnd (_http_client.js:493:9)
        at Socket.emit (events.js:327:22)
        at endReadableNT (internal/streams/readable.js:1327:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)
        at PollingBlockTracker._performSync (/root/dapp1/Dapp/node_modules/eth-block-tracker/src/polling.js:51:24)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

This is my truffle-config.js

    const HDWalletProvider = require("@truffle/hdwallet-provider");
    const mnemonic = "not my real mn emon ic words this is pl cfff was";
    
    module.exports = {
      networks: {
      rinkeby: {
        provider: function() {
          return new HDWalletProvider(mnemonic, "https://rinkeby.infura.io/v3/2342342342344345344343434");
        },
        network_id: '*',
        timeoutBlocks: 100000,
        networkCheckTimeout:2000000
      },
    // https://www.trufflesuite.com/docs/truffle/distributed-ledger-support/working-with-quorum
       quorum: {
        provider: function() {
          return new HDWalletProvider(mnemonic, "http://127.0.0.1:21000/");
        },
        network_id: '*',
        type: "quorum",
        timeoutBlocks: 1000000,
        networkCheckTimeout:20000000
      }
      },
      compilers: {
        solc: {
          version: "0.5.0",
          settings: {
            optimizer: {
              enabled: true, // Default: false
              runs: 1000     // Default: 200
            },
            evmVersion: "homestead"  // Default: "byzantium"
          }
        }
      }
    };

I am using

Node v14.16.1

Ubuntu 18.04 (64 Bit)

Quorum 21.1.0

Web3.js v1.3.5

Truffle v5.3.4 (core: 5.3.4)

solidity v0.5.0

**Comment by gnidan** [comment] 2021-05-03 17:30
Thanks for opening this @andychri123! This is likely a duplicate of #4000, which is currently in progress. Stay tuned on that issue!

**Closed by gnidan** 2021-05-03 17:30 UTC
