### ISSUE TITLE
HD-wallet-provider cannot be installed with npm

### ISSUE THREAD

**Issue by Mr124** [trufflesuite/truffle#2711] opened 2019-12-28 08:37 UTC
## Issue

I somehow can't install the hdwallet-provider. When I'm in my project directory I'm using npm i @truffle/hdwallet-provider but I only receive errors "npm ERR! enoent This is related to npm not being able to find a file." Could there be a problem with hosting the file?

## Steps to Reproduce

Latest truffle version v5.1.4
Latest npm version 6.13.4

## Expected Behavior

I would expect the package to be installed into my project directory and be ready to be used.

## Actual Results

PS C:\Coding\blockchain-toolkit> npm i @truffle/hdwallet-provider
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/trufflesuite/provider-engine.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`v.5.1.4`):
* node version (`v12.14.0`):
* npm version (`6.13.4`):

**Comment by MrRefactoring** [comment] 2020-01-06 08:15
Everything works for me. Strange behavior

**Comment by GiovanniCapizzi** [comment] 2020-01-07 13:51
same problem here

**Comment by fainashalts** [comment] 2020-01-08 18:38
@Mr124 do you have git installed locally? It looks like you need to have git in order to install HD-wallet-provider. We should fix this though, because you should be able to do this without git. Thank you for bringing this to our attention!

**Comment by heathdrobertson** [comment] 2020-01-14 00:34
I ran into the same issue.  Installing @truffle/hdwallet-provider into a Docker container running a NixOs development environment.  Adding git to my Nix packages solved the problem.  @fainashalts thanks!

**Comment by gnidan** [comment] 2020-01-15 19:06
NPM package requiring Git? Sounds like a bug!

**Comment by MrRefactoring** [comment] 2020-01-15 19:13
> NPM package requiring Git? Sounds like a bug!

Yeah. After all, he has a git repository in his dependencies :)

**Comment by CruzMolina** [comment] 2020-07-02 16:38
Closing this as a duplicate of #2852 (#2852 has the latest info on this issue).

**Closed by CruzMolina** 2020-07-02 16:38 UTC
Labels: bug, priority3 🔧

**Comment by RajivSrivatsan** [comment] 2022-01-06 11:29
I have the same issue, I could not install hd provide
<img width="681" alt="hdwallet error" src="https://user-images.githubusercontent.com/83394239/148376251-a6bcbc08-298c-448e-b7b1-6f4880e968d7.png">
r

**Comment by wajahat8888** [comment] 2022-01-07 22:52
PS D:\Etherum\Blood  donation> npm install @truffle/hdwallet-provider
npm ERR! code ENOENT      
npm ERR! syscall spawn git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Local\npm-cache\_logs\2022-01-07T22_27_27_872Z-debug-0.log



I got same error, how should i resolve it

**Comment by cepoiuanamaria** [comment] 2022-01-12 11:11
Try: npm i @truffle/hdwallet-provider@next
this worked for me

**Comment by bennyair** [comment] 2022-01-24 19:02
Perfect - that worked!

**Comment by darkx-11** [comment] 2022-02-03 02:25
> Try: npm i @truffle/hdwallet-provider@next this worked for me

Thank you! worked!

**Comment by IzaanSohail1999** [comment] 2022-03-18 23:00
Thankyou @cepoiuanamaria it worked

**Comment by HalloWorld23333** [comment] 2022-04-04 01:07
> Try: npm i @truffle/hdwallet-provider@next this worked for me

That really worked! Thank you!

**Comment by CoccoAndrea** [comment] 2022-04-09 13:00
> Try: npm i @truffle/hdwallet-provider@next this worked for me

Thanks :-)

**Comment by Shivam-vishwakarma991** [comment] 2022-07-19 17:36
> Try: npm i @truffle/hdwallet-provider@next this worked for me

Thankyou

**Comment by EmmanuelRigobert** [comment] 2022-08-18 16:20
> Try: npm i @truffle/hdwallet-provider@next this worked for me

Me too. Thanks

**Comment by ahmed-fz11** [comment] 2022-08-31 18:43
> Try: npm i @truffle/hdwallet-provider@next this worked for me

Wonderful. It worked for me

**Comment by king112ola** [comment] 2022-09-23 21:02
> Try: npm i @truffle/hdwallet-provider@next this worked for me

this worked, thx

**Comment by mik305** [comment] 2023-03-22 11:48
> Try: npm i @truffle/hdwallet-provider@next this worked for me

still works, thanks :)
