### ISSUE TITLE
truffle migrate not returning ... (Quorum nodes)

### ISSUE THREAD

**Issue by paliwalg** [trufflesuite/truffle#860] opened 2018-03-21 11:26 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Running the initial migration script to deploy the Migration contract takes long time to complete.

What the issue is, in broad strokes.
I am trying to run the truffle metacoin project pointing to a quorum node. 
Doing truffle migrate displays below at the terminal and then it just gets stuck there. I checked the transactionReceipt for the same from the geth console and there I can see the blocknumber  and contractaddress that concludes the transcation is successfully mined and contract is deployed. 

---------------------------------------
Running migration: 1_initial_migration.js
  Replacing Migrations..
  ... 0x143141d9efa38281f73c0f03ddf4e0ef52c20613f076c2ed2a4b36ad232f700d
---------------------------------------
   
## Steps to Reproduce
1. Create the 7 node quorum node setup. Refer to https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes
2. Run the truffle metacoin example project
 

## Environment

* Operating System: Ubuntu 16.04
* Ethereum client:  1.7, Quorum version 2.0.1
* Truffle version (`truffle version`):  v4.0.6 (core: 4.0.6)
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by cgewecke** [comment] 2018-03-21 14:35
@paliwalg Could you verify you are funding the deployment correctly? See [this](https://ethereum.stackexchange.com/questions/31335/issue-in-truffle-migration-with-quorum) stack-exchange issue. Additionally, we have a small tutorial on Quorum [here](http://truffleframework.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains) you might find helpful.

**Comment by cgewecke** [comment] 2018-03-22 15:30
@paliwalg This may also be a duplicate of or related to #863.

**Comment by paliwalg** [comment] 2018-03-23 13:59
Yes, seems like same as #863. So, Is it still exist with Truffle v4.0.6 (core: 4.0.6) ?

**Comment by cgewecke** [comment] 2018-03-23 15:19
@paliwalg I believe so. Latest `truffle` is 4.1.3, for what it's worth.

I hope you don't mind - I'm going to close this as a duplicate of #863 so that everyone with this problem can help each other in the same thread.

**Closed by cgewecke** 2018-03-23 15:19 UTC
