### ISSUE TITLE
Migrating multiple contracts where a subsequent contract is deployed in a .then clause or after an await results in only first contract being deployed

### ISSUE THREAD

**Issue by mhchu** [trufflesuite/truffle#650] opened 2017-11-01 09:07 UTC
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When migrating more than one contract the following works:
````
deployer.deploy(contractA);
deployer.deploy(contractB);
````
but if the second contract needs information from the first contract to be deployed, then this:
````
await deployer.deploy(contractA);
const instanceA = await contractA.deployed();
const value = await instanceA.getValue();
deployer.deploy(contractB, value);
````
does not work. Only contractA is deployed to the network and `truffle migrate` ends after showing contractB's address and does not say "Saving successful migration to network..."

This is true even in the simplified example of:
````
await deployer.deploy(contractA);
deployer.deploy(contractB);
````

The use of .then() or deployer.then() results in the same behavior - only the first contract is saved to the network.
````
deployer.deploy(contractA).then( ()=>{ deployer.deploy(contractB); });
````
````
deployer.deploy(contractA);
deployer.then( ()=> deployer.deploy(contractB); );
````
In all cases, `truffle migrate` says `Deploying contractB` and provides `contractB: <contractB address>` but it does not say `Saving successful migration to network...`

## Steps to Reproduce

Running truffle 3.4.11, node 7.10.1, and TestRPC 4.1.3 and simple contractA in contracts/contractA.sol and contractB in contracts/contractB.sol with migrations/2_deploy_contracts.js containing:
````
var contractA = artifacts.require("../contracts/contractA.sol");
var contractB = artifacts.require("../contracts/contractB.sol");

module.exports = async function(deployer, network, accounts) {
	await deployer.deploy(contractA);
	deployer.deploy(contractB);
}
````
contractA will be deployed on the network while contractB will not. (Obviously, this is not the use case, this is the simplest replication. The use case would be something closer to:
````
var contractA = artifacts.require("../contracts/contractA.sol");
var contractB = artifacts.require("../contracts/contractB.sol");

module.exports = async function(deployer, network, accounts) {
	const addr = accounts[0];

	await deployer.deploy(contractA, addr);
	const instance = await contractA.deployed();
	const value = await instance.getValue();
	console.log('DEBUG:', value); // provides an expected value
	deployer.deploy(contractB, value);
}
````

## Expected Behavior

Both contracts should be on the network.

## Actual Results

`truffle network` shows only the first contract. Using `truffle console` and trying to access `contractB.deployed()` results in a message that the contract is not deployed on the network.

**Comment by Velenir** [comment] 2017-11-08 08:55
You need to return `deployer.deploy(...)` from inside `.then(() => {...})`

**Comment by mhchu** [comment] 2017-11-08 23:04
I will give it a try and report back (probably in a couple days when I can return to my project).

**Comment by zcstarr** [comment] 2017-12-14 04:19
This is still an issue in 4.0.1

**Comment by dzentota** [comment] 2018-01-30 14:23
Tried every possible combination, async + await, then()  and async+await+then(), it doesn't work. In fact it always save Artifacts before deploying second contract, that's why you do not see address of the second contract. In my case I see address of the second contract after saving artifacts:
Running step...
  Deploying SampleCampaign...
  ... 0x68e6e16d86617689f9522e6dc9b56e0e9f66c7400e7c101fd3e0afaf5ffe8ca4
Saving artifacts...
  ... 0xdc7a4c7cdc7634c1b68fa254f863b2d54edbb475100f52fe87f084c63dcbd95d
  SampleCampaign: 0xad89528ffe22aa057cfbec6c9ccf2367a638eb79

So if I run `truffle console` and then in console:
`SampleCampaign.deployed()`

I get:
SampleCampaign has not been deployed to detected network (network/artifact mismatch)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:318327:17
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

But if I check address "0xad89528ffe22aa057cfbec6c9ccf2367a638eb79" I see that contract is there:
`SampleCampaign.at("0xad89528ffe22aa057cfbec6c9ccf2367a638eb79")`

**Comment by ismaelbej** [comment] 2018-02-06 18:52
This issue seems to be a duplicate of https://github.com/trufflesuite/truffle/issues/501.

**Comment by cgewecke** [comment] 2018-02-08 21:06
@ismaelbej Thank you for noting this, closing here in favor of #501..

@dzentota @mhchu 
The deployer stages deployments rather than running them at the execution time of the migration function. It's possible to use async/await within its context but ultimately you also have to follow the deployer's interface by returning a promise to its `.then` property. More guidance on this at the other issue [here](https://github.com/trufflesuite/truffle/issues/501#issuecomment-332589663)

**Closed by cgewecke** 2018-02-08 21:06 UTC

**Comment by dzentota** [comment] 2018-02-09 08:49
I saw #501 before and some similar. But approach mentioned in #501 doesn't work, output is the same

**Comment by cgewecke** [comment] 2018-02-09 14:46
@dzentota Could you share the code from the migrations that's not working?

**Comment by cgewecke** [comment] 2018-02-11 20:03
@dzentota The example @Velenir gives in this issue [above](https://github.com/trufflesuite/truffle/issues/650#issuecomment-342751957) is the model you should follow. If you want to run async logic in the migrations you must return it as a promise to the **`deployer`** method. In your case, 
```javascript
module.exports = function (deployer) {
  deployer.then( function() {
     return Crowdsale.deployed() .... etc ...
);
```

Additionally make sure you return **everything** async in the promise chain. For example the `deployer.deploy` in your final clause should also be prefaced with a return.

**Comment by dzentota** [comment] 2018-02-12 08:08
Thanks @cgewecke now it works!!!

**Comment by benediamond** [comment] 2019-08-05 15:42
> Additionally make sure you return everything async in the promise chain

@dzentota @cgewecke yes, this part is key in a way I can't quite understand yet. Is this because the main deployment function "knows to wait" for the promise chain to finish executing when it depends on its return value?

Is the value returned from the deployment function actually used by truffle in any way...?
