### ISSUE TITLE
Need to add documentation and change error message when incorrectly using inheritance

### ISSUE THREAD

**Issue by JackPickering** [trufflesuite/truffle#725] opened 2017-12-20 12:17 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

There is a lack of documentation on inheritance in solidity that does not make it obvious that the process of deploying a base contract WITH PARAMETERS, must be deployed inside the inheriting contract. 

The error message that Truffle shows for this is 'Error: Please check your gas amount' which isn't remotely true and if anything, throws people off when debugging this error. 

I assumed that I would have to deploy the base contract, then refer to that contract and deploy my inheriting contract which would use 'is BaseContract' in the name as per the documentation. 

But instead what you have to do, if just specify the inheriting contract in the migrations file and then deploy to the base contract within the constructor of the inheriting contract.

## Steps to Reproduce

Create two contracts, one base which requires a parameter in constructor and on inheriting contract (doesn't have to do anything at all) which simply imports the base contract file and uses the 'is' keyword to refer to it i.e. 

```
 function InheritingContract is Base {
     function Inheriting(uint256 SomeOtherVariable)
     {
          uint256 doSomething = SomeOtherVariable
      }
}
```

Deploy the base contract in migrations file with the parameter using: 
`deployer.deploy(Base, SomeVariable);`

Deploy the inheriting contract afterwards using: 
`deployer.deploy(Inheriting, SomeOtherVariable);`

The documentation should say (somewhere in Truffles docs too) that when inheriting a base contract with params you must specify it in the constructor of the inheriting contract like so:
    
```
function Inheriting(uint256 SomeVariable, uint256 SomeOtherVariable)
        Base(SomeVariable)
    {
        uint256 doSomething = SomeOtherVariable
    }
```

And then deploy the contract in migrations like so: 
`deployer.deploy(Inheriting, SomeVariable, SomeOtherVariable);`

This is rather important as anyone who wishes to write a worthy smart contract must split them down to keep under the block gas limit.

## Expected Behavior

The contract is either deployed OR an error message showing 'Incorrectly inheriting contract'

## Actual Results

You get the error 'Error: please check your gas amount'

## Environment

* Operating System: Mac OSX El Capitan
* Truffle version: v4.0.1
* Ethereum client: Geth
* node version: v8.9.0
* npm version: v5.6.0

**Comment by cgewecke** [comment] 2018-04-02 18:00
@JackPickering Agree this is a problem and that the message coming back from the client is uselessly cryptic. Not sure there is a straightforward fix for this other than enumerating the known causes of the error (there are many, unfortunately) in our reporting. 

Have opened an [issue](https://github.com/trufflesuite/truffle-migrate/issues/22) at `truffle-migrate` that covers this general topic and am linking back to this one. Closing here in order to track everything there. 

Thanks for taking the time to articulate the cause of this error so clearly, likely very helpful to other users.

**Closed by cgewecke** 2018-04-02 18:00 UTC
