### ISSUE TITLE
[v5] Migrations loss of information

### ISSUE THREAD

**Issue by roderik** [trufflesuite/truffle#1252] opened 2018-09-01 13:37 UTC
I use migrations quite extensively, not only for deploying contracts, but also to execute a lot of other transactions like assigning permissions etc. in the v4 migration output you could see all tx hashes, in v5 I only see the contract deployments. Is it possible to put the others back?

**Comment by cgewecke** [comment] 2018-09-03 16:27
Hi @roderik, thanks for raising this.

The non-deploy transaction hash logging was removed because it was difficult to represent meaningfully (although you were able to interpret it :) ). Web3 1.0 exposes event listeners for transaction hash and receipt so a work-around for your case might look something like:
```javascript
await deployer.deploy(Registry);
const registry = await Registry.deployed();
await registry.authorize()
              .on('transactionHash', hash => log(`Submitted registry authorization tx: ${hash}`))
              .on('receipt', receipt => log(`Registry authorized`));
```

More broadly, the Migrations module has been rewritten to emit await-able events and have output managed by an extensible [reporter service](https://github.com/trufflesuite/truffle/tree/next/packages/truffle-reporters/reporters/migrations-V5) that tracks state across a series of migrations files. This feature needs a little more work and lots of documentation but you should soon be able to plug in your own reporter and control it from the migrations file. Example:
```javascript
await deployer.deploy(Registry);
const registry = await Registry.deployed();

await deployer.emit('startRegistryAuthorization', registry.address);
const receipt = await registry.authorize();
await deployer.emit('endRegistryAuthorization', receipt);
```

The reporter might just log to the command line, or track additional gas usage, but it could basically do anything - like text you if your deployment errors or wrap a server that connects the migrations to a browser interface.

**Comment by roderik** [comment] 2018-10-06 17:54
@gnidan this is the loss of information issue I mentioned during TruffleCon

**Comment by gnidan** [comment] 2019-05-29 17:42
Closing this as duplicate of #1347. Don't worry @roderik, we haven't forgotten about wanting to add this behavior back in!

**Closed by gnidan** 2019-05-29 17:42 UTC
Labels: Migrations, Next
