### ISSUE TITLE
Truffle stuck when deploy smart contract

### ISSUE THREAD

**Issue by FilipLaurentiu** [trufflesuite/truffle#3091] opened 2020-06-04 11:22 UTC
---------------------------

## Issue
I have a little problem deploying smart contract with ledger nano s as provider on ropsten. The script just remain stuck at first migration
```
Starting migrations...
======================
> Network name:    'ropsten'
> Network id:      3
> Block gas limit: 8000029 (0x7a121d)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x1b85c85699b9f40798b5892a7492c303048915e80ac69803f94e617744769865
   ⠋ Blocks: 211          Seconds: 2829
```

This is my truffle configuration 
```
    ropsten: {
      provider: () => LedgerProviderRopsten,
      network_id: "*",
      gasPrice: web3.utils.toWei("3", "gwei"),
    },

```
## Steps to Reproduce

`truffle migrate --network ropsten`

## Expected Behavior
To migrate all the contract 
## Actual Results

In my example it wait for  Blocks: 211 but is stuck with first migration and don't run the next one

## Environment

* Operating System: Ubuntu 20
* Ethereum client: geth Version: 1.9.14-stable
* Truffle version (`truffle version`): 5.2.28
* node version (`node --version`): 12.8.0
* npm version (`npm --version`): 6.14.5

**Comment by fainashalts** [comment] 2020-06-17 17:42
Hi @FilipLaurentiu is your project available somewhere for us to take a look? We're not sure what is causing this issue and would like to try to reproduce. Thanks!

**Comment by FilipLaurentiu** [comment] 2020-06-18 05:34
> 
> 
> Hi @FilipLaurentiu is your project available somewhere for us to take a look? We're not sure what is causing this issue and would like to try to reproduce. Thanks!

[repository](https://github.com/FilipLaurentiu/LedgerExample)
I create a minimal repository to reproduce the issue. Just replace the rpc node with your node in 

> truffle-config.js 

and run 

> npm run deploy

**Comment by fainashalts** [comment] 2020-07-29 18:01
Thanks for the reproduction steps @FilipLaurentiu! Sorry this has taken us a while to get to. One of us will take a look soon!

**Comment by FilipLaurentiu** [comment] 2020-07-29 19:33
> Thanks for the reproduction steps @FilipLaurentiu! Sorry this has taken us a while to get to. One of us will take a look soon!

Thank you very much for response:+1:

**Comment by fainashalts** [comment] 2020-08-05 17:57
Hi @FilipLaurentiu so sorry for the delay on this one! We're waiting to receive a dedicated hardware wallet for development purposes so we can test this properly. We'll keep you posted!

**Comment by eggplantzzz** [comment] 2020-08-26 19:39
Hey again @FilipLaurentiu! I'm investigating your problem here and I wanted to verify that your use-case is supported by the device. Would you be able to link me to some docs describing how to use the ledger like you are doing? That would really help a lot in investigating your issue. Thanks!

**Comment by FilipLaurentiu** [comment] 2020-08-27 08:56
> Hey again @FilipLaurentiu! I'm investigating your problem here and I wanted to verify that your use-case is supported by the device. Would you be able to link me to some docs describing how to use the ledger like you are doing? That would really help a lot in investigating your issue. Thanks!

I don't find any official document supporting this functionality, but as long as I use the [provider engine](https://www.npmjs.com/package/web3-provider-engine) with ledger as provider It should work. We use this provider for web3 in other parts of the project for smart contract interaction and its working with no problem.

**Comment by eggplantzzz** [comment] 2020-08-27 20:49
So you can use this provider to interact with your contracts and send transactions? I wonder what could be going on because that is kind of what Truffle does in its internals. I'll look at that package. Thanks!

**Comment by eggplantzzz** [comment] 2020-08-27 21:04
Ah! One thing I noticed that could be the cause of the problem: try using our fork of `web3-provider-engine`. The package is called `@trufflesuite/web3-provider-engine`. I don't think Truffle is compatible with the most recent version of `web3-provider-engine`. We forked it a long time ago, I think because we are on an older version of `web3`. Try switching and let me know if you still encounter the same problem.

**Comment by FilipLaurentiu** [comment] 2020-08-28 07:04
> Ah! One thing I noticed that could be the cause of the problem: try using our fork of `web3-provider-engine`. The package is called `@trufflesuite/web3-provider-engine`. I don't think Truffle is compatible with the most recent version of `web3-provider-engine`. We forked it a long time ago, I think because we are on an older version of `web3`. Try switching and let me know if you still encounter the same problem.

```
filip@filip-pc:~/Work$ yarn deploy
yarn run v1.22.5
$ truffle deploy -f 2 --to 2 --network ropsten --skip-dry-run --verbose-rpc --reset

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'ropsten'
> Network id:      3
> Block gas limit: 8000029 (0x7a121d)


2_deploy_smart_contracts.js
===========================

   Deploying 'ContractName'
   -----------------------------
   > transaction hash:    0x1c4e8c1f14cbeb9470d7d4bc294ea3a5c447484c674c16bd22c4425c732d1923
   ⠴ Blocks: 64           Seconds: 701^C
```

Unfortunately, the same result. This is a temporal change or we should keep the 

> @trufflesuite/web3-provider-engine
instead of web3-provider-engine ?

**Comment by eggplantzzz** [comment] 2020-08-28 11:30
Ah too bad, I thought it might be caused by an incompatible version of web3. Let me go ahead and I'll do some more investigation and get back to you. Thanks!

**Comment by eggplantzzz** [comment] 2020-08-28 14:59
So can you give a simple example of how you would use the above setup to interact with a contract successfully?

**Comment by FilipLaurentiu** [comment] 2020-08-30 14:33
We need truffle to support deploying smart contract using ledger. Just that. Smart Contract interaction is made with ledger connected to metamask.

**Comment by FilipLaurentiu** [comment] 2020-08-30 14:34
> So can you give a simple example of how you would use the above setup to interact with a contract successfully?
> 
> Also, are you able to get this setup to work on a local test network like Ganache?

We need truffle to support deploying smart contract using ledger. Just that. Smart Contract interaction is made with ledger connected to metamask.

**Comment by eggplantzzz** [comment] 2020-08-31 14:44
I'm just trying to confirm that I can use this provider to send a transaction. So is it possible that you can provide me with a simple example of how I could use this to successfully send a transaction? This would be helpful so I can compare the successful and unsuccessful cases.

**Comment by fainashalts** [comment] 2020-09-30 18:12
Hi @FilipLaurentiu I'm going to close this for issue maintenance, but if you get together an example of what you're trying to do with a ledger here so we can test it out more, we'd be happy to troubleshoot some more!

**Comment by FilipLaurentiu** [comment] 2020-10-20 06:25
> > Interesting, can you tell us what you are using for `LedgerProviderRopsten`? Also, do you still get the same error when you remove the `gasPrice` field on your network settings? It should be optional and it would simplify troubleshooting. Let us know!
> 
> ```
> const LedgerWalletProvider = require('@ledgerhq/web3-subprovider');
> const createLedgerSubprovider = LedgerWalletProvider.default;
> const TransportNodeHid = require('@ledgerhq/hw-transport-node-hid').default;
> const ProviderEngine = require('web3-provider-engine');
> const RpcSubprovider = require('web3-provider-engine/subproviders/rpc');
> 
> // const logger = require("@ledgerhq/logs");
> 
> const localNode = 'http://127.0.0.1:8545';
> 
> 
> // logger.listen(log => console.log(log));
> const getTransport = () => TransportNodeHid.create();
> const ledger = createLedgerSubprovider(getTransport, {
>     networkId: 3, paths: ["44'/1'/x'/0/0", "44'/1'/0'/x"], askConfirm: false,
> });
> 
> const engine = new ProviderEngine();
> engine.addProvider(ledger);
> engine.addProvider(new RpcSubprovider({ rpcUrl: process.env.BLOCKCHAIN_NODE_ROPSTEN }));
> engine.start();
> 
> 
> module.exports = engine;
> ```
> 
> This is the code for `LedgerProviderRopsten` . Same behavior without the `gasPrice` field

This is an example

**Comment by FilipLaurentiu** [comment] 2020-10-20 06:25
> Hi @FilipLaurentiu I'm going to close this for issue maintenance, but if you get together an example of what you're trying to do with a ledger here so we can test it out more, we'd be happy to troubleshoot some more!

and the truffle provider is configure like that:
```
    ropsten: {
      provider: () => LedgerProviderRopsten,
      network_id: "*",
      gasPrice: web3.utils.toWei("3", "gwei"),
    },

```

**Comment by haltman-at** [comment] 2020-10-21 18:16
Thanks for the further information!  But, could you provide a simple example of a working transaction with this setup as suggested above?  It would be helpful in trying to debug this.

**Comment by FilipLaurentiu** [comment] 2020-10-22 06:43
> > Ah! One thing I noticed that could be the cause of the problem: try using our fork of `web3-provider-engine`. The package is called `@trufflesuite/web3-provider-engine`. I don't think Truffle is compatible with the most recent version of `web3-provider-engine`. We forked it a long time ago, I think because we are on an older version of `web3`. Try switching and let me know if you still encounter the same problem.
> 
> ```
> filip@filip-pc:~/Work$ yarn deploy
> yarn run v1.22.5
> $ truffle deploy -f 2 --to 2 --network ropsten --skip-dry-run --verbose-rpc --reset
> 
> Compiling your contracts...
> ===========================
> > Everything is up to date, there is nothing to compile.
> 
> 
> 
> Starting migrations...
> ======================
> > Network name:    'ropsten'
> > Network id:      3
> > Block gas limit: 8000029 (0x7a121d)
> 
> 
> 2_deploy_smart_contracts.js
> ===========================
> 
>    Deploying 'ContractName'
>    -----------------------------
>    > transaction hash:    0x1c4e8c1f14cbeb9470d7d4bc294ea3a5c447484c674c16bd22c4425c732d1923
>    ⠴ Blocks: 64           Seconds: 701^C
> ```
> 
> Unfortunately, the same result. This is a temporal change or we should keep the `@trufflesuite/web3-provider-engine` instead of `web3-provider-engine `?

@haltman-at is ok ?

**Comment by FilipLaurentiu** [comment] 2020-10-22 06:44
> > Hi @FilipLaurentiu is your project available somewhere for us to take a look? We're not sure what is causing this issue and would like to try to reproduce. Thanks!
> 
> [repository](https://github.com/FilipLaurentiu/LedgerExample)
> I create a minimal repository to reproduce the issue. Just replace the rpc node with your node in
> 
> > truffle-config.js
> 
> and run
> 
> > npm run deploy
@haltman-at 
is Ok ? https://github.com/FilipLaurentiu/LedgerExample

**Comment by eggplantzzz** [comment] 2020-10-26 16:57
@FilipLaurentiu Yes, those are the instructions for an UNSUCCESSFUL transaction. We would like to see an example of running a simple transaction SUCCESSFULLY. I don't know about that provider setup and would like to ensure that it does indeed work. Thanks!

**Comment by FilipLaurentiu** [comment] 2020-10-26 20:19
> @FilipLaurentiu Yes, those are the instructions for an UNSUCCESSFUL transaction. We would like to see an example of running a simple transaction SUCCESSFULLY. I don't know about that provider setup and would like to ensure that it does indeed work. Thanks!
Short example
https://github.com/FilipLaurentiu/WorkingLedgerExample

**Comment by eggplantzzz** [comment] 2020-10-27 14:33
Thanks @FilipLaurentiu! I'll go ahead and see what I can find out.

**Comment by eggplantzzz** [comment] 2020-10-27 14:36
Actually, I just looked at your example and it does not use the provider setup that you are trying to use in your main project. In other words, it does not demonstrate that the setup you are trying to use actually works. Can you provide me with an example that demonstrates that your provider setup works for a simple transaction? Do you understand what I'm looking for?

**Comment by gnidan** [comment] 2020-12-09 19:12
@FilipLaurentiu closing this for issue maintenance, but feel free to get back to us and we'll be happy to re-open! Thanks!

**Comment by adriadrop** [comment] 2021-06-27 21:44
Having the same issue at this point, all looks the same just using Rinkeby and HDWalletProvider(MNEMONIC, rinkebyNodeUrl); provider :(

**Comment by gnidan** [comment] 2022-02-10 20:14
> @gnidan can you reopen this?

Sure can!

**Comment by eggplantzzz** [comment] 2022-02-10 20:45
Can someone provide us with sample code and specific steps to reproduce this error?

**Comment by gelinger777** [comment] 2022-02-11 15:38
@eggplantzzz  I think we will have to go a bit opposite way. Long before it was possible (from what I read here) Possible to make deployments using Legder Nano Device using https://www.npmjs.com/package/@ledgerhq/web3-subprovider . But when you go now to the lib and make some research you understand that it's depreciated Because they moved away from U2F

```
this package is deprecated due to the fact we had to move away from U2F.
```

Nowdays when you want to make real deployments with truffle, mostly from what I understand you have to use HDWalletProvider with Mnemonics. But that's so dangerouse for serious projects. So the question here is not why it does not work, but HOW IT CAN be done.

**Comment by eggplantzzz** [comment] 2022-02-11 15:51
So it sounds more like this is a feature request. This issue doesn't really seem to be exactly what we should keep around; how would you feel about us closing this and you opening up a more fully-fleshed out feature request that robustly documents exactly what you would like to see Truffle support? We would love to support these kinds of use-cases...we have a feature dropping next week that is related to this but I'm not sure I can fully disclose it right now (sorry for the tease). Would you be into creating another issue with exactly what you'd like to see us support?

**Comment by eggplantzzz** [comment] 2022-03-22 15:23
So the feature I mentioned earlier that was released is the [Truffle Dashboard](https://trufflesuite.com/blog/introducing-truffle-dashboard/) which allows you to sign transactions with MetaMask. If you are using a hardware wallet with MM this will allow you to use it! If this is not sufficient for your use-case then please do open an issue with a request! Thanks!

**Closed by eggplantzzz** 2022-03-22 15:23 UTC
Labels: needs investigated

**Comment by bennyvenassi** [comment] 2022-05-10 19:01
Hi,
I got the same Problem with a normal MNEMONIC config and infura as endpoint. I used the config several times but since yesterday its stuck at the point replacing Migrations. The Dry Run runs without problems.

I tried to delete the node_modules folder, changed the truffle version from 5.3.xx to 5.5.xx its not working anymore.
Deploying to mumbai or fuji works. :/

What can I do to get it back to working with ropsten?

` ropsten: {
            provider: () => new HDWalletProvider(MNEMONIC, `wss://ropsten.infura.io/ws/v3/`),
            network_id: 3,
            //gas: 5500000,
            //confirmations: 2,
            //timeoutBlocks: 200,
            //skipDryRun: true,
            //pollingInterval: 1800000,
            //networkCheckTimeout: 8000,
            //deploymentPollingInterval: 30000
        },
     `

`Migrations dry-run (simulation)
===============================
> Network name:    'ropsten-fork'
> Network id:      3
> Block gas limit: 8000000 (0x7a1200)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > block number:        12254153
   > block timestamp:     1652208828
   > account:             0x53F9
   > balance:             5.521044825013136288
   > gas used:            257788 (0x3eefc)
   > gas price:           2 gwei
   > value sent:          0 ETH
   > total cost:          0.000515576 ETH

   -------------------------------------
   > Total cost:         0.000515576 ETH


2_deploy_contracts.js
=====================

   Deploying ''
   -------------------------
   > block number:        12254155
   > block timestamp:     1652208837
   > account:             0x53F90b0f
   > balance:             5.514190599013136288
   > gas used:            3399578 (0x33df9a)
   > gas price:           2 gwei
   > value sent:          0 ETH
   > total cost:          0.006799156 ETH


   Deploying ''
   ----------------------
   > block number:        12254156
   > block timestamp:     1652208845
   > account:             0x53F90b
   > balance:             5.509275691013136288
   > gas used:            2457454 (0x257f6e)
   > gas price:           2 gwei
   > value sent:          0 ETH
   > total cost:          0.004914908 ETH

   -------------------------------------
   > Total cost:         0.011714064 ETH


Summary
=======
> Total deployments:   3
> Final cost:          0.01222964 ETH





Starting migrations...
======================
> Network name:    'ropsten'
> Network id:      3
> Block gas limit: 8000000 (0x7a1200)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0x99bbced75fc968cebcd7c183b35e3a90d19e1050c3e1c6e587b59a91deeab3e5
   ⠸ Blocks: 10           Seconds: 364`
