### ISSUE TITLE
silent die of deploy ERC20 token from array

### ISSUE THREAD

**Issue by stanta** [trufflesuite/truffle#3889] opened 2021-02-27 05:41 UTC
## Issue

silent die of deploy ERC20 token from array
## Steps to Reproduce

I try to deploy array of ERC20 tokens from tokens.json:
```
{"XXXX":{"symbol":"XXX", "totAmount": "21000000",  "address":""}, 
"YYYY":{"symbol": "YYY", "totAmount": "21000000",  "address":""},
"ZZZZ":{"symbol":"ZZZ", "totAmount":"21000000", "address":""},
```

with code in migrations:
```
const MockERC20 = artifacts.require('MockERC20.sol');
const tokens = require ("../tokens.json");

module.exports = async function(deployer,_network, addresses) {
const admin = addresses[0];
await Object.keys(tokens).forEach (async (tokenName) => {
  var token = tokens[tokenName];
  const contERC = (tokenName, token, admin) => {
  try { 
    if (token.address == '') {
      const totAm = web3.utils.toWei(token['totAmount']);
      return MockERC20.new (tokenName, token['symbol'], totAm, {from:admin});
   } 
   else {
      return MockERC20.at(token.address);
     } 
   } 
  catch (e) {
     console.log (e)
}
}
const contract = await contERC(tokenName, token, admin);

}
```

And every way (in a lot of variants) got silent die (no post-mortem messages) at  
`return MockERC20.new (tokenName, token['symbol'], totAm, {from:admin});`

test code like 
`return  MockERC20.new (“Nametoken”, “NTT”, “21000000”, {from:admin});`
– don’t works too

but this test code outside  
```
Object.keys(tokens).forEach (async (tokenName) => {
…
}
```

 -  works properly, token deployed.

## Expected Behavior
Deploy several ERC20 tokens 
## Actual Result
tokens didn't deploy
## Environment

* Operating System: Linux Mint 19 
* Ethereum client: Web3/ Ganache
* Truffle version (`truffle version`): Truffle v5.1.67 (core: 5.1.67)
* node version (`node --version`):  v12.14.1 (same behavior in 10.18 and 14.15)
* npm version (`npm --version`): 6.13.4

**Comment by eggplantzzz** [comment] 2021-04-07 17:42
Hey @stanta, thanks for reporting this. Can you give us a repo and steps to reproduce this error? If you can we'll go ahead and troubleshoot this. As is, I don't know if we have quite enough info. Thanks!

**Comment by gnidan** [comment] 2021-05-19 18:07
Note that you have some JS issues here... `await array.forEach(...)` won't do anything, because `array.forEach()` returns `undefined` - so you're kicking off a bunch of promises but not awaiting those promises.

The right way to do this would be something like:
```javascript
await Promise.all(
  array.map(async (item) => { /* ... */ })
);
```

**Comment by gnidan** [comment] 2021-07-28 18:18
Closing this for issue maintenance. Hopefully you were able to fix the JS problems! Thanks for reporting!

**Closed by gnidan** 2021-07-28 18:18 UTC
