### ISSUE TITLE
Async await tests

### ISSUE THREAD

**Issue by ethers** [trufflesuite/truffle#314] opened 2016-12-13 00:04 UTC
Should the metacoin.js test be updated / cleaned up to use `await`?  And relevant docs too?

**Comment by tcoulter** [comment] 2016-12-13 00:09
It's possible. The issue is whether or not we should expect everyone to be updated to the latest node or to use Babel. I think there are many cases where neither may be available.

**Comment by tcoulter** [comment] 2017-02-01 20:50
Thinking about this again; this is probably best left to a tutorial on the truffleframework.com website.

**Comment by dotcypress** [comment] 2017-06-15 05:07
Yes, tests with `async/await` is more readable.

Default test rewritten with ES6 features:
```js
const MetaCoin = artifacts.require('./MetaCoin.sol')

contract('MetaCoin', (accounts) => {
  it('should put 10000 MetaCoin in the first account', async () => {
    const instance = await MetaCoin.deployed()
    const balance = await instance.getBalance.call(accounts[0])
    assert.equal(balance.valueOf(), 10000, "10000 wasn't in the first account")
  })
  it('should call a function that depends on a linked library', async () => {
    const meta = await MetaCoin.deployed()
    const outCoinBalance = await meta.getBalance.call(accounts[0])
    const outCoinBalanceEth = await meta.getBalanceInEth.call(accounts[0])
    assert.equal(
      outCoinBalanceEth.toNumber(),
      outCoinBalance.toNumber() * 2,
      'Library function returned unexpected function, linkage may be broken'
    )
  })
  it('should send coin correctly', async () => {
    // Get initial balances of first and second account.
    const account_one = accounts[0]
    const account_two = accounts[1]

    const meta = await MetaCoin.deployed()

    const account_one_starting_balance = await meta.getBalance.call(account_one)
    const account_two_starting_balance = await meta.getBalance.call(account_two)

    const amount = 10
    await meta.sendCoin(account_two, amount, {from: account_one})

    const account_one_ending_balance = await meta.getBalance.call(account_one)
    const account_two_ending_balance = await meta.getBalance.call(account_two)

    assert.equal(
      account_one_ending_balance.toNumber(),
      account_one_starting_balance.toNumber() - amount,
      "Amount wasn't correctly taken from the sender"
    )
    assert.equal(
      account_two_ending_balance.toNumber(),
      account_two_starting_balance.toNumber() + amount,
      "Amount wasn't correctly sent to the receiver"
    )
  })
})

```

**Comment by raineorshine** [comment] 2017-06-15 14:00
Great time for this now that node 8 supports async/await natively without a performance hit.

**Comment by tcoulter** [comment] 2017-07-13 16:55
@raineorshine Totally agree. I'm worried about the cost to new users who don't have Node 8, or for some reason can't get it (i.e., I'm being conservative). I'm going to plan this for a future milestone and revisit it in a few months. Thanks all!

**Comment by gnidan** [comment] 2018-10-24 18:13
This ticket is out of date, probably in a couple different ways. Closing. Thanks!

**Closed by gnidan** 2018-10-24 18:13 UTC
