### ISSUE TITLE
TypeError: Cannot read property 'number' of null

### ISSUE THREAD

**Issue by naszam** [trufflesuite/truffle#3132] opened 2020-06-29 16:52 UTC
Hi, 

I'm trying to deploy on Kovan via:
```
$ truffle migrate --network kovan
```
I'm getting the following:
```
/home/sencha/maker-badges/node_modules/@trufflesuite/web3-provider-engine/index.js:219
    number:           ethUtil.toBuffer(jsonBlock.number),
TypeError: Cannot read property 'number' of null
    at toBufferBlock (/home/sencha/maker-badges/node_modules/@trufflesuite/web3-provider-engine/index.js:219:50)
    at /home/sencha/maker-badges/node_modules/@trufflesuite/web3-provider-engine/index.js:60:27
    at /home/sencha/maker-badges/node_modules/@trufflesuite/web3-provider-engine/index.js:136:12
    at /home/sencha/maker-badges/node_modules/@trufflesuite/web3-provider-engine/index.js:199:9
    at /home/sencha/maker-badges/node_modules/async/internal/once.js:12:16
    at replenish (/home/sencha/maker-badges/node_modules/async/internal/eachOfLimit.js:61:25)
    at /home/sencha/maker-badges/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/home/sencha/maker-badges/node_modules/async/eachLimit.js:43:36)
    at /home/sencha/maker-badges/node_modules/async/internal/doLimit.js:9:16
    at end (/home/sencha/maker-badges/node_modules/@trufflesuite/web3-provider-engine/index.js:176:5)
    at /home/sencha/maker-badges/node_modules/@trufflesuite/web3-provider-engine/subproviders/provider.js:19:5
    at XMLHttpRequest.request.onreadystatechange (/home/sencha/maker-badges/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/sencha/maker-badges/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/home/sencha/maker-badges/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/home/sencha/maker-badges/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/home/sencha/maker-badges/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
I'm using:
- Truffle v5.1.32
-  @truffle/hdwallet-provider  v1.0.36
- Ubuntu 18.04
- npm v13.13.0

**Comment by CruzMolina** [comment] 2020-06-29 17:04
Thanks for reporting @naszam ! @ltfschoen has a fix for this in https://github.com/trufflesuite/provider-engine/pull/6. Closing as a duplicate of #3130 .

**Closed by CruzMolina** 2020-06-29 17:04 UTC

**Comment by CruzMolina** [comment] 2020-06-29 23:13
Until this goes out in our official weekly release, the fix for this is out at `@truffle/hdwallet-provider@next`.

Please give it a shot and let us know if this particular error has been resolved! 🙏

**Comment by naszam** [comment] 2020-06-30 09:27
Great! Thanks!
I will do!

**Comment by naszam** [comment] 2020-06-30 11:53
It worked! Thanks a lot!

**Comment by garethcurtis** [comment] 2020-07-03 20:00
Hi - not sure if this is helpful or not but FYI....

I was using
`truffle console --network ropsten`
And then once connected:
`migrate --reset`

And the above error still occurs for me, even in 5.1.33. Connect to the network, within 20 seconds or so, that error appears.

However, I did what naszam said and instead used:
`truffle migrate --network ropsten`

And it's all good. Thanks!

**Comment by CruzMolina** [comment] 2020-07-03 21:03
Hey @garethcurtis, are you using `@truffle/hdwallet-provider@latest`?

**Comment by garethcurtis** [comment] 2020-07-04 04:55
Hi @CruzMolina does that came as part of 5.1.33? I assumed so... If not then sorry, nope.

**Comment by CruzMolina** [comment] 2020-07-04 17:07
@garethcurtis , `@truffle/hdwallet-provider` is a separate pkg from `truffle`.

**Comment by garethcurtis** [comment] 2020-07-04 17:28
OK, sorry, new to this. I normally do Objective C/Swift on iOS :)

I thought hdwallet-provider came as part of  @trufflesuite/web3-provider-engine@14.0.7. Apologies. I will try and figure out how to get hdwallet-provider separately! Thanks @CruzMolina 

I managed to get the contract deployed anyway, so all good from that perspective.

**Comment by CruzMolina** [comment] 2020-07-05 14:22
No worries @garethcurtis , `@truffle/hdwallet-provider` includes `@trufflesuite/web3-provider-engine` as a dependency. To install and use `@truffle/hdwallet-provider`, run `npm install @truffle/hdwallet-provider` and see the [README](https://github.com/trufflesuite/truffle/tree/develop/packages/hdwallet-provider#truffle-usage) for configuration.
