### ISSUE TITLE
Truffle in not recognize in vs code 

### ISSUE THREAD

**Issue by Prathamesh532** [trufflesuite/truffle#5586] opened 2022-10-02 13:42 UTC
truffle is not install properly in vs code

**Comment by leeftk** [comment] 2022-10-06 17:36
Hey @Prathamesh532 would you mind giving us some more details on what the issue is here? Do you mean the vs code extension is not installing or truffle itself? If you could provide some screenshots or error output of the issue that would be great. Thanks!

**Comment by leeftk** [comment] 2022-11-10 17:13
Closing here for issue maintenance. Feel free to open another issue if you're still having any problems with this. Thanks!

**Closed by leeftk** 2022-11-10 17:13 UTC
