### ISSUE TITLE
Truffle seems to want Python

### ISSUE THREAD

**Issue by YumYumOutlast** [trufflesuite/truffle#3980] opened 2021-04-17 15:08 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I'm new.. please forgive me but i'm attempting to learn this on my own from home.

I opened the command terminal (Ran as Admin) and input >$ npm install -g truffle

To which I got the response: 
'$' is not recognized as an internal or external command,
operable program or batch file.

Then I dropped the '$' and input >npm install -g truffle

To which I got the response:
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

And all of the install looked similar to the above.

 Not sure what to do....

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: Windows 10
![Screenshot 2021-04-16 22 24 12](https://user-images.githubusercontent.com/82629508/115117863-ce7cea80-9f5d-11eb-96c4-6a2b054388c8.png)

* Ethereum client: 
* Truffle version (`truffle version`):  v5.3.2 (core: 5.3.2)
* node version (`node --version`): v14.16.1.
* npm version (`npm --version`): '6.14.12',

**Comment by eggplantzzz** [comment] 2021-04-19 17:30
Hey @YumYumOutlast! You should only really need to do `npm install -g truffle`. So it is normal to get a bunch of warning when installing Truffle but that shouldn't really prevent it from installing and running fine.

I'm a little confused about what happened after you installed, what happens when you do `truffle version` after it finishes installing? Or did you get all those errors during installation?

**Comment by YumYumOutlast** [comment] 2021-04-19 19:18
Yeah I got the warnings when I dropped the ‘$’ and did npm install -g
truffle

Support told me it was probably because I didn’t have python installed lol
so that shows how green I am.

I’ll try it again with python integrated and we'll see lol

**Comment by gnidan** [comment] 2021-04-21 17:49
Looks like there may be more than one issue here - there are a bunch of warnings about deprecated packages (which should be easy enough to upgrade), but this business about Python being required is particularly alarming.

We'll get it on the list to address these.

(For reference, my hunch is that the problem lies with the @truffle/db package, which is an optionalDependency of truffle... @truffle/db requires sqlite3 which looks maybe to require Python, but if anything there fails to install, the optional nature of the dependency means that Truffle should still install just fine.)

@YumYumOutlast before you go and install Python, can you just try running `truffle version`? I'm wondering if the error can be ignored — that would mean the question just becomes "how do we make this really ugly error from happening?"

Anyway, thank you for taking the time to write this up.

**Comment by gnidan** [comment] 2021-04-21 17:57
Since there's also issue https://github.com/trufflesuite/truffle/issues/3980, I'm updating this issue here to pertain only to the Python concern.

**Comment by cds-amal** [comment] 2021-06-17 09:02
@YumYumOutlast , @gnidan It looks  related to `node-gyp`, node's cross platform build tool used to compile nodejs native add-ons. It has a `python` dependency. [Here are instructions for installing on Windows](https://github.com/nodejs/node-gyp#on-windows)

**Comment by leeftk** [comment] 2021-07-21 18:49
We've reproduced the behavior and Truffle seems to install fine. We'll circle back with the team and come back to you with next steps.

**Comment by gnidan** [comment] 2021-07-28 17:41
@YumYumOutlast so since Truffle installs despite the warning, this issue should probably turn into an effort to improve messaging around this situation.

Problem is, when installing Truffle, there's not much we can do about the output. I think we're stuck closing this issue and following up later to improve the story around Truffle's optional dependencies.

Thanks for reporting this and getting us thinking about it!

**Closed by gnidan** 2021-07-28 17:41 UTC

**Comment by YumYumOutlast** [comment] 2021-10-30 11:12
@gnidan Okay, months later lol im back. 

so i tried truffle version, and got

C:\Users\famil>truffle version
Truffle v5.0.5 (core: 5.0.5)
Solidity - 0.8.9 (solc-js)
Node v14.16.1

I'm trying to work through a tutorial with Gregory over with Dapp University. That's why 5.0.5 is downloaded. I'm still very beginner in coding. My problem is when I write $truffle init 

I get this:

√ Preparing to download
/ DownloadingError: write EPROTO 13240:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)

Can you help? Hope you're having a fantastic Saturday, brother!

**Comment by cds-amal** [comment] 2021-10-30 16:45
Hello @YumYumOutlast, can you open a new issue for your last comment? It will help us track and address the problem more efficiently.
