### ISSUE TITLE
Configuration changes for multi-network projects

### ISSUE THREAD

**Issue by fainashalts** [trufflesuite/truffle#5272] opened 2022-07-08 21:23 UTC
Consult with gnidan on specs for this. 

* truffle-config.js probably needs to have separate environments baked in; may be a breaking change depending on how we set it up (default to no environment to prevent breaking changes)

* Really how we already built the L2 boxes, but would be nice to have it all in one file (be aware that Starknet may be a special case and consider elements that may be specific to it when designing this architecture)

* Format may need to be shared with Ganache (as it needs to know the order networks needs to be started)

** Declarative Deployments needs this finished to function fully as expected **

**Comment by gnidan** [comment] 2022-09-29 18:07
Discovery efforts for designing the format of these changes is underway.

**Comment by gnidan** [comment] 2022-09-29 18:14
Actually, seems like we should close this as duplicate of #5478

**Closed by gnidan** 2022-09-29 18:14 UTC
Labels: needs requirements, priority2 ⚠️
