### ISSUE TITLE
Debugger displays incorrect source after stepping past inline assembly

### ISSUE THREAD

**Issue by prestwich** [trufflesuite/truffle#3079] opened 2020-05-29 19:04 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Debugger source map breaks after it encounters assembly blocks

## Steps to Reproduce

- Check out the `debugger-issues` branch of [this repo](https://github.com/summa-tx/bitcoin-spv)
- run ganache-cli in a separate terminal
- run `truffle test`
- grab the last txid from ganache, and run `truffle debug $TXID`
- step through, mixing `n` and `o`
  - The call starts in `ViewBTCTest.sol` at `indexVin`.

## Expected Behavior

Debugger should display the currently executing line of code.

## Actual Results

Debugger displays unrelated code blocks that are not executed. Behavior is not predictable. 

- It seems to occur towards the end of the transaction. 
- It seems to occur only in txns that execute in-line assembly. 
- Output is not repeated exactly on different debug runs
  - It may depend on the exact sequence of `;` `n` and `o` steps made in the debugger.
- Debugger will fail to show local vars with message `cannot read stack at position 9 to 9`

![Screenshot from 2020-05-29 11-28-36](https://user-images.githubusercontent.com/10149425/83295509-ef9ce700-a1a3-11ea-8d0c-f5cc7c100138.png)

- Some local variables are missing from the stack. Memory layout has the expected 2 `bytes memory` types after execution of `.clone()`.

![Screenshot from 2020-05-29 11-28-13](https://user-images.githubusercontent.com/10149425/83295512-f166aa80-a1a3-11ea-987f-b8e915380fb3.png)

- These functions are never called

![Screenshot from 2020-05-29 11-27-59](https://user-images.githubusercontent.com/10149425/83295514-f166aa80-a1a3-11ea-9e73-74bed7c3ccd1.png)

-  Some of these functions are never called

## Environment

* Operating System: `Ubuntu 16.04`
* Ethereum client: `ganache-cli`
* Truffle version (`truffle version`): Truffle v5.1.24 (core: 5.1.24)
Solidity v0.5.16 (solc-js)
Node v12.16.1
Web3.js v1.2.1

**Comment by prestwich** [comment] 2020-05-29 22:57
![Screenshot from 2020-05-29 15-57-08](https://user-images.githubusercontent.com/10149425/83311779-161f4a00-a1c5-11ea-9505-7f673b4463f6.png)

- example of missing stack variables from a different transaction

**Comment by haltman-at** [comment] 2020-05-30 00:40
OK, so I looked at this a bit and definitely was able to confirm the debugger reporting some wrong results, yup.  But, I notice you have the optimizer turned on.  Unfortunately, the debugger doesn't really work with optimized contracts, as their sourcemaps can be a bit sparse or otherwise irregular... and I only just realized our documentation doesn't list this caveat. >_>   (I'll have to go add that...) Question, can you reproduce these problems with the optimizer turned off?

**Comment by prestwich** [comment] 2020-05-30 02:29
I ran through 2 different txns with optimization disabled. While output was much much better overall, there were still a few hiccups. So that was probably >90% of the problem

![Screenshot from 2020-05-29 19-26-35](https://user-images.githubusercontent.com/10149425/83317535-55a85f00-a1e2-11ea-8bbf-82f5b6794b77.png)

- still missing a stack var

![Screenshot from 2020-05-29 19-26-12](https://user-images.githubusercontent.com/10149425/83317536-5640f580-a1e2-11ea-9d57-2e061b8f718f.png)

- a random jump to an unrelated function that's not being executed

If the debugger is known to break if optimization is enabled, here are a couple suggestions:

- emit a warning if the optimizer is enabled in the config file when the debugger starts
- use a separate build directory for the debugger, and emit artefacts without optimization

**Comment by haltman-at** [comment] 2020-05-30 03:42
Hm, troublesome.  OK, I'll have to take a more detailed look on returning next week.

Some questions for ease of reproducing these -- are these transactions also from your tests?  If so, which ones are they?  If not, can you say what functions you ran with what parameters?  Also, for the first problem, with the missing stack variable, can you say at what point in the code this occurred?

And yeah, recompiling with optimization turned off has exactly the problem you say. :-/  A warning sounds like a good idea though!  Will have to figure out the details of how that would work, though we could just check the config like you say for a crude method that will work most of the time.

Thanks again for all this!

**Comment by prestwich** [comment] 2020-05-30 03:58
I've pushed a new commit to the `debugger-issues` branch. Again, run `ganache-cli`. This time debug the tx that errors with the message `DEBUG ME`.

The `DEBUG ME` transaction is calling the `slicing` function on `TestMemView.sol`.

The first screenshot with the missing stack variable is at ~L180 of TestMemView. The second screenshot with the bad sourcemap happened just after L174. The debug output shows `L24`, which is not executed in that transaction

**Comment by haltman-at** [comment] 2020-06-01 20:33
OK, thanks for the detail!  Should have a chance to sit down and investigate this soon.

**Comment by prestwich** [comment] 2020-06-01 20:51
Awesome, thanks. This is not blocking any work, as disabling the optimizer gets us close enough to be useful

**Comment by haltman-at** [comment] 2020-06-02 07:34
Hm, unfortunately I can't seem to reproduce either of these errors, including on 5.1.24.  No clue.

**Comment by haltman-at** [comment] 2020-06-03 17:49
Just to check, did you recompile everything with `truffle compile --all`, or `truffle migrate --compile-all --reset`, after turning off optimization?  Thanks!

**Comment by prestwich** [comment] 2020-06-04 19:03
I believe I recompiled everything

**Comment by haltman-at** [comment] 2020-06-04 19:24
Hm, troublesome...

**Comment by haltman-at** [comment] 2020-06-18 00:48
OK, I finally had some time to try this again with Node 12 and I still couldn't reproduce the problem.  No clue.

**Comment by prestwich** [comment] 2020-06-18 16:31
Weird. Still might be some idiosyncrasy in my setup. because disabling the optimizer solved 90% of the problem, I'm fine if you delete this issue

**Comment by fainashalts** [comment] 2020-06-24 18:12
@prestwich thanks for bringing this up, per your previous comment we're going to close this for issue maintenance (and only feel slightly defeated).

**Closed by fainashalts** 2020-06-24 18:12 UTC
Labels: needs reproduced

**Comment by redigaffi** [comment] 2022-04-14 17:22
Oh lord, debugging with optimizations turned off is a whole different story, wasn't aware. Dont forgot to cleanup your build folder before doing a new compilation/deployment without optimizations, if not debugger could not find any source code.
