### ISSUE TITLE
truffle init error

### ISSUE THREAD

**Issue by librauee** [trufflesuite/truffle#2832] opened 2020-02-14 08:19 UTC
when I use command truffle init ,

Starting unbox...
=================

√ Preparing to download box
× Downloading
Unbox failed!
RequestError: Error: read ECONNRESET
    at new RequestError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\errors.js:14:1)
    at Request.plumbing.callback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:87:1)
    at Request.RP$callback [as _callback] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:46:1)
    at self.callback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:185:1)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:881:1)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Truffle v5.1.12 (core: 5.1.12)
Node v10.16.0

How can I sovle it ?

**Comment by librauee** [comment] 2020-02-17 05:19
When I change my network to another,it works.
But I really don't know why how to explain.

**Comment by gnidan** [comment] 2020-02-19 18:48
Could you perhaps describe your network configuration for the failing case?

Not sure what the issue is here, but would love to get to the bottom of it. Thanks for raising this!

**Comment by gnidan** [comment] 2020-02-19 19:02
Actually, this issue appears to be a duplicate of #2692 - closing this to move the discussion there. Thanks again!

**Closed by gnidan** 2020-02-19 19:02 UTC

**Comment by lidaxuan** [comment] 2022-07-13 01:48
weishenmequanshiyngwen
