### ISSUE TITLE
TypeError: this.parent.titlePath is not a function

### ISSUE THREAD

**Issue by chenweiyj** [trufflesuite/truffle#1149] opened 2018-07-25 13:41 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I met a problem `TypeError: this.parent.titlePath is not a function` when I running `truffle test`.
It seems a mocha Error. But I cannot solve it.

## Steps to Reproduce

Running `truffle test` command and it shows out.

## Expected Behavior

It should test the solidity file, and show the testing results.

## Actual Results

Actually, it shows the result as follows.

```
Using network 'test'.

Compiling ./contracts/BCD.sol...
Compiling ./test/TestBCD.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...
TypeError: this.parent.titlePath is not a function
    at Suite.titlePath (/Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/build/webpack:/~/mocha/lib/suite.js:380:1)
    at Test.Runnable.titlePath (/Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/build/webpack:/~/mocha/lib/runnable.js:197:1)
    at Test.Runnable.fullTitle (/Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/build/webpack:/~/mocha/lib/runnable.js:185:1)
    at /Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/node_modules/_mocha@3.5.3@mocha/lib/runner.js:134:38
    at Array.forEach (native)
    at Suite.eachTest (/Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/build/webpack:/~/mocha/lib/suite.js:413:1)
    at /Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/node_modules/_mocha@3.5.3@mocha/lib/suite.js:390:11
    at Object.exports.forEach (/Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/node_modules/_mocha@3.5.3@mocha/lib/utils.js:52:8)
    at Suite.eachTest (/Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/node_modules/_mocha@3.5.3@mocha/lib/suite.js:389:9)
    at Runner.grepTotal (/Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/node_modules/_mocha@3.5.3@mocha/lib/runner.js:133:9)
    at Runner.grep (/Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/node_modules/_mocha@3.5.3@mocha/lib/runner.js:115:21)
    at new Runner (/Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/node_modules/_mocha@3.5.3@mocha/lib/runner.js:82:8)
    at Mocha.run (/Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/node_modules/_mocha@3.5.3@mocha/lib/mocha.js:519:16)
    at /Users/chenwei/.nvm/versions/node/v6.12.3/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/test.js:125:1
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

## Environment

* Operating System: macOS 10.13.6
* Ethereum client: truffle test env; also I installed `geth 1.8.12-stable` via brew
* Truffle version (`truffle version`): v4.1.13
* node version (`node --version`): v6.12.3
* npm version (`npm --version`): 6.2.0

**Comment by cgewecke** [comment] 2018-07-25 16:07
@chenweiyj  This is a weird mocha bug that comes from mixing versions of mocha - v3 is not compatible with v4.  We need to investigate how Mocha 3.5 is getting into the build - this should be happening since `4.1.11`

**Comment by cgewecke** [comment] 2018-08-05 18:12
@chenweiyj I wasn't able to reproduce this locally. . . it may be a quirk of how truffle installed on your machine / in your project. The upshot is that mocha versions can't conflict so if you see this error run 
```
npm list mocha 
npm list -g mocha
```
and try makes sure that you're using Mocha 4 or above. 

Closing for now but please ping if anyone continue to have this problem and there's a clear reproduction path.

**Closed by cgewecke** 2018-08-05 18:12 UTC

**Comment by chenweiyj** [comment] 2018-08-07 02:37
Yes, in node v6 it only supports mocha 3.5.3. By using node v8, it is solved, and I can use mocha 4 now.

**Comment by cgewecke** [comment] 2018-08-07 22:18
@chenweiyj Ah thanks! That's helpful.
