### ISSUE TITLE
Truffle Dashboard is a blank page

### ISSUE THREAD

**Issue by Bodiebuilds** [trufflesuite/truffle#5050] opened 2022-04-24 01:17 UTC
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Running truffle dashboard opens a blank page

## Steps to Reproduce

nvm use 14
npm i -g truffle
npm truffle dashboard

tried rolling back versions but still same issue
npm uninstall -g truffle 
npm i -g truffle@v5.5.3

## Expected Behavior

open truffle dashboard webpage 

## Actual Results

node version is good and tried rolling back various versions of truffle (5.5.3 ; 5.5.4 and latest version) with no luck. Updated VS code as well. running dashboard command brings me to a blank white page. It has worked before with no problem but has been giving me this same result now.

## Environment

* Operating System: macOS
* Ethereum client:
* Truffle version (`truffle version`):5.5.11
* node version (`node --version`): 14.9.1
* npm version (`npm --version`): 6.14.16

**Comment by lsqproduction** [comment] 2022-04-27 17:46
@Bodiebuilds Thank you for opening the issue.  Please note `npm truffle dashboard` is not the correct command. It should just be `truffle dashboard`. May I also know what are the terminal outputs you were getting after running this command? 
Attaching a guide for [truffle dashboard](https://trufflesuite.com/blog/introducing-truffle-dashboard/)

**Comment by dashboarduser** [comment] 2022-05-01 01:18
I have the same problem after truffle reinstallation
npm uninstall -g truffle
npm install -g truffle
truffle dashboard — opens blank in Chrome (my default browser)
sudo truffle dashboard — opens in Safari all good, but can't use MetaMask

Environment:
macOS
truffle version
Truffle v5.5.12 (core: 5.5.12)
Ganache v^7.1.0
Solidity - 0.8.13 (solc-js)
Node v14.18.2
Web3.js v1.5.3

**Comment by gnidan** [comment] 2022-05-05 17:51
Thanks for reporting this! We've heard of a couple users running into this periodically, but we haven't been able to get the information we need to understand what's causing this behavior. If this is still occurring for anyone, would you mind please checking the browser console (like, right-click -> Inspect, or see [these instructions for Chrome](https://developer.chrome.com/docs/devtools/open/)) and share any errors you see?

Also, if the `truffle dashboard` terminal window has any odd-looking output, please share that as well! Any additional information would be enormously helpful, because otherwise we're a bit stumped.

Thanks all. 🙏

**Comment by sukanyaparashar** [comment] 2022-06-22 21:48
Closing this for issue maintenance. @Bodiebuilds, please feel free to open a new issue if it still exists.

**Comment by emilyJLin95** [comment] 2022-07-09 01:04
Just ran into this

The inspect gives:
```
GET http://localhost:24012/static/js/2.c92ece40.chunk.js net::ERR_ABORTED 404 (Not Found)
GET http://localhost:24012/static/js/main.13631e75.chunk.js net::ERR_ABORTED 404 (Not Found)
```

Nothing looks weird on the terminal side

**Comment by emilyJLin95** [comment] 2022-07-09 01:19
Actually uninstalled truffle, updated node, and reinstalled truffle, and now everything works find again. Feel free to close then?

After reinstalling:
Truffle v5.5.21 (core: 5.5.21)
Ganache v7.2.0
Solidity v0.5.16 (solc-js)
Node v16.16.0
Web3.js v1.7.4

**Comment by cliffoo** [comment] 2022-07-09 03:58
🤷‍♂️ I guess I'll keep this in the back of my head as I work through [pr#5241](https://github.com/trufflesuite/truffle/pull/5241). Thanks for reopening this.

**Comment by cliffoo** [comment] 2022-07-15 21:32
So this just happened to me on Truffle v5.5.20. I got similar error output as @emilyJLin95 shared.

I restarted `truffle dashboard`, hard-refreshed the page and it's back.

Doesn't seem like a frontend issue as the build is clearly there. Perhaps something is up with how the build is served by the dashboard server. I'll keep this in mind.

**Comment by haltman-at** [comment] 2022-08-24 22:47
OK, this should now be fixed!  There is still a problem where you'll get a blank page if MetaMask isn't installed, but I'm going to open that as a separate issue.

**Closed by haltman-at** 2022-08-24 22:47 UTC

**Comment by Faisal-FS** [comment] 2022-09-14 08:17
Although the issue is closed but I am sharing my solution here.

Got the same issue but the error output was different for me: 
![image](https://user-images.githubusercontent.com/25268271/190099458-beaed4bc-1b4d-406b-865b-f21d4d79b6b6.png)

On the suggestion of @haltman-at. 

After the installation of MetaMask extensions in chrome. The page is back again.

Thanks @haltman-at

**Comment by drintg** [comment] 2022-10-20 17:39
Hi ! I have a similar problem, but for me, didn't even worked for once the "truffle dashboard" command. All I see is a blank white page since the beginning.
<img width="556" alt="2" src="https://user-images.githubusercontent.com/116302475/197019743-ff55ee80-27c5-48f1-bde7-cf9ff02d36f2.png">
<img width="1194" alt="1" src="https://user-images.githubusercontent.com/116302475/197019746-47359251-2bc8-485b-8b39-e3f383bb8432.png">

do you have any advice ?
