### ISSUE TITLE
Update documentation for Infura API v3

### ISSUE THREAD

**Issue by jamesmorgan** [trufflesuite/truffle#1874] opened 2019-04-02 11:33 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Today, when deploying contracts to mainnet I have received the following error whilst using truffle deploy `Error: legacy access request rate exceeded`

## Steps to Reproduce

Deploy a new contract to main.

## Expected Behavior

No exceptions

## Actual Results

Sample stack trace I get:

```
   ⠋ Blocks: 29           Seconds: 340Error: legacy access request rate exceeded
    at /Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/web3-provider-engine/subproviders/provider.js:18:1
    at e.callback [as onreadystatechange] (/Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/web3/node_modules/web3-providers-http/src/index.js:96:1)
    at e.call [as dispatchEvent] (/Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at e.dispatchEvent [as _setReadyState] (/Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
    at e._setReadyState [as _onHttpResponseEnd] (/Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
    at IncomingMessage._onHttpResponseEnd (/Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
   ⠸ Blocks: 41           Seconds: 528Error: legacy access request rate exceeded
    at /Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/web3-provider-engine/subproviders/provider.js:18:1
    at e.callback [as onreadystatechange] (/Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/web3/node_modules/web3-providers-http/src/index.js:96:1)
    at e.call [as dispatchEvent] (/Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at e.dispatchEvent [as _setReadyState] (/Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
    at e._setReadyState [as _onHttpResponseEnd] (/Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
    at IncomingMessage._onHttpResponseEnd (/Users/jamesmorgan/Dropbox/workspace-blockrocket/blockcities/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/fainashalts/truffle-dev/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
   ⠸ Blocks: 46           Seconds: 624^C
```

## Environment

* Operating System: OXS
* Ethereum client: Truffle/Infura
* Truffle version (`truffle version`): 
* node version (`node --version`):  `v5.0.5`
* npm version (`npm --version`): `6.5.0`

**Comment by jamesmorgan** [comment] 2019-04-02 13:54
TBH - looking at this again I guess it may be a HD wallet issue?

**Comment by eggplantzzz** [comment] 2019-04-03 15:46
@jamesmorgan Can you give some more details about what you were doing so we can try and reproduce/troubleshoot the problem? What version of Truffle are you using? I assume you are not using the most recent version as you need to be using a version of node >= `8.94`. Consider upgrading the most recent version of Truffle (and a more recent version of node :) ).

**Comment by jamesmorgan** [comment] 2019-04-03 16:26
Ah ye, sorry I copy pasted into the wrong bit, this is my output, I am using a new version of truffle:
```
truffle version
Truffle v5.0.5 (core: 5.0.5)
Solidity v0.5.0 (solc-js)
Node v8.9.4
```
I was just deploying several fairly large contracts to mainnet from truffle - this is the command I used, I had 4 migrations to run in total `truffle compile; truffle migrate --network live;`

`live` is an option in my truffle config which looks like this:
```
live: {
            provider: function () {
                return new HDWalletProvider(process.env.BLOCK_CITIES_MNEMONIC, `https://mainnet.infura.io/v3/${process.env.INFURA_KEY}`);
            },
            network_id: 1,
            gas: 6075039,
            gasPrice: 7000000000,
            timeoutBlocks: 200,
            skipDryRun: true
        },
```

I have been using truffle for a long time and have never seen this message so thought I would raise it.

**Comment by eggplantzzz** [comment] 2019-04-05 13:11
@jamesmorgan I'm not familiar with this error either. Is your codebase available somewhere?

**Comment by eggplantzzz** [comment] 2019-04-24 17:54
@jamesmorgan By the way, are you using a legacy infura endpoint? Sounds like it could be the result of you not using the new format? Let me know.

**Comment by jamesmorgan** [comment] 2019-04-25 12:28
@eggplantzzz nope I was using the `V3` endpoint and I havent seen the error since reporting this. Maybe it was a networking issue which surfaced as the error?

**Comment by eggplantzzz** [comment] 2019-04-26 11:17
Huh, very weird. Well I guess it is nice when problems seem to fix themselves. Maybe it was just an infura blip or something. Closing this for now, if it surfaces again feel free to open another!

**Comment by yuwiggin** [comment] 2019-09-08 11:46
I had the same issue when deploy a contract on Rinkeby network. 

```
Error: legacy access request rate exceeded
    at /Users/viking/ethereum/project/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-provider-engine/subproviders/provider.js:18:1
```

How to fix it? 
Here is a part of `truffle.js`: 

```
        rinkeby: {
            provider: () =>
                new HDWalletProvider(mnemonic,"https://rinkeby.infura.io/v3/"+PROJECT_ID, 2),
            network_id: 4,
            gas:  6e6,
            gasPrice: 2e9,
        },
```

Operating System: OXS
Ethereum client: Truffle/Infura
Truffle v5.0.27 
node: v8.15.1
Solidity v0.5.11 (solc-js)

**Comment by yuwiggin** [comment] 2019-09-08 11:46
I had the same issue when deploy a contract on Rinkeby network. 

```
Error: legacy access request rate exceeded
    at /Users/viking/ethereum/project/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-provider-engine/subproviders/provider.js:18:1
```

How to fix it? 
here is a part of truffle.js 
```
        rinkeby: {
            provider: () =>
                new HDWalletProvider(mnemonic,"https://rinkeby.infura.io/v3/"+PROJECT_ID, 2),
            network_id: 4,
            gas:  6e6,
            gasPrice: 2e9,
        },
```

Operating System: OXS
Ethereum client: Truffle/Infura
Truffle v5.0.27 
node: v8.15.1
Solidity v0.5.11 (solc-js)

**Comment by guix77** [comment] 2019-11-16 16:06
I’m also having this problem with truffle migrate using latest Truffle 5.1.0

```
const HDWalletProvider = require('@truffle/hdwallet-provider')

module.exports = {
  networks: {
    ropsten: {
      provider: new HDWalletProvider(process.env.MNEMONIC, 'https://ropsten.infura.io/v3/' + process.env.INFURA_PROJECT_ID),
      gas: 4700000,
      network_id: 3
    },
  },
  migrations_directory: './migrations',
};
```

**Comment by CruzMolina** [comment] 2019-11-17 03:36
Hi @guix77, can you confirm that your Infura Project is set to use Project IDs? (See https://community.infura.io/t/legacy-key-deprecation/443)

Based on your code snippet it looks it already uses Project IDs, but wanted to double-check. 🙂

**Comment by guix77** [comment] 2019-11-17 11:06
Hi @CruzMolina, yes I set up a project in my Infura account, and in my .env I have :

`INFURA_PROJECT_ID=abcd...`

I tried with "" too and with wss:// but this one does not seem to be implemented.

Furthermore on my Infura account I can see my amount of requests attached to this project.

The error is consistently :

```
⠼ Saving migration to chain.Error: legacy access request rate exceeded
    at /home/guix/dev/my-smart-contracts/node_modules/web3-provider-engine/subproviders/provider.js:18:36
    at XMLHttpRequest.request.onreadystatechange (/home/guix/dev/my-smart-contracts/node_modules/@truffle/hdwallet-provider/node_modules/web3-providers-http/src/index.js:102:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/guix/dev/my-smart-contracts/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (/home/guix/dev/my-smart-contracts/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (/home/guix/dev/my-smart-contracts/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (/home/guix/dev/my-smart-contracts/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

**Comment by eggplantzzz** [comment] 2019-11-18 19:07
Hey @guix77, two things that come to mind:
 - try logging the url that you are creating exactly as it is written to confirm that it is indeed the url that you want to use
 - try making the value of provider a function that returns the created provider

In some cases not having the provider be a function causes issues (though I forget exactly what the conditions are!). So your network config should look something like 
```
  ropsten: {
    provider: function() {
      return new HDWalletProvider(....blah blah....);
    },
    network_id: 3,
    etc.....
```

Let me know if you have any success!

**Comment by pepihasenfuss** [comment] 2019-12-09 08:36
I did get the same error message and switched my web3.js dapp towards v3 while generating a fresh API-ID. Then it worked for me. BTW, I did slow down the firing of requests towards Infura. It also helped. It seems that Infura load-balancing or some sort of middleware takes a bit of time between different calls. After a deployment of a contract, e.g., I really need to wait a bit (for confirmations) before I can access the contract and fire read/get calls. A locally running node is always more responsive and produces less error messages.

**Comment by gnidan** [comment] 2020-01-15 18:59
Thanks for the confirmation @pepihasenfuss that v3+fresh ID works.

I'll leave this open because it sounds like there's documentation to improve on our side. Can others confirm that @pepihasenfuss's fix works?

Would love this to stop being a source of confusion.

**Comment by lsqproduction** [comment] 2023-01-12 19:03
Closing for issue maintenance. It's been fixed in the Truffle boilerplate projects as well as the Truffle suite website.

**Closed** 2023-01-12 19:04 UTC
Labels: help wanted, Docs, needs investigated, good first issue, priority3 🔧
