### ISSUE TITLE
Upgrade solc to v0.4.21 

### ISSUE THREAD

**Issue by gfijrb** [trufflesuite/truffle#870] opened 2018-03-26 13:15 UTC
Hi please how can I connect **solcjs** manually for truffle or when you update it for **0.4.21**?
```
$ truffle compile
Error parsing C:\Users\user\Desktop\truffle test\contracts\token.sol: ParsedContract.sol:57:31: ParserError: Expected token Semicolon got 'LParen'
        emit NewPotentialOwner(owner, _new);
                              ^
Compilation failed. See above.

```

**Comment by cgewecke** [comment] 2018-03-26 14:40
@gfijrb We're planning to publish a patch release early this week which includes a solc upgrade. At the moment the only way to manually change the solcjs version in your local environment is to install `truffle-core` and manipulate its dependencies yourself. Making the compiler versioning more flexible is on our near-term roadmap though. 

Closing as duplicate of [truffle-compile 50](https://github.com/trufflesuite/truffle-compile/issues/50)

**Closed by cgewecke** 2018-03-26 14:40 UTC
