### ISSUE TITLE
Installation Error due outdated dependencies

### ISSUE THREAD

**Issue by hushino** [trufflesuite/truffle#4704] opened 2022-02-08 02:22 UTC
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

npm install -g truffle fail cause node-gyp
https://www.npmjs.com/package/keccak
have node-gyp version 5 and is incompatible in w10 
Path: ganache\node_modules\keccak

## Steps to Reproduce

npm install -g truffle

## Environment

* Operating System: windows 10.0.19044.1503, visual studio 2022 v17.0.5, vs build tools 2019 v16.11.9
* Truffle version (`5.4.32`):
* node version (`v16.13.2`):
* npm version (`8.3.0`):

**Comment by eggplantzzz** [comment] 2022-02-08 19:26
Try downgrading to npm 6, Truffle is not yet compatible with npm 8.

**Comment by MicaiahReid** [comment] 2022-02-16 18:37
Closing as duplicate of #4702

**Closed by MicaiahReid** 2022-02-16 18:37 UTC
