### ISSUE TITLE
Truffle should work when filename does not match contract name, example from the docs

### ISSUE THREAD

**Issue by debris** [trufflesuite/truffle#552] opened 2017-09-01 11:05 UTC
## Issue

According to `Getting started` guide, the name of the contract does not have to match filename.

> The name specified does not have to match the filename of your contract source files

It does not work for me

## Steps to Reproduce

Follow the steps described in [the docs](http://truffleframework.com/docs/getting_started/migrations#artifacts-require-)

```
truffle init
```

create file `./contracts/Contracts.sol`

source:

```
contract ContractOne {
}

contract ContractTwo {
}
```

run:

```
truffle test
```

## Expected Behavior

All tests should pass.

## Actual Results

tests fail with

```

  TestMetacoin
    1) "before all" hook: prepare suite

  Contract: MetaCoin
    ✓ should put 10000 MetaCoin in the first account (39ms)
    ✓ should call a function that depends on a linked library (75ms)
    ✓ should send coin correctly (153ms)


  3 passing (613ms)
  1 failing

  1) TestMetacoin "before all" hook: prepare suite:
     Error: Could not find artifacts for /Users/marek/projects/ethcore/bridge/truffle/contracts/Contracts.sol from any sources
      at Resolver.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:49072:9)
      at TestResolver.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:89733:30)
      at TestResolver.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:89733:30)
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:214313:49
      at Array.forEach (native)
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:214312:24
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:218209:15
      at process._tickCallback (internal/process/next_tick.js:103:7)

```

## Environment

* Operating System: `macOS Sierra 10.12.6`
* Truffle version: `Truffle v3.4.9`
* Ethereum client: `testrpc`
* node version: `v7.4.0`
* npm version: `5.0.4`

**Comment by tcoulter** [comment] 2017-09-19 16:08
Hi there. 

The correct way to get the artifacts for each individual contract is like this:

```
var ContracOne = artifacts.require("ContractOne");
var ContractTwo = artifacts.require("ContractTwo");
```

Note the `.sol` extension isn't needed (especially in this case, since there are multiple contracts in each file).

Thanks for the ticket. Will use this to beef up our documentation.

Cheers!

**Comment by debris** [comment] 2017-09-21 11:05
hi @tcoulter !

This issue is not related with loading artifacts for js tests. It's about a bug in default solidity tests loader. The bug is somehow related with loading .sol files containing multiple tests by a default test .sol file.

If I remove default .sol tests, everything works fine.

**Comment by t4t5** [comment] 2017-10-19 07:37
Stumbled upon this bug as well. Seems like it makes it impossible to test multiple contracts that are in the same file through Solidity tests.

**Comment by bmmpxf** [comment] 2017-11-03 19:31
PR for docs update: https://github.com/trufflesuite/trufflesuite.com/pull/10

This should hopefully clear up the confusion.

**Comment by debris** [comment] 2017-11-08 10:35
@bmmpxf the pr for the docs is totally unrelated. Please look at 'steps to reproduce' again.

**Comment by tcoulter** [comment] 2017-11-08 18:02
Looks like there might be a different issue here, but we'll need to investigate. Would also be great to get more information.

@t4t5 @debris Did you add an `artifacts.require()` statement in any of your tests related to Contracts.sol, ContractOne or ContractTwo?

**Comment by debris** [comment] 2017-11-08 18:09
> Did you add an artifacts.require() statement in any of your tests related to Contracts.sol, ContractOne or ContractTwo?

No ;)

**Comment by Asone** [comment] 2018-01-25 21:54
Any news on this ? I just managed to have the same problem. I'll post my code and config tomorrow to see if it can help

**Comment by alexaltair** [comment] 2018-01-30 04:19
I ran into this problem as well, with truffle `v4.0.5`. I have a contract called `Foos` in a file called `Foo.sol`. If my migration used any of the following lines, it fails;
* `var Foo = artifacts.require("./Foo.sol");` (despite it working for `./Migrations.sol`)
* `var Foo = artifacts.require("Foo.sol");`
* `var Foo = artifacts.require("Foo");`

and if I changed it to `var Foo = artifacts.require("Foos");` it worked.

**Comment by kktam** [comment] 2018-04-20 22:02
> truffle migrate 

also have the same issue. there was an older YouTube that shows this used to work with Solidity 0.4.11 where the name of the contracts does not match the file [Youtube look at time 21:28 (min:sec)](https://www.youtube.com/watch?v=3681ZYbDSSk), and you will see the demo show truffle migrate can do this.

Instead when I tried it I go the following error:

```
/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:37
  throw new Error("Could not find artifacts for " + import_path + " from any sources");
^
Error: Could not find artifacts for ./Elections from any sources
    at Resolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:37:1)
    at Object.require (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-migrate/index.js:234:1)
    at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-migrate/resolverintercept.js:20:1)
    at /Users/nelsontam/Documents/Work/blockchain/election/migrations/2_deploy_contracts.js:1:26
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-require/require.js:97:1
    at tryToString (fs.js:456:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
```

**Comment by toledoal** [comment] 2018-04-23 20:41
This happened to me as well. It appears that the contract name "must" match the variable name on import/export (because is the object you are actually importing): 

_YourContractFileName.sol_
`pragma solidity ^0.4.4;

contract **ContractName** {
    string public candidate = "Any Name";
    constructor () public {
    }
    function GetMessage() public returns (string) { 
    return candidate;
  }
}`

_Your migration file_
`var **ContractName** = artifacts.require("./YourContractFileName");

module.exports = function(deployer) {
  deployer.deploy(**ContractName**);
};`

**Comment by psyshe** [comment] 2018-05-15 11:25
Have related issue with:

1_initial_migration.js

```
const DMT = artifacts.require("Token");
const DemoCrowdsale = artifacts.require("Crowdsale");

module.exports = function(deployer) {
  deployer.deploy(Token)
    .then(function() {
      return deployer.deploy(Crowdsale);
        });
};
```

truffle.js

```
networks: {
  ropsten: {
    provider: function() {
      return new HDWalletProvider(mnemonic, providerUrl);
    },
    network_id: '3',
    gas: 4512388
  }
```

As result of execution all contracts deployed but:

```
Running migration: 1_initial_migration.js
  Deploying Token...
  ... 0x
  Token: 0x
  Deploying Crowdsale...
  ... 0x
  Crowdsale: 0x
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Could not find artifacts for ./Migrations from any sources
    at Resolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:37:1)
    at Object.require (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-migrate/index.js:234:1)
    at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-migrate/resolverintercept.js:20:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-migrate/index.js:49:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

There is no folder /usr/local/lib/node_modules/truffle/build/webpack nor ~/truffle-resolver .

Anyone knows what a hell is that and why it still looks for ./Mgrations.sol and where I can remove it?
Already removed any './Migrations.sol' and related stuff from machine and folders.

**Comment by eggplantzzz** [comment] 2018-11-02 11:30
I attempted to duplicate this on the most recent version of truffle and could not do so.  Is this still a problem?  If not I will close this issue in a few days.

**Comment by kyriediculous** [comment] 2018-11-09 16:08
This is still a problem in 4.1.14 yes.

**Comment by eggplantzzz** [comment] 2019-01-09 17:12
I would upgrade to version 5 as that is the newest stable version of Truffle. As far as I can tell this issue does not exist there but let me know if you encounter problems!
https://github.com/trufflesuite/truffle/releases/tag/v5.0.1

**Comment by CruzMolina** [comment] 2019-04-09 22:24
Closing since this no longer appears to be an issue on the latest version of truffle (#1878). Happy to reopen if it still is!

**Closed by CruzMolina** 2019-04-09 22:24 UTC

**Comment by PochenriederAlex** [comment] 2019-08-05 16:24
Happening to me on v5.0.25

**Comment by CruzMolina** [comment] 2019-08-06 01:59
@PochenriederAlex can you provide reproducible steps?

**Comment by williamrobertbush** [comment] 2021-03-17 19:18
Am I running into this issue right now? I read that node v14 won't migrate with truffle and reproduce multiple contracts. It seems the issue has come back. 

truffle migrate --reset

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'ganache'
> Network id:      5777
> Block gas limit: 6721975 (0x6691b7)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0xd2b2ef0b3a02d8190ee2ab14d8ba9a2fe927a28b61a8c897d6aac3a1814baa23
   > Blocks: 0            Seconds: 0
   > contract address:    0xc1Eb6BF501865B83b029bD642DAEd2Dd6bB49440
   > block number:        49
   > block timestamp:     1616008635
   > account:             0x5F2E1C47C1e80De7F08a1bbB7aBf4dec40c28eeE
   > balance:             99.86837952
   > gas used:            191943 (0x2edc7)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00383886 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00383886 ETH


2_deployed_contract.js
======================

/usr/local/lib/node_modules/truffle/build/459.bundled.js:25222
        throw new Error("Could not find artifacts for " + import_path + " from any sources");
        ^

Error: Could not find artifacts for MoneyZilla from any sources
    at Resolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:61:1)
    at Object.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:172:1)
    at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/ResolverIntercept.js:22:1)
    at /Users/williambush/money_zilla/migrations/2_deployed_contract.js:1:30
    at Script.runInContext (vm.js:143:18)
    at Script.runInNewContext (vm.js:148:17)
    at Object.file (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:94:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:49:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:212:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:263:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:228:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
Truffle v5.2.4 (core: 5.2.4)
Node v14.16.0

**Comment by williamrobertbush** [comment] 2021-03-17 19:18
Am I running into this issue right now? I read that node v14 won't migrate with truffle and reproduce multiple contracts. It seems the issue has come back.



`truffle migrate --reset

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'ganache'
> Network id:      5777
> Block gas limit: 6721975 (0x6691b7)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0xd2b2ef0b3a02d8190ee2ab14d8ba9a2fe927a28b61a8c897d6aac3a1814baa23
   > Blocks: 0            Seconds: 0
   > contract address:    0xc1Eb6BF501865B83b029bD642DAEd2Dd6bB49440
   > block number:        49
   > block timestamp:     1616008635
   > account:             0x5F2E1C47C1e80De7F08a1bbB7aBf4dec40c28eeE
   > balance:             99.86837952
   > gas used:            191943 (0x2edc7)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00383886 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00383886 ETH


2_deployed_contract.js
======================

/usr/local/lib/node_modules/truffle/build/459.bundled.js:25222
        throw new Error("Could not find artifacts for " + import_path + " from any sources");
        ^

Error: Could not find artifacts for MoneyZilla from any sources
    at Resolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:61:1)
    at Object.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:172:1)
    at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/ResolverIntercept.js:22:1)
    at /Users/williambush/money_zilla/migrations/2_deployed_contract.js:1:30
    at Script.runInContext (vm.js:143:18)
    at Script.runInNewContext (vm.js:148:17)
    at Object.file (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:94:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:49:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:212:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:263:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:228:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
Truffle v5.2.4 (core: 5.2.4)
Node v14.16.0
`
