### ISSUE TITLE
JSON files not properly generated under contracts folder

### ISSUE THREAD

**Issue by eloudsa** [trufflesuite/truffle#706] opened 2017-12-06 22:12 UTC
Hello

I'm using Truffle Develop to compile and to test my contract.
I've notice strange behaviour when I interact with my contract from the console.

For example, if I call a constant function, the output is not the one expected or an error:
`Error: Invalid number of arguments to Solidity function`

It's weird because I have compile the contract using the command:
truffle(develop)> migrate --reset --compile-all

The only solution I found is to remove the contracts folder and to rebuild the contract.

Is there a proper way to reset the JSON files from the contracts folder?

## Environment

* Operating System: macOS High Sierra 
* Truffle version: 4.0.1

Said

**Comment by inflector** [comment] 2017-12-10 01:14
I have encountered this problem two times in the last couple of days. Can't pin down the cause yet. Next time I have it I will package up the contracts and build folders for the devs...

**Comment by gnidan** [comment] 2017-12-21 01:55
Hello all, a bug that caused this problem has been fixed in v4.0.4.

Please upgrade and let us know if the problem persists for you! Thank you!

(Release notes: https://github.com/trufflesuite/truffle/releases/tag/v4.0.4)

**Comment by cgewecke** [comment] 2018-04-07 01:52
@eloudsa We think this has been fixed in `4.1.5`. Closing for housekeeping but please re-open if you see this again.  Thanks for reporting!

**Closed by cgewecke** 2018-04-07 01:52 UTC
