### ISSUE TITLE
Reference Error - not defined (develop console)

### ISSUE THREAD

**Issue by salmanahmad3333** [trufflesuite/truffle#1393] opened 2018-10-30 19:41 UTC
I've asked for help in the Truffle Gitter before filing this issue.

truffle(development)> Election.deployed().then(function(instance) { app = instance })
ReferenceError: Election is not defined
truffle(development)> app.address
ReferenceError: app is not defined

Not sure why I'm receiving reference errors. 

Here is the previous issue link which is closed. 
https://github.com/trufflesuite/truffle/issues/943#issuecomment-391326824

Environment
Operating System: Windows 10

Please Help

**Comment by fainashalts** [comment] 2018-11-01 17:30
Hello, thanks for reaching out! I am not able to reproduce this issue. Without any code to look at it's a difficult to figure out why you are getting this error. 

On first glance, I wonder if you have required your Election contract appropriately. It may help to try this out with a Truffle box so you can see how all the pieces are supposed to work. Perhaps try truffle unbox metacoin in a separate empty directory and look at how metacoin is required, etc. 

I'm going to close this issue as I cannot to reproduce it, but if you are unable to resolve it or would like to provide more information, feel free to open a new issue in the future.

**Closed by fainashalts** 2018-11-01 17:30 UTC
