### ISSUE TITLE
Truffle Debug: TypeError: Cannot read property 'sourcePath' of undefined

### ISSUE THREAD

**Issue by jleeh** [trufflesuite/truffle#1051] opened 2018-06-21 10:20 UTC
### Environment
- OS: W10 Pro 1803
- Truffle v4.1.12 (core: 4.1.12)
- Solidity v0.4.24 (solc-js)
- Ganache CLI v6.1.3 (ganache-core: 2.1.2)
- NodeJS v8.9.3

### Issue
Every time I try to debug a tx, I get the following:
```
-> truffle debug 0x703ae6c18730a773f16b289b5277305eee9eb9441c371cf403137e9268c61402

Compiling ./contracts/ERC20.sol...
Compiling ./contracts/ERC20Basic.sol...
Compiling ./contracts/ERC677.sol...
Compiling ./contracts/LinkPool.sol...
Compiling ./contracts/LinkToken.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/Node.sol...
Compiling ./contracts/NodeFactory.sol...
Compiling ./contracts/NodeStaking.sol...
Compiling ./contracts/Ownable.sol...
Compiling ./contracts/PoolOwners.sol...
Compiling ./contracts/PoolStorage.sol...
Compiling ./contracts/PoolStorageFactory.sol...
Compiling ./contracts/SafeMath.sol...
Compiling ./contracts/interface/NodeArithmeticInterface.sol...
Compiling ./contracts/interface/NodeFactoryInterface.sol...
Compiling ./contracts/interface/NodeInterface.sol...
Compiling ./contracts/interface/PoolStorageFactoryInterface.sol...
Compiling ./contracts/interface/PoolStorageInterface.sol...
Compiling ./contracts/lib/NodeArithmetic.sol...

Gathering transaction data...

redux-saga error: uncaught at session.saga
at session.saga
 TypeError: Cannot read property 'sourcePath' of undefined
    at recordSources$ (/usr/lib/node_modules/truffle/build/webpack:/.-debugger/dist/debugger.js:3734:1)
    at tryCatch (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/regenerator-runtime/runtime.js:62:15)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/regenerator-runtime/runtime.js:296:1)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/regenerator-runtime/runtime.js:114:1)
    at tryCatch (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/regenerator-runtime/runtime.js:62:15)
    at maybeInvokeDelegate (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/regenerator-runtime/runtime.js:358:1)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/regenerator-runtime/runtime.js:270:1)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/regenerator-runtime/runtime.js:114:1)
    at next (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/redux-saga/es/internal/proc.js:311:1)
    at currCb (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/redux-saga/es/internal/proc.js:388:1)
    at /usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/redux-saga/es/internal/proc.js:499:1
    at exec (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/redux-saga/es/internal/scheduler.js:19:1)
    at flush (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/redux-saga/es/internal/scheduler.js:60:1)
    at asap (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/redux-saga/es/internal/scheduler.js:33:1)
    at Array.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/redux-saga/es/internal/channel.js:185:1)
    at Object.emit (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/redux-saga/es/internal/channel.js:26:1)
    at Object.dispatch (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/redux-saga/es/internal/middleware.js:67:1)
    at new Session (/usr/lib/node_modules/truffle/build/webpack:/.-debugger/dist/debugger.js:2887:1)
    at Function._callee$ (/usr/lib/node_modules/truffle/build/webpack:/.-debugger/dist/debugger.js:2712:1)
    at tryCatch (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/regenerator-runtime/runtime.js:62:15)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/regenerator-runtime/runtime.js:296:1)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/truffle/build/webpack:/Users/gnidan/src/work/truffle/~/regenerator-runtime/runtime.js:114:1)
```
Notice the path of `/Users/gnidan/` being referenced many times in the stacktrace, that doesn't exist on my system and can only think it refers to @gnidan.

### Additional Information
This only started occurring once I updated the dependencies, latest version of truffle/ganache-cli and our dev deps. I could rectify this issue by downgrading to truffle version that was sub `4.1.3` or so, but now when I downgrade, I always get different debugging errors.

Our package.json deps:
```
"devDependencies": {
    "ascii-art": "^1.4.2",
    "autoprefixer": "6.5.1",
    "babel-core": "6.17.0",
    "babel-eslint": "7.1.1",
    "babel-jest": "17.0.2",
    "babel-loader": "6.2.7",
    "babel-preset-react-app": "^2.0.1",
    "case-sensitive-paths-webpack-plugin": "1.1.4",
    "chalk": "1.1.3",
    "connect-history-api-fallback": "1.3.0",
    "cross-spawn": "4.0.2",
    "css-loader": "0.26.0",
    "detect-port": "1.0.1",
    "dotenv": "2.0.0",
    "eslint": "3.8.1",
    "eslint-config-react-app": "^0.5.0",
    "eslint-loader": "1.6.0",
    "eslint-plugin-flowtype": "2.21.0",
    "eslint-plugin-import": "2.0.1",
    "eslint-plugin-jsx-a11y": "2.2.3",
    "eslint-plugin-react": "6.4.1",
    "extract-text-webpack-plugin": "1.0.1",
    "file-loader": "0.9.0",
    "filesize": "3.3.0",
    "fs-extra": "0.30.0",
    "gzip-size": "3.0.0",
    "html-webpack-plugin": "2.24.0",
    "http-proxy-middleware": "0.17.2",
    "jest": "18.1.0",
    "json-loader": "0.5.4",
    "object-assign": "4.1.0",
    "path-exists": "2.1.0",
    "postcss-loader": "1.0.0",
    "promise": "7.1.1",
    "react-dev-utils": "^0.4.2",
    "recursive-readdir": "2.1.0",
    "strip-ansi": "3.0.1",
    "style-loader": "0.13.1",
    "truffle-contract": "^1.1.8",
    "truffle-solidity-loader": "0.0.8",
    "url-loader": "0.5.7",
    "web3-utils": "^1.0.0-beta.26",
    "webpack": "1.14.0",
    "webpack-dev-server": "1.16.2",
    "webpack-manifest-plugin": "1.1.0",
    "whatwg-fetch": "1.0.0",
    "simple-line-icons": "^2.4.1"
  },
  "dependencies": {
    "bootstrap": "^3.3.7",
    "dotenv": "^2.0.0",
    "es6-promise": "^4.2.2",
    "isomorphic-fetch": "^2.2.1",
    "lodash": "^4.17.4",
    "node-waves": "^0.7.6",
    "prop-types": "^15.6.1",
    "react": "^15.4.2",
    "react-bootstrap": "^0.32.1",
    "react-dom": "^15.4.2",
    "react-highcharts": "^16.0.2",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-table": "^6.8.5",
    "truffle-debug-utils": "^1.0.0",
    "truffle-debugger": "^1.1.0",
    "web3": "^1.0.0-beta.27",
    "zeppelin-solidity": "^1.3.0"
  }
```

I've looked at similar issues online and I've tried actions such as deleting the build folder, running migrate with `truffle migrate --reset --compile-all` and none of has fixed the issue or changed the error.

**Comment by cgewecke** [comment] 2018-06-23 21:43
Hi @jleeh thanks for reporting this. It looks like something went wrong with our webpack build in the most recent release - we'll be patching it shortly. Will ping you here when that's fixed.

**Comment by cgewecke** [comment] 2018-06-27 18:56
@jleeh. This should be fixed in `4.1.13`. Please ping if you continue to see it.

**Comment by jleeh** [comment] 2018-06-28 11:01
I've updated truffle to 4.1.3, debugger is at 4.0.2 and I'm getting a different, but similar error (looks same as #998):
```
redux-saga error: uncaught at session.saga
at session.saga
 TypeError: Cannot destructure property `sourcePath` of 'undefined' or 'null'.
    at recordSources (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:3445:36)
    at recordSources.next (<anonymous>)
    at session.saga (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:3370:1)
    at saga.next (<anonymous>)
    at next (/usr/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:311:1)
    at currCb (/usr/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:499:1
    at exec (/usr/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/scheduler.js:19:1)
    at flush (/usr/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/scheduler.js:60:1)
    at asap (/usr/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/scheduler.js:33:1)
    at Array.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/channel.js:185:1)
    at Object.emit (/usr/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/channel.js:26:1)
    at Object.dispatch (/usr/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/middleware.js:67:1)
    at new Session (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:2157:1)
    at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:2007:1
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/truffle/build/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:35:1
    at new Promise (<anonymous>)
    at new F (/usr/lib/node_modules/truffle/build/webpack:/~/core-js/library/modules/_export.js:36:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:14:1
    at Function.forTx (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:2016:6)
    at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/debug.js:69:1
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
Is there any quick hack I could do to get this to work? Not sure if it's anything to do with my local setup? I thought it could be related to having truffle installed globally and truffle-debugger not. I installed truffle in the package scope with debugger and got the same.

**Comment by cgewecke** [comment] 2018-06-28 14:46
Thanks @jleeh - re-opening. This is also being reported (for Windows) in #998 where the example being used appears to be the Fibonacci number tutorial. 

For additional context: On my machine if I:
+ unbox MetaCoin 
+ delete the solidity test so that there is only one contract suite
+ launch ganache-cli in a separate terminal tab
+ `truffle test`
+ pull the transaction hash from the last recorded tx in the ganache-cli output

The debugger launches successfully:

```
Users-MacBook-Air:metacoin cgewecke$ sudo npm install -g truffle
/usr/local/bin/truffle -> /usr/local/lib/node_modules/truffle/build/cli.bundled.js
+ truffle@4.1.13
added 81 packages in 2.857s
Users-MacBook-Air:metacoin cgewecke$ truffle test
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...


  Contract: MetaCoin
    ✓ should put 10000 MetaCoin in the first account
    ✓ should call a function that depends on a linked library (50ms)
    ✓ should send coin correctly (111ms)


  3 passing (211ms)

Users-MacBook-Air:metacoin cgewecke$ truffle debug 0x4c5f6cfb01d2912f892e1953e846d1aae41a8b955edd776a9ed4ef389d67ecd8
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...

Gathering transaction data...

Addresses affected:
 0xa0777e0f14e85f2b069929246dc8b793d3039c5c - MetaCoin

Commands:
(enter) last command entered (step next)
(o) step over, (i) step into, (u) step out, (n) step next
(;) step instruction, (p) print instruction, (h) print this help, (q) quit
(b) toggle breakpoint, (c) continue until breakpoint
(+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
(?) list existing watch expressions
(v) print variables and values, (:) evaluate expression - see `v`


MetaCoin.sol:

 8: // token, see: https://github.com/ConsenSys/Tokens. Cheers!
 9: 
10: contract MetaCoin {
    ^^^^^^^^^^^^^^^^^^^

debug(development:0x4c5f6cfb...)> 
```

cc: @gnidan

**Comment by RobertoC27** [comment] 2018-06-28 15:01
@cgewecke Fibonacci example was indeed what i tried debugging, did a `truffle init` on a clean folder, then `npm init` (because i'm working with `truffle@next` and copied contract code into a new file. Added a migration file, ran `truffle console` then `compile` and finally `migrate`. Last step was entering the debugger which resulted in #998

**Comment by HarryR** [comment] 2018-07-03 12:31
I'm having the same problem on Linux with Truffle v4.1.13, it means that I can't debug any transactions.

I started doing some debugging by editing the `cli.bundled.js` file directly, in `recordSources` I output `sources`, then for each item I output the `_ref2` variable (see cli.bundled.js:200413):

It turns out the problem was caused by my `std/ERC20.sol` interface. When the file is an interface the `sources` variable ends up with an `undefined` entry in the list instead of the JSON data for it.

I added something to skip the the `undefined` item and now debugging works again.

@cgewecke  The problem is with `interface` being used instead of `contract` - after making the small hack debugging now works. If you use the same hack (skipping undefined items) then that should fix the problem - or - a better fix would be working out why an undefined item ends up in the list as a the result of an `interface` being used.

**Comment by jleeh** [comment] 2018-07-03 14:24
Just tried that @HarryR and it got further as I saw a `debug_traceTransaction`, but got a different error:
```
redux-saga error: uncaught at session.saga
at session.saga
 at recordInstance
 TypeError: Cannot destructure property `context` of 'undefined' or 'null'.
    at Object.addInstance (/mnt/d/dev-gitlab/staking-dapp/node_modules/truffle-debugger/dist/lib/evm/sagas/index.js:35:1)
    at addInstance.next (<anonymous>)
    at recordInstance (/mnt/d/dev-gitlab/staking-dapp/node_modules/truffle-debugger/dist/lib/session/sagas/index.js:121:1)
    at recordInstance.next (<anonymous>)
    at next (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:322:27)
    at currCb (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:399:7)
    at runSelectEffect (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:710:7)
    at runEffect (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:446:761)
    at next (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:326:9)
    at proc (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:281:3)
    at resolveIterator (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:467:5)
    at runCallEffect (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:528:98)
    at runEffect (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:446:402)
    at /mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:655:14
    at Array.forEach (<anonymous>)
    at runAllEffect (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:654:10)
    at runEffect (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:446:249)
    at next (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:326:9)
    at currCb (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:399:7)
    at checkEffectEnd (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:623:9)
    at chCbAtKey (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:638:11)
    at Object.currCb [as cb] (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:399:7)
    at /mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:369:16
    at Array.forEach (<anonymous>)
    at end (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:368:18)
    at Object.task.cont (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:110:11)
    at next (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:332:35)
    at currCb (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:399:7)
    at takeCb (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/proc.js:477:108)
    at Object.put (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/channel.js:85:16)
    at /mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/channel.js:173:10
    at Array.<anonymous> (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/channel.js:194:9)
    at Object.emit (/mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/channel.js:38:13)
    at /mnt/d/dev-gitlab/staking-dapp/node_modules/redux-saga/lib/internal/middleware.js:73:21
```

I did the same thing as you mentioned and dumped the sources from the debugger, and there was 3 undefined entries at the top. After cross checking what was included and wasn't, it was the bang same as you:
- ERC677.sol
- ERC20.sol
- ERC20Basic.sol

I have interfaces in my own contracts and they're completely fine. I can't see any difference between the token contracts and my own that'd cause anything like this.

**Comment by jleeh** [comment] 2018-07-03 14:49
I've fixed my own issue! 

Weirdly, the `sourcePath` being undefined was completely fixed when I moved the ERC contracts into a std folder, deleted build and migrated them again. Proved this as I left the console output of the sources, and the 3 entries I had at the top had gone, with ERC 20, Basic and 677 appearing in the list.

Although like @HarryR said, when I dumped the contexts there were no binaries for any of the Interfaces, including my own. 

For it to work after I got the above error, I edited `debugger.js` at line 4523 and performed a check to see if the binary was empty (0x0). As when it was doing a binary search it was returning nothing. So the `addInstance` method in my `debugger.js` now looks like this:
```js
function* addInstance(address, binary) {
  let search = yield (0, _effects.select)(_selectors2.default.info.binaries.search);
  if (binary != "0x0") {
   let { context } = search(binary);

    yield (0, _effects.put)(actions.addInstance(address, context, binary));

    return context;
  }
}
```

Now:
```
LinkPool.sol:

 8: import "./interface/NodeFactoryInterface.sol";
 9:
10: contract LinkPool is Ownable {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

debug(development:0x9bba8f3f...)>
```
🎉

**Comment by gnidan** [comment] 2018-07-03 17:18
@jleeh want to open a PR with that change here: https://github.com/trufflesuite/truffle/blob/develop/packages/truffle-debugger/lib/evm/sagas/index.js#L28?

Thanks for finding that! I'm happy to do the change myself, but figured you should get credit :)

**Comment by timothywangdev** [comment] 2018-07-03 19:16
same

**Comment by dshm** [comment] 2018-07-25 09:17
I have same issue

**Comment by Chippi** [comment] 2018-09-20 11:46
same error in truffle@5.0.0-beta.0. pls fix

**Comment by stevenleeg** [comment] 2018-11-20 22:15
Seeing the same issue on 4.1.14. Any updates here?

**Comment by hadarbmdev** [comment] 2018-11-21 11:33
Same issue here. Truffle v5.0.0-beta.1 Solidity v0.4.25 Ganache v1.2.2

**Comment by trifist** [comment] 2019-01-04 03:33
similar issue here, truffle v5.0.1

![image](https://user-images.githubusercontent.com/22070288/50672588-12a98280-1014-11e9-95ce-428a2b3322ac.png)

**Comment by jleeh** [comment] 2019-01-07 13:30
I recently reset my main dev machine and started seeing the same issue with our projects locally installed truffle, although the globally installed truffle was fine.

Project local truffle (seeing debugger issue):
```
> ./node_modules/.bin/truffle version
Truffle (unbundled) (core: 4.1.15)
Solidity v0.4.24 (solc-js)
```

Global truffle (worked):
```
> truffle version
Truffle v4.1.15 (core: 4.1.15)
Solidity v0.4.25 (solc-js)
```

In our `package.json`, I then seen we was including specific truffle deps which caused the truffle version to be unbundled:
```
"truffle": "^4.1.14",
"truffle-contract": "^1.1.8",
"truffle-debug-utils": "^1.0.6",
"truffle-debugger": "^4.0.2",
```

I changed that to just:
```
"truffle": "^4.1.15"
```
Re-ran install then got:
```
> ./node_modules/.bin/truffle version
Truffle v4.1.15 (core: 4.1.15)
Solidity v0.4.25 (solc-js
```

Then re-ran ran the debugger and it was all good:
```
Gathering transaction data...

Addresses affected:
 0x2612af3a521c2df9eaf28422ca335b04adf3ac66 - NodeStaking
 0xdf9fd2e8cf22f173168f320172bbbb29f6d6b011 - PoolStorage
 0xca24282be001a428d27fdac4676561c2eb1de393 - PoolStorage
 0x9b1f7f645351af3631a656421ed2e40f2802e6c0 - PoolOwners
 0xcfeb869f69431e42cdb54a4f4f105c19c080a601 - LinkToken

Commands:
(enter) last command entered (step next)
(o) step over, (i) step into, (u) step out, (n) step next
(;) step instruction, (p) print instruction, (h) print this help, (q) quit
(b) toggle breakpoint, (c) continue until breakpoint
(+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
(?) list existing watch expressions
(v) print variables and values, (:) evaluate expression - see `v`


LinkToken.sol:

217: }
218:
219: contract LinkToken is StandardToken, ERC677Token {
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

debug(development:0x10bd84b0...)>
```

So if you see your truffle version as `unbundled`, remove any extra truffle deps in your package.json, or any extra deps that are globally installed and that should fix it.

**Comment by gnidan** [comment] 2019-01-16 18:51
Looks like this issue specifically is fine on v4.1.15? Closing for issue maintenance. If you run into the specific problem of `sourcePath` being undefined, let us know and we'll re-open and investigate. Thanks a bunch!

**Closed by gnidan** 2019-01-16 18:51 UTC
Labels: Debugger
