### ISSUE TITLE
truffle unbox failed

### ISSUE THREAD

**Issue by RunHippo** [trufflesuite/truffle#4152] opened 2021-06-30 06:13 UTC
- The Problem
truffle unbox webpack

```
This directory is non-empty...
? Proceed anyway? (Y/n) 
Starting unbox...
=================

? Proceed anyway? Yes
✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
Error: Error connecting to github.com. Please check your internet connection and try again.
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:45:1
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:6:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```
Local Environment

```
Truffle v5.3.13 (core: 5.3.13)
Node v14.16.0
```

**Comment by yipu0v0** [comment] 2021-06-30 15:21
Same
```
> truffle unbox pet-shop

Starting unbox...
=================
✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
Error: Error connecting to github.com. Please check your internet connection and try again.
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:45:1
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:6:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Truffle v5.3.13 (core: 5.3.13)
Node v14.16.1
```

And connection to github.com works well using `wget github.com`.

Using proxy or not does not effect the result.

**Comment by cds-amal** [comment] 2021-06-30 18:05
Hi @RunHippo,

We were unable to reproduce this. Though we have seen it when we simulate network connection issues. Could it be an internet issue on your side?

**Comment by yipu0v0** [comment] 2021-07-01 08:45
[](url)
![屏幕快照 2021-07-01 下午4 39 25](https://user-images.githubusercontent.com/5365604/124094114-0c80a980-da8b-11eb-9685-e1fd2e5b4454.png)
I think the output of error omit necessary key information. URL and error should be printed, not just `Error connecting to github.com`. Actually I can connect to github.com in my terminal.

**Comment by cds-amal** [comment] 2021-07-01 09:45
That's a good suggestion @yipu0v0 ! I'll update the output. The following command might help trace down the issue.
```console
 $ DEBUG=unbox truffle unbox pet-shop ps   
```
When I test the command I get the following output
```
 $ DEBUG=unbox truffle unbox pet-shop ps
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.
  unbox { in: 'pet-shop',
  unbox   out: 'https://github.com:truffle-box/pet-shop-box' } +0ms

Starting unbox...
=================

✔ Preparing to download box
✔ Downloading
npm WARN pet-shop@1.0.0 No description
npm WARN pet-shop@1.0.0 No repository field.

✔ Cleaning up temporary files
✔ Setting up box

Unbox successful, sweet!

Commands:

  Compile:        truffle compile
  Migrate:        truffle migrate
  Test contracts: truffle test
  Run dev server: npm run dev
  ```

**Comment by LIYANG-UST** [comment] 2021-07-05 13:22
I still have the same error. But I can use git clone to get the project.
![image](https://user-images.githubusercontent.com/42539774/124477838-11b95d80-ddd7-11eb-9e7d-97b9f6e19480.png)

**Comment by yipu0v0** [comment] 2021-07-06 16:25
```
➜  crypto DEBUG=unbox truffle unbox pet-shop ps
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.
  unbox { in: 'pet-shop', out: 'https://github.com:truffle-box/pet-shop-box' } +0ms

Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
Error: Error connecting to github.com. Please check your internet connection and try again.
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:45:1
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:6:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Truffle v5.3.13 (core: 5.3.13)
Node v14.16.1
```

**Comment by haltman-at** [comment] 2021-07-09 21:44
Going to close this now that #4169 is released.  Feel free to open a new issue if there's still a problem.

**Comment by jwzh222** [comment] 2021-09-18 02:56
same issue with truffle unbox on ubuntu and win10

Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
Error: Error connecting to https://raw.githubusercontent.com/truffle-box/Metacoin-box/master/truffle-box.json. Please check your internet connection and try again.

Request failed with status code 503
    at createError (/home/linuxbrew/.linuxbrew/lib/node_modules/truffle/build/webpack:/node_modules/axios/lib/core/createError.js:16:1)
    at settle (/home/linuxbrew/.linuxbrew/lib/node_modules/truffle/build/webpack:/node_modules/axios/lib/core/settle.js:17:1)
    at IncomingMessage.handleStreamEnd (/home/linuxbrew/.linuxbrew/lib/node_modules/truffle/build/webpack:/node_modules/axios/lib/adapters/http.js:260:1)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Truffle v5.4.11 (core: 5.4.11)
Node v16.9.1

Truffle v5.4.11 (core: 5.4.11)
Solidity v0.5.16 (solc-js)
Node v16.9.1
Web3.js v1.5.2

FYI. "wget raw.githubusercontent.com" works good on my terminal. and i can git clone.

**Comment by wilmerhenao** [comment] 2021-10-25 00:22
Mac:

Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12)
Truffle v5.4.14 (core: 5.4.14)
Node v14.17.6

**Comment by RogerLiNing** [comment] 2021-11-25 02:53
same issue with win 11 executing `truffle unbox react`

```shell

Starting unbox...                                                                                                       
=================                 
                                                                                      
√ Preparing to download box
× Downloading
Unbox failed!
× Downloading
Unbox failed!
Error: Error connecting to https://raw.githubusercontent.com/truffle-box/react-box/master/truffle-box.json. Please check your internet connection and try again.

Request failed with status code 503
    at createError (C:\Users\Roger lee\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\axios\lib\core\createError.js:16:1)
    at settle (C:\Users\Roger lee\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\axios\lib\core\settle.js:17:1)
    at IncomingMessage.handleStreamEnd (C:\Users\Roger lee\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\axios\lib\adapters\http.js:269:1)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Truffle v5.4.22 (core: 5.4.22)
Node v14.16.0
```
while no problem of fetching content using PowerShell:
```
PS D:\code\web3> (Invoke-WebRequest -Uri https://raw.githubusercontent.com/truffle-box/react-box/master/truffle-box.json).content
{
  "ignore": ["README.md", ".gitignore", "box-img-lg.png", "box-img-sm.png", ".github"],
  "commands": {
    "Compile": "truffle compile",
    "Migrate": "truffle migrate",
    "Test contracts": "truffle test",
    "Test dapp": "cd client && npm test",
    "Run dev server": "cd client && npm run start",
    "Build for production": "cd client && npm run build"
  },
  "hooks": {
    "post-unpack": "cd client && npm ci"
  }
}
```

**Comment by zhi114** [comment] 2022-02-10 07:17
Same issue with mac m1 executing truffle unbox pet-shop.
Adding http_proxy and https_proxy don't solve problem.
Anyone help?
![1644477266352](https://user-images.githubusercontent.com/4452972/153356595-80ec5859-3148-479d-94b8-0854adfe55f5.jpg)

while no problem of fetching content using curl:
![2](https://user-images.githubusercontent.com/4452972/153356850-0951e078-b7cc-464a-8535-e86840285081.jpg)

**Comment by rockyoung** [comment] 2022-02-24 10:24
Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
Error: Error connecting to https://raw.githubusercontent.com/truffle-box/metacoin-box/master/truffle-box.json. Please check your internet connection and try again.

Request failed with status code 503
    at createError (/home/rock_u/.nvm/versions/node/v17.6.0/lib/node_modules/truffle/build/webpack:/node_modules/axios/lib/core/createError.js:16:1)
    at settle (/home/rock_u/.nvm/versions/node/v17.6.0/lib/node_modules/truffle/build/webpack:/node_modules/axios/lib/core/settle.js:17:1)
    at IncomingMessage.handleStreamEnd (/home/rock_u/.nvm/versions/node/v17.6.0/lib/node_modules/truffle/build/webpack:/node_modules/axios/lib/adapters/http.js:269:1)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1342:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Truffle v5.5.1 (core: 5.5.1)
Node v17.6.0



$ curl https://raw.githubusercontent.com/truffle-box/metacoin-box/master/truffle-box.json
{
  "ignore": [
    "README.md",
    ".gitignore"
  ],
  "commands": {
    "Compile contracts": "truffle compile",
    "Migrate contracts": "truffle migrate",
    "Test contracts": "truffle test"
  },
  "hooks": {
    "post-unpack": ""
  }
}

**Comment by cds-amal** [comment] 2022-07-11 20:52
Closing this as issues seem to be related to PROXY configuration. Anyone coming here, please see if the following links help

- https://github.com/trufflesuite/truffle/issues/4016#issuecomment-1023471003
- https://github.com/trufflesuite/truffle/issues/2692#issuecomment-577178735

**Closed by cds-amal** 2022-07-11 20:52 UTC
Labels: error better, priority3 🔧

**Comment by Deepthitv** [comment] 2022-07-19 14:45
✓ Preparing to download box
✖ Downloading
Unbox failed!
Error: Truffle Box at URL https://github.com:chainskills/chainskills-box doesn't exist. If you believe this is an error, please contact Truffle support.
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:43:1
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:6:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Truffle v5.5.14 (core: 5.5.14)
Node v14.17.5

**Comment by cliffoo** [comment] 2022-07-19 16:27
> ✓ Preparing to download box ✖ Downloading Unbox failed! Error: Truffle Box at URL https://github.com:chainskills/chainskills-box doesn't exist. If you believe this is an error, please contact Truffle support. at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:43:1 at Generator.throw () at rejected (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:6:42) at processTicksAndRejections (internal/process/task_queues.js:95:5) Truffle v5.5.14 (core: 5.5.14) Node v14.17.5

That url looks invalid: Try `truffle unbox chainskills/chainskills-box`

**Comment by cliffoo** [comment] 2022-07-19 17:05
Hey @Deepthitv, looks like [chainskills/chainskills-box](https://github.com/chainskills/chainskills-box) doesn't have a `truffle-box.json` file at the repo's root, which is what the `unbox` command uses to identify if the repo is indeed a Truffle box.

Give our [react box](https://github.com/truffle-box/react-box) a try?

**Comment by ZulquarnainKhan** [comment] 2023-02-19 00:14
Unbox failed!
Error: Error connecting to https://raw.githubusercontent.com/truffle-box/react-box/master/truffle-box.json. Please check your internet connection and try again.

connect ETIMEDOUT 2405:200:1607:2820:41::36:443
    at Function.AxiosError.from (C:\Users\tabas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\axios\dist\node\axios.cjs:789:1)
    at RedirectableRequest.handleRequestError (C:\Users\tabas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\axios\dist\node\axios.cjs:2744:1)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (C:\Users\tabas\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\follow-redirects\index.js:14:1)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Truffle v5.7.7 (core: 5.7.7)
Node v18.14.1

**Comment by ZulquarnainKhan** [comment] 2023-02-19 00:15
facing this issue is there any solution

**Comment by Siddharth-sing** [comment] 2023-03-06 10:04
For windows (might also work for others) 

I have a solution where we don't have to downgrade the node version and `truffle-box react` will be up and running. We will go old school. 

* **Step 1** -  Clone the truffle-box/react-box repo. from [here](https://github.com/truffle-box/react-box/) to your code editor (I have used VSCode).

> Now we have to do two major things, first one is to `compile` & `migrate` the smart contracts and the next is to install the `npm` dependencies (because `npm module` doesn't go in a repo. instead `package.json` have all the dependencies required written.)
 
* **Step 2** -  Use the command `cd truffle` to go inside the truffle folder in your project structure through the command line(Terminal). Now run **`truffle develop`**, and after that run **`compile`** and **`migrate`** one by one, after all these three commands are successfully executed, exit the terminal.
* **Step 3** - Type `cd ..` to get out of the truffle folder and use `cd client` to enter inside the `client` folder, now run **`npm install`**.
* **Step 4** - All done 👌, use command **`npm start`** inside the client folder, your truffle-box + react is configured.
<img width="862" alt="image" src="https://user-images.githubusercontent.com/72120258/223074489-ea18ccc6-1ff3-4505-901a-7258743d6c9d.png">

**Comment by Kunal766** [comment] 2023-03-17 11:23
USE A VPN

**Comment by yjshi2015** [comment] 2023-08-07 09:19
> same issue with truffle unbox on ubuntu and win10
> 
> # Starting unbox...
> ✔ Preparing to download box ✖ Downloading Unbox failed! ✖ Downloading Unbox failed! Error: Error connecting to https://raw.githubusercontent.com/truffle-box/Metacoin-box/master/truffle-box.json. Please check your internet connection and try again.
> 
> Request failed with status code 503 at createError (/home/linuxbrew/.linuxbrew/lib/node_modules/truffle/build/webpack:/node_modules/axios/lib/core/createError.js:16:1) at settle (/home/linuxbrew/.linuxbrew/lib/node_modules/truffle/build/webpack:/node_modules/axios/lib/core/settle.js:17:1) at IncomingMessage.handleStreamEnd (/home/linuxbrew/.linuxbrew/lib/node_modules/truffle/build/webpack:/node_modules/axios/lib/adapters/http.js:260:1) at IncomingMessage.emit (node:events:406:35) at endReadableNT (node:internal/streams/readable:1343:12) at processTicksAndRejections (node:internal/process/task_queues:83:21) Truffle v5.4.11 (core: 5.4.11) Node v16.9.1
> 
> Truffle v5.4.11 (core: 5.4.11) Solidity v0.5.16 (solc-js) Node v16.9.1 Web3.js v1.5.2
> 
> FYI. "wget raw.githubusercontent.com" works good on my terminal. and i can git clone.

do you resolved this problem?
