### ISSUE TITLE
Migration only save the first deployed smart contract.

### ISSUE THREAD

**Issue by Pedro-vk** [trufflesuite/truffle#881] opened 2018-04-02 10:31 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

My migration deploys a few contracts in a row. The JSON files get created with ABI and bytecode, but only the first contract deployed gets the deployed address saved under the network in the artefacts.

## Steps to Reproduce

Run a migration of that:

```javascript
var FirstContract = artifacts.require("./FirstContract.sol");
var SecondContract = artifacts.reqre("./SecondContract.sol");

module.exports = async function (deployer, helper, accounts)  {
  try {
    await deployer.deploy(FirstContract)
    let firstContract = await FirstContract.deployed()

    await deployer.deploy(SecondContract, firstContract.address)
    let secondContract = await SecondContract.deployed()
  } catch (error) {
    console.log(error)
  }
}
```

## Expected Behavior

`FirstContract` and `SecondContract` must have the network parameter written, with the address where have been deployed.

## Actual Results

Check the result of the `FirstContract` and `SecondContract`, only `FirstContract` have written the network parameter.

## Environment

* Operating System: Ubuntu 16.04
* Ethereum client: Ganache v1.1.0-beta.1 and Ropsten network throught infura.
* Truffle version (`truffle version`): 4.1.5 and 4.1.3
* node version (`node --version`): 9.5.0
* npm version (`npm --version`): 5.8.0

**Comment by cgewecke** [comment] 2018-04-02 17:41
@Pedro-vk Thanks for opening - this is a duplicate of #501. 

The way async/await integrates with the migrations feature is confusing for a lot of users. `truffle-migrate` was written before `await` became common and it stages deployments as 'thennables' rather than executing them as true promises. See [this comment](https://github.com/trufflesuite/truffle/issues/501#issuecomment-332589663) for advice about how to resolve.

**Closed by cgewecke** 2018-04-02 17:41 UTC
