### ISSUE TITLE
Not Able see my Account

### ISSUE THREAD

**Issue by sarthakmis** [trufflesuite/truffle#679] opened 2017-11-13 10:15 UTC
I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

Hi there, I am trying upload some data on my Local IPFS,during the process i am using "web3.eth.getAccounts(function(error,accounts)". After uploading part, i am using the method but it get skipped(web3.eth.getAccounts(function(error,accounts)) and further i am not able to see my account on my localhost

## Environment

* Operating System: Windows 10
* Truffle version: 4.0.1
* Ethereum client: Local
* node version: 6.11.1
* npm version: 5.4.0

**Comment by onetom** [comment] 2017-11-14 13:54
Your description is insufficient to reproduce the issue.
It also seem too broad in scope. Try to isolate the issue.
It's most likely doesn't have to do anything with IPFS and I don't see how is it related to Truffle,
since you don't mention anything Truffle specific in your description.

**Comment by cgewecke** [comment] 2018-01-23 20:06
@sarthakmis Closing this for house keeping but please re-open if you continue to have difficulty with this.

**Closed by cgewecke** 2018-01-23 20:06 UTC
