### ISSUE TITLE
Contract name collision handling?

### ISSUE THREAD

**Issue by illuzen** [trufflesuite/truffle#410] opened 2017-05-22 17:19 UTC
## Issue

There seems to be some strange handling of the situation in which multiple contracts with the same name exist in the truffle system. I haven't quite figured it out, but renaming one of my contracts made my test pass. Changing the contract was changing the behavior, but the following remains a mystery. 

`

contract OldToken is ERC20 {}

    contract A  {

     uint256 public originalSupply; 

     function A(address a) {

        oldToken = OldToken(a);

        originalSupply = oldToken.totalSupply();

    }
}

`

This was throwing at runtime, but commenting out the originalSupply = line made it go thru. And it turns out I had a contract named A before in another file, but I had removed it and blown away my build directory so I thought that should be enough to deal with any name collision issues. Well, changing my contract name to AA, which I had never used before allows me to call oldToken.totalSupply(). It's strange that the code responded to changes in this contract even tho there was apparently a name collision. Maybe the abi wasn't changing, but the implementation was? 

Not familiar enough with truffle internals yet to say what this might be but I think there must be some cache somewhere that I need to reset to prevent this from happening in the future. And maybe if truffle is installed globally it could be picking up on contracts in other projects with the same name?

## Environment

* Operating System: OSX 10.12.4
* Truffle version: v3.1.2
* Ethereum client: v3.0.5
* node version: v7.7.4
* npm version: 4.1.2

**Comment by tcoulter** [comment] 2017-07-11 16:49
Thanks for this! Marking as a duplicate of #443. Cheers!

**Closed by tcoulter** 2017-07-11 16:49 UTC
