### ISSUE TITLE
unlimited contract size error? 

### ISSUE THREAD

**Issue by seongeunC** [trufflesuite/truffle#2089] opened 2019-06-10 04:13 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

My Contract has a bytecode size of at least 245676.
deploying contract in truffle test code with optimizations will cause an 'out of gas'
how can i solve this problem

## Steps to Reproduce

1. remix 
   - enable optimization
   -> deploying Success

2. truffle
   -  ganache-cli -l 8000000 --allowUnlimitedContractSize
   -  optimizer: {
        enabled: true,
        runs: 200
      },
  - `this.contract = await contract.new()`
  - test
   -> deploying fail 

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`Truffle v5.0.4`):
* node version (`v8.15.1`):
* npm version (`6.4.1`):

**Comment by CruzMolina** [comment] 2019-06-10 15:21
Hey @seongeunC , can you upgrade to the latest truffle and see if the issue has been resolved? 🤞

**Comment by seongeunC** [comment] 2019-06-11 04:05
The same problem occurs when using Truffle version 5.0.21.

**Comment by CruzMolina** [comment] 2019-06-11 04:40
Can you provide a reproducible repo for debugging purposes?

**Comment by haltman-at** [comment] 2019-06-11 05:15
Is your complaint that you got the wrong error message?  If so, I think this is basically a duplicate of #1655.  Because such long bytecode *is* going to generate an error regardless...

**Comment by haltman-at** [comment] 2019-09-18 17:59
Closing this for issue maintenance; please let us know if this is still a problem and we can re-open it.  Thank you!

**Closed by haltman-at** 2019-09-18 17:59 UTC
