### ISSUE TITLE
--miner.defaultGasPrice 0 cannot be set to 0

### ISSUE THREAD

**Issue by bruck93** [trufflesuite/truffle#5084] opened 2022-04-29 16:21 UTC
Hello,
I've noticed that from the Ganace UI is possible to apply the defaultGasPrice to 0.

But if I run

`ganache -e 100 -l 6721975 --miner.defaultGasPrice 0 -p 7545`

On the CLI seems 0, but in fact all the tx are consuming gas. Could you check this please ?

**Comment by gnidan** [comment] 2022-05-05 17:16
Hi @bruck93, nice to see you over on the Truffle side now :)

> If I run manually each test, one by one, is working fine.

Could you please provide more information about your tests? We can try to reproduce, but I suspect we'll find it easier if we have a better idea what your project setup looks like in full. If you can't share your whole project source on GitHub, could you maybe share the parts that you're comfortable with?

In the meantime, we'll add this to our list to start investigating. Thanks for reporting this!

**Comment by bruck93** [comment] 2022-05-06 09:16
Hey Truffle side @gnidan 
I can't share the code base of our product at the moment.

I'll discuss with the others at least if I could share some tests.
I'll follow up as soon as possible.

**Comment by sukanyaparashar** [comment] 2022-06-22 21:55
Hi @bruck93 . Just wondering if you are still facing this issue?

**Comment by bruck93** [comment] 2022-06-30 08:51
Hey @sukanyaparashar .
Yes I still have the issue.

But I've runned manually all the tests... which I didn't like honestly but was the only way

**Comment by kevinweaver** [comment] 2022-07-07 17:52
@bruck93 please send over any reproduction steps you can provide so we can help you look into this. Thanks!

**Comment by cds-amal** [comment] 2022-08-04 16:52
I'm closing this for issue maintenance @bruck93. If you can share any information, please feel free to comment, and we'll re-open. Thanks!

**Closed by cds-amal** 2022-08-04 16:52 UTC
Labels: needs investigated
