### ISSUE TITLE
Truffle v4 'truffle develop' on Windows without connection to internet/offline gives error

### ISSUE THREAD

**Issue by GeoffreySari** [trufflesuite/truffle#656] opened 2017-11-02 04:42 UTC
[ethereum.stackexchange.com]https://ethereum.stackexchange.com/questions/29669/user-truffle-on-testrpc-offline

---------------------------

## Issue

Running `truffle develop` on windows, while not connected to network/internet gives error. 

## Steps to Reproduce

1. Create initial project in a desire folder `truffle init`
2. Disconnect Wifi/Lan connection. Then run `truffle develop` 

## Expected Behavior
Unable to connect to ethereum client when disconnected from network/internet though WIFI/LAN. 
However, when connected to a Wifi/Lan with internet, it works as expected and opens a console that we can run truffle commands `migrate`, `test` normally.

It be great to connect to `http://localhost:9545/` while offline and not connected to internet.

## Actual Results
```
$ truffle develop
Truffle Develop started at http://localhost:9545/

Accounts:
(0) 0x627306090abab3a6e1400e9345bc60c78a8bef57
...
(9) 0x5aeda56215b167893e80b4fe645ba6d5bab767de

Mnemonic: candy maple cake sugar pudding cream honey rich smooth crumble sweet t                                                                                                                reat

Could not connect to your Ethereum client. Please check that your Ethereum clien                                                                                                                t:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)
```
## Environment
* Operating System: Windows
* Truffle version: v4
* Ethereum client: Testrpc

**Comment by GeoffreySari** [comment] 2017-11-03 04:38
For anyone, who may experience similar issue. Here's a quick solution I found to get truffle working offline.

So truffle deploy doesn't work because of truffle's need to create an external RPC IP Address, as it seems.

A quick solution to this issue of truffle deploy not working, was simply running a mobile hotspot from my Smart phone and connecting my host machine to the wifi. Then running truffle deploy without internet connection disabled from Smart phone got it working as expected, at least for now

**Comment by gnidan** [comment] 2017-11-09 17:44
Re-opening this; it's a real problem!

Discovered the cause via a [StackOverflow question](https://stackoverflow.com/questions/31326178/does-node-js-server-need-internet-connection-to-run).

**Required Truffle fix**: Replace `localhost` with `127.0.0.1` everywhere.

**Comment by wouterbruinings** [comment] 2017-11-29 09:57
I am experiencing a similar problems on a mac Higher Sierra. 
I cannot connect to the truffle development environment when wifi is turned off. 

For me it depends to which wifi I am connected whether or not it works: 
- Cannot connect to the truffle development environment on home wifi
- Can connect to truffle development environment on work wifi 

In case truffle cannot connect, I also cannot find a node (truffle dev) process running on port 9545. I do find a process running on the expected port if I run truffle development --log and can successfully connect to it from a different terminal. 

**Workaround:** 

1. Open 2 terminals 
2. Run truffle develop --log in one 
3. Run truffle console in the other 


I am experiencing a similar problems on a mac Higher Sierra. 
I cannot connect to the truffle development environment when wifi is turned off. 

For me it depends to which wifi I am connected whether or not it works: 
- Cannot connect to the truffle development environment on home wifi
- Can connect to truffle development environment on work wifi 

In case truffle cannot connect, I also cannot find a node (truffle dev) process running on port 9545. I do find a process running on the expected port if I run truffle development --log and can successfully connect to it from a different terminal. 

**Workaround:** 

1. Open 2 terminals 
2. Run truffle develop --log in one 
3. Run truffle console in the other

**Comment by cgewecke** [comment] 2018-03-31 17:18
Tested this on `4.1.5` and it seems to be working. Closing.

**Closed by cgewecke** 2018-03-31 17:18 UTC

**Comment by raky35** [comment] 2018-04-27 09:46
$ npm -version truffle 
5.8.0
turffle.js
  mistConnection: {
    host: '127.0.0.1',
    port: 8545,
    network_id: "*",
    from:'0xXXXXXXXX'

truffle migrate --network mistConnection
Compiling ./contracts/Voting.sol...
Writing artifacts to ./build/contracts

Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

**Comment by mryellow** [comment] 2018-09-25 19:54
Believe this remains an issue in 4.1.8.

'Invalid JSON RPC response'

Sent from mobile (no connectivity)

**Comment by yhjhoo** [comment] 2021-09-16 02:11
to working in a retricted network, can't connect to internet to reach to RPC connections.
