### ISSUE TITLE
Error: Number can only safely store up to 53 bits @Truffle5.0.xx

### ISSUE THREAD

**Issue by W3stside** [trufflesuite/truffle#1704] opened 2019-02-07 10:14 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Using Truffle@5.0.2 console and attempting to get a locally deployed contract throw an `Error: Number can only safely store up to 53 bits`

However this does NOT happen deterministically. Sometimes it works, sometimes not. 

On Truffle@4.1.15, there are no issues.

On Truffle@5.0.xx, if you skip `truffle-contract` and use web3 to grab an already deployed contract (just doing what `Contract.deployed()` does) via

`await new web3.eth.Contract(ContractName.abi, '0x8E7a8d3CAeEbbe9A92faC4db19424218aE6791a3')`

It works fine as well. Internally `truffle-contract` + `bn.js` is breaking. 

No issues with `BigNumber` on `Truffle 4.1.15 w/`Web3@0.20.6` 
or via 
`Truffle 5.0.xx` w/`Web3@1.0` `web3.eth.Contract`

## Steps to Reproduce

Run ganache-cli
Migrate contracts w/0.5.2 sol-c

`npx truffle@latest console` (or npx truffle@5.0.xx)

`await ContractName.deployed()` <-- but it is contract specific - something with my bytecode could be off. I did check that none of our contract events are indexing `bytes` or `string`s - only `bytes32` is indexed

## Expected Behavior

That is grabs deployed contract with no number error.

## Actual Results

`Error: Number can only safely store up to 53 bits`

## Environment

* Operating System: Linux Ubuntu 0.18.xx
* Ethereum client:
* Truffle version (`truffle version`): 0.5.3
* node version (`node --version`): 10.7.0
* npm version (`npm --version`): 6.5.0

**Comment by eggplantzzz** [comment] 2019-02-11 20:45
@W3stside Hmm, do you have code I can try and duplicate this from? I haven't seen this behavior before.

**Comment by 18dew** [comment] 2019-03-09 07:36
Same error, Rolling back to 4.x.x till stability is achieved.

**Comment by eggplantzzz** [comment] 2019-03-11 18:44
If anyone can provide some specific repro steps it would help a lot in troubleshooting this.

**Comment by gnidan** [comment] 2019-03-27 17:50
Following up again: anyone have reproduce steps for this? Or can anyone confirm whether or not the problem still exists on more recent versions of Truffle? Thanks!

**Comment by aosanya** [comment] 2019-04-13 04:22
Incase your problem stems from the javascript side, I was getting the same error and solved it by changing:

 assert.equal(policySummary.payout.toNumber(), policySummary.premium.toNumber() * 1.5, "Final Payout Value is wrong")

To
let payout = parseFloat(policySummary.payout) // big wei number
let premium = parseFloat(policySummary.premium) * 1.5
assert.equal(payout, premium, "Final Payout Value is wrong")
assert.equal(policySummary.isWithdrawn, false, "Test requires a non withdrawn payout")

**Comment by W3stside** [comment] 2019-04-15 08:10
Hey sorry guys was away on vacation and never had a chance to come back around here - I've been unable to reproduce it so honestly not sure how to help out - if I come across this issue again I'll better document steps to reproduce and post. Thanks @gnidan

**Comment by eggplantzzz** [comment] 2019-04-19 08:36
Ok thanks @W3stside. Closing this for issue maintenance.

**Closed by eggplantzzz** 2019-04-19 08:36 UTC
Labels: needs reproduced

**Comment by hanlaohan** [comment] 2019-05-08 03:37
5.0.15,问题依然存在

**Comment by macman18** [comment] 2019-05-21 16:04
Agree with @18dev .
How I have seen in several blogs: the best solution is downgrade the truffle version to truffle@4.1.5. The problem is related to quorum in truffle version 5. I have made this downgrading and now everything works!

**Comment by macman18** [comment] 2019-05-21 16:05
> Same error, Rolling back to 4.x.x till stability is achieved.
> 
> Getting this error when deploying using trufflehd-wallet provider with private keys explicitly mentioned in code. ( insecure method )
> 
> However I stumbled on to this error as in truffle 5.x.x wallet provider does not work. as in no errors and no contract deployment also.

Agree with @18dev.
How I have seen in several blogs: the best solution is downgrade the truffle version to truffle@4.1.5. The problem is related to quorum in truffle version 5. I have made this downgrading and now everything works!

**Comment by CruzMolina** [comment] 2019-05-21 17:07
@macman18 Just to clarify, are you having issues with quorum in truffle v5?

**Comment by macman18** [comment] 2019-05-21 17:17
> @macman18 Just to clarify, are you having issues with quorum in truffle v5?
I have modified my previous comment. I'm not really sure of quorum but many blogs referred to it.
Thank u for check.

**Comment by bh2smith** [comment] 2019-06-25 12:13
I can provide a situation where this happened to me that could line up with reason for this error (although it was happening non-deterministically for myself). 

Consider the following contract;

```C
pragma solidity ^0.5.0
contract TestScenario {
    uint public value = 2**256 - 1;
    function incrementValue() public {
        value++;
    }
}
```
and a unit test that attempts to read the value after incrementing it. Something like, 

```js
const instance = await TestScenario.new()
instance.incrementValue()
const value = (await instance.value.call()).toNumber()
```

In this case we will find that the unit test inconsistently passes and fails with the error described here

```bash
Error: Number can only safely store up to 53 bits
```

and is probably/most-likely/certainly happening because of a missing `await` on `instance.incrementValue()`.

Hope this helps, It worked for me!

**Comment by xuesu** [comment] 2019-07-05 13:22
Try this contract, I cannot migrate this one because it is too big.
[oraclizeContractUserSimple.txt](https://github.com/trufflesuite/truffle/files/3362840/oraclizeContractUserSimple.txt)

**Comment by tpkeeper** [comment] 2020-07-16 10:52
Truffle v5.1.34 (core: 5.1.34)
Solidity v0.5.16 (solc-js)
Node v12.18.2
Web3.js v1.2.1

#### the same error

**Comment by ryzhak** [comment] 2021-01-13 20:40
I'm getting the same error when running any migration via `truffle migrate --reset` with ganache opened with weird gas limit `ganache-cli -l 0xfffffffffffffffffffffff`

environment:
```
Truffle v5.1.61 (core: 5.1.61)
Solidity v0.5.16 (solc-js)
Node v15.3.0
Web3.js v1.2.9

```

**Comment by araskachoi** [comment] 2021-01-25 21:52
Hello guys!
I am also experiencing this issue as well. I am using [ethermint](https://github.com/cosmos/ethermint) to run some truffle tests. I am running these steps here: https://github.com/cosmos/ethermint/blob/development/docs/guides/truffle.md

when running `truffle migrate --network development`, the error i am running into is:
```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Starting migrations...
======================
> Network name:    'development'
> Network id:      888
> Block gas limit: 4294967295 (0xffffffff)

1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0xc373c702150d1f5e279c7ef121d58413a8001b52bf622b181c3a501ac605aada
   ⠙ Blocks: 0            Seconds: 4
Error: Number can only safely store up to 53 bits
    at assert (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/bn.js/lib/bn.js:6:1)
    at BN.toNumber (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/bn.js/lib/bn.js:506:1)
    at Object.hexToNumber (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-utils/src/utils.js:239:1)
    at Method.outputBlockFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/src/formatters.js:303:1)
    at Method.web3.eth.getBlock.method.outputFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/packages/interface-adapter/dist/shim/overloads/ethereum.js:38:1)
    at Method.formatOutput (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:169:1)
    at sendTxCallback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-core-method/src/index.js:640:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js:177:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/src/index.js:111:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

env (using the latest greatest version of truffle):
```
Truffle v5.1.63 (core: 5.1.63)
Solidity v0.5.16 (solc-js)
Node v10.21.0
Web3.js v1.2.9
```

**Comment by dominictracey** [comment] 2021-05-02 13:50
set up:
`Truffle v5.3.4 (core: 5.3.4)
Solidity - 0.4.24 (solc-js)
Node v12.20.0
Web3.js v1.3.5`

error:
`  1) Contract: CrowdFundingWithDeadline
       contract is initialized:
     Error: Number can only safely store up to 53 bits
      at assert (/Users/dtracey/.nvm/versions/node/v12.20.0/lib/node_modules/truffle/build/webpack:/node_modules/bn.js/lib/bn.js:6:1)
      at BN.toNumber (/Users/dtracey/.nvm/versions/node/v12.20.0/lib/node_modules/truffle/build/webpack:/node_modules/bn.js/lib/bn.js:506:1)
      at Context.<anonymous> (test/crowd_funding_test.js:29:33)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
`

test code:
`            let targetAmount = await contract.targetAmount.call();
            expect(targetAmount.toNumber()).to.equal(1000000000000000000);
`

**Comment by casperyonel** [comment] 2021-12-07 01:27
> set up: `Truffle v5.3.4 (core: 5.3.4) Solidity - 0.4.24 (solc-js) Node v12.20.0 Web3.js v1.3.5`
> 
> error: ` 1) Contract: CrowdFundingWithDeadline contract is initialized: Error: Number can only safely store up to 53 bits at assert (/Users/dtracey/.nvm/versions/node/v12.20.0/lib/node_modules/truffle/build/webpack:/node_modules/bn.js/lib/bn.js:6:1) at BN.toNumber (/Users/dtracey/.nvm/versions/node/v12.20.0/lib/node_modules/truffle/build/webpack:/node_modules/bn.js/lib/bn.js:506:1) at Context.<anonymous> (test/crowd_funding_test.js:29:33) at processTicksAndRejections (internal/process/task_queues.js:97:5)`
> 
> test code: ` let targetAmount = await contract.targetAmount.call(); expect(targetAmount.toNumber()).to.equal(1000000000000000000);`

I'm running the same code and can't seem to get it working. Seems like the only viable solution is to downgrade truffle to v3 where people had better luck. Might revert back to prior version until stability is found with BigInts on v5.

**Comment by dvncan** [comment] 2022-05-23 22:46
Hi I have this error and am able to replicate it. I was following this tutorial: https://itnext.io/building-a-decentralized-application-with-bep-20-contract-in-solidity-d2c066447aa6 

Mid way at the unit tests, after a totalSupply variable is introduced everytime the getter function fails with this error.
