### ISSUE TITLE
Migration Error: "this.queueOrExec is not a function"

### ISSUE THREAD

**Issue by batjko** [trufflesuite/truffle#521] opened 2017-07-29 14:26 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Following the pet-shop tutorial, I am attempting the first migration of my Adoption contract.
`truffle migrate` produces the described error when trying to process `2_deploy_contracts.js`.

## Steps to Reproduce

1. Follow pet-shop Tutorial up to the [Migration section](http://truffleframework.com/tutorials/pet-shop#migration).
2. run `truffle migrate`

This is my migration file (`2_deploy_contracts.js`):
```js
const Adoption = artifacts.require('./Adoption.sol');
module.exports = ({ deploy }) => deploy(Adoption);
```

## Expected Behavior

Successful migration message.

## Actual Results

![image](https://user-images.githubusercontent.com/7287076/28745520-e21b20cc-7471-11e7-9367-29300a734108.png)

## Environment

* Operating System: **Windows 10 (64bit)** w/ Bash
* Truffle version: **v3.4.6**
* Ethereum client: **TestRPC v3.9.2**
* node version: **v8.2.1**
* npm version: **v5.3.0**

**Comment by batjko** [comment] 2017-07-29 14:38
Actually, I went ahead and tried the oldschool (non-ES6) version shown in the tutorial instead of the one I mentioned above.
That now works.

Does this mean, truffle doesn't allow ES6+, i.e. *current* Javascript standards, i.e. the ones supported by the installed Node.js version? Does it come bundled with its own node library or something?

**Comment by gnidan** [comment] 2019-01-09 18:48
Does this problem still exist? Thanks!

**Comment by CruzMolina** [comment] 2019-04-04 00:10
Looks like this is still a problem. Current reproduction steps result in the following on truffle v5:

```
$ metacoin truffle migrate

Compiling your contracts...
===========================
> Compiling ./contracts/Adoption.sol
> Compiling ./contracts/Migrations.sol
> Artifacts written to /Users/cruzmolina/Code/truffle-projects/metacoin/build/contracts
> Compiled successfully using:
   - solc: 0.5.0+commit.1d4f565a.Emscripten.clang


Starting migrations...
======================
> Network name:    'development'
> Network id:      5777
> Block gas limit: 0x6691b7


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x45286f4288740dea96c9e8545c5ff424b20088c2a08e94fc7b7e2eaf9815a96f
   > Blocks: 0            Seconds: 0
   > contract address:    0xcdc5E605564edDF8fbf4202219536FCBE139D40a
   > block number:        1
   > block timestamp:     1554336551
   > account:             0x3485d430F23A62a8B4A262B175aFf68e6f582fB7
   > balance:             99.99430184
   > gas used:            284908
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00569816 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00569816 ETH


2_deploy_contracts.js
=====================
TypeError: Cannot read property 'networks' of undefined
    at deploy (/Users/cruzmolina/Code/truffle-projects/truffle/packages/truffle/build/webpack:/packages/truffle-deployer/index.js:46:1)
    at module.exports (/Users/cruzmolina/Code/truffle-projects/metacoin/migrations/2_deploy_contracts.js:8:36)
    at Require.file (/Users/cruzmolina/Code/truffle-projects/truffle/packages/truffle/build/webpack:/packages/truffle-migrate/migration.js:59:1)
    at /Users/cruzmolina/Code/truffle-projects/truffle/packages/truffle/build/webpack:/packages/truffle-require/require.js:99:1
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
Truffle v5.0.10 (core: 5.0.10)
Node v11.4.0
```

**Comment by CruzMolina** [comment] 2019-04-04 00:17
Ah, so using the following for `migrations/2_deploy_contracts.js` works.

```
const Adoption = artifacts.require('./Adoption.sol');
module.exports = deployer => deployer.deploy(Adoption);
```

Looks like we need/use the `Deployer` class to do a bunch of heavy-lifting during migrations.

**Comment by eggplantzzz** [comment] 2019-06-19 17:53
Closing this. When you destructure a method like this, it loses the `this` binding. You will need to use method call syntax to keep the binding.

**Closed by eggplantzzz** 2019-06-19 17:53 UTC
Labels: Migrations, bug
