### ISSUE TITLE
truffle console: SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by vidhyaramani** [trufflesuite/truffle#910] opened 2018-04-23 09:33 UTC
Truffle migrate is working good but while running truffle console

- SyntaxError: Unexpected identifier
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInContext (vm.js:181:10)
    at Console.interpret (C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:106593:17)
    at ReplManager.interpret (C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:107310:18)
    at bound (domain.js:375:14)
    at REPLServer.runBound [as eval] (domain.js:388:12)
    at REPLServer.onLine (repl.js:492:10)
    at REPLServer.emit (events.js:180:13)
    at REPLServer.emit (domain.js:421:20)
## Environment

* Operating System: Windows
* Ethereum client:
* Truffle version (`truffle version`):v4.1.6
* node version (`node --version`):v9.9.0
* npm version (`npm --version`): 5.8.0

**Comment by cgewecke** [comment] 2018-04-23 15:05
@vidhyaramani Hi. Within `truffle console` you don't need to prefix the commands with `truffle`. To migrate, just type `migrate`.  There's a list of available commands [here](http://truffleframework.com/docs/getting_started/console#commands-available).

Could you check to see if removing the word 'truffle' from your command solves this problem?

**Comment by vidhyaramani** [comment] 2018-04-24 07:11
no its not working still. Could you explain me how to deploy the smart contract? steps to do it  after truffle migrate. Thanks!

**Comment by cgewecke** [comment] 2018-04-24 14:49
@vidhyaramani Are you still seeing this syntax error after making the change suggested? If so could provide steps to reproduce it?

`truffle-migrate` deploys the the contract. Please see the truffle documentation [here](http://truffleframework.com/docs/getting_started/migrations#running-migrations) for more.

**Comment by vidhyaramani** [comment] 2018-04-24 14:52
yes am still searching for it. yes,i have also checked the steps, everything is same. Please check my code.Thanks!

pragma solidity ^0.4.0;
contract healthcare {

    struct hospital {
       string patientID;
        uint date; 
        string doctorID;
        
    }
    struct data {
       bytes32 records;
       bool approvedbypatient;
    }
      
      
       hospital _patient;
       hospital _doctor;
    
    
    address patient;
    address doctor;
 
    mapping(address => hospital) patients;
    mapping(address=>hospital) doctors;
    
   
    data[] records;
     
     
     
  
  function agreement()public payable returns(bool success){
         bool accepted=false;
        if(msg.sender==patient){
            accepted==true;
            if(_patient.date==0){
                _patient.date==now;
            }
        }
        
        if(msg.sender==doctor){
            accepted==true;
            if(_doctor.date==0){
                _doctor.date==now;
            }
        }
        
        if(_patient.date==now && _doctor.date==now){
            return accepted;
            
            
        }
    }
    
     function recoveraddressforrecord(bytes32 h,uint8 v,bytes32 r,bytes32 s) internal pure returns(address){
         bytes memory prefix="\x9ethereum signed message:\n32";
         bytes32 prefixedhash=keccak256(prefix,h);
         address addr_record=ecrecover(prefixedhash,v,r,s);
         return addr_record;
         
     }
}
     contract p2p is healthcare{
         
         
              address patient;
              address doctor;
              uint index;
               bytes32 records;
             
              address addr_records;
              mapping(address=>bytes32[])public datalist;
              
         
         
         
         
         function retrivedata()public view returns(bytes32){
             if(msg.sender==patient || msg.sender==doctor){
                 
                 return (records);
                
                 
             }
         }
          
          function getNumofdata()public returns(uint256){
              if(msg.sender==doctor){
                  return datalist[patient].push(records);
              }
          }
             
          function getdata() public returns(bytes32){
              
              if(msg.sender==doctor && msg.sender==patient){
                  datalist[patient].push(records);
                  
                  return(records);
              }
          }   
             
             
          function appenddata()public returns(bytes32){
              if(msg.sender==doctor){
                  datalist[patient].push(records);
                  
                  return 1;
              }
          }
         
         
         
         
     }

**Comment by cgewecke** [comment] 2018-04-24 15:25
@vidhyaramani You are seeing this message: `SyntaxError: Unexpected identifier` after running `migrate` in truffle console? Please list steps to reproduce the error you're seeing, including the output you see in your terminal.

**Comment by vidhyaramani** [comment] 2018-04-24 15:32
Yes ,I got the output ..do you want me to explain the steps which I did in the coding?

**Comment by vidhyaramani** [comment] 2018-04-24 15:32
I didn't see any output ..am getting the error

**Comment by cgewecke** [comment] 2018-04-24 15:35
@vidhyaramani Could you post a screenshot of your terminal where the command you're using is visible as well as truffle's response?

**Comment by vidhyaramani** [comment] 2018-04-24 15:40
SyntaxError: Unexpected identifier
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInContext (vm.js:181:10)
    at Console.interpret (C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:106593:17)
    at ReplManager.interpret (C:\Users\labo\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:107310:18)
    at bound (domain.js:375:14)
    at REPLServer.runBound [as eval] (domain.js:388:12)
    at REPLServer.onLine (repl.js:492:10)
    at REPLServer.emit (events.js:180:13)
    at REPLServer.emit (domain.js:421:20)

**Comment by cgewecke** [comment] 2018-04-24 15:46
@vidhyarama Is the command you're using and the way you used it visible in what you just posted?

**Comment by vidhyaramani** [comment] 2018-04-24 15:56
Yes, I have given console and got this error

**Comment by cgewecke** [comment] 2018-04-24 19:31
@vidhyaramani I see the error you're describing when I do this:
```
truffle console
truffle(development)> truffle migrate
```

Error goes away when I do this:
```
truffle console
truffle(development)> migrate
```

Is there anything different about the way you are doing it?

**Comment by vidhyaramani** [comment] 2018-04-24 20:00
Yes, I did the same way.. but I didn't get the output for the program.. since I tried it many ways..have you got any output? Thanks!

**Comment by vidhyaramani** [comment] 2018-04-24 20:05
Same error is coming so it's not deploying the  coding..please need to get rid of this.thanks!

**Comment by cgewecke** [comment] 2018-04-24 20:10
@vidhyaramani Yes. I've done the following. In an empty folder
```
truffle unbox metacoin
```
Set up `truffle.js` (or `truffle-config.js`)
```
module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*" // Match any network id
    }
  }
};
```
In a second terminal tab launch the client:
```
ganache-cli
```

In the first tab:
```
truffle console --network development
truffle(development) > migrate
.. etc ..
Using network 'development'.

Running migration: 1_initial_migration.js
 Deploying Migrations...
 ... 0xeee49866e9d5889f909477b628b19e6ddf11e274cd62b2f8ad2c2bc2469f3326
 Migrations: 0x48c2c18a8ab877d350f1d4849d06089fd7e0f0e7
Saving successful migration to network...
 ... 0x85cebe250754642574fad883ff79f41b8916737637fa71002040c2e03d2e7b5a
Saving artifacts...
Running migration: 2_deploy_contracts.js
 Deploying ConvertLib...
 ... 0xa5e0d95aa1d9baa1f5ae558a9dbc7546b5057075813ecaaf9c9342cab7a9cbb8
 ConvertLib: 0x8154c2fae504a6c045fa5c475ecda86977a0803a
 Linking ConvertLib to MetaCoin
 Deploying MetaCoin...
 ... 0x35649421b5635a3f58fa59d10616a206769825ebe6fb5440c9a12c7fc9726a98
 MetaCoin: 0x8548d05328106e07224c9647347d2362dbb1f9d7
Saving successful migration to network...
 ... 0xf78116512b3d89483a023dd4da9c1ec6efdccd5d4aaf169c656688d3cdcb50de
Saving artifacts...
truffle(development)>
```

**Comment by vidhyaramani** [comment] 2018-04-24 20:13
Do I have start it from the first? Or just to follow the unbox metacoin and those steps?

**Comment by vidhyaramani** [comment] 2018-04-24 20:14
Have you got any output through this?

**Comment by vidhyaramani** [comment] 2018-04-24 20:25
I did it but after truffle compile, I have checked in the truffle.js and truffle configure.js is empty..not comments in that..?? 

Do we have any change anything in the initial.js and deploy contract.js??

**Comment by vidhyaramani** [comment] 2018-04-24 20:27
Y there is no metacoin.js file ?? Do we need to have it after compiling the program?

**Comment by cgewecke** [comment] 2018-04-24 20:46
@vidhyaramani I'm going to close this issue I'm sorry. I would advise you to read through the [documentation](http://truffleframework.com/docs/) and familiarize yourself with the plaform, following each step in a tutorial. We have some available on the site. The GitHub issues are for bug reports and feature requests and it looks like your initial report about the syntax error is not what's at issue here anymore.

**Closed by cgewecke** 2018-04-24 20:46 UTC
