### ISSUE TITLE
Reference to issue "Ethers are wiped out in account during sendTransaction or migrations #997"

### ISSUE THREAD

**Issue by samaujs** [trufflesuite/truffle#1021] opened 2018-06-15 04:46 UTC
Unfortunately, tokens are transferred again today to the same account **"https://rinkeby.etherscan.io/address/0x7097f41f1c1847d52407c629d0e0ae0fdd24fd58"**
at block **"2464270"**
This time it is with the following information :
(1) The account is unlocked with Metamask and not geth; within only appropriately 20 minutes, ethers are being transferred;
(2) geth --rinkeby --rpc --rpccorsdomain "http://localhost:8000" --rpcapi="personal,eth,network,web3,net" --ipcpath "~/Library/Ethereum/geth.ipc"
with  **--rpcaddr "0.0.0.0"**  removed

**Comment by samaujs** [comment] 2018-06-15 04:51
Also opened issue in geth :
**Reference to issue "Ethers are wiped out in account during sendTransaction or migrations #16936" #16992**

**Comment by cgewecke** [comment] 2018-06-15 14:30
Thanks @samaujs - will repost the response you received above for anyone else running into this. Once an account has been exposed to an attack made possible by leaving a local client open on `--rpcaddr "0.0.0.0"` it is **no longer usable**.  More detailed explanation from Geth:

>  The issue here is that an attacker can pre-sign arbitrarily many transactions ahead of time. Once they find an unlocked account accessible over the internet, they will just sign many many many transactions into the future, so whenever there are funds, they can drain it without having access any more to the original account.

> The only way out is to use a new account which wasn't leaked out.

Closing as duplicate of #997

**Closed by cgewecke** 2018-06-15 14:30 UTC
