### ISSUE TITLE
function return data corrupted in browser

### ISSUE THREAD

**Issue by oddmarthon-lende** [trufflesuite/truffle#612] opened 2017-10-10 17:57 UTC
## Issue

In the browser the return data for a contract function is corrupted. In truffle console it looks ok and also in remix ide. I tried reordering and putting the arrays last, but then they are always empty. Im running truffle with webpack.

## Steps to Reproduce

Create a contract

`

      contract Test  {

         function test() public constant returns (bytes32, bytes32, bytes32, bytes32[] memory, bytes16[] memory, bytes16, uint8, bool, uint) {

             bytes16[] memory t = new bytes16[](4);
             bytes32[] memory u  = new bytes32[](4);

             return ("s.title", "s.hash", "s.directory", t, u, "s.category", 120, true, now);
           }
      }

`

Then access the function from the browser

`
      Test.deployed().then((t) => {
           t.test.call().then((response) => {
               console.log(response);
            }
        });
`

## Expected Behavior

That the data is correct for all the fields in the return data

## Actual Results

[Browser Screenshot](https://www.dropbox.com/s/f5xp8p1ybt5uxn1/browser.png?dl=1)
[Truffle Console screenshot](https://www.dropbox.com/s/pgue36dqugdzes1/console.png?dl=1)

## Environment

* Operating System: macOS Sierra 10.12.6
* Chrome version: 61.0.3163.100 (Official Build) (64-bit)
* Truffle version: 3.4.11 (core: 3.4.11)
* Ethereum client: TestRPC v4.1.3 (ganache-core: 1.1.3)
* node version: 6.11.0
* npm version: 3.10.10

**Comment by cgewecke** [comment] 2018-01-26 19:12
@oddmarthon-lende Apologies for the delay in getting to this - I wasn't able to reproduce this issue. When I look at the two images you provided, it seems like the data values are different for several fields in the return object which suggests the issue might be a difference locally - different versions of the same contract perhaps? 

**Browser**
<img width="414" alt="browser 3" src="https://user-images.githubusercontent.com/7332026/35456192-8958489c-0289-11e8-9149-6d4ed28c367d.png">

**Console**
<img width="636" alt="console 2" src="https://user-images.githubusercontent.com/7332026/35456222-9a65f5e4-0289-11e8-8679-3632e989ad92.png">



Closing this for house-keeping since it's been open for a while but please re-open if you're still seeing this unusual behavior with the latest Truffle.

**Closed by cgewecke** 2018-01-26 19:12 UTC
