### ISSUE TITLE
metamask syncing problem with local RPC

### ISSUE THREAD

**Issue by mahiruddinseikh** [trufflesuite/truffle#925] opened 2018-04-28 13:53 UTC
We had trouble loading your token balances. You can view them here

**Comment by cgewecke** [comment] 2018-04-28 15:38
@mahiruddinseikh Apologies - you've provided almost no information in your issue that helps people identify what the problem is or what context you're running in. Closing - if you re-open please fill out each field in the provided issues template.

**Closed by cgewecke** 2018-04-28 15:38 UTC
