### ISSUE TITLE
Truffle source code spills onto console when migration deploys contract with mismatching number of arguments

### ISSUE THREAD

**Issue by deluca-mike** [trufflesuite/truffle#3495] opened 2020-11-03 19:53 UTC
## Issue

Truffle spills its guts onto the console when migration script deploys a contract with mismatching number of arguments.

## Steps to Reproduce

Create contract that takes 3 arguments, yet pass it 4 arguments in the migration script. Run migrate and watch the console just fill up with source code for about 10 minutes.

## Expected Behavior

Just a normal error so that I can move on.

## Actual Results

It fills the entire console with endless source code for about 10 minutes. Unstoppably.

![Screen Shot 2020-11-03 at 2 49 10 PM](https://user-images.githubusercontent.com/35537333/98033624-cbdd6d00-1de3-11eb-8df3-6ec6cada3fc9.png)
![Screen Shot 2020-11-03 at 2 50 57 PM](https://user-images.githubusercontent.com/35537333/98033793-01825600-1de4-11eb-8724-493cb44f4ff3.png)

## Environment

* Operating System: MacOS 10.15.7 
* Ethereum client: Ganache
* Truffle version (`truffle version`): Truffle v5.1.51 (core: 5.1.51)
* node version (`node --version`): 14.12.0
* npm version (`npm --version`): 6.14.8

**Comment by gnidan** [comment] 2020-11-04 18:38
Yikes! Well, we're gonna have to reproduce this and try to fix it. Thanks for reporting!

**Comment by eggplantzzz** [comment] 2020-11-11 18:54
Any chance you could provide a simple example with maybe a toy project for reproducing this?

**Comment by deluca-mike** [comment] 2020-11-20 05:51
@eggplantzzz I don't really have much time, however, if you pull this [my project](https://github.com/circle-free/optimistic-roll-in) and modify `optimistic-roll-in/eth/migrations/2_deploy_contracts.js` to pas in one less or one more argument for the deployer on line 11, it should give you the error. (Not, you may need a root-level `.infura` and `.mnemonic` file to exist, because my `truffle-config` depends on them existing)

**Comment by deluca-mike** [comment] 2020-12-04 22:41
I realize this is an issue that only occurs if the developer (me) makes an error, but it's still a nuisance and a half.
(I'm writing this to kill time while my console blows up with Truffle source code again...)

**Comment by eggplantzzz** [comment] 2020-12-08 21:18
Hmm, I'm not sure what is going wrong for you but I am unable to reproduce your error. I added infura details, added an extra parameter to line 11 as you recommended and got the following:
<img width="1397" alt="Screen Shot 2020-12-08 at 4 17 35 PM" src="https://user-images.githubusercontent.com/14827965/101542607-00a78b80-3971-11eb-9bac-d78eceb5840c.png">

I wonder why your code is acting up...

**Comment by fainashalts** [comment] 2021-01-13 19:09
Hi @deluca-mike we haven't been able to reproduce this issue, are you still encountering problems with this?

**Comment by gnidan** [comment] 2021-04-21 18:46
Closing this for issue maintenance. Let us know if you're still looking for this to get fixed and we can reopen. Thanks!

**Closed by gnidan** 2021-04-21 18:46 UTC
Labels: Migrations, bug, error better, needs reproduced
