### ISSUE TITLE
better logging on revert

### ISSUE THREAD

**Issue by pdlla** [trufflesuite/truffle#2881] opened 2020-03-12 03:55 UTC
Right now, if a contract ever reverts, `truffle test` just crashes and gives no useful error messages. This seems like a big miss as one expects test to fail during development. It would be really nice if:

1. it gave better output. In particular, it would great if it could print the failed transaction so it can be used for debugging. Right now I have to find it inside of my ganache console. 
2. it didn't crash

```
truffle(development)> test

....

  Contract: Helper
    ✓ print code sizes

  Contract: Government
Government: 6888 bytes out of 24577 %0.2802620336086585 capacity.
    ✓ initial state test (68ms)
    ✓ PotatoERC20 test (92ms)
    ✓ Animal (107ms)
Error: Returned error: VM Exception while processing transaction: revert ERC20: transfer amount exceeds allowance -- Reason given: ERC20: transfer amount exceeds allowance.
Error: Returned error: VM Exception while processing transaction: revert ERC20: transfer amount exceeds allowance -- Reason given: ERC20: transfer amount exceeds allowance.

/Users/user/.config/truffle/compilers/node_modules/soljson-v0.6.0+commit.26b70077.js:1
"use strict";var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,
abort(Error: Returned error: VM Exception while processing transaction: revert ERC20: transfer amount exceeds allowance -- Reason given: ERC20: transfer amount exceeds allowance.). Build with -s ASSERTIONS=1 for more info.
(Use `node --trace-uncaught ...` to show where the exception was thrown)
~/kitchen/faucet/P2CBG_design/potato_game_code:master$
```

Note the above example was fairly benign. The really annoying one I had was when it reverted because my contract size exceeded the 24kb limit but the VM reported "out of gas" for some reason (I had plenty of gas left). The 24kb limit issue (during deployments) is probably a separate issue but the lack of good error messages on VM reverts is seems to be the root cause.

**Comment by eggplantzzz** [comment] 2020-03-18 17:43
@pdlla Thanks for reporting this! Actually this is partially a duplicate of [this](https://github.com/trufflesuite/truffle/issues/1655). The "out of gas" error is actually the specification. See [this](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md).

What are you doing to get your tests failing as they do in your example? I don't think tests always fail like that. If you can give me repro steps we can try and figure out why the output is so junky.

**Comment by pdlla** [comment] 2020-03-18 18:15
I set gananche block gas limit to something very high. I deployed like 3 variations of ERC20/ERC721 contracts in my contract and that was enough to exceed the code size limit. I didn't realize it was so small D:.

I've since split them out and added this helper function to my migrations to track how close I'm getting to the limit

```
async function logGasContract(instance) {
  txr = await web3.eth.getTransactionReceipt(instance.transactionHash)
  const gasUsed = parseInt(txr.gasUsed);
  logGasUsed(gasUsed, instance.constructor._json.contractName);
}
```

Thx for sharing the EIP. Kind of makes sense they piggy backed on an existing error message to make the hardfork as seamless as possible. Thanks for the info. 

Generally speaking, it would be great if truffle gave better logging and analytics for gas usage both in test cases and deployments. These issues are very hard to comprehend and even harder to track down for new developers. Thankfully, I've worked with geth a lot so it was much easier for me.

I've been adding my own helper methods like the above to track things like this. Maybe I'll look into making a PR. Unfortunately I'm not exactly a JS developer so these helper functions are just `console.log` hacks to get me through my task.

**Comment by gnidan** [comment] 2020-03-25 17:59
Hey do you know about [eth-gas-reporter](https://github.com/cgewecke/eth-gas-reporter)? It plugs into your `truffle test` and gives you a table listing gas cost of each contract function as executed by your tests. Might be what you're looking for? Let us know! Thanks!

**Comment by eggplantzzz** [comment] 2020-04-01 17:47
@pdlla Do you get the kind of garbage output you pasted above? There might have been something that fixed this recently...I can't remember. Let us know!

**Comment by haltman-at** [comment] 2020-05-06 18:11
Closing for issue maintenance.  Please let us know if there's still a problem and we can reopen this.

**Closed by haltman-at** 2020-05-06 18:11 UTC
