### ISSUE TITLE
npm test failing on Vyper checks 

### ISSUE THREAD

**Issue by Mordax** [trufflesuite/truffle#1338] opened 2018-10-14 02:48 UTC
## Issue

npm test fails on Windows, fails at Vyper checks.

## Steps to Reproduce

Install Lerna, Yarn, run bootstrap, then npm test. Git Bash and Admin Command Prompt 
has the same issue.

## Expected Behavior

All checks pass.

## Actual Results

```bash
yarn run v1.10.1
$ mocha --colors
truffle-compile-vyper:
truffle-compile-vyper:   vyper compiler
truffle-compile-vyper:     1) compiles vyper contracts
truffle-compile-vyper:     2) skips solidity contracts
truffle-compile-vyper:   0 passing (85ms)
truffle-compile-vyper:   2 failing
truffle-compile-vyper:   1) vyper compiler
truffle-compile-vyper:        compiles vyper contracts:
truffle-compile-vyper:      Uncaught AssertionError [ERR_ASSERTION]: Compiles without error
truffle-compile-vyper:       at D:\truffle\packages\truffle-compile-vyper\test\test_compiler.js:18:14
truffle-compile-vyper:       at D:\truffle\packages\truffle-compile-vyper\index.js:160:21
truffle-compile-vyper:       at D:\truffle\packages\truffle-compile-vyper\index.js:77:21
truffle-compile-vyper:       at ChildProcess.exithandler (child_process.js:282:5)
truffle-compile-vyper:       at maybeClose (internal/child_process.js:925:16)
truffle-compile-vyper:       at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
truffle-compile-vyper:
truffle-compile-vyper:   2) vyper compiler
truffle-compile-vyper:        skips solidity contracts:
truffle-compile-vyper:      Uncaught AssertionError [ERR_ASSERTION]: Compiles without error
truffle-compile-vyper:       at D:\truffle\packages\truffle-compile-vyper\test\test_compiler.js:48:14
truffle-compile-vyper:       at D:\truffle\packages\truffle-compile-vyper\index.js:160:21
truffle-compile-vyper:       at D:\truffle\packages\truffle-compile-vyper\index.js:77:21
truffle-compile-vyper:       at ChildProcess.exithandler (child_process.js:282:5)
truffle-compile-vyper:       at maybeClose (internal/child_process.js:925:16)
truffle-compile-vyper:       at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
truffle-compile-vyper:
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run test --colors
error Command failed with exit code 2.
lerna ERR!
yarn run v1.10.1
$ mocha --colors
lerna ERR!
lerna ERR!
lerna ERR!   vyper compiler
lerna ERR!     1) compiles vyper contracts
lerna ERR!     2) skips solidity contracts
lerna ERR!
lerna ERR!
lerna ERR!   0 passing (85ms)
lerna ERR!   2 failing
lerna ERR!
lerna ERR!   1) vyper compiler
lerna ERR!        compiles vyper contracts:
lerna ERR!      Uncaught AssertionError [ERR_ASSERTION]: Compiles without error
lerna ERR!       at D:\truffle\packages\truffle-compile-vyper\test\test_compiler.js:18:14
lerna ERR!       at D:\truffle\packages\truffle-compile-vyper\index.js:160:21
lerna ERR!       at D:\truffle\packages\truffle-compile-vyper\index.js:77:21
lerna ERR!       at ChildProcess.exithandler (child_process.js:282:5)
lerna ERR!       at maybeClose (internal/child_process.js:925:16)
lerna ERR!       at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
lerna ERR!
lerna ERR!   2) vyper compiler
lerna ERR!        skips solidity contracts:
lerna ERR!      Uncaught AssertionError [ERR_ASSERTION]: Compiles without error
lerna ERR!       at D:\truffle\packages\truffle-compile-vyper\test\test_compiler.js:48:14
lerna ERR!       at D:\truffle\packages\truffle-compile-vyper\index.js:160:21
lerna ERR!       at D:\truffle\packages\truffle-compile-vyper\index.js:77:21
lerna ERR!       at ChildProcess.exithandler (child_process.js:282:5)
lerna ERR!       at maybeClose (internal/child_process.js:925:16)
lerna ERR!       at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
lerna ERR!
lerna ERR!
lerna ERR!
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (D:\truffle\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: yarn run test --colors
error Command failed with exit code 2.

yarn run v1.10.1
$ mocha --colors


  vyper compiler
    1) compiles vyper contracts
    2) skips solidity contracts


  0 passing (85ms)
  2 failing

  1) vyper compiler
       compiles vyper contracts:
     Uncaught AssertionError [ERR_ASSERTION]: Compiles without error
      at D:\truffle\packages\truffle-compile-vyper\test\test_compiler.js:18:14
      at D:\truffle\packages\truffle-compile-vyper\index.js:160:21
      at D:\truffle\packages\truffle-compile-vyper\index.js:77:21
      at ChildProcess.exithandler (child_process.js:282:5)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

  2) vyper compiler
       skips solidity contracts:
     Uncaught AssertionError [ERR_ASSERTION]: Compiles without error
      at D:\truffle\packages\truffle-compile-vyper\test\test_compiler.js:48:14
      at D:\truffle\packages\truffle-compile-vyper\index.js:160:21
      at D:\truffle\packages\truffle-compile-vyper\index.js:77:21
      at ChildProcess.exithandler (child_process.js:282:5)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)



info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (D:\truffle\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '\u001b[2K\u001b[1G\u001b[1myarn run v1.10.1\u001b[22m\u001b[m\n\u001b[2K\u001b[1G\u001b[2m$ mocha --colors\u001b[22m\n\n\u001b[0m\u001b[0m\n\u001b[0m  vyper compiler\u001b[0m\n  \u001b[31m  1) compiles vyper contracts\u001b[0m\n  \u001b[31m  2) skips solidity contracts\u001b[0m\n\n\n\u001b[92m \u001b[0m\u001b[32m 0 passing\u001b[0m\u001b[90m (85ms)\u001b[0m\n\u001b[31m  2 failing\u001b[0m\n\n\u001b[0m  1) vyper compiler\n       compiles vyper contracts:\n\u001b[0m\u001b[31m     Uncaught AssertionError [ERR_ASSERTION]: Compiles without error\u001b[0m\u001b[90m\n      at D:\\truffle\\packages\\truffle-compile-vyper\\test\\test_compiler.js:18:14\n      at D:\\truffle\\packages\\truffle-compile-vyper\\index.js:160:21\n      at D:\\truffle\\packages\\truffle-compile-vyper\\index.js:77:21\n      at ChildProcess.exithandler (child_process.js:282:5)\n      at maybeClose (internal/child_process.js:925:16)\n      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)\n\u001b[0m\n\u001b[0m  2) vyper compiler\n       skips solidity contracts:\n\u001b[0m\u001b[31m     Uncaught AssertionError [ERR_ASSERTION]: Compiles without error\u001b[0m\u001b[90m\n      at D:\\truffle\\packages\\truffle-compile-vyper\\test\\test_compiler.js:48:14\n      at D:\\truffle\\packages\\truffle-compile-vyper\\index.js:160:21\n      at D:\\truffle\\packages\\truffle-compile-vyper\\index.js:77:21\n      at ChildProcess.exithandler (child_process.js:282:5)\n      at maybeClose (internal/child_process.js:925:16)\n      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)\n\u001b[0m\n\n\n\u001b[2K\u001b[1G\u001b[94minfo\u001b[39m Visit \u001b[1mhttps://yarnpkg.com/en/docs/cli/run\u001b[22m for documentation about this command.\n',
  stderr: '\u001b[2K\u001b[1G\u001b[31merror\u001b[39m Command failed with exit code 2.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run test --colors',
  timedOut: false,
  exitCode: 1 }
npm ERR! Test failed.  See above for more details.
```

## Environment

* Operating System: Windows 10
* Ethereum client: Is it needed for running developer tests on Truffle? 
* Truffle version (`truffle version`): v4.1.14 
* node version (`node --version`): v8.11.4
* npm version (`npm --version`): 6.1.0

**Comment by gnidan** [comment] 2018-10-14 23:07
Thanks for raising this issue! I opened #1336 recently, to address the problem of tests with external dependencies running locally. Closing this issue as duplicate of that.

**Closed by gnidan** 2018-10-14 23:07 UTC
