### ISSUE TITLE
Default Truffle project gives 'Expected parameter 'from' not passed to function.' error after 'truffle migrate' command

### ISSUE THREAD

**Issue by linkas45** [trufflesuite/truffle#548] opened 2017-08-29 11:20 UTC
## Issue

I want to create a default generated project working with Truffle. After running the commands `truffle init`, `truffle compile` and `truffle migrate` I got the error: `Expected parameter 'from' not passed to function.` The geth rpc is successfully running in the other window of Terminal so it's not a problem.

## Expected Behavior

I expect Truffle to start deploying migrations for the default Truffle project.

## Actual Results

```
Using network 'development'.

/usr/local/lib/node_modules/truffle/build/cli.bundled.js:23538
        throw new Error("Expected parameter '" + key + "' not passed to function.");
        ^

Error: Expected parameter 'from' not passed to function.
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:23538:15
    at Array.forEach (<anonymous>)
    at Object.options (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:23536:19)
    at Object.run (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:66868:12)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:88946:23
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:67033:9
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:66861:7
    at done (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:155469:5)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:155526:11
    at FSReqWrap.oncomplete (fs.js:153:5)
```

## Environment

* Operating System: macOS Sierra
* Truffle version: 3.4.9
* Ethereum client: Geth 1.6.7
* node version: 8.3.0
* npm version: 5.3.0

**Comment by 86me** [comment] 2017-09-06 05:45
I'm receiving the same error. Just trying to follow the truffle token tutorial.

```
╰ % truffle migrate                                                                        10:43 PM 1 ↵
Using network 'development'.

/usr/local/lib/node_modules/truffle/build/cli.bundled.js:23538
        throw new Error("Expected parameter '" + key + "' not passed to function.");
        ^

Error: Expected parameter 'from' not passed to function.
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:23538:15
    at Array.forEach (<anonymous>)
    at Object.options (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:23536:19)
    at Object.run (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:66868:12)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:88946:23
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:67033:9
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:66861:7
    at done (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:155469:5)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:155526:11
    at FSReqWrap.oncomplete (fs.js:153:5)
```


MacOS 10.11.1
Truffle v3.4.9 (core: 3.4.8)
geth 1.6.7-stable-ab5646c5
node: stable 8.4.0 (bottled), HEAD
npm 5.3.0

**Comment by leopoldjoy** [comment] 2017-09-07 06:59
@linkas45 @86me Adding a default `from` field to the `truffle.js` file solved this problem for me, [see here](https://github.com/leopoldjoy/truffle-init-default/blob/d7931872e85e1e43e69292663d790e63f01f77b6/truffle.js#L7). I created a pull request for the fix: https://github.com/trufflesuite/truffle-init-default/pull/3.

**Comment by casidiablo** [comment] 2017-09-07 16:02
This usually happens if the running node has no accounts. By default, it seems that truffle will try to deploy the contracts using the first account available, which can be manually forced using the `from` property in the config.

**Comment by leopoldjoy** [comment] 2017-09-07 18:49
@casidiablo Yes, I think you're right. The error `Expected parameter 'from' not passed to function` ([from here](https://github.com/trufflesuite/truffle-expect/blob/f335f791cabc5fccaad2d7c2bcea776c9e002a6f/index.js#L5)) seems unclear to me since it doesn't express the actual problem: the running node has no accounts. Once you specify the `from` field in `truffle.js` you get the slightly more logical error: `Error: unknown account`. Do you think it makes sense to have the `from` field set [by default](https://github.com/leopoldjoy/truffle-init-default/blob/d7931872e85e1e43e69292663d790e63f01f77b6/truffle.js#L7)? Or maybe there should be a clearer error if the node has no accounts?

**Comment by 86me** [comment] 2017-09-07 20:38
@casidiablo Adding a 'from' paramater to truffle.js got me past this error. Only to open up another issue
```
╰ % truffle migrate                                                                         1:30 PM 1 ↵
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: unknown account
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:37295:16)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:224765:36
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:66971:11
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:208348:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:209773:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67130:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67420:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67575:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:67535:24)
    at emitNone (events.js:110:20)
```

Not sure why it's saying unknown account, because I'm currently running a testnet with a custom genesis block and an open rpc port with the specified account. I know the account exists; this is the output from an attached console:
```
> eth.coinbase
"0x6498b84547e91c853a4ecf0254589d3464d2444c"
> eth.getBalance(eth.coinbase)
5000000000000300000
```
The unknown account error I'm getting know is odd, because before I created my private network, I was getting an "insufficient gas" error using the same account, on the live network.

I will keep trying, and open up a different issue if I can't figure this out.

**Comment by casidiablo** [comment] 2017-09-07 21:44
That sucks. Does it happen if you deploy against an official testnet? Rinkeby for example.

**Comment by 86me** [comment] 2017-09-07 22:55
@casidiablo Yes, it worked when deployed with ```geth --testnet --rpc```. Just had to lower the gas threshhold. Not sure what the difference was, but I'll take it.

Thanks for your help.

**Comment by DeveloperUX** [comment] 2017-10-08 23:34
@86me Can you post what your `truffle.js` ended up looking like? I'm running into the same issue, played around with `gas` and the address in `from` but to no avail.

I'm trying to use the **ropsten** testnet:

```
networks: {
    "ropsten": {
      host: "localhost", // Connect to geth on the specified
      port: 8545,
      from: "0xf5071a2d92135545eaedffba45df5d3e7adbcfee", // default address to use for any transaction Truffle makes during migrations
      network_id: 3,  // The Ropsten testnet
      gas: 4612388 // Gas limit used for deploys
    }
}
```

**Comment by 86me** [comment] 2017-11-11 04:13
@DeveloperUX This is my current `truffle.js`

```
module.exports = {
  rpc: {
      host:"localhost",
      port:8545
  },
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "1337",
      from: "0x572857f9a9a59bdef971394f256f657dc963f1f5",
      gasPrice: 100000000000,
      gas: 4712388
    },
    rinkeby: {
      host: "localhost",
      port: 8545,
      network_id: "4",
      gas: 4712388,
      gasPrice: 100000000000,
      from: "0x79a1b6fecfa9c954803d2b59773fadc39d063e64"
    }
  }
};
```
I would try removing the quotes around `"ropsten"`.

**Comment by 86me** [comment] 2017-11-11 04:20
@DeveloperUX Another technique I've found helpful when getting unexpected **"out of gas"** error messages is to pass the properties through the constructor in `deployer.deploy()` in `2_deploy_contracts.js`. Here's an example:
```
var MyContract = artifacts.require("./MyContract.sol");

module.exports = function(deployer) {
  ...
  deployer.deploy(MyContract, startTime, endTime, wallet, { gas: 4712388 });
};
```

**Comment by stefek99** [comment] 2017-11-25 00:38
# please update error message

Very often there are deprecation warning.

A lot of old tutorials are using old syntax.

> throw new Error("Expected parameter '" + key + "' not passed to function.");

> Error: Expected parameter 'from' not passed to function.

Google works well, this issue is the first result but still... Updating error message is an easy job that will save some time.

**Comment by Shrugs** [comment] 2018-04-17 17:29
for googlers: you may also have something else running on 8545 (like an ssh session) that truffle doesn't respond to correctly. this is the error that comes up in that case.

**Comment by holyxiaoxin** [comment] 2018-06-07 07:45
@shrugs you're right, I had parity running on 8545!

**Comment by mjibril** [comment] 2018-08-28 19:44
I still had the same issue despite doing as @86me suggested. It turned out I had previously created an account with 

`geth account new`

and the account was not found.
If you are using the testnet network you need to create a different account with

`geth --testnet account new`

**Comment by RobinJQ** [comment] 2018-11-15 08:58
I have the same problem! What is the solution??

**Comment by gnidan** [comment] 2019-01-09 18:50
Does this problem still exist on Truffle v5? Thanks!

**Comment by marsrobertson** [comment] 2019-04-30 09:32
https://github.com/trufflesuite/truffle/issues/548#issuecomment-382076559

> that truffle doesn't respond to correctly

In `truffle.js` I had some things commented out. Uncommented, now using:

```
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*", // Match any network id
      gas: 6000000
    }
  }
};
```

* Now getting another error: `TypeError: this.provider.sendAsync is not a function`
* Which is (most likely) caused by incompatible version on web3.js: https://github.com/ethereum/web3.js/issues/1742#issuecomment-421332983
* Which is caused by code I'm integrating using `pragma solidity ^0.4.15;` *(that's why using an old versions of Truffle)*
* Oh yes, now I remember, I wanted to debug units tests: https://ethereum.stackexchange.com/a/43633/2524

**Comment by CruzMolina** [comment] 2019-04-30 15:21
Hey @marsrobertson , if I'm following correctly, you're using a v4 version of Truffle, and locally using an incompatible version of web3? Trying to grok the context of the bug you're seeing.

**Comment by CplXhristianUSMC** [comment] 2019-05-01 01:13
Thank you so much for your reply I'm sorry that it's taking me so long to
get back to your emails currently I'm in the process of moving and will be
driving no less than 1300 miles tonight across state lines to get to my new
house please forgive any late replies I greatly appreciate any and all work
that you have been doing to help rectify this matter truly thankful and
gratefully yours cplxhristianusmc

**Comment by eggplantzzz** [comment] 2019-06-19 17:54
Looks like this is not a thing any more. Closing this but please feel free to comment if I made a mistake! Thanks!

**Closed by eggplantzzz** 2019-06-19 17:54 UTC

**Comment by sg552** [comment] 2022-07-09 01:38
If using `truffle`, you should best always specify the `--network` option. e.g.

```
truffle migrate --f 9 --network=ganache
```
