### ISSUE TITLE
Truffle init fails to create new project behind a proxy

### ISSUE THREAD

**Issue by davebryson** [trufflesuite/truffle#380] opened 2017-03-23 12:56 UTC
OSX
Truffle: 3.2.1 (but I saw the same problem with earlier 3.x versions as well)
Node: 6.2.2
Npm: 3.9.3

I've used truffle for some time now,  but the recent updates with the way `init` pulls from github is causing problems behind a proxy.    Currently `truffle init` fails to create a new project with

`Error: connect ECONNREFUSED 151.101.56.133:443`

**Comment by simbro** [comment] 2017-05-08 13:49
Did you ever find a solution for this?  I'm having the exact same issue:

```
> truffle init

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ENETUNREACH xxx.xxx.xx.xxx:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

I'm running:
 * Truffle v3.2.1
 * Node v6.9.5
 * NPM 3.10.10

on Ubuntu 14.04

**Comment by christianlundkvist** [comment] 2017-05-16 13:45
I'm seeing this problem when offline. When online: works fine. When offline:

```
chris@chris-VBox:~/tmp/truffle_test$ truffle init
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com:443
    at Object.exports._errnoException (util.js:1026:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
```

**Comment by Shreekavithaa** [comment] 2017-06-22 12:17
Same issue for me too. Any solution?

**Comment by tcoulter** [comment] 2017-07-12 15:18
Marking as a duplicate of trufflesuite/truffle-init#1. See that ticket for more info.

**Closed by tcoulter** 2017-07-12 15:18 UTC
