### ISSUE TITLE
Cannot destructure property `body` of 'undefined' or 'null' (5.1.10 to any later version)

### ISSUE THREAD

**Issue by slmatthiesen** [trufflesuite/truffle#2834] opened 2020-02-17 07:46 UTC
- [ X ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue. 
Didn't see anything there. 
I didn't see anything in the release notes that called anything out. 
Looks like another related issue here: 
https://github.com/trufflesuite/truffle/issues/1574 and https://github.com/trufflesuite/truffle/issues/1365 and https://github.com/trufflesuite/truffle/issues/991 and https://github.com/trufflesuite/truffle/issues/1936
with zero info.

I've been using truffle with the same contract consistently for a while now (6 months easily). This latest upgrade 5.1.10 to 5.1.13 (I missed one) is the first time I've seen this error. Wondering if anyone else has.

## Solution

Downgrading to 5.1.10 allows me to  truffle migrate --network development without issue.

---------------------------

## Issue

I've been using the same contract for 6+ months. After upgrading from 5.1.10 to 5.1.1x , I started getting this error when attempting to launch my contract on any network:

**Cannot destructure property `body` of 'undefined' or 'null'**

Downgrading to 5.1.10 allows me to launch my contract again. Worked my way down from 5.1.13 to 5.1.10.

## Steps to Reproduce

truffle migrate --network development
or
truffle migrate --network ropsten

## Expected Behavior

My contract would compile and launch as expected.

## Actual Results

√ Fetching solc version list from solc-bin. Attempt #1
Error: TypeError: Error parsing C:/Users/Mine/Projects/project/contracts/Contract.sol: Cannot destructure property `body` of 'undefined' or 'null'.
    at Object.compile (C:\Users\Mine\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\workflow-compile\legacy\index.js:80:1)

## Environment

* Operating System: Windows
* Ethereum client:
* Truffle version (`truffle version`): 5.1.13
* node version (`node --version`): 12.15.0
* npm version (`npm --version`): 6.13.7

**Comment by CruzMolina** [comment] 2020-02-17 16:46
Hey @slmatthiesen ! 👋 

Can you share a reproduction repo for debugging purposes?

**Comment by readme55** [comment] 2020-02-19 11:27
I'm getting the error doing the pet-shop tutorial - executing 'truffle test':

```
  TestAdoption
    1) "before all" hook: prepare suite


  0 passing (438ms)
  1 failing

  1) TestAdoption
       "before all" hook: prepare suite:
     TypeError: Error parsing c:/Users/rm/Documents/Projects/pet-shop-tutorial/contracts/Adoption.sol: Cannot destructure property `body` of 'undefined' or 'null'.
      at getImports (C:\Users\rm\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\profiler\getImports.js:5:1)
      at C:\Users\rm\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\profiler\index.js:145:1
```

truffle version
Truffle v5.1.13 (core: 5.1.13)
Solidity v0.5.16 (solc-js)
Node v12.14.0
Web3.js v1.2.1

**Comment by CruzMolina** [comment] 2020-02-19 16:23
Thanks for sharing that @readme55 !

I notice both you and @slmatthiesen are on Windows 🤔 .

**Comment by CruzMolina** [comment] 2020-02-19 16:50
Investigated a bit, this looks like a compilation OS-compatibility path issue.

**Comment by gnidan** [comment] 2020-02-19 18:49
Hooray a path compatibility issue! We'll have to dig into this. Thanks for raising this!

**Comment by CruzMolina** [comment] 2020-02-19 19:00
Actually, it might be a missing `return` in this PR (merged & released in v5.1.11) to get rid of some callbacks in the resolver code (specifically `resolver/fs`): https://github.com/trufflesuite/truffle/pull/2693/files#diff-741d320df0fc163eac3fec99a9e78b75R65

cc @eggplantzzz

**Comment by slmatthiesen** [comment] 2020-02-20 05:34
Big ups to @readme55 
Thank you all and sorry for my delay in reply.

**Comment by eggplantzzz** [comment] 2020-02-20 14:33
Does anyone have reproduction steps for this error? It would be super helpful in diagnosing this. So far it looks like we only have a vague guess as to what is causing this.

**Comment by slmatthiesen** [comment] 2020-02-20 16:42
Sure thing -

On a windows machine, install truffle 5.1.13.
Setup the petshop: https://www.trufflesuite.com/tutorials/pet-shop
(Compact Sol files) 
[Adoption.sol] 
pragma solidity ^0.5.0;
contract Adoption {
    address[16] public adopters;
    function adopt(uint petId) public returns (uint) {
    require(petId >= 0 && petId <= 15);
    adopters[petId] = msg.sender;
    return petId;
    }
    function getAdopters() public view returns (address[16] memory) {
    return adopters;
    }
}
and
[TestAdoption.sol]
pragma solidity ^0.5.0;
import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Adoption.sol";
contract TestAdoption {
Adoption adoption = Adoption(DeployedAddresses.Adoption());
uint expectedPetId = 8;
address expectedAdopter = address(this);
    function testUserCanAdoptPet() public {
    uint returnedId = adoption.adopt(expectedPetId);
    Assert.equal(returnedId, expectedPetId, "Adoption of the expected pet should match what is returned.");
    }
    function testGetAdopterAddressByPetId() public {
    address adopter = adoption.adopters(expectedPetId);
    Assert.equal(adopter, expectedAdopter, "Owner of the expected pet should be this contract");
    }
    function testGetAdopterAddressByPetIdInArray() public {
    address[16] memory adopters = adoption.getAdopters();
    Assert.equal(adopters[expectedPetId], expectedAdopter, "Owner of the expected pet should be this contract");
    }
}

Then run truffle test and you'll hit the 
       "before all" hook: prepare suite:
     TypeError: Error parsing C:/Users/___/Projects/pet-shop-tutorial/contracts/Adoption.sol: Cannot destructure property `body` of 'undefined' or 'null'.
      at getImports (C:\Users\____\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\profiler\getImports.js:5:1)
      at C:\Users\_____\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\profiler\index.js:145:1

Probably the fastest way to see the error.

**Comment by eggplantzzz** [comment] 2020-02-20 19:23
Thanks very much @slmatthiesen! I'll see if I can duplicate this on my mac.

**Comment by eggplantzzz** [comment] 2020-02-20 21:49
So I can confirm that your code example is able to run `truffle test` successfully on a mac. I had to add a migration to deploy the Adoption contract, but afterwards everything works fine. I'll have to see if I can test it on a Windows machine.

**Comment by topnotchbiz** [comment] 2020-03-04 15:10
Thanks @slmatthiesen and thanks you @CruzMolina . I had same issue using v5.1.15 and the old v5.1.10 solved my issue. Thanks again.

**Comment by 24thsaint** [comment] 2020-03-13 18:24
@topnotchbiz downgrading solved my issue. Thank you! 
---
Running on Windows with the following versions when this issue occurred:

Truffle v5.1.15 (core: 5.1.15)
Solidity - 0.5.16 (solc-js)
Node v13.5.0
Web3.js v1.2.1

**Comment by 3rdstage** [comment] 2020-03-24 08:09
I also met this problem right after upgrading to v5.1.18.   I had tested this on my Windows 7 laptop with Node.js 10.15  and Ubuntu 16 guest of Virtual Boxy with Node.js 10.19, and found the same problem.
Deleting files under build directory ('build/contracts/*.json' files) doesn't help at all.


I downgraded my Truffle back to v5.1.9 and the problem disappeared.  So, this problem is taught to appear after v5.1.10.

**Comment by ReedAlan** [comment] 2020-03-27 12:57
Same happens to me on windows 10 (64bit)

C:\Users\Alan\Documents\DAPPS\pet-shop-tutorial>truffle version
Truffle v5.1.19 (core: 5.1.19)
Solidity v0.5.16 (solc-js)
Node v13.11.0
Web3.js v1.2.1

**Comment by 4math2379** [comment] 2020-03-31 21:35
i got the same issue with 5.1.19 / when i downgrade to 5.1.9 all compile perfectly.

I try to investigate the issue, but i really don't know where it come from.

**Comment by ajlopez** [comment] 2020-04-05 15:51
Today, I got this error, with truffle 5.1.14 in Windows 10

I removed `build` directory, and then `truffle compile` worked

**Comment by ReedAlan** [comment] 2020-04-05 18:22
Oh. Well for me  on windows 10, even after I removed the build directory from pet-shop-tutorialTruffle compile is OkTruffle migrate is OkTruffle test fails with the above error.Truffle version givesTruffle v5.1.14 (core: 5.1.14)Solidity - 0.5.10 (solc-js)Node v13.11.0Web3.js v1.2.1Alan Reed On 5 Apr 2020 16:51, ajlopez <notifications@github.com> wrote:
Today, I got this error, with truffle 5.1.14 in Windows 10
I removed build directory, and then truffle compile worked

**Comment by slmatthiesen** [comment] 2020-04-06 18:11
With the new release out (5.1.20) I thought I'd give it a try again.

1. npm uninstall -g truffle
2. npm install -g truffle
3. Deleted my .json files in the build folder.
4. truffle migrate --reset --network development

And the same project that didn't compile for me a month+ ago **now compiled successfully!**

Give it a try if you are having issues. If you need to revert just:
npm uninstall -g truffle
npm install -g truffle@5.1.10  (always got me back on track)

**Comment by pauliax** [comment] 2020-04-08 04:50
Also experienced this issue with _Truffle 5.1.20_
Had to downgrade:
_npm install truffle@5.1.9 -g_

**Comment by michaeldurocher** [comment] 2020-04-19 16:33
I experienced the same issue on Windows 10  (truffle@5.1.22) while using the MetaCoin box.  The error was referring to the ConvertLib.sol library. 

`TypeError: Error parsing C:/Projects/MetaCoin/contracts/ConvertLib.sol: Cannot destructure property `body` of 'undefined' or 'null'.`

Reverting to 5.1.10 solved the issue.

**Comment by xlwwww** [comment] 2020-04-21 09:51
yes，this problem can be solved by 
npm install truffle@5.1.9 -g
and then delete the build directory and re-compile and migrate the contract

**Comment by gorgos** [comment] 2020-05-26 02:30
Can we fix this? I need something older than `5.1.16` due to https://github.com/trufflesuite/truffle/issues/2723 🤦‍♂️

**Comment by eggplantzzz** [comment] 2020-07-08 15:05
So does the problem still occur on version 5.1.33? It looks like some of the people in here had it resolve for them?

**Comment by slmatthiesen** [comment] 2020-07-08 15:44
Adding my 2c, I am able to compile a couple of my codebases successfully on Windows with:  version 5.1.33

**Comment by spresnal** [comment] 2020-07-09 03:56
Just updated my project to use 5.1.33 and this issue is still occurring for me

**Comment by eggplantzzz** [comment] 2020-07-09 14:53
So just to confirm @spresnal, you get this error after you unbox the metacoin project and run `truffle test`?

I'll have to go get a Windows machine to see if I can reproduce and troubleshoot this.

**Comment by EuLeEr** [comment] 2020-07-13 16:18
I confirm . I get this error after you unbox the metacoin project and run truffle test.
truffle version
Truffle v5.1.34 (core: 5.1.34)
Solidity v0.5.16 (solc-js)
Node v12.18.2
Web3.js v1.2.1
Windows 10 (10.0.19041.0)

**Comment by C0deMunk33** [comment] 2020-07-15 14:50
> yes，this problem can be solved by
> npm install truffle@5.1.9 -g
> and then delete the build directory and re-compile and migrate the contract

For anyone stumbling across this problem ^ is the quick fix

**Closed** 2020-07-15 15:03 UTC
Labels: needs investigated, priority2 ⚠️

**Comment by avrdan** [comment] 2020-08-09 19:58
Why is this closed? How is downgrading a valid solution? I don't want to downgrade just to use one project. This should NOT be closed.

**Comment by gorgos** [comment] 2020-08-09 20:05
@avrdan Fixed since v5.1.35: https://github.com/trufflesuite/truffle/releases/tag/v5.1.35.

**Comment by avrdan** [comment] 2020-08-09 20:11
@gorgos Ok, great, thanks for the clarification. I think I had to switch to NodeLTS for another issue, however. https://github.com/trufflesuite/truffle/issues/2070

**Comment by gorgos** [comment] 2020-08-09 20:16
@avrdan You can manually add those changes locally as a temporary fix: https://github.com/trufflesuite/truffle/pull/3075. That's how I did it until 5.1.35 was released.
