### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by sndeshmukh00** [trufflesuite/truffle#4107] opened 2021-06-12 11:51 UTC
---------------------------

## Issue

`Uncaught TypeError: Cannot read property 'on' of undefined`

## Code

```
initContract: function () {
    $.getJSON('Election.json', function (data) {
      // Get the necessary contract artifact file and instantiate it with truffle-contract
      var ElectionArtifact = data;
      App.contracts.Election = TruffleContract(ElectionArtifact);

      // Set the provider for our contract
      App.contracts.Election.setProvider(App.web3Provider);

      // Listen for events in the contract
      App.listenForEvents();

      web3.currentProvider.publicConfigStore.on('update', function (result) {
        if (result.selectedAddress != App.yourAddress) {
          location.reload();
        }

      });

      return App.showResult();
    });
    return App.bindEvents();
  },
```

## Environment

* Operating System: Windows 10
* Truffle version (`truffle version`): 5.3.9
* node version (`node --version`): 12.18.3

**Comment by eggplantzzz** [comment] 2021-06-14 16:02
It's hard to know what's going on because you haven't really provided any steps to reproduce your error but maybe you should make sure `web3.currentProvider.publicConfigStore` has a value. That is the only guess I have with the information you provided. If you want to elaborate a little bit more on the problem, then maybe I can help you further.

**Comment by haltman-at** [comment] 2022-02-09 19:13
We're going to close this for issue maintenance, but please let us know if there's still a problem and we can reopen it!

**Closed by haltman-at** 2022-02-09 19:13 UTC
