### ISSUE TITLE
Solidity function that returns (byte, bytes, bytes) causes BigNumber Error

### ISSUE THREAD

**Issue by D-Nice** [trufflesuite/truffle#369] opened 2017-03-06 22:37 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Calling a solidity function, which returns a byte type, and subsequently 2 bytes types (byte, bytes, bytes), throws a bigNumber error in Truffle console. 

## Steps to Reproduce

Use the following two function in a test contract

    function bytePre()
    external constant
    returns (byte a, bytes b) {
        a = hex'ff';
        b = hex'11';
    }
    function byteError()
    external constant
    returns (byte a, bytes b, bytes c) {
        a = hex'ff';
        b = hex'11';
        c = hex'11';
    }

Compile, migrate and then test on truffle console as follows:

`testContract.deployed().bytePre.call()`

`testContract.deployed().byteError.call()`

## Expected Behavior

Return the corresponding bytes correctly
`[ '0xff',
 '0x11',
 '0x11', ]`
## Actual Results

bytePre function returns:

`[ '0xff',
 '0x000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000011100000000000000000000000000000000000000000000000000000000000000' ]`

byteError function throws:

`BigNumber Error: new BigNumber() not a base 16 number:
    at raise (C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\bignumber
.js\bignumber.js:1177:25)
    at C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\bignumber.js\big
number.js:1165:33
    at new BigNumber (C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\b
ignumber.js\bignumber.js:212:28)
    at SolidityTypeDynamicBytes.formatOutputDynamicBytes [as _outputFormatter] (C:\Users\D-Nice\AppData\Roaming\npm\node
_modules\truffle\node_modules\ether-pudding\node_modules\web3\lib\solidity\formatters.js:205:19)
    at C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\web3\lib\solidit
y\type.js:237:25
    at SolidityTypeDynamicBytes.SolidityType.decode (C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modul
es\ether-pudding\node_modules\web3\lib\solidity\type.js:238:11)
    at C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\web3\lib\solidit
y\coder.js:219:29
    at Array.map (native)
    at SolidityCoder.decodeParams (C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\n
ode_modules\web3\lib\solidity\coder.js:218:26)
    at SolidityFunction.unpackOutput (C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-puddin
g\node_modules\web3\lib\web3\function.js:90:24)
    at Object.callback (C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules
\web3\lib\web3\function.js:118:30)
    at C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\web3\lib\web3\me
thod.js:142:25
    at C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\ether-pudding\node_modules\web3\lib\web3\re
questmanager.js:89:9
    at request.onreadystatechange (C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\web3\lib\web3\h
ttpprovider.js:114:13)
    at dispatchEvent (C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\xmlhttprequest\lib\XMLHttpRe
quest.js:591:25)
    at setState (C:\Users\D-Nice\AppData\Roaming\npm\node_modules\truffle\node_modules\xmlhttprequest\lib\XMLHttpRequest
.js:610:14)`

## Environment

* Operating System: Win 7 & Debian 8
* Truffle version:  2.1.1 on Win 7 & 3.0.2 on Debian
* Ethereum client: TestRPC
* node version: 6.10.0 
* npm version: 3.10.10

**Comment by treeder** [comment] 2017-06-22 19:57
I'm getting this too, it seems truffle assumes that every `call()` returns a number or something.

**Comment by gnidan** [comment] 2018-10-24 18:16
Is this still a problem? In Truffle v5 I think we changed how this works (for starters, we're using BN.js instead now)

Let me know! Thanks!

**Comment by pf89** [comment] 2018-12-05 16:12
Hello, does anyone have a solution or at least a workaround? Get this bug too. Thank you very much

**Comment by D-Nice** [comment] 2018-12-28 17:19
I have not run into this scenario under Truffle v5 I believe, but have migrated towards using it, and would recommend others experiencing this issue atm to do the same and then report if they still have this issue.

**Comment by malkevych** [comment] 2019-01-25 15:47
Have the same bug with truffle 5

**Comment by eggplantzzz** [comment] 2019-01-28 13:46
@malkevych I am unable to reproduce the above error on version 5. Can you give me some steps?

**Comment by eggplantzzz** [comment] 2019-06-19 17:45
Closing this during maintenance.

**Closed by eggplantzzz** 2019-06-19 17:45 UTC
Labels: needs reproduced
