### ISSUE TITLE
truffle debug error: Cannot read property 'binary' of undefined

### ISSUE THREAD

**Issue by rustamakhmetov** [trufflesuite/truffle#882] opened 2018-04-02 12:46 UTC
## Issue

I've encountered an issue which I do not know how to debug with this error message:
`(node:4399) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'binary' of undefined`

[code](https://github.com/rustamakhmetov/safe_ico/tree/debug_bug1)

## Steps to Reproduce

1. `truffle compile`
2. `truffle develop`
3. `migrate --reset`
4. `MainICO.deployed().then(function(instance) { return instance.sendTransaction({ from: web3.eth.accounts[0], gas: 50000, value: web3.toWei(0.001, "ether") });}).then(function(result) { console.log(result); })`
5. `debug [transaction]` 

## Expected Behavior

lets me debug

## Actual Results

Gathering transaction data...

(node:4399) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'binary' of undefined

## Environment

* Operating System: Mac
* Ethereum client:
* Truffle version (`truffle version`): Truffle v4.1.5 (core: 4.1.5), Solidity v0.4.21 (solc-js)
* node version (`node --version`): v6.11.5
* npm version (`npm --version`): 3.10.10

**Comment by rustamakhmetov** [comment] 2018-04-03 07:18
After the upgrade Node to version v9.10.1, with the same actions I get the error:

**Comment by kriskelly** [comment] 2018-04-03 17:57
I'm also seeing this error after upgrading from Truffle v4.1.3. I'm attempting to debug a transaction on the Rinkeby network. Before I upgraded Truffle, it was telling me that it was unable to show the source code for any of the contracts involved. Not sure why, but it's probably relevant.

Here's a bit more of the stack trace in case that helps:

```
Gathering transaction data...

redux-saga error: uncaught at session.saga
at session.saga
 TypeError: Cannot read property 'binary' of undefined
    at recordContracts$ (/Users/kriskelly/.nvm/versions/node/v8.9.1/lib/node_modules/truffle/build/webpack:/~/truffle-debugger/dist/debugger.js:3288:1)
    at tryCatch (/Users/kriskelly/.nvm/versions/node/v8.9.1/lib/node_modules/truffle/build/webpack:/~/regenerator-runtime/runtime.js:62:15)
    at Generator.invoke [as _invoke] (/Users/kriskelly/.nvm/versions/node/v8.9.1/lib/node_modules/truffle/build/webpack:/~/regenerator-runtime/runtime.js:296:1)
    at Generator.prototype.(anonymous function) [as next] (/Users/kriskelly/.nvm/versions/node/v8.9.1/lib/node_modules/truffle/build/webpack:/~/regenerator-runtime/runtime.js:114:1)
```

Pretty sure it's this function: https://github.com/trufflesuite/truffle-debugger/blob/3c2ae1e0c980f9aef0ac1ec79d4d7b7108e83c39/lib/session/sagas/index.js#L83 and if so, it's iterating over undefined contracts.

**Comment by melnikaite** [comment] 2018-04-03 18:03
I have the same error message when I just change function name in a contract, to try new feature in v4.0.0 "Debug transactions without code". Backing previous name allows me to debug transaction without any issues.

## Environment

* Operating System: OS X
* Ethereum client: truffle develop
* Truffle version (`truffle version`): Truffle v4.1.5 (core: 4.1.5) Solidity v0.4.21 (solc-js)
* node version (`node --version`): v9.2.1
* npm version (`npm --version`): 5.8.0

**Comment by gnidan** [comment] 2018-04-13 16:31
Thanks for reporting this issue everyone.

Closing as duplicate of trufflesuite/truffle-debugger#51

**Closed by gnidan** 2018-04-13 16:31 UTC
