### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by Solidy** [trufflesuite/truffle#4014] opened 2021-05-04 14:08 UTC
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
contract
^

Uncaught ReferenceError: contract is not defined

This Issue is in Git console in others is the same

## Steps to Reproduce

"open console"
"cd (contract name)"
"migrate"
"truffle console"
"contract"

## Expected Behavior

I think it is something with computer

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: windows
* Ethereum client:yes
* Truffle version (`truffle version`):2.3.3
* node version (`node --version`):15.14.0
* npm version (`npm --version`): 7.10.0

**Comment by gnidan** [comment] 2021-05-05 18:24
Thanks for trying out Truffle. You might want to start by reading the [Pet Shop Tutorial](https://www.trufflesuite.com/tutorial) to get a sense for how to use Truffle. If you want more information about the `truffle console` command, please see the [specific documentation about this command](https://www.trufflesuite.com/docs/truffle/getting-started/using-truffle-develop-and-the-console). You might also find [this webinar](https://www.crowdcast.io/e/truffle-webinar-series-episode1) (and corresponding [code](https://github.com/trufflesuite/webinar-episode-01)) helpful.

Closing this issue since it's not a bug or feature request. If you'd like more support, please open a ticket with our excellent Customer Success team [here](https://trufflesuite.zendesk.com/hc/en-us/requests/new).

Thank you and best of luck.

**Closed by gnidan** 2021-05-05 18:24 UTC
