### ISSUE TITLE
On windows "truffle compile" fails on "import" statements

### ISSUE THREAD

**Issue by popra** [trufflesuite/truffle#400] opened 2017-05-10 13:33 UTC
## Issue

With truffle 3.2.2 on windows, "truffle compile" fails on "import" statements, with error:

sol:1:1: : Source "XXX.sol" not found: File import callback not supported
import "./XXX.sol";
^----------------^

It works fine with truffle 3.2.1.

## Steps to Reproduce

Create any contract that imports another .sol file.
truffle compile

## Expected Behavior

contracts should compile

## Actual Results

Error:
sol:1:1: : Source "XXX.sol" not found: File import callback not supported
import "./XXX.sol";

## Environment

* Operating System: Windows 10
* Truffle version: 3.2.2
* node version: 6.10.3
* npm version: 3.10.10

**Comment by hister** [comment] 2017-05-10 13:54
I have the same issue just create a new project and on compile i get this:
` Source "ConvertLib.sol" not found: File import callback not supported`

**Comment by KaTXi** [comment] 2017-05-10 20:54
Same here, I was about to report the same error. Happens with old projects that were working on 3.2.1 and brand new ones created with "truffle init"

**Comment by tcoulter** [comment] 2017-05-11 16:45
Hi all, thanks for the reports. This was a bug specifically for Windows - my apologies. I just pushed a fix to one of Truffle's dependencies. To get the fix, simply uninstall then reinstall Truffle. It's important you _do_ uninstall Truffle first to ensure the latest dependencies are downloaded. Cheers!

**Comment by popra** [comment] 2017-05-11 18:17
Thank you! Works nicely.

**Comment by hister** [comment] 2017-05-11 19:49
@popra The same error appears when I do `truffle test` but no problem when running `truffle compile`

**Comment by kowalski** [comment] 2017-05-12 12:05
I see the same problem on Linux. I'm using docker for development.
Host OS: Ubuntu 14.04
Docker version: Docker version 1.11.2, build b9f10c9

Steps to reproduce.
1. Run machine:
```
docker run -it node:7.7.2 bash
```

2. Update stuff inside 
```
apt-get -y update &&\
    apt-get -y upgrade &&\
    apt-get install build-essential -y
```

3. Install truffle
```
npm install -g truffle@3.2.2
```

4. Make dummy project
```
root@27d5ee4ec94d:/# mkdir -p /tmp/truffle
root@27d5ee4ec94d:/# cd /tmp/truffle
root@27d5ee4ec94d:/tmp/truffle# truffle init
Downloading project...
Project initialized.

  Documentation: http://truffleframework.com/docs

Commands:

  Compile: truffle compile
  Migrate: truffle migrate
  Test:    truffle test

```

5. Edit `/tmp/truffle/truffle.js` to point to testrpc. 
```
apt-get install -y nano
nano truffle.js
(substitute `localhost` with where you have your testrpc running. For me it's 172.17.0.1)
```
```
root@27d5ee4ec94d:/tmp/truffle# cat truffle.js 
module.exports = {
  networks: {
    development: {
      host: "172.17.0.1",
      port: 8545,
      network_id: "*" // Match any network id
    }
  }
};

```

6. Run tests
```
root@27d5ee4ec94d:/tmp/truffle# truffle test
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./test/TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

/tmp/truffle/test/TestMetacoin.sol:3:1: : Source "truffle/Assert.sol" not found: File import callback not supported
import "truffle/Assert.sol";
^--------------------------^
,/tmp/truffle/test/TestMetacoin.sol:4:1: : Source "truffle/DeployedAddresses.sol" not found: File import callback not supported
import "truffle/DeployedAddresses.sol";
^-------------------------------------^
Compiliation failed. See above.

```

**Comment by dukei** [comment] 2017-05-12 16:02
Problem still persists on Windows 10, Node 7.10.0, npm 4.3.0, truffle 3.2.2 (fresh npm install -g truffle after npm uninstall -g truffle).
I get errors similar to this:
,/ico/CrowdsaleToken.sol:3:1: : Source "zeppelin/contracts/token/StandardToken.sol" not found: File import callback not supported

The standard example generated by truffle init compiles ok though. It seems that the problem occurs when contracts import contracts from installed_contracts folder.

Reverting to truffle 3.2.1 solves the issue (but reverts solidity to 0.4.8 as well, that's sad).

**Comment by tcoulter** [comment] 2017-05-12 18:08
Thanks for the reports. I've pushed out new fix. Can you uninstall and reinstall Truffle again?

**Comment by dukei** [comment] 2017-05-12 18:39
Yes, now it works perfectly! Thank you!

**Comment by tcoulter** [comment] 2017-05-12 18:41
Awesome. Thanks again for the quick report.

**Comment by pgrzesik** [comment] 2017-05-15 08:15
I just checked and it looks like the issue is solved, thanks a lot @tcoulter !

**Comment by shribits** [comment] 2018-01-26 14:15
I am getting the same error on windows 10 with visual studio code.
truffle@4.0.5
ganache-cli@6.0.3
![capture](https://user-images.githubusercontent.com/9196395/35443517-7d5a3e26-02ff-11e8-8494-c96985ff0244.PNG)

**Comment by polyglot0027** [comment] 2018-01-28 13:27
Same thing on MacOs Sierra 10.12.6, truffle@4.0.5, ganache-cli@6.0.3

**Comment by superlazycoder** [comment] 2018-02-10 22:39
The contract seems to compile, and the project runs the tests, but the errors in the GUI are annoying.

**Comment by Ste91** [comment] 2018-04-19 12:16
Still getting the same issue "fails on import statements" on windows 10 using truffle@4.1.6

**Comment by Toniboy1** [comment] 2018-05-04 12:11
Same as Ste91 are you working on a fix?

**Comment by cgewecke** [comment] 2018-05-05 16:46
@vicnaum Are you using VS Code? If so the problem is documented at #756 with a solution.

**Comment by vicnaum** [comment] 2018-05-06 16:55
@cgewecke I guess I know exactly what the problem is (at least at my side).

I had misplaced the Test .sol into the "contracts/" folder. When it was properly placed in "test" folder - everything went fine.

Guess worth mentioning if someone else repeats my silly mistake.

**Comment by Shreshth5625** [comment] 2020-05-29 11:07
Can anyone help me out with the same issue please ?
Windows 10, truffle version: 6.14.4
Cannot find truffle/Assert.sol from any sources

**Comment by not-idol** [comment] 2021-04-12 09:26
mac 11.2.3, same error.

**Comment by yanivel** [comment] 2021-07-19 07:35
Why was this closed? This issue is still happening.

**Comment by BigSamu** [comment] 2021-07-19 09:56
Same error here in MacOS. Using following versions:

Truffle v5.4.1 (core: 5.4.1)
Solidity v0.5.16 (solc-js)
Node v16.5.0
Web3.js v1.4.0

**Comment by cds-amal** [comment] 2021-07-19 19:30
@yanivel I was unable to reproduce this on a windows machine. Do you have a public repo that we can use to debug this issue?

**Comment by eggplantzzz** [comment] 2021-07-21 18:09
Can someone provide us with fresh reproduction steps? The original issue was with a very old version of Truffle and I would like to make sure we are troubleshooting the right problem. Thanks!

**Comment by justintime4tea** [comment] 2021-07-24 04:59
**Reproduction on Windows 10**
```
npm install -g truffle
mkdir MetaCoin
cd MetaCoin
truffle unbox metacoin
truffle compile
# Launch ganache either through GUI and using Quickstart or ganache-cli
truffle migrate
truffle test
```

Truffle test fails because it cannot find the following:
* import "truffle/Assert.sol";
* import "truffle/DeployedAddresses.sol";

Output from truffle test:
```
Using network 'test'.


Compiling your contracts...
===========================
> Compiling .\contracts\ConvertLib.sol
> Compiling .\contracts\ConvertLib.sol
> Compiling .\contracts\MetaCoin.sol
> Compiling .\contracts\MetaCoin.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\test\TestMetaCoin.sol

project:/test/TestMetaCoin.sol:3:1: ParserError: Source "truffle/Assert.sol" not found
import "truffle/Assert.sol";
^--------------------------^
,project:/test/TestMetaCoin.sol:4:1: ParserError: Source "truffle/DeployedAddresses.sol" not found
import "truffle/DeployedAddresses.sol";
^-------------------------------------^

Compilation failed. See above.
Truffle v5.4.2 (core: 5.4.2)
Node v14.17.3
```

**Comment by cds-amal** [comment] 2021-07-26 00:47
Thanks @justintime4tea. This is very helpful!

**Comment by cds-amal** [comment] 2021-07-26 03:01
@blue0d @yanivel @BigSamu I'm unable to reproduce this on OS X and linux, do you have reproduction steps? Thanks!

**Comment by nathanrhoda** [comment] 2021-07-26 20:36
Same issue persists for windows as well

**Comment by gnidan** [comment] 2021-07-28 18:05
The linked PR above (#4202) fixes the `import "truffle/Assert.sol"` issue on Windows, but we're not sure about any other issues here. Once 4202 gets released, could any of you please try again and see if it fixes it? Will post here when the release goes out. Thanks!

**Closed** 2021-07-30 20:49 UTC

**Comment by psyfreak** [comment] 2021-08-08 01:06
> **Reproduction on Windows 10**
> 
> ```
> npm install -g truffle
> mkdir MetaCoin
> cd MetaCoin
> truffle unbox metacoin
> truffle compile
> # Launch ganache either through GUI and using Quickstart or ganache-cli
> truffle migrate
> truffle test
> ```
> 
> Truffle test fails because it cannot find the following:
> 
> * import "truffle/Assert.sol";
> * import "truffle/DeployedAddresses.sol";
> 
> Output from truffle test:
> 
> ```
> Using network 'test'.
> 
> 
> Compiling your contracts...
> ===========================
> > Compiling .\contracts\ConvertLib.sol
> > Compiling .\contracts\ConvertLib.sol
> > Compiling .\contracts\MetaCoin.sol
> > Compiling .\contracts\MetaCoin.sol
> > Compiling .\contracts\Migrations.sol
> > Compiling .\contracts\Migrations.sol
> > Compiling .\test\TestMetaCoin.sol
> 
> project:/test/TestMetaCoin.sol:3:1: ParserError: Source "truffle/Assert.sol" not found
> import "truffle/Assert.sol";
> ^--------------------------^
> ,project:/test/TestMetaCoin.sol:4:1: ParserError: Source "truffle/DeployedAddresses.sol" not found
> import "truffle/DeployedAddresses.sol";
> ^-------------------------------------^
> 
> Compilation failed. See above.
> Truffle v5.4.2 (core: 5.4.2)
> Node v14.17.3
> ```

I had the same issue on windows7 with truffle 5.4.2.
The newest version 5.4.5 fixed it and it works now :)

**Comment by oluwafemi08** [comment] 2022-01-03 21:30
Same error on windows 10
Using following versions; 
Truffle v5.4.26 (core: 5.4.26)
Node v12.17.0

**Comment by cds-amal** [comment] 2022-01-03 23:08
@oluwafemi08 Can you please open a new issue? I want to make sure there's no regression in recent releases
