### ISSUE TITLE
Truffle version from 5.1.49 to later versions slows down tests significantly

### ISSUE THREAD

**Issue by hellwolf** [trufflesuite/truffle#3780] opened 2021-02-08 11:15 UTC
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

By upgrading from truffle version 5.1.49 to 5.1.65 slows down tests significantly

## Steps to Reproduce

```
$ git clone https://github.com/superfluid-finance/protocol-monorepo
$ cd protocol-monorepo
$ yarn install
$ yarn build
$ cd packages/ethereum-contracts
$ npx truffle test test/contracts/agreements/ConstantFlowAgreementV1.test.js
```

Clock the time.

Now do the same thing after changing in package.json the truffle version to 5.1.65, then do yarn install, and test again.

## Expected Behavior

Test speed should not deteriorate, if not improve.

## Actual Results

Test speed slowed twice.

## Environment

* Operating System:  Ubuntu
* Ethereum client: ganache
* Truffle version (`truffle version`): 5.1.49, 5.1.65
* node version (`node --version`): v12.20.1
* npm version (`npm --version`):  6.14.11

**Comment by haltman-at** [comment] 2021-02-08 19:59
Do you know what the first version that has this problem is?  Thank you!

**Comment by hellwolf** [comment] 2021-02-09 15:34
@haltman-at I think 5.1.49 was the last known "good" version for us.

**Comment by haltman-at** [comment] 2021-02-09 19:24
So, are you saying that the issue was in fact introduced in 5.1.50, or is 5.1.49 simply the most recent version you happened to try that worked out?

**Comment by hellwolf** [comment] 2021-02-09 20:41
@haltman-at 

I tried again following the reproduce steps.

- with truffle 5.1.49, the test took 265.334 seconds.
- with truffle 5.1.50, the test took 357.748 seconds.

**Comment by haltman-at** [comment] 2021-02-09 21:00
I see, OK, thanks!  That gives us a place to start looking.  Thanks for the report!

**Comment by haltman-at** [comment] 2021-02-19 03:15
OK, so the most likely culprit for this seems to be that we upgraded web3 to 1.2.9...?  It's not clear what we can do about this; we can't upgrade further at the moment due to various problems with later versions that haven't been fixed yet.  That said, this week's release is going to include what should be an across-the-board performance improvement, so hopefully that should help mitigate this!

**Comment by hellwolf** [comment] 2021-02-19 09:15
okay, I will test again when it's released

**Comment by hellwolf** [comment] 2021-02-22 14:41
the problem persists with `5.1.67`

**Comment by haltman-at** [comment] 2021-02-22 18:56
Troublesome.  OK, we'll have to look into this more later.  Thanks for alerting us.

**Comment by sirhill** [comment] 2021-02-26 16:40
I've encountered what I think is the same issue.

Here before and after circle-ci builds:

Sub 10 minutes successfull build  (11 Oct 2020)
> https://app.circleci.com/pipelines/github/c-layer/contracts/139/workflows/f667581a-d186-44f3-8cce-5cb4df2fb52b

Over 20 minutes successfull build (22 Oct 2020)
>https://app.circleci.com/pipelines/github/c-layer/contracts/158/workflows/da04c938-f6f5-4908-9cd4-d5ed66991921

Only minor changes appart.

**Comment by hellwolf** [comment] 2021-03-09 18:43
Today I tried with "truffle": "5.2.3", the testing speed still experiences major slow down:

https://github.com/superfluid-finance/protocol-monorepo/actions/workflows/ci.yml

![image](https://user-images.githubusercontent.com/186660/110520550-47935180-8117-11eb-8d03-77c12872d6d0.png)

![image](https://user-images.githubusercontent.com/186660/110521214-22eba980-8118-11eb-9596-07c6d6fb77d2.png)

**Comment by hellwolf** [comment] 2021-03-29 10:24
BUMP, I think it's quite high priority for us. Otherwise we will have to make the move to some other framework in the long run. We are already under lots of questioning why we are still using truffle. I always use truffle since I have been in this space long enough and the inertial has been the major factor while new comers always asking for using new tools. But I always believe truffle will be improving and still be the major framework going forward.

**Comment by hellwolf** [comment] 2021-04-09 09:51
@haltman-at thanks for coming back on this.

Unfortunately not, it still takes lots of time with `5.3.1`. I am happy to do some benchmarking and traces to identify where is the hotspot or bottleneck for the slowdown. I could do some research on tools to be used, unless you have something to recommend me to us?

**Comment by Arvolear** [comment] 2021-04-14 11:42
Encountered the same issue. I believe the problem is indeed in web3, cause truffle test runner and openzeppelin test runner are experiencing the same degradation by running a lot of tests in the project.

I have noticed that in ganache there are a lot of logs of eth_getBlockByNumber for each transaction in test execution (2-3k). I think that this is a consequence of transaction execution time slowing down for some reason while running a lot of tests (big file or all tests in a project). 

Seems like the whole environment doesn't free up itself before each test. Running the test files separately speeds up the process a bit (because truffle hard resets).

**Comment by haltman-at** [comment] 2021-04-14 17:40
@Arvolear, you may possibly want to use the `disableConfirmationListener` network configuration option to avoid the large number of `eth_getBlockByNumber`s.

Interesting that running the tests separately is faster.  That's certainly worrying.  We'll have to look into that, thanks.

**Comment by joequant** [comment] 2021-05-11 14:27
We are also running into slow downs with 5.1.50 in which each test seems to be taking longer and longer.

**Comment by hellwolf** [comment] 2021-05-12 08:00
It should have a higher priority.

**Comment by Arvolear** [comment] 2021-05-12 09:11
Absolutely agree, we were forced to downgrade to 5.1.49 because the later versions are pretty much unusable.

**Comment by eggplantzzz** [comment] 2021-05-12 21:05
@Arvolear did you try @haltman-at's suggestion to use `disableConfirmationListener`?

**Comment by Arvolear** [comment] 2021-05-13 08:53
@eggplantzzz Hey, I tried and disabled the listener, however, the major truffle version still experienced a huge speed degradation while running the tests in the project (there are roughly 400 of them in 20 separate test files). 

While using the 5.2.6 version (back then) the CI would take more than 2 hours to complete and downgrading truffle to 5.1.49 reduced the time to 10 minutes.

I am still running the tests with the `disableConfirmationListener` and from my personal analysis, the tests get faster by 10-15% with it.

**Comment by eggplantzzz** [comment] 2021-05-13 15:23
Hmm that is not good, that is still quite a bit slower. Can you link a repo that we can use to try and reproduce your issues?

**Comment by devinaconley** [comment] 2021-05-16 03:58
I can also confirm that this affected the open zeppelin test runner. We were experiencing 2-3x slowdowns, especially when running a large number of tests.

Reverting to these versions resolved the issue
```
    "@openzeppelin/test-environment": "^0.1.4",
    "@openzeppelin/test-helpers": "^0.5.6",
    "truffle": "^5.1.39",
    "web3": "^1.2.11",
    "web3-utils": "^1.3.4"
```

I didn't exhaustively check for the "breaking" version, so there may be working ones in between

**Comment by hellwolf** [comment] 2021-09-23 15:05
guys, this is getting really annoying, anything we can help with?

**Comment by hellwolf** [comment] 2021-09-23 20:57
Disabling `disableConfirmationListener` definitely helped!

But how do you configure the default "test" network, the one that is launched as a "internal ganache" by truffle test?

**Comment by haltman-at** [comment] 2021-09-24 21:57
> guys, this is getting really annoying, anything we can help with?

Unfortunately this may be difficult.  As best we can tell, the cause of this issue is due to a web3 upgrade.  This is by process of elimination; none of the other changes made in [v5.1.50](https://github.com/trufflesuite/truffle/releases/tag/v5.1.50) are a plausible candidate.  But we're not about to downgrade web3, so...?

Now if we're wrong and it's due to one of the other changes in that release, then there might be more to work with here, but at the moment there's no obvious way forward.

**Comment by haltman-at** [comment] 2021-09-24 21:59
> Disabling `disableConfirmationListener` definitely helped!

Glad to hear it!

> But how do you configure the default "test" network, the one that is launched as a "internal ganache" by truffle test?

Good question.  You can of course configure the `test` network... but if you do so, Truffle Test will look for that network to already exist (i.e. you'll have to start up Ganache separately), rather than creating its own internal Ganache.

So the answer to your question is that at the moment, there is no way to do that.  We ought to change that.  I'll go file an issue for it!

**Comment by rchrdw** [comment] 2022-03-29 15:42
I'm experiencing this issue as well.  For a very simple project, the difference was 23x slower.

Tests on Truffle v5.5.6 took 23s, Truffle v5.1.49  took 1s.

**Comment by eggplantzzz** [comment] 2022-03-29 20:00
Hey @rchrdw, are you using an http provider? If you use a websocket provider in your test network configuration does it speed them up?

**Comment by rchrdw** [comment] 2022-03-30 18:14
> Hey @rchrdw, are you using an http provider? If you use a websocket provider in your test network configuration does it speed them up?

I'm using the default internal Ganache network.

**Comment by InfectedIsm** [comment] 2022-08-13 20:23
@rchrdw could you provide more details about your workaround ? I face the same issue and I don't know how to implement your solution (wihch http provider ? which websocket provider ?)
Are you talking about infura or something like that ? So you do this on a testnet ?

**Comment by cds-amal** [comment] 2022-08-14 00:09
@InfectedIsm, [Truffle v5.5.26](https://github.com/trufflesuite/truffle/releases/tag/v5.5.26) includes [a change](https://github.com/trufflesuite/truffle/pull/5407) that should speed up tests. Can you upgrade your truffle version and let me know if your issue is resolved?

**Comment by InfectedIsm** [comment] 2022-08-14 07:20
@cds-amal hey, thanks for replying, I'm using 5.5.6 right now (I started with this version)
I noticed the issue was related when a compared my execution time to the instructor time (the training is 2-3 yo) 
Same code, ~50ms per test for him, 1000ms on my side (x20, like rchrdw)
Truffle v5.5.6 (core: 5.5.6)
Ganache v^7.0.3

**Comment by cds-amal** [comment] 2022-08-14 11:40
Thanks, @InfectedIsm. That is interesting! Is sharing your repo an option? I'd like to investigate the issue.

**Comment by InfectedIsm** [comment] 2022-08-14 13:44
Sure @cds-amal, I've added you as a collaborator rn because it is set as private. I suppose you should be able to check what you want

**Comment by cds-amal** [comment] 2022-08-14 16:45
Thanks for the access @InfectedIsm. The tests didn't run, and I don't see how this project resulted in slower test speeds, as the tests did not run!  Anyway, after fixing the error, the two tests took 53ms and 135ms, for a total of 1sec runtime, rounded up. Did you share the correct project?

**Comment by rchrdw** [comment] 2022-08-14 17:34
> @rchrdw could you provide more details about your workaround ? I face the same issue and I don't know how to implement your solution (wihch http provider ? which websocket provider ?) Are you talking about infura or something like that ? So you do this on a testnet ?

Manually starting ganache, instead of using letting truffle start and use its own internal instance, and rerunning the tests resolved the issue for me.

**Comment by sahilrajput03** [comment] 2022-10-09 16:04
for me the command `truffle test` command waits for 10 more seconds before exiting.

I mean I see that tests gets passed in 5 seconds and after that it takes additional 10 seconds,, and god knows why is that?

and for me `truffle watch` is not working, i.e, 
![image](https://user-images.githubusercontent.com/31458531/194767217-1f9d4661-dc99-48ae-a7b5-6d0ff26e47f1.png)

**Comment by eggplantzzz** [comment] 2022-10-11 15:24
Hey @sahilrajput03, I want to look into this issue of the test suite running slowly. On my own toy project the tests don't seem to hang, do you have a repo I could use to try and reproduce your issue? Maybe you forgot to tear down something that is causing Node to hang? Let me know if you have something on GitHub that I could pull down and try.

**Comment by sahilrajput03** [comment] 2022-10-11 20:13
https://github.com/sahilrajput03/dapp-6fig-eattheblocks/tree/main/multisig-wallet

@eggplantzzz

**Comment by eggplantzzz** [comment] 2022-10-12 19:26
Thanks @sahilrajput03!

**Comment by eggplantzzz** [comment] 2022-10-12 19:42
Hey, so I tried the test suite for multisig-wallet locally here and the tests run speedy quick! I used a separate Ganache instance as well as `truffle develop` to run the tests. They both took around 2-3 seconds to run the suite. Maybe something got fixed since the last time you ran these. If you have time, could you try again with the latest version? If you are still having slow tests maybe I can help you troubleshoot the issue. Thanks!

**Comment by sahilrajput03** [comment] 2022-10-12 20:52
@eggplantzzz can you show the outputs of the following command of yours please:

![image](https://user-images.githubusercontent.com/31458531/195445409-4ddb3b2d-0a36-416a-a273-451f79ca2f33.png)

**Comment by eggplantzzz** [comment] 2022-10-13 14:32
I'll post some images below.
<img width="1696" alt="Screen Shot 2022-10-13 at 10 30 59 AM" src="https://user-images.githubusercontent.com/14827965/195625352-2334b768-c59d-491d-a89a-e38bb9574569.png">
<img width="1713" alt="Screen Shot 2022-10-13 at 10 32 07 AM" src="https://user-images.githubusercontent.com/14827965/195625762-f8f119ca-fa77-49cf-9d69-fce862be18e1.png">
<img width="1705" alt="Screen Shot 2022-10-13 at 10 32 46 AM" src="https://user-images.githubusercontent.com/14827965/195625780-2fdc7477-df24-4a50-90ec-74f254cf703e.png">

**Comment by sahilrajput03** [comment] 2022-10-13 14:40
In the last message, I posted all the versions.

>	```bash
>	# Truffle v5.6.0 (core: 5.6.0)
>	# Ganache v7.4.3
>	# Solidity v0.5.16 (solc-js)
>	# Node v16.16.0
>	# Web3.js v1.7.4
>	# ganache v7.4.4 (@ganache/cli: 0.5.4, @ganache/core: 0.5.4
>	```

**Comment by sahilrajput03** [comment] 2022-10-17 19:25
@eggplantzzz My computer is not slow at all and my system I am not running heavy applications at all. My specs:

CPU: Intel i5-6200U (4) @ 2.800GHz
GPU: AMD ATI Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / Radeon 520 Mobile
GPU: Intel Skylake GT2 [HD Graphics 520]
Memory: 7849MiB

I have a very minimal setup on my desktop and using i3wm.

**Comment by sahilrajput03** [comment] 2022-10-17 19:25
@eggplantzzz My computer is not slow at all and my system I am not running heavy applications at all. My specs:

CPU: Intel i5-6200U (4) @ 2.800GHz
GPU: AMD ATI Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / Radeon 520 Mobile
GPU: Intel Skylake GT2 [HD Graphics 520]
Memory: 7849MiB

I have a very minimal setup on my desktop and using i3wm.

**Comment by cds-amal** [comment] 2022-10-18 09:50
@sahilrajput03, what do the numbers look like when you [comment out the `development` network](https://github.com/sahilrajput03/dapp-6fig-eattheblocks/blob/main/multisig-wallet/truffle-config.js#L79)? Truffle will use an in-memory Ganache provider when`development` is unspecified.

**Comment by sahilrajput03** [comment] 2022-10-18 09:57
@cds-amal

**Comment by sahilrajput03** [comment] 2022-10-18 10:07
@cds-amal here is a video of how it looks in that time on my system: https://www.youtube.com/watch?v=UHDuL7lcv1Q

**Comment by eggplantzzz** [comment] 2022-10-18 15:43
@sahilrajput03 hmm very strange. I can't reproduce those results. I'll have to try and think of another way to troubleshoot this.

**Comment by cds-amal** [comment] 2022-10-19 16:08
Ouch, @sahilrajput03! I couldn't reproduce that on Ubuntu, Arch, Manjaro, or OS X. I wonder if we're testing the same config/code, as the main branch doesn't work without setup. Can you push a branch that I can run w/o modification? **Please do not include mnemonics, or private keys**.  

## test output

```console
╭─amal@mrlo  ~/dev/etb/multisig-wallet ‹node-16.18.0›  ‹› (exp*)
╰─$ disable -r time && time -p truffle test
Using network 'test'.


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.


  Contract: MultiSigWallet
    ✔ should have correct approvers and quorum
    ✔ should create transfers (48ms)


  2 passing (259ms)

real 6.37
user 18.54
sys 0.31
```

**Comment by sahilrajput03** [comment] 2022-10-19 17:31
I don't think its related to my specific code, even if I run any simple test with just hello world it takes same time.

So, from now we can consider this example:
![image](https://user-images.githubusercontent.com/31458531/196761747-90bc92f9-e6f2-4ace-b0d4-a1e5e7d55ce3.png)

tests take 7 seconds but program exits in in 26 seconds.

I tried to use raspberry pi:

![image](https://user-images.githubusercontent.com/31458531/196763445-d904b4bc-46f1-402c-b3e8-c269173308fe.png)

**Comment by cds-amal** [comment] 2022-10-20 01:25
I tried [different node versions and can't reproduce your issue](https://asciinema.org/a/1GOgjYDZID5NnZIfc1CLHgfYK). I'm at a loss on how to debug this. Did you observe the same performance issue on different Node versions? 

- Truffle v5.6.2 (core: 5.6.2)                                                                                                                                                                                          
- Ganache v7.4.4                                                                                                                                                                                                        
- Solidity - 0.8.13 (solc-js)                                                                                                                                                                                           

| Node Version  | npm version   | clock/real time (sec)  | user time (sec)  | system time (sec) |
|---|---|---|---|---|
| v18.11.0  | v8.19.2  | 6.52  | 8.67  |  0.40 |
| v16.18.0  | v8.19.2  | 8.30  | 23.61  | 0.44  |
| v14.20.1  | v6.14.17  | 8.01  |  23.61  | 0.53  |

**Comment by sahilrajput03** [comment] 2022-10-20 07:41
Okay, I'll test on a new docker image soon and post the results here.

**Comment by hellwolf** [comment] 2022-10-20 07:44
can we not use benchmarking software to see where is the bottleneck?

Last time (1.5 years ago almost) I remember where was the problem, it was some buggy callbacks build-ups when using web3.js stack.

The point is, if we just have some bechmarking setup it could turn out to be quite obvious, but that has to be built into the truffle development process.

**Comment by kevinbluer** [comment] 2022-11-03 17:53
Hey @hellwolf, if we do a special release to test @haltman-at's theory regarding the web3.js version difference would you be willing to test it and let us know what happens? Thanks again for working with us on this!

**Comment by eggplantzzz** [comment] 2022-12-01 19:19
@sahilrajput03 did you ever do any further tests? Let me know! Thanks!

**Comment by sahilrajput03** [comment] 2022-12-01 19:22
Give me some tips how/what/which I can do to make it run in most isolated way?.

**Comment by gnidan** [comment] 2022-12-08 19:02
> Give me some tips how/what/which I can do to make it run in most isolated way?.

Hey @sahilrajput03. Looks like [above](https://github.com/trufflesuite/truffle/issues/3780#issuecomment-1285083634) you suggested using just a new Docker image... maybe start with that?

No worries if you're not sure how to proceed. We have some work in progress that may help this front.

**Comment by cliffoo** [comment] 2023-02-09 19:25
It looks like no one has been able to reliably reproduce this and this is getting noisy. @sahilrajput03 if you run into this issue again with the latest release, feel free to open a new issue with reproduction steps. Using docker to isolate potential uncertainties with arch would be very welcome and make investigating this much easier.

Thanks all! Closing.

**Closed by cliffoo** 2023-02-09 19:25 UTC
Labels: bug, truffle test, needs investigated, priority3 🔧
