### ISSUE TITLE
Deployer error: only replay-protected (EIP-155) transactions allowed over RPC

### ISSUE THREAD

**Issue by shoenseiwaso** [trufflesuite/truffle#3935] opened 2021-03-20 16:08 UTC
Since the upgrade to 1.10, the chain ID is now a required parameter. Although #3923 was merged to address it in the contract package, the deployer seems to be broken. The issue might be in [executeDeployment()](https://github.com/trufflesuite/truffle/blob/500fdcc35202839ac785f7b0fe3de623cbcac074/packages/deployer/src/deployment.js#L278), where chain ID is not set.

Running `truffle migrate --reset` we see:

```
1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- only replay-protected (EIP-155) transactions allowed over RPC.
```

**Comment by MariusVanDerWijden** [comment] 2021-03-20 18:43
This issue might also manifests as
```
1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- invalid sender.
```

**Comment by maxwellfortney** [comment] 2021-03-21 04:59
Master (v5.2.5 released yesterday) does not solve this issue when trying to deploy with infura or alchemy, deploying with remix did work however.

**Comment by shoenseiwaso** [comment] 2021-03-22 03:00
Probably a dupe of #3913.

**Comment by robbelouwet** [comment] 2021-03-22 09:39
I can confirm I have the same issue.

I try to deploy my contract to ropsten, all parameters set with enough eth in the right address, and get the 'invalid sender' error. I've checked everything, my truffle-config.js file is correct.
See [my stackoverflow post](https://stackoverflow.com/q/66735307/13214834) where I describe into detail.

using Truffle v5.2.5

**Comment by noahfigueras** [comment] 2021-03-25 21:48
Stuck with the same issue! Is there a fix for the error ?

**Comment by maxwellfortney** [comment] 2021-03-25 21:52
@noahfigueras Fix is to downgrade `@truffle/hdwallet-provider`

**Comment by noahfigueras** [comment] 2021-03-25 22:21
Thanks @maxwellfortney I downgraded @truffle/hdwallet-provider@1.2.2 and it deploys correctly now!

**Comment by haltman-at** [comment] 2021-03-26 19:14
Question, are these problems still happening on Truffle 5.2.6?  Thank you!

**Comment by idealatom** [comment] 2021-03-27 05:32
@haltman-at Yes. I couldn't deploy a contract now. Downgrading a @truffle/hdwallet-provider is helped for me.

**Comment by Tenoke** [comment] 2021-03-27 13:05
I was getting `"Migrations" -- invalid sender.` as well before downgrading which worked here, too.

**Comment by Jovonni** [comment] 2021-03-28 05:01
> Since the upgrade to 1.10, the chain ID is now a required parameter. Although #3923 was merged to address it in the contract package, the deployer seems to be broken. The issue might be in [executeDeployment()](https://github.com/trufflesuite/truffle/blob/500fdcc35202839ac785f7b0fe3de623cbcac074/packages/deployer/src/deployment.js#L278), where chain ID is not set.
> 
> Running `truffle migrate --reset` we see:
> 
> ```
> 1_initial_migration.js
> ======================
> 
>    Deploying 'Migrations'
>    ----------------------
> 
> Error:  *** Deployment Failed ***
> 
> "Migrations" -- only replay-protected (EIP-155) transactions allowed over RPC.
> ```

@shoenseiwaso Is a fix as simple as just adding the chainid key to the eventArgs object in https://github.com/trufflesuite/truffle/blob/500fdcc35202839ac785f7b0fe3de623cbcac074/packages/deployer/src/deployment.js#L278

In here:
https://github.com/trufflesuite/truffle/blob/500fdcc35202839ac785f7b0fe3de623cbcac074/packages/deployer/src/deployment.js#L309-L320

**Comment by gabmontes** [comment] 2021-03-29 21:19
Possible dup of #3946.

**Comment by eggplantzzz** [comment] 2021-03-30 14:35
Could someone provide me with a simple project and detailed steps to reproduce this error? It would be really helpful to have to test against.

**Comment by MariusVanDerWijden** [comment] 2021-03-30 14:55
@eggplantzzz Any project migrating against you own geth node (v1.10.1 and higher) with `geth --dev`

**Comment by eggplantzzz** [comment] 2021-03-30 15:02
@MariusVanDerWijden It would be helpful if you have a specific project. I am able to successfully migrate a toy project to Geth version 1.10.1-stable using the currently released version of Truffle. If you have one handy and specific steps, I would appreciate it!

**Comment by shoenseiwaso** [comment] 2021-03-30 15:48
@eggplantzzz repo which reproduces the issue is here. Follow the steps in the README:
https://github.com/curvegrid/truffle-eip155-issues

**Comment by eggplantzzz** [comment] 2021-03-30 16:05
Thanks for providing the repro steps! I was able to recreate the error - it looks like upgrading `ethereumjs-tx` without extra configuration caused the issue. When I dowgrade that library it works fine, I put in a PR for downgrading [here](https://github.com/trufflesuite/truffle/pull/3954) until we get a chance to spend more time upgrading it. Thank you all!

**Comment by gnidan** [comment] 2021-03-31 23:37
This should be fixed in Truffle v5.3.0. Closing optimistically, but let us know if the problem persists, and we'll be glad to re-open!

Thanks all!

**Closed by gnidan** 2021-03-31 23:37 UTC

**Comment by shoenseiwaso** [comment] 2021-04-01 00:57
@eggplantzzz @gnidan Truffle v5.3.0 did indeed fix the issue. However, upgrading Truffle alone was not enough: I also had to upgrade the `@truffle/hdwallet-provider` from 1.2.5 to 1.2.6 as well. This might seem obvious to some, but I think it's still going to catch a lot of people off guard that the error `only replay-protected (EIP-155) transactions allowed over RPC.` means, "upgrade the `@truffle/hdwallet-provider` depedency to 1.2.6.

Is it worth putting a note in the v5.3.0 release notes?

```
{
  "dependencies": {
    "@truffle/hdwallet-provider": "1.2.6"
  }
}
```

**Comment by shoenseiwaso** [comment] 2021-04-04 08:25
Note that the fix did not address the case where the network ID and chain ID differ. Opened #3961 for this.

**Comment by mmotiy** [comment] 2021-05-10 17:20
> Thanks @maxwellfortney I downgraded @truffle/hdwallet-provider@1.2.2 and it deploys correctly now!

it work now
